### ISSUE TITLE
YellowBox has been replaced with LogBox. Please call LogBox.ignoreLogs() instead when using expo-sentry

### ISSUE THREAD

**Issue by 9710willy** [expo/expo#10300]
When I call Sentry.init in my App.js I get the warning mentioned above. 
If I comment the call to Sentry.init out, it doesn't prompt me with the warning.

I'm not importing YellowBox anywhere in my code, perhaps Sentry implementation is calling YellowBox?

```
YellowBox has been replaced with LogBox. Please call LogBox.ignoreLogs() instead.
- node_modules\react-native\Libraries\LogBox\LogBox.js:117:10 in registerWarning
- node_modules\react-native\Libraries\LogBox\LogBox.js:63:8 in warnImpl
- node_modules\react-native\Libraries\LogBox\LogBox.js:36:4 in console.warn
- node_modules\expo\build\environment\react-native-logs.fx.js:18:4 in warn
- node_modules\react-native\Libraries\YellowBox\YellowBoxDeprecated.js:25:6 in YellowBox.ignoreWarnings
* http://10.0.0.77:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:252511:43 in ReactNativeBackend
* http://10.0.0.77:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:249763:38 in BaseClient
* [native code]:null in construct
- node_modules\@sentry\browser\dist\client.js:38:32 in BrowserClient.prototype.showReportDialog
- node_modules\@sentry\browser\dist\client.js:48:25 in BrowserClient.prototype._prepareEvent
- node_modules\@sentry\utils\dist\path.js:5:0 in normalizeArray
- node_modules\@sentry\browser\dist\eventbuilder.js:19:26 in eventFromException
- node_modules\expo-permissions\build\Permissions.js:80:0 in _handlePermissionsRequestAsync
* App.js:8:0 in <global>
- node_modules\metro\src\lib\polyfills\require.js:321:11 in loadModuleImplementation
- node_modules\expo\AppEntry.js:3:0 in <global>
- ... 4 more stack frames from framework internals
```

### Expected Behavior vs Actual Behavior
No warning vs warning

**Comment by brentvatne** [comment]
can you share a mcve please?

**Comment by 9710willy** [comment]
Hi, sorry about that - it was my first time opening up an issue.

The example below can reproduce the problem.

`import React from "react";

import { Text } from "react-native";
import * as Sentry from "sentry-expo";

// Sentry.init({
//   dsn:
//     "https://7739bce434534f12903bf51b9135cc75@o451027.ingest.sentry.io/5436334",
//   enableInExpoDevelopment: true,
//   debug: true,
// });

export default function App() {
  return (
    <Text>AAAA</Text>
  );
}`

**My package.json**

`  "dependencies": {
    "@expo/vector-icons": "^10.2.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/viewpager": "^4.1.6",
    "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "@seznam/compose-react-refs": "^1.0.4",
    "cors": "^2.8.5",
    "dayjs": "^1.8.33",
    "expo": "^39.0.2",
    "expo-analytics-segment": "~9.0.0",
    "expo-av": "~8.6.0",
    "expo-camera": "~9.0.0",
    "expo-constants": "~9.2.0",
    "expo-image-picker": "~9.1.0",
    "expo-linear-gradient": "~8.3.0",
    "expo-notifications": "^0.7.2",
    "expo-random": "~9.0.0",
    "expo-secure-store": "~9.2.0",
    "expo-status-bar": "^1.0.0",
    "expo-video-thumbnails": "~4.3.0",
    "firebase": "^7.17.1",
    "firebase-admin": "^9.0.0",
    "formik": "^2.1.5",
    "lodash": "^4.17.19",
    "lodash.get": "^4.4.2",
    "lodash.reject": "^4.6.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "^0.63.2",
    "react-native-animatable": "^1.3.3",
    "react-native-elements": "^2.0.2",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-indicators": "^0.17.0",
    "react-native-modal": "^11.5.6",
    "react-native-multiple-tags": "0.0.4",
    "react-native-progress": "^4.1.2",
    "react-native-reanimated": "~1.13.0",
    "react-native-safe-area-context": "3.1.4",
    "react-native-safe-area-view": "^1.1.1",
    "react-native-screens": "~2.10.1",
    "react-native-text-gradient": "^0.1.7",
    "react-native-video": "^5.1.0-alpha8",
    "react-native-web": "~0.13.13",
    "sentry-expo": "^2.1.2",
    "yup": "^0.29.1"
  },`

**Test on physical device, ios 14**

**Comment by 9710willy** [comment]
Hi, sorry about that - it was my first time opening up an issue.

The example below can reproduce the problem.

```
`import React from "react";

import { Text } from "react-native";
import * as Sentry from "sentry-expo";

// Sentry.init({
//   dsn:
//     "MYSENTRYDSN",
//   enableInExpoDevelopment: true,
//   debug: true,
// });

export default function App() {
  return (
    <Text>AAAA</Text>
  );
}`
```

**My package.json**

```
`  "dependencies": {
    "@expo/vector-icons": "^10.2.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/viewpager": "^4.1.6",
    "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "@seznam/compose-react-refs": "^1.0.4",
    "cors": "^2.8.5",
    "dayjs": "^1.8.33",
    "expo": "^39.0.2",
    "expo-analytics-segment": "~9.0.0",
    "expo-av": "~8.6.0",
    "expo-camera": "~9.0.0",
    "expo-constants": "~9.2.0",
    "expo-image-picker": "~9.1.0",
    "expo-linear-gradient": "~8.3.0",
    "expo-notifications": "^0.7.2",
    "expo-random": "~9.0.0",
    "expo-secure-store": "~9.2.0",
    "expo-status-bar": "^1.0.0",
    "expo-video-thumbnails": "~4.3.0",
    "firebase": "^7.17.1",
    "firebase-admin": "^9.0.0",
    "formik": "^2.1.5",
    "lodash": "^4.17.19",
    "lodash.get": "^4.4.2",
    "lodash.reject": "^4.6.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "^0.63.2",
    "react-native-animatable": "^1.3.3",
    "react-native-elements": "^2.0.2",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-indicators": "^0.17.0",
    "react-native-modal": "^11.5.6",
    "react-native-multiple-tags": "0.0.4",
    "react-native-progress": "^4.1.2",
    "react-native-reanimated": "~1.13.0",
    "react-native-safe-area-context": "3.1.4",
    "react-native-safe-area-view": "^1.1.1",
    "react-native-screens": "~2.10.1",
    "react-native-text-gradient": "^0.1.7",
    "react-native-video": "^5.1.0-alpha8",
    "react-native-web": "~0.13.13",
    "sentry-expo": "^2.1.2",
    "yup": "^0.29.1"
  },`
```

**Tested on physical device, iOS 14**

**Comment by pdandradeb** [comment]
thanks @9710willy. I've just upgraded my app to SDK 39 and was having a hard time to identify what was causing this warning to show up.
I've tried to look at `expo-sentry` for Yellowbox usages but couldn't find any.

**Comment by SimonHausdorf** [comment]
Linking: #10276

**Comment by brentvatne** [comment]
hey @9710willy - thanks for sharing, that isn't particularly helpful for us to identify this issue though. please read the link i shared to the description of a mcve for more information on what we need to help here: https://stackoverflow.com/help/mcve. in simple terms, i need to be able to make this happen on my computer to help investigate it.

**Comment by SimonHausdorf** [comment]
@brentvatne https://github.com/SimonHausdorf/yellowBox/blob/master/App.js

Just install sentry
```
yarn add sentry-expo
````

and add this to your `app.js`

```javascript
import * as Sentry from "sentry-expo";

Sentry.init({
  dsn: "https://test@test.ingest.sentry.io/123",
  enableInExpoDevelopment: true,
  debug: true,
});
```

And the warning will be shown.

**Comment by SimonHausdorf** [comment]
This is responsible: https://github.com/getsentry/sentry-react-native/blob/b523bbc0857219c9e8b76cf924fa57e30252616a/src/js/backend.ts#L52

It was fixed in `sentry-react-native` 1.7.0 https://github.com/getsentry/sentry-react-native/blob/6254597e77a1c59430ad1b9cd5455d02f2734776/src/js/backend.ts#L54

**Comment by JacobJaffe** [comment]
>  I've tried to look at `expo-sentry` for Yellowbox usages but couldn't find any.

Note that this dependency is fixed in `sentry-expo` 3.x., while the last release is still on 2.1.2. (See: https://github.com/expo/sentry-expo/issues/140).

I'm hesitant to jump over to the 3.x release candidate, so instead I've added a simple patch-package to make the corresponding change in `@sentry/react-native`. This fixes the warning at the dependency without any potentially breaking changes from upgrading:

```.patch
diff --git a/node_modules/@sentry/react-native/dist/js/backend.js b/node_modules/@sentry/react-native/dist/js/backend.js
index cd0a3a1..8e5bcfc 100644
--- a/node_modules/@sentry/react-native/dist/js/backend.js
+++ b/node_modules/@sentry/react-native/dist/js/backend.js
@@ -3,7 +3,7 @@ import { Transports } from "@sentry/browser";
 import { BrowserBackend } from "@sentry/browser/dist/backend";
 import { BaseBackend, NoopTransport } from "@sentry/core";
 import { Severity } from "@sentry/types";
-import { Alert, YellowBox } from "react-native";
+import { Alert, LogBox } from "react-native";
 import { NativeTransport } from "./transports/native";
 import { NATIVE } from "./wrapper";
 /** The Sentry ReactNative SDK Backend. */
@@ -14,7 +14,7 @@ export class ReactNativeBackend extends BaseBackend {
         this._options = _options;
         this._browserBackend = new BrowserBackend(_options);
         // This is a workaround for now using fetch on RN, this is a known issue in react-native and only generates a warning
-        YellowBox.ignoreWarnings(["Require cycle:"]);
+        LogBox.ignoreLogs(["Require cycle:"]);
         if (this._options.enableNative) {
             // tslint:disable-next-line: no-floating-promises
             this._startWithOptions();
```

**Comment by Aryk** [comment]
I'm trying to update to sentry-expo 3.x RC, all of the methods except for "init" are no longer found. My guessing there are some API changes but cannot find any new documentation.

This is all I found: 

https://docs.sentry.io/platforms/react-native 

which has `Sentry.captureException` and all the old methods. What is the "new way" for Sentry-Expo?

**Comment by aav7fl** [comment]
> I'm trying to update to sentry-expo 3.x RC, all of the methods except for "init" are no longer found. My guessing there are some API changes but cannot find any new documentation.
> 
> This is all I found:
> 
> https://docs.sentry.io/platforms/react-native
> 
> which has `Sentry.captureException` and all the old methods. What is the "new way" for Sentry-Expo?

@Aryk I think you may have wanted to look at https://github.com/expo/sentry-expo/ instead?

One of the [breaking changes from the changelog](https://github.com/expo/sentry-expo/blob/1ae09d34365b33d3ffa5afe96ad4f7323edfb3dd/CHANGELOG.md#-breaking-changes) is currently:

> - Exports from `@sentry/react-native` or `@sentry/browser` are now namespaced.
> 
>   ```js
>   import { Native, Browser } from 'sentry-expo';
> 
>   const { ReactNativeClient } = Native;
>   const { Transports } = Browser;
>   ```

When we upgrade to `sentry-expo@3.0.0-rc3` we found all of our exports (aside from `init`) had been folded into `Native` from `sentry-expo`. 

Try importing that instead of `React` for the missing methods and I think that should cover most/all of them.

**Comment by cruzach** [comment]
@JacobJaffe no need for hesitation on upgrading to `sentry-expo@3.0.0-rc3`, it's all set to go. There's still a small bug which is why I'm not promoting to `latest` just yet, need to wait for an upstream PR ( https://github.com/getsentry/sentry-react-native/pull/1084) to land and be published

**Comment by Svarto** [comment]
@cruzach I am still having this error with sentry-expo@3.0.0-rc3. Not sure if it is related to sentry-expo, but the trace goes through @sentry in there?

```
YellowBox has been replaced with LogBox. Please call LogBox.ignoreLogs() instead.
- node_modules/react-native/Libraries/LogBox/LogBox.js:117:10 in registerWarning
- node_modules/react-native/Libraries/LogBox/LogBox.js:63:8 in warnImpl
- node_modules/react-native/Libraries/LogBox/LogBox.js:36:4 in console.warn
- node_modules/expo/build/environment/react-native-logs.fx.js:18:4 in warn
- node_modules/react-native/Libraries/YellowBox/YellowBoxDeprecated.js:25:6 in YellowBox.ignoreWarnings
* http://10.0.0.99:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:228016:43 in ReactNativeBackend
- node_modules/@sentry/core/dist/baseclient.js:50:8 in BaseClient
* [native code]:null in construct
* http://10.0.0.99:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:228375:321 in _createSuperInternal
- node_modules/@sentry/react-native/dist/js/client.js:15:25 in ReactNativeClient#constructor
- node_modules/@sentry/core/dist/sdk.js:15:20 in initAndBind
* http://10.0.0.99:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:228496:26 in init
* App.js:30:11 in <global>
- node_modules/metro/src/lib/polyfills/require.js:321:11 in loadModuleImplementation
- node_modules/expo/AppEntry.js:3:0 in <global>
- node_modules/metro/src/lib/polyfills/require.js:321:11 in loadModuleImplementation
- node_modules/metro/src/lib/polyfills/require.js:201:44 in guardedLoadModule
* http://10.0.0.99:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:278914:3 in global code
```

**Comment by mattrabe** [comment]
Thanks @aav7fl for clarifying how to use `sentry-expo` 3.0. To paraphrase - **to get rid of the YellowBox warnings when using sentry-expo:**

1. Switch to the latest 3.x sentry-expo (currently at 3.0.0-rc4): `"sentry-expo": "3.0.0-rc4"` in package.json
1. Change any uses like this:
    ```
    import * as Sentry from 'sentry-expo'
    ...
    Sentry.captureException(error)
    ```
    to this:
    ```
    import { Native as Sentry } from 'sentry-expo'
    ...
    Sentry.captureException(error)
    ```
    or, if your prefer, this:
    ```
    import * as Sentry from 'sentry-expo'
    ...
    Sentry.Native.captureException(error)
    ```

-----

If you happen to use `redux-sentry-middleware` you may need to also ensure that you pass the correct object to `createSentryMiddleware()`. If, like me, you both `init` Sentry and define your middleware in the same file (e.g. configureStore.js), you'll want to make sure you make this change: ~~`createSentryMiddleware(Sentry ...`~~ -> `createSentryMiddleware(Sentry.Native ...`. I created a documentation PR on that repo here: https://github.com/vidit-sh/redux-sentry-middleware/pull/26

**Comment by cruzach** [comment]
`sentry-expo@latest` (3.0.2) has been released, please enjoy 😄 and thanks for the patience

**Comment by pdugan20** [comment]
@cruzach no thank YOU!

**Comment by darrylyoung** [comment]
> sentry-expo@latest (3.0.2) has been released, please enjoy 😄 and thanks for the patience on this one

@cruzach Thank you! Have a nice weekend.

**Comment by gasolin** [comment]
As @mattrabe said, general import need to change to

```js
import { Native as Sentry } from 'sentry-expo'
...
Sentry.captureException(error)
```

To init Sentry, can use

```
import { init as initSentry } from 'sentry-expo'

initSentry({
...
})
```

Note that `setRelease` and `setDist` are deprecated and changed to the config params (as `release`, `dist`) that can pass to `init`
https://github.com/getsentry/sentry-react-native/pull/1009/files

**Comment by cruzach** [comment]
I update our docs for this new major version now, as well, in case anyone's having trouble with anything- https://docs.expo.io/guides/using-sentry/
