### ISSUE TITLE
Localization.region is undefined on Android

### ISSUE THREAD

**Issue by Badyl1g** [expo/expo#10347]
### Summary of Issue 
Localization.region is `undefined` on Android

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.27.4 environment info:
    System:
      OS: Windows 10 10.0.17763
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.3
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.5429.30.34.5452501
    npmPackages:
      expo: ^36.0.0 => 36.0.0
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-native-web: ^0.11.7 => 0.11.7
    Expo Workflow: managed

### Reproducible Demo
https://snack.expo.io/@wgalbarczyk/localization-repro

 
### Steps to Reproduce
1. Import Localization package and extract region (see App.js in the linked snack above)
2. Display region on both platforms

### Expected Behavior vs Actual Behavior
Region should be displayed on both platforms correctly. Right now it works only on iOS and is `undefined` on Android

**Comment by byCedric** [comment]
Hi @Badyl1g! Thanks for the issue report. Unfortunately, as [the docs mention](https://docs.expo.io/versions/v36.0.0/sdk/localization/#localizationregion), we do not return the region on Android. I've created a PR to add support for that, but that probably won't be backported to SDK 36.

Hope this helps!

**Comment by butri71** [comment]
Hi @byCedric  Any news on this? I'm on the latest SDK 40 and still not working. Thanks

**Comment by IjzerenHein** [comment]
Hi! This has been fixed in #11663 and will be released with SDK 41.

**Comment by butri71** [comment]
Hi, Fantastic, thanks for the heads up!

**Comment by tobzy** [comment]
Same issue. Just commenting to be aware of any comments added later.

**Comment by Stevemoretz** [comment]
I'm on sdk 42 it's working on my android 7 huawie mate 8.You forgot to update the docs though.

**Comment by IjzerenHein** [comment]
@Stevemoretz which part of the docs is incorrect according to you?

**Comment by IjzerenHein** [comment]
Closing this as this issue has been resolved

**Comment by Stevemoretz** [comment]
> @Stevemoretz which part of the docs is incorrect according to you?

Maybe it isn't incorrect, but according to my tests on from Android 7 physical device to andorid 8,9,10 simulators, all returns US and none returned null, docs mentions that Android might return null, it that is not the case anymore the docs should be updated to remove that and add Android implementation information, currently it says where this value comes from ios ie the region settings but for android there is no information.

**Comment by IjzerenHein** [comment]
Depending on the locale set on the Android device, it will know its country (=region). For instance, if the locale consists only of a language-tag (eg `en`), it does not know the country and region would be `null`. The Android docs don't specifically mention whether the default-locale always contains a country-code. However, the native [Locale.getCountry()](https://developer.android.com/reference/java/util/Locale#getCountry()) API method does specify that it may return `an empty string if none is defined`, in which case the country/region code cannot be obtained.

Android code:
https://github.com/expo/expo/blob/master/packages/expo-localization/android/src/main/java/expo/modules/localization/LocalizationModule.java#L130-L145

So unless there is some proof that the default-locale always contains a country-code, I think the docs are correct.

**Comment by Stevemoretz** [comment]
> Depending on the locale set on the Android device, it will know its country (=region). For instance, if the locale consists only of a language-tag (eg `en`), it does not know the country and region would be `null`. The Android docs don't specifically mention whether the default-locale always contains a country-code. However, the native [Locale.getCountry()](https://developer.android.com/reference/java/util/Locale#getCountry()) API method does specify that it may return `an empty string if none is defined`, in which case the country/region code cannot be obtained.
> 
> Android code:
> https://github.com/expo/expo/blob/master/packages/expo-localization/android/src/main/java/expo/modules/localization/LocalizationModule.java#L130-L145
> 
> So unless there is some proof that the default-locale always contains a country-code, I think the docs are correct.

Sounds pretty right I thought this issue was the about changing the way that it works so it always returns the right thing but sounds like that part hasn't changed, and since I have English in all my devices in returns US.

If it's actually not possible to do that on andorid, how does whatsapp and telegram know your phone prefix or country, the first time you open their apps, that has been a question I've had for a long time.

**Comment by IjzerenHein** [comment]
> f it's actually not possible to do that on andorid, how does whatsapp and telegram know your phone prefix or country, the first time you open their apps, that has been a question I've had for a long time.

good question. Like I said, it's possible that the default locale always has a country-code 🤷‍♂️ And apart from the locale there are also cellular APIs  from which you can read the country-code: https://docs.expo.dev/versions/latest/sdk/cellular/

**Comment by Stevemoretz** [comment]
> > If it's actually not possible to do that on andorid, how does whatsapp and telegram know your phone prefix or country, the first time you open their apps, that has been a question I've had for a long time.
> 
> good question. Like I said, it's possible that the default locale always has a country-code 🤷‍♂️ And apart from the locale there are also cellular APIs from which you can read the country-code: https://docs.expo.dev/versions/latest/sdk/cellular/

Thank you so much for the reply, no whatsapp and telegram don't give me US and I'm not in US, but Localization.region gives me US because of my locale which is en-US, cellular looks fantastic thank you for introducing it, I had never seen it myself.
