### ISSUE TITLE
SDK 39++ bug fix release

### ISSUE THREAD

**Issue by ide** [expo/expo#10464]
* Standalone apps built for SDK 39 will only pull releases from the "default" release channel #10304
* Standalone apps for iOS will not read assets correctly in exported projects (with expo export) #10342
* Remote JS debugging on Android in the Expo client crashes the app #10284
  * fixed by https://github.com/expo/expo/pull/10383 and https://github.com/expo/expo/pull/10381, commits cherry-picked to `sdk-39` ✅ 
* DocumentPicker on iOS 14 crashes in Expo client on iOS 14 #10303
  * fixed by https://github.com/expo/expo/pull/10327, change cherry-picked to `sdk-39` ✅
* TaskManager crashes on Android in release mode #9570, #9288
  * **probably** fixed by https://github.com/expo/expo/pull/10409, https://github.com/expo/expo/pull/10410 and https://github.com/expo/expo/pull/10411 (and then https://github.com/expo/expo/pull/10421), 2 out of 3 commits cherry-picked to `sdk-39` (pending: https://github.com/expo/expo/pull/10421) 🔜 
* android.splash.image is not being used in place of splash.image #10382 
* Linking.getInitialUrl() on Android returns null rather than the originating link #10323 
* invalid request token error #10313 - cherry-pick [this react native commit](https://forums.expo.io/t/blob-stopped-working-in-expo-sdk-39/43516) to our fork to fix
* Cherry-pick this expo-notifications pure JS fix to sdk-39: https://github.com/expo/expo/pull/10478
* Problems with the large icon in standalone apps, part of https://github.com/expo/expo/issues/10469
  * fixed by https://github.com/expo/expo/pull/10492, https://github.com/expo/expo/pull/10471,  changes cherry-picked to `sdk-39`

**Comment by himrocks33** [comment]
@ide Would this not be 39.0.4? It appears the current released version is already 39.0.3?

**Comment by ide** [comment]
The title refers to an abstract version number, not the expo package.

**Comment by ejia-techsursolutions** [comment]
Is this released already?

**Comment by ide** [comment]
No this is an in-progress issue.

**Comment by natemartins** [comment]
Opening the app on an iOS device in development throws this error: 
- Unable to start your application. Please refer to [https://expo.fyi/no-registered-application](https://expo.fyi/no-registered-application) for more information.
The information at the provided URL doesn't help.

This error does occur on android. Instead, Android is throwing a Splash Screen error.
When is the fix going to be ready? My client is on my neck to deploy the app already. I can't do that if these errors are not fixed.

**Comment by ide** [comment]
If you can trace your issue back to one of the ones in the first post, it will be fixed with an upcoming release. It sounds like you may need to debug further, though, to narrow the cause down.

For Android there is a splash screen configuration fix coming, but not one that would fix an error - that probably requires a deeper understanding of the cause too. It's a lot easier to help if you can identify the root cause or one close to it.

We are prioritizing the fixes in the first post and I'd expect them to take a couple of days. The app review process is unpredictable and at best (if lucky) will take a few hours but typically takes a day or two.

**Comment by natemartins** [comment]
I'm pretty sure it's not an error on my part. I did not have those issues in SDK 38. The issues occurred the moment I updated to SDK 39

**Comment by ide** [comment]
That's probably the best course of action for now. Hopefully you can save your 39 work on one branch and cherry-pick application code back to a new branch from your last working 38 state.

**Comment by brentvatne** [comment]
@natemartins - this is a common issue when upgrading and not necessarily a bug in sdk 39 but rather an issue in your app code that resulted from updating a variety of libraries. perhaps the issue is in one of your project dependencies, please read https://expo.fyi/no-registered-application and try narrowing down the source of the error [as described in this doc](https://docs.expo.io/workflow/debugging/#development-errors). i'm going to hide comments above because they are not related to this issue. if you do determine while debugging that this you have discovered a bug and you've been able to isolate it, please create a new issue and fill out the issue template so we have the information that we need to help.

**Comment by barthap** [comment]
I think we should also consider adding #10488, a few people had problems with that, I'll PR a fix today.

**Comment by yuraxdrumz** [comment]
Hey, guys. Thanks for the hard work!
Will the fix for splash screen be included in this release (https://github.com/expo/expo/issues/10263)?
Looks like the fix for it was introduced in expo-splash-screen@0.7.1 but I cant install it yet, as I probably need the native dependencies as well.

**Comment by lukmccall** [comment]
I think we should also fix https://github.com/expo/expo/issues/10469.

This problem consists of two minor ones:
- In standalone bundle, the image on the right can not be removed (or changed to something other than notification.icon) when remote notification is displayed. - It was fixed by https://github.com/expo/expo/commit/710776d3e60b3b8554288cd44e81cbc7762701b2
- In standalone bundle, the icon and text coloring is different for local and remote notifications. - still in progress

**Comment by himrocks33** [comment]
@ide Is there an idea of when this may be released?  The document picker crashing is holding up out deployment. 
Thank you,
Ben

**Comment by ide** [comment]
The estimate is sometime within the next 1-5 days.

**Comment by brentvatne** [comment]
Hi everyone! I am both pleased and relieved to be able to tell you that we have now rolled out the following fixes for SDK 39:

- expo-updates:
    - Standalone apps built for SDK 39 now properly read updates from the release channel they are built against ([issue](https://github.com/expo/expo/issues/10304)).
    - Standalone apps for iOS will read assets correctly from exported projects (built with `expo export`), and iOS and Android standalone apps support `assetUrlOverride` with absolute urls. ([issue](https://github.com/expo/expo/pull/10342), [issue](https://forums.expo.io/t/android-expo-updates-issues/38250))
    - `Updates.reloadAsync()` is supported in development once again. ([pr](https://github.com/expo/expo/pull/10310))
- expo-splash-screen:
    - `android.splash.hdpi` and other `*dpi` properties are used as expected in Expo client on Android. ([issue](https://github.com/expo/expo/issues/10382))
    - iOS and Android splash screen image no longer flickers after completing bundle download within Expo client ([issue](https://github.com/expo/expo/issues/10510))
    - Configuration of splash screen in Android standalone apps now works the same as before. ([issue](https://github.com/expo/expo/issues/10382))
- react-native:
    - Fixed regression in Blob support. ([issue](https://github.com/expo/expo/issues/10313))
    - TouchableOpacity press-in delay removed. ([issue](https://forums.expo.io/t/updating-to-39-0-0-causes-touchableopacity-to-not-work-100/43221))
    - Fix Xiaomi TextInput native crash. ([issue](https://github.com/facebook/react-native/issues/27204))
- Remote JS debugging on Android no longer crashes the Expo client app ([issue](https://github.com/expo/expo/issues/10284)).
- DocumentPicker on iOS 14 no crashes in Expo client on iOS 14, also fixed issue with being unable to open it more than once on iOS 14. ([issue](https://github.com/expo/expo/issues/10303)).
- TaskManager no longer crashes on Android in release mode. (issue [1](https://github.com/expo/expo/issues/9570), [2](https://github.com/expo/expo/issues/9288))
- `Linking.getInitialUrl()` on Android returns the correct deep link URL ([issue](https://github.com/expo/expo/issues/10323)).
- Published apps that throw exceptions before loading no longer hang on splash screen in Expo client, instead they will show an error screen. In standalone apps, the app will crash rather than hang (as expected). ([issue](https://github.com/expo/expo/issues/10463))
- Updated Facebook Audience Network SDK ([pr](https://github.com/expo/expo/pull/10430)).
- Fix regression in notification icons with expo-notifications. ([issue](https://github.com/expo/expo/issues/10469))
- QR code scanner to scan to open apps in Expo client for Android no longer skewed on some devices. ([issue](https://github.com/expo/expo/issues/10270))

### Next steps

- Download the latest iOS and Android clients from the stores.
- Install the latest iOS and Android clients with `expo client:install:ios` and `expo client:install:android`

### If you previously upgraded your project to SDK 39

- For managed apps, change your `react-native` version to [https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz](https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz). For bare apps, recommend using `react-native` 0.63.3.
- Run `yarn upgrade` to update to the latest version of packages in your project for their current semantic version range. `npm` does not have an equivalent command, so you can delete your `package-lock.json` and `node_modules` and run `npm install` again.
- Build your standalone apps again.

Thank you again for your patience and detailed issue reports! We'll follow up again soon with plans for avoiding shipping significant regressions again in the future.

**Comment by abudhia-oyo** [comment]
Hi, when trying to upgrade I still get the 39.0.3 version. Also don't see the 39.0.4 version [here](https://www.npmjs.com/package/expo).

Am I missing anything?

**Comment by brentvatne** [comment]
@abudhia-oyo - there is no 39.0.4

**Comment by abudhia-oyo** [comment]
Okay. So it will come as the same release number?

However on the Facebook SDK version fix, it's still picking the old "expo-ads-facebook": "~8.4.0" & not the 8.5.0 by default.

**Comment by brentvatne** [comment]
@abudhia-oyo - in the managed workflow the changes are all included on the native side, so it doesn't matter what your JavaScript dependencies are in many cases (and indeed in almost all of the cases mentioned here except for the react-native version, which we explicitly ask you to update, and expo-updates version, which will be pulled in when you follow the `yarn upgrade` step mentioned above).

**Comment by abudhia-oyo** [comment]
On force editing the  expo-ads-facebook version to next, I get this message:
Some of your project's dependencies are not compatible with currently installed expo package version:
 - expo-ads-facebook - expected version range: ~8.4.0 - actual version installed: ~8.5.0

**Comment by brentvatne** [comment]
@abudhia-oyo - i will repeat myself: you do not need to update that package in the managed workflow, those changes are on the native side.

**Comment by ac15aeq** [comment]
Hi,

Might be a silly question, but how do I do this?:
`For managed apps, change your react-native version to https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz`

I tried doing expo cli upgrade and then expo upgrade but that didn't seem to get the new version, still says 39.0.0.

Do I need to uninstall current react-native and somehow install this folder?? I've only npm installed packages before, I am fairly new to this type of development.

Thanks

**Comment by brentvatne** [comment]
@ac15aeq - update the version of react-native in package.json to `"https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz"` and then run `npm install` or `yarn`. the sdk version is still 39.0.0, this is just bumping the react-native version.

**Comment by gregfenton** [comment]
> Might be a silly question, but how do I do this?:

@ac15aeq - steps:
1. edit `package.json` and in the "scripts" section set the value of `react-native` to:
   ```"react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz",```
2. run `npm install`   (or, alternatively, `yarn install`)
3. to confirm you now have the correct version installed, you can use `npm ls react-native`.  I believe that it will show:
   `react-native@0.63.2`

**Comment by kailo777** [comment]
Hey @all, 

package.json looks now like that:

  "dependencies": {
    "expo": "~39.0.3",
    "expo-status-bar": "~1.0.2",
    "react": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz",
    "react-native-web": "~0.13.7"
  },

expo --version => 3.27.13 



1. I delete the package-lock.json & node_modules
2. run npm install
3. run npm ls react-native => react-native@0.63.2

App still crashes/shuts down when remote js debug is activated on SDK 39 for Android

**Comment by brentvatne** [comment]
@kailo777 - you need to install the latest version of expo client as mentioned in my comment above:

> ### Next steps
> - Download the latest iOS and Android clients from the stores.
> - Install the latest iOS and Android clients with expo client:install:ios and expo client:install:android

**Comment by Razorholt** [comment]
What does it mean?

```
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting react-native@https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz:
npm ERR! Verification failed while extracting react-native@https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz:
npm ERR! sha512-xb7qKCp5pJotQLMUQkF2vr6DxRFVkUeXj3m+tjrBXL8l3FMjHwR3hOiXmTPOGJXKszwvv6CK2yU9RLzh76g4/g== integrity checksum failed when using sha512: wanted sha512-xb7qKCp5pJotQLMUQkF2vr6DxRFVkUeXj3m+tjrBXL8l3FMjHwR3hOiXmTPOGJXKszwvv6CK2yU9RLzh76g4/g== but got sha512-1Zi/pl7HQVG0I/+feIZJzv6MTHiS4w7dOESx/PTrl2Yblr8ZxCvOFnDYyId0k4QAoKH+vbftc5S39bqVXvwgRg==. (5692740 bytes)
```

**Comment by brentvatne** [comment]
@Razorholt - sorry i'm not familiar with that, you might want to try `npm cache clean -g` and/or `npm cache clean` in your project directory

**Comment by calvinkei** [comment]
@brentvatne thanks for the update! do we have to rebuild and re-upload to app store for production app?

**Comment by brentvatne** [comment]
@calvinkei - yes, please refer to the instructions above:


> ### If you previously upgraded your project to SDK 39
>
> - For managed apps, change your `react-native` version to [https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz](https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz). For bare apps, we recommend using `react-native` 0.63.3.
> - Run `yarn upgrade` to update to the latest version of packages in your project for their current semantic version range. `npm` does not have an equivalent command, so you can delete your `package-lock.json` and `node_modules` and run `npm install` again.
> - Build your standalone apps again.

in particular, the final point
```

**Comment by buslocteam** [comment]
we have already upgraded to expo 39,
we followed the above mentioned instructions and the react-native version is changed to 39.0.3.

package lock.json and node_modules are removed
npm install is done 
expo version remains 30.0.0

Is that ok or do we need to update expo version also in package.json to 39.0.3

**Comment by nightmarelie** [comment]
> Hey @ALL,
> 
> package.json looks now like that:
> 
> "dependencies": {
> "expo": "~39.0.3",
> "expo-status-bar": "~1.0.2",
> "react": "16.13.1",
> "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz",
> "react-native-web": "~0.13.7"
> },
> 
> expo --version => 3.27.13
> 
> 1. I delete the package-lock.json & node_modules
> 2. run npm install
> 3. run npm ls react-native => react-native@0.63.2
> 
> App still crashes/shuts down when remote js debug is activated on SDK 39 for Android

I faced with the same behavior

**Comment by girishjjain** [comment]
Hi @brentvatne, I followed your steps to upgrade and got app updated but I don't see this [fix](https://github.com/expo/expo/issues/8237) working. Is that fix not available as part of this release? or do I need to follow any additional steps for it? Thanks.

Note: I did download the latest client on device/simulator to verify the fix.

**Comment by xnaveira** [comment]
@nightmarelie Did you followed this step to upgrade the mobile client? That helped me.

>Install the latest iOS and Android clients with expo client:install:ios and expo client:install:android

**Comment by nightmarelie** [comment]
> @nightmarelie Did you followed this step to upgrade the mobile client? That helped me.
> 
> > Install the latest iOS and Android clients with expo client:install:ios and expo client:install:android

Yes, it helped. I thought a simple removal of the client with subsequent installation would be enough, but no!

**Comment by kailo777** [comment]
@nightmarelie @xnaveira 

I also try it with expo client:install:android

expo client:install:android
You are currently using SDK 39.0.0. Would you like to install client 2.17.4 released for this SDK? 

the expo --version 3.27.13

What did I miss?

**Comment by donni106** [comment]
> @nightmarelie @xnaveira
> 
> I also try it with expo client:install:android
> 
> expo client:install:android
> You are currently using SDK 39.0.0. Would you like to install client 2.17.4 released for this SDK?
> 
> the expo --version 3.27.13
> 
> What did I miss?

`2.17.4` is the version of the Expo Client App on the Phone.
`3.27.13` is the Expo CLI version you are using in the terminal.

**Comment by nightmarelie** [comment]
> @nightmarelie @xnaveira
> 
> I also try it with expo client:install:android
> 
> expo client:install:android
> You are currently using SDK 39.0.0. Would you like to install client 2.17.4 released for this SDK?
> 
> the expo --version 3.27.13
> 
> What did I miss?

I have the following versions:
`2.17.4` - client version
`3.27.13` - cli
and everything works

try to start with `-c` flag. `yarn start -c` (Clear the Metro bundler cache)

**Comment by svaldi** [comment]
Thank you so much @brentvatne @ide and all the ones involve on this new release. 👍

**Comment by sreimer15** [comment]
I've followed the instructions here and i'm still getting errors when trying to deploy my project to a specific release channel. For expo 39.
The android app deploys correctly to the release channel but the ios app does not. It loads the splash screen for a second and then shows a completely blank screen. 
I can run the app locally however.
No errors appear in logs or anywhere else. Is there anyway I can debug this a little bit better? Thank you!

**Comment by gang544043963** [comment]
Hi, I've followed the instructions to update the SDK to 39.0.3, and I can check the version from 'node_modules/expo' and 'node_modules/react-native', expo is 39.0.3, react-native is 0.63.2.  
But, expo version in my package.json is still 39.0.0 ("expo": "^39.0.0"), and when I build my project, I got many log info like "Expo SDK: 39.0.0", "sdkVersion": "39.0.0".
I'm not sure whether I update the SDK version successful.

**Comment by bcteam2020** [comment]
@gang544043963 Change the "expo": "^39.0.0" to 39.0.3 manually and then delete package-lock.json,  node_modules, npm install
it should work

**Comment by gang544043963** [comment]
@bcteam2020 I'v tried this, the same result.

**Comment by bcteam2020** [comment]
@gang544043963 
Try these steps

make sure expo-cli is 3.27.14
expo client (uninstall and install)
create new build
publish update

**Comment by gang544043963** [comment]
Thank you @bcteam2020  for your kindly reply. 
One more question,  is it display "Expo SDK: 39.0.0" or "Expo SDK: 39.0.3" when you run expo publish in terminal?
Mine is "Expo SDK: 39.0.0". (My OTA just work well in default channel, so I can make sure the SDK hasn't update successfully)
Thanks again!

**Comment by dante314** [comment]
Hola, acabo de solucionar mi problema 

**Problema**:
==========
[Unhandled promise rejection: Error: No native splash screen registered for provided activity. Please configure your application's main Activity to call 'SplashScreen.show' (https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-configure-android).]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:103:50 in promiseMethodWrapper

**Causa:**
==========
`
import React, { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import CategoriesScreen from './screens/CategoriesScreen';
// npm install --save expo-font o expo install --save expo-font
import * as Font from 'expo-font';
import { AppLoading } from 'expo';

const fetchFont = () => {
  return Font.loadAsync({
    'open-sans': require('./assets/fonts/OpenSans-Regular.ttf'),
  });
};

export default function App() {
  const [fontLoaded, setFontLoaded] = useState(false);

  if (!fontLoaded) {
    return (
    <AppLoading
      startAsync={fetchFont}
      onFinish={() => setFontLoaded(true)}
    />)
  }
  return (
    <View >
      <CategoriesScreen />
    </View>
  );
}

const styles = StyleSheet.create({

});
`

**Salida en terminal:**
================

[Unhandled promise rejection: Error: No native splash screen registered for provided activity. Please configure your application's main Activity to call 'SplashScreen.show' (https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-configure-android).]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:103:50 in promiseMethodWrapper
- node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
- node_modules/expo-splash-screen/build/SplashScreen.js:23:7 in preventAutoHideAsync
- node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
- node_modules/regenerator-runtime/runtime.js:293:29 in invoke
- node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
- node_modules/regenerator-runtime/runtime.js:154:27 in invoke
- node_modules/regenerator-runtime/runtime.js:189:16 in PromiseImpl$argument_0
- node_modules/react-native/node_modules/promise/setimmediate/core.js:45:6 in tryCallTwo
- node_modules/react-native/node_modules/promise/setimmediate/core.js:200:22 in doResolve
- node_modules/react-native/node_modules/promise/setimmediate/core.js:66:11 in Promise
- node_modules/regenerator-runtime/runtime.js:188:15 in callInvokeWithMethodAndArg
- node_modules/regenerator-runtime/runtime.js:211:38 in enqueue
- node_modules/regenerator-runtime/runtime.js:238:8 in exports.async
- node_modules/expo-splash-screen/build/SplashScreen.js:23:7 in preventAutoHideAsync
- node_modules/expo/build/launch/AppLoadingNativeWrapper.js:5:8 in AppLoading#constructor
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:7655:17 in constructClassInstance
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:12377:26 in updateClassComponent
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:19181:22 in beginWork$1
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18085:22 in performUnitOfWork
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18013:38 in workLoopSync
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:17977:18 in renderRootSync
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:17674:33 in performSyncWorkOnRoot
* [native code]:null in performSyncWorkOnRoot
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5321:31 in runWithPriority$argument_1
- node_modules/scheduler/cjs/scheduler.development.js:653:23 in unstable_runWithPriority
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5316:21 in flushSyncCallbackQueueImpl
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5304:28 in flushSyncCallbackQueue
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:17125:30 in scheduleUpdateOnFiber
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:20527:14 in updateContainer
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:21068:17 in render
- node_modules/react-native/Libraries/ReactNative/renderApplication.js:54:4 in renderApplication
- node_modules/react-native/Libraries/ReactNative/AppRegistry.js:117:25 in runnables.appKey.run
- node_modules/react-native/Libraries/ReactNative/AppRegistry.js:213:4 in runApplication
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:416:4 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:109:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:108:4 in callFunctionReturnFlushedQueue
* [native code]:null in callFunctionReturnFlushedQueue

[Unhandled promise rejection: Error: No native splash screen registered for provided activity. Please configure your application's main Activity to call 'SplashScreen.show' (https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-configure-android).]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:103:50 in promiseMethodWrapper
- node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
- node_modules/expo-splash-screen/build/SplashScreen.js:29:7 in hideAsync
- node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
- node_modules/regenerator-runtime/runtime.js:293:29 in invoke
- node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
- node_modules/regenerator-runtime/runtime.js:154:27 in invoke
- node_modules/regenerator-runtime/runtime.js:189:16 in PromiseImpl$argument_0
- node_modules/react-native/node_modules/promise/setimmediate/core.js:45:6 in tryCallTwo
- node_modules/react-native/node_modules/promise/setimmediate/core.js:200:22 in doResolve
- node_modules/react-native/node_modules/promise/setimmediate/core.js:66:11 in Promise
- node_modules/regenerator-runtime/runtime.js:188:15 in callInvokeWithMethodAndArg
- node_modules/regenerator-runtime/runtime.js:211:38 in enqueue
- node_modules/regenerator-runtime/runtime.js:238:8 in exports.async
- node_modules/expo-splash-screen/build/SplashScreen.js:29:7 in hideAsync
- node_modules/expo/build/launch/AppLoadingNativeWrapper.js:15:33 in setTimeout$argument_0
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:130:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:383:16 in callTimers
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:416:4 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:109:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:108:4 in callFunctionReturnFlushedQueue
* [native code]:null in callFunctionReturnFlushedQueue

**HIlo seguido para solucionarlo:**
=======================
revisar file >  package.json:  

`  "dependencies": {
    "expo": "~39.0.3",
    "expo-status-bar": "~1.0.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz",
    "react-native-web": "~0.13.12"
  },`

expo --version => 3.27.14

$ rm -rf node_modules , $ rm package-lock.json
$ npm ls react-native => react-native@0.63.2
$ expo client:install:ios and $ expo client:install:android // trabajo en linux y solo uso android
$ npm install 
$ expo start

PDT: Antes de empezar todo este proceso, había corrido: $ npm i -g expo-cli@latest

Suerte!

**Comment by summerkiflain** [comment]
@brentvatne `https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz` is installing `react-native 0.62.2` for managed workflows, I have tried `expo upgrade`, `yarn upgrade`, `yarn i` after removing `node_modules` and `yarn.lock` file even cleared yarn cache with `yarn cache clean` but it always fetches `0.62.2`, shouldn't it get `0.63.3` for managed workflows?

**Comment by daniel** [comment]
Should I upgrade the expo package to 39.0.3 too? The instructions above doesn't mention it.

**Comment by brentvatne** [comment]
@daniel - it doesn't matter. we didn't mention it in instructions because it's not needed

**Comment by brentvatne** [comment]
@summerkiflain - the version is 0.62.2 but we cherry-picked in some commits from 0.63.3, which was a small patch release.

**Comment by brentvatne** [comment]
hi all, i just wanted to update you with some news on what we'll be doing to help ensure stability and reliability in future releases. starting with sdk 40, we're going to try out a beta release period final to the sdk release. you can read more about this in this blog post: [Coming soon: Beta release period for Expo SDK](https://blog.expo.io/coming-soon-beta-release-period-for-expo-sdk-965ab3bd177f)

i'm going to lock this thread now because i believe everything has been covered and it's becoming inactive. please create a new issue and follow the issue template if you were intending on replying in here.
