### ISSUE TITLE
Translucent splash status bar works in managed app but not in bare app

### ISSUE THREAD

**Issue by kevgrig** [expo/expo#11604]
### Summary of Issue 

In a managed app, the status bar on Android is translucent while the splash screen is up, as desired:

![Screenshot_1610436423](https://user-images.githubusercontent.com/6432587/104283919-1c1d1f00-5466-11eb-94b5-32873483da6c.png)

However, after ejecting and launching from Android Studio, it is not translucent and the [documented options](https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-optional-customize-statusbar-1) 1 (`<item name="android:windowFullscreen">true</item>`) and 4 (`statusBarTranslucent=true`) don't work:

![Screenshot_1610436708](https://user-images.githubusercontent.com/6432587/104284042-4373ec00-5466-11eb-9230-9c20b18a82dd.png)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
$ expo diagnostics

  Expo CLI 4.0.17 environment info:
    System:
      OS: Linux 5.9 Fedora 33 (Workstation Edition) 33 (Workstation Edition)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.15.1 - /usr/bin/node
      Yarn: 1.22.10 - /usr/bin/yarn
      npm: 6.14.8 - /usr/bin/npm
    npmPackages:
      expo: ~40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.27.4
    Expo Workflow: bare
```

### Reproducible Demo

* Managed app: https://github.com/kevgrig/testsplash
* Ejected app: https://github.com/kevgrig/testsplash/tree/ejected

Code to delay the splash a bit:

```
import React from 'react';
import { Text, View } from 'react-native';
import * as SplashScreen from 'expo-splash-screen';

export default class App extends React.Component {
  state = {
    appIsReady: false,
  };
  
  async componentDidMount() {
    // Prevent native splash screen from autohiding
    try {
      console.log("Calling SplashScreen.preventAutoHideAsync");
      await SplashScreen.preventAutoHideAsync();
      console.log("Calling setTimeout");
      setTimeout(this.slowSplashCallback, 5000);
    } catch (e) {
      console.warn(e);
    }
  }

  slowSplashCallback = async () => {
    console.log("setTimeout finished");
    this.setState({ appIsReady: true }, async () => {
      await SplashScreen.hideAsync();
    });
  }

  render() {
    if (!this.state.appIsReady) {
      return null;
    }

    return (
      <View style={{ flex: 1, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' }}>
        <Text>testsplash</Text>
      </View>
    );
  }
}
```

Attempt at setting `statusBarTranslucent=true`: https://github.com/kevgrig/testsplash/blob/ejected/android/app/src/main/java/com/example/testsplash/MainActivity.java#L19

```
SplashScreen.show(this, SplashScreenImageResizeMode.COVER, ReactRootView.class, true);
```

Attempt at running the splash screen in full screen mode: https://github.com/kevgrig/testsplash/blob/ejected/android/app/src/main/res/values/styles.xml

```
  <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:textColor">#000000</item>
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="android:windowTranslucentStatus">true</item>
    <item name="android:windowFullscreen">true</item>
  </style>
```
 
### Steps to Reproduce

Run https://github.com/kevgrig/testsplash/tree/ejected from Android Studio in an Android emulator.

### Expected Behavior vs Actual Behavior

Expect translucent status bar in ejected app during splash.

**Comment by kevgrig** [comment]
I got this to work by removing `<item name="android:windowFullscreen">true</item>`, adding `<item name="android:statusBarColor">@android:color/transparent</item>` along the lines of option 3, and keeping `true` in `SplashScreen.show(this, SplashScreenImageResizeMode.COVER, ReactRootView.class, true)`: <https://github.com/kevgrig/testsplash/compare/ejected...fixed?expand=1>

Option 3 doesn't discuss using `@android:color/transparent` so that might be a helpful addition.

... if I'm doing this correctly:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<resources>
  <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:textColor">#000000</item>
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="android:windowTranslucentStatus">true</item>
  </style>
  <style name="Theme.App.SplashScreen" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:windowBackground">@drawable/splashscreen</item>
    <item name="android:statusBarColor">@android:color/transparent</item>
  </style>
</resources>
```

**Comment by AronBe** [comment]
This issue is still present, let me describe the behaviour and issues identified:

If the desired outcome of the application is to have `transparent` background a `translucent` status bar - ideally this behaviour would be setup before app launches and not once it mounts.
```
import { StatusBar } from 'expo-status-bar';
<StatusBar style="dark" backgroundColor="transparent" translucent />
```

The issue is that it cannot be replicated from `app.json` due to `translucent: true` setting overriding the `backgroundColor` creating the ugly status bar background. It even overrides the mounted statusBar setting.
```
  "androidStatusBar": {
      "barStyle": "dark-content",
      "translucent": true,
      "backgroundColor": "#00000000"
    },
```
<img src="https://user-images.githubusercontent.com/32416348/141088537-0eac22f2-de97-49dd-bd26-82923350fc89.jpg" height="400" />


It is because of this setting in `styles.xml` that the flag generates. 
`<item name="android:windowTranslucentStatus">true</item>`

When it is removed and the other setting generated is kept  `<string name="expo_splash_screen_status_bar_translucent" translatable="false">true</string>`, then the status bar behaves as `translucent` and `transparent` during the splashscreen. If the status bar is not set as translucent from the beginning, then the screen content will jump once it is mounted and set to translucent.

Is there any way to set `<string name="expo_splash_screen_status_bar_translucent" translatable="false">true</string>` without setting `<item name="android:windowTranslucentStatus">true</item>` in managed workflow?

**Comment by Aryk** [comment]
@AronBe - If you do end up using EAS...you can play with this config plugin:

This is what I have:

```js
const {
  AndroidConfig,
  withAndroidStyles,
} = require("@expo/config-plugins");

const withFullScreenDialogStyles = (config) => {
  return withAndroidStyles(config, async (config) => {
    config.modResults = await configureFullScreenDialog(config.modResults);
    return config;
  });
};

async function configureFullScreenDialog(
  styles
) {
  // Set the statusBarColor to transparent.
  const splashScreen = styles.resources.style.find(
    style => style.$.name === "Theme.App.SplashScreen"
  );

  if (splashScreen) {
    splashScreen.item.push(
      AndroidConfig.Resources.buildResourceItem({
        name: 'android:statusBarColor',
        value: '@android:color/transparent'
      })
    );
  }

  // Go through and do what he suggests:
  // https://github.com/expo/expo/issues/11604#issuecomment-964953312
  const appTheme = styles.resources.style.find(
    style => style.$.name === "AppTheme"
  );
  if (appTheme) {
    appTheme.item = appTheme.item.filter(item => item.$.name !== "android:windowTranslucentStatus");
    appTheme.item.push(
      AndroidConfig.Resources.buildResourceItem({
        name: 'android:windowTranslucentStatus',
        value: false
      })
    );
  }

  // styles.resources.style.push(res);
  return styles;
}

module.exports = withFullScreenDialogStyles;
```

I'm not sure if it's also necessary but I set the statusBarColor to "transparent" as well. I use that on "<StatusBar />" and that also seems to do the trick.

**Comment by AronBe** [comment]
I also went with an expo config plugin, I described the approach and solution in [my blog post](https://www.aronberezkin.com/posts/a-step-by-step-guide-to-writing-your-first-expo-config-plugin)

I got the desired solution with:
```js
import type { ConfigPlugin } from "@expo/config-plugins";
import { AndroidConfig, withStringsXml } from "@expo/config-plugins";

const withAndroidSplashScreen: ConfigPlugin = (expoConfig) =>
  withStringsXml(expoConfig, (modConfig) => {
    modConfig.modResults = AndroidConfig.Strings.setStringItem(
      [
        {
          _: "true",
          $: {
            name: "expo_splash_screen_status_bar_translucent",
            translatable: "false",
          },
        },
      ],
      modConfig.modResults
    );
    return modConfig;
  });

export default withAndroidSplashScreen;
```

**Comment by Aryk** [comment]
@AronBe nice I'll try that out... it's much simpler.

**Comment by Aryk** [comment]
Hey @AronBe I used that code, and I'm still getting the dark translucent bar across the top. I looked at your code and I'm a little confused. You said: 

> The solution is to make expo_splash_screen_status_bar_translucent set to true while keeping android:windowTranslucentStatus as false  

in your article. But then later on you have this code which is actually setting expo_splash_screen_status_bar_translucent to true, but doesn't do anything about `android:windowTranslucentStatus`:


I verified too in my android build that it still outputs:

```
<resources xmlns:tools="http://schemas.android.com/tools">
  <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:textColor">@android:color/black</item>
    <item name="android:editTextStyle">@style/ResetEditText</item>
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="android:windowTranslucentStatus">true</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
  </style>
  <style name="ResetEditText" parent="@android:style/Widget.EditText">
    <item name="android:padding">0dp</item>
    <item name="android:textColorHint">#c8c8c8</item>
    <item name="android:textColor">@android:color/black</item>
  </style>
  <style name="Theme.App.SplashScreen" parent="AppTheme">
    <item name="android:windowBackground">@drawable/splashscreen</item>
  </style>
</resources>
```

**Comment by AronBe** [comment]
@Aryk how is `translucent` in `androidStatusBar` looking in `app.json`, it should be either unset or set to
` "translucent": false`

**Comment by Aryk** [comment]
Oh i see what you did, you removed the setting translucent setting, and just flipped it with the config plugin. Got it!

**Comment by jbreuer95** [comment]
This is still an issue the expo config plugin should not be necessary

**Comment by ShivS01** [comment]
Facing the same issue, looking into plugin as a workaround.
As @jbreuer95 said, plugin should not be necessary.

**Comment by Svarto** [comment]
There is a working example repo to help with debugging this for the expo team here: https://github.com/expo/expo-cli/issues/3832

**Comment by nunoplima** [comment]
> I also went with an expo config plugin, I described the approach and solution in [my blog post](https://www.aronberezkin.com/posts/a-step-by-step-guide-to-writing-your-first-expo-config-plugin)
> 
> I got the desired solution with:
> 
> ```js
> import type { ConfigPlugin } from "@expo/config-plugins";
> import { AndroidConfig, withStringsXml } from "@expo/config-plugins";
> 
> const withAndroidSplashScreen: ConfigPlugin = (expoConfig) =>
>   withStringsXml(expoConfig, (modConfig) => {
>     modConfig.modResults = AndroidConfig.Strings.setStringItem(
>       [
>         {
>           _: "true",
>           $: {
>             name: "expo_splash_screen_status_bar_translucent",
>             translatable: "false",
>           },
>         },
>       ],
>       modConfig.modResults
>     );
>     return modConfig;
>   });
> 
> export default withAndroidSplashScreen;
> ```

Spent the hole weekend eas building different attempts to get this one right, finally got it working as it should thanks to @AronBe 's solution, made my day. Thanks. Also enjoyed reading the blog post.

**Comment by Daniel3711997** [comment]
> I also went with an expo config plugin, I described the approach and solution in [my blog post](https://www.aronberezkin.com/posts/a-step-by-step-guide-to-writing-your-first-expo-config-plugin)
> 
> I got the desired solution with:
> 
> ```js
> import type { ConfigPlugin } from "@expo/config-plugins";
> import { AndroidConfig, withStringsXml } from "@expo/config-plugins";
> 
> const withAndroidSplashScreen: ConfigPlugin = (expoConfig) =>
>   withStringsXml(expoConfig, (modConfig) => {
>     modConfig.modResults = AndroidConfig.Strings.setStringItem(
>       [
>         {
>           _: "true",
>           $: {
>             name: "expo_splash_screen_status_bar_translucent",
>             translatable: "false",
>           },
>         },
>       ],
>       modConfig.modResults
>     );
>     return modConfig;
>   });
> 
> export default withAndroidSplashScreen;
> ```

You're a genius 🎉

**Comment by Julioevm** [comment]
Same issue here, Ill have to look into the plugin till theres a fix...

**Comment by Svarto** [comment]
Still a problem...

**Comment by Noitidart** [comment]
@Svarto can you try adding this to your app.json:

```
    "androidStatusBar": {
      "barStyle": "light-content",
      "translucent": true,
      "backgroundColor": "#00000000"
    },
```

I did this and then in my App/index.ts file I put this:

```
import { StatusBar } from 'expo-status-bar';

const App = memo(function App() {
  return (
      <StatusBar style="light" animated translucent />
  );
});
```

And it seems to work.

**Comment by Noitidart** [comment]
Never mind, it worked in the development build, but when pushed to store it doesn't work. I'll keep experiementing and will let you know if I ever get it to work.

**Comment by Svarto** [comment]
@Noitidart let me know! I fixed it by injecting some stuff at prebuild time (custom Dev client and EAS). But that's not optimal, as currently the app.json doesn't do what it say it should do - and there's a different between Dev and production builds.

**Comment by Noitidart** [comment]
Thank you very much I was going to try to follow the first expo configuration plug-in article you and the other very helpful friend shared.  Will try it on my next putrid build which will probably be in about a week or so please, thank you!

**Comment by ewein** [comment]
Having the same issue as well.

**Comment by jbreuer95** [comment]
Still a problem!

**Comment by Noitidart** [comment]
I promised to update if I could ever fix, and agreed jbreuer95, still a problem. I had to use the config-plugin from here in order to get around this issue. https://www.aronberezkin.com/posts/a-step-by-step-guide-to-writing-your-first-expo-config-plugin

**Comment by outaTiME** [comment]
I am still using @AronBe hot fix on Expo 49 🤔

**Comment by outaTiME** [comment]
still happening, I don't know what will occur with SDK 50

**Comment by VictorioMolina** [comment]
Expo plssss fix this!!! 🥹

**Comment by BrandonYuen** [comment]
Still broken on Expo 50 @outaTiME 😢

**Comment by outaTiME** [comment]
> Still broken on Expo 50 @outaTiME 😢

Yup, I can confirm, sadly it is still happening in Expo 50 so you have to keep using @AronBe patch which is still working.

**Comment by jakobvase** [comment]
Yep, still broken

**Comment by PopJoestar** [comment]
Still broken ...
