### ISSUE TITLE
Upgrade version of Google Play Billing library to 3 (InAppPurchases)

### ISSUE THREAD

**Issue by AlenToma** [expo/expo#12193]
### Summary

I have installed and used `expo-in-app-purchases`. But now when I publish an app on google play store I get a warning.

```
We've detected that this app is using an old version of Google Play Billing.
 By November 1, 2021, all app updates must use Billing Library version 3 or newer. Update to Billing Library 3 before this date.
 Learn More about Billing Library 3.
```

How do I upgrade it to version 3? this should automatically be updated when I installed the latest version of `expo-in-app-purchases` right?

Should we just wait or is there already a support for it in expo and I just do not know about it?

`AndroidManafist.xml`

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.***">
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.MANAGE_DOCUMENTS" />
	<uses-permission android:name="com.android.vending.BILLING" />
	<application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher" android:allowBackup="false" android:theme="@style/AppTheme" android:requestLegacyExternalStorage="true">
		<meta-data android:name="expo.modules.updates.EXPO_UPDATE_URL" android:value="https://exp.host/@***/***" />
		<meta-data android:name="expo.modules.updates.EXPO_SDK_VERSION" android:value="40.0.0" />
		<meta-data android:name="expo.modules.updates.EXPO_RELEASE_CHANNEL" android:value="***" />
		<meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true" />
		<activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize">
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
				<action android:name="android.intent.action.DOWNLOAD_COMPLETE" />
			</intent-filter>
		</activity>
		<activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
	</application>
</manifest>

```

I want it to be installed so I could be prepared before google block my app suddenly.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40.0.0 

### Environment

  Expo CLI 4.1.4 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 15.6.0 - C:\Program Files\nodejs\node.EXE
      npm: 7.5.4 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 26, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom
    npmPackages:
      expo: ^40.0.1 => 40.0.1
      react: ~16.13.1 => 16.13.1
      react-native: ^0.63.4 => 0.63.4
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Install and `expo-in-app-purchases` and publish it on google play console. 
And then you will get a warning.

**Comment by AdamJNavarro** [comment]
Hey @AlenToma, as the message from Google states this won't be a blocking issue until November 1st of this year. We'll aim to provide guidance on the best path forward and give Expo users enough time to make whatever changes may be necessary.

**Comment by cruzach** [comment]
woops I opened a duplicate issue for this- https://github.com/expo/expo/issues/12238- will close it in favor of this one

**Comment by diogomachado** [comment]
I'm concerned with this message as well, I have an app in production using in-app-purchase, I will follow this issue closest.

**Comment by RohovDmytro** [comment]
AFAICT, `expo-in-app-purchases` does not play well with `react-native-purchases` due to conflicts in Billing versions.

````
Possible Unhandled Promise Rejection (id: 0):
Error: Encountered an exception while calling native method: Exception occurred while executing exported method purchaseItemAsync on module ExpoInAppPurchases: No virtual method setOldSku(Ljava/lang/String;)Lcom/android/billingclient/api/BillingFlowParams$Builder; in class Lcom/android/billingclient/api/BillingFlowParams$Builder; or its super classes (declaration of 'com.android.billingclient.api.BillingFlowParams$Builder' appears in
````

**Comment by kesha-antonov** [comment]
Google Play Billing Library 4.0 Release (2021-05-18) is out

https://developer.android.com/google/play/billing/release-notes

**Comment by paradyo** [comment]
Still following the topic and waiting for an answer ...

**Comment by TPXP** [comment]
I wish this item could get more attention from the expo team too, since Google will start requiring v3 of the play store library for new apps in a few weeks (August 2, 2021). Updates will be required to use this version by November 1, 2021

**Comment by dpnick** [comment]
I totally agree without any news we won't be able to get android IAP in few months

**Comment by cruzach** [comment]
We plan on upgrading this dependency and releasing a new version far enough ahead of that deadline so that users have time to upgrade, test, and push out a new release

**Comment by AlexDanault** [comment]
> Starting on August 2, 2021, all new apps must use Billing Library version 3 or newer. By November 1, 2021, all updates to existing apps must use Billing Library version 3 or newer. Learn more.

This means that as of today, new apps can't use this library. Sandly, I had to recreate my app on the Play store, and suddenly I can't upload any builds because of the date the app was created.

I see some progress has been made (yay !) , an ETA would be really helpful.

Thanks !

**Comment by AlenToma** [comment]
Please Upload a new Package to `npmjs.com` before closing this one so we could know that it is ready.

**Comment by AlenToma** [comment]
Hi @cruzach I cant seems to be able to upload new version to google anymore. Will there be a package soon ? or should I implement other react package instead because its very imported to upload new version to google play.

**Comment by cruzach** [comment]
Hi @AlenToma, we just landed the upgrade and will hopefully be landing a followup PR which also includes a breaking change. Once that's landed, we can publish a new version as `next` for you to upgrade to

If you cannot wait, then you can apply the changes that are in the upgrade PR linked above in a `patch-package` script 👍

**Comment by kesha-antonov** [comment]
PR works with expo-in-app-purchases 10.1.1
https://github.com/expo/expo/pull/13019

**Comment by kesha-antonov** [comment]
Here's patch file `patches/expo-in-app-purchases+10.1.1.patch`:

```
diff --git a/node_modules/expo-in-app-purchases/android/build.gradle b/node_modules/expo-in-app-purchases/android/build.gradle
index 0d9f49b..d6691c0 100644
--- a/node_modules/expo-in-app-purchases/android/build.gradle
+++ b/node_modules/expo-in-app-purchases/android/build.gradle
@@ -60,5 +60,5 @@ allprojects {
 
 dependencies {
   unimodule 'unimodules-core'
-  api 'com.android.billingclient:billing:2.0.0'
+  api 'com.android.billingclient:billing:4.0.0'
 }
diff --git a/node_modules/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java b/node_modules/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java
index 9273ab5..e78bfbd 100644
--- a/node_modules/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java
+++ b/node_modules/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java
@@ -131,9 +131,9 @@ public class BillingManager implements PurchasesUpdatedListener {
   /**
    * Start a purchase or subscription replace flow
    */
-  public void purchaseItemAsync(final String skuId, final String oldSku, final Promise promise) {
+  public void purchaseItemAsync(final String skuId, final String purchaseToken, final Promise promise) {
 
-    // oldSku is for subscription replacements and may be null.
+    // purchaseToken is for subscription replacements and may be null.
     Runnable purchaseFlowRequest = new Runnable() {
       @Override
       public void run() {
@@ -143,9 +143,17 @@ public class BillingManager implements PurchasesUpdatedListener {
           return;
         }
 
-        BillingFlowParams purchaseParams = BillingFlowParams.newBuilder()
-          .setSkuDetails(skuDetails).setOldSku(oldSku).build();
-        mBillingClient.launchBillingFlow(mActivity, purchaseParams);
+        BillingFlowParams.Builder purchaseParams = BillingFlowParams.newBuilder()
+          .setSkuDetails(skuDetails);
+
+        if (purchaseToken != null) {
+          BillingFlowParams.SubscriptionUpdateParams subscriptionUpdateParams = BillingFlowParams.SubscriptionUpdateParams.newBuilder()
+            .setOldSkuPurchaseToken(purchaseToken)
+            .build();
+          purchaseParams.setSubscriptionUpdateParams(subscriptionUpdateParams);
+        }
+
+        mBillingClient.launchBillingFlow(mActivity, purchaseParams.build());
       }
     };
 
@@ -225,7 +233,6 @@ public class BillingManager implements PurchasesUpdatedListener {
         ConsumeParams consumeParams =
           ConsumeParams.newBuilder()
             .setPurchaseToken(purchaseToken)
-            .setDeveloperPayload(null)
             .build();
         // Consume the purchase async
         mBillingClient.consumeAsync(consumeParams, onConsumeListener);
@@ -416,7 +423,7 @@ public class BillingManager implements PurchasesUpdatedListener {
 
     bundle.putBoolean("acknowledged", purchase.isAcknowledged());
     bundle.putString("orderId", purchase.getOrderId());
-    bundle.putString("productId", purchase.getSku());
+    bundle.putStringArrayList("productIds", purchase.getSkus());
     bundle.putInt("purchaseState", purchaseStateNativeToJS(purchase.getPurchaseState()));
     bundle.putLong("purchaseTime", purchase.getPurchaseTime());
     bundle.putString("packageName", purchase.getPackageName());
@@ -429,7 +436,7 @@ public class BillingManager implements PurchasesUpdatedListener {
     Bundle bundle = new Bundle();
 
     // PurchaseHistoryRecord is a subset of Purchase
-    bundle.putString("productId", purchaseRecord.getSku());
+    bundle.putStringArrayList("productIds", purchaseRecord.getSkus());
     bundle.putLong("purchaseTime", purchaseRecord.getPurchaseTime());
     bundle.putString("purchaseToken", purchaseRecord.getPurchaseToken());
 
diff --git a/node_modules/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/InAppPurchasesModule.java b/node_modules/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/InAppPurchasesModule.java
index 77a8f66..661636d 100644
--- a/node_modules/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/InAppPurchasesModule.java
+++ b/node_modules/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/InAppPurchasesModule.java
@@ -62,8 +62,8 @@ public class InAppPurchasesModule extends ExportedModule implements RegistryLife
   }
 
   @ExpoMethod
-  public void purchaseItemAsync(String skuId, String oldSku, final Promise promise) {
-    mBillingManager.purchaseItemAsync(skuId, oldSku, promise);
+  public void purchaseItemAsync(String skuId, String purchaseToken, final Promise promise) {
+    mBillingManager.purchaseItemAsync(skuId, purchaseToken, promise);
   }
 
   @ExpoMethod
diff --git a/node_modules/expo-in-app-purchases/build/InAppPurchases.d.ts b/node_modules/expo-in-app-purchases/build/InAppPurchases.d.ts
index 08eb860..38fe650 100644
--- a/node_modules/expo-in-app-purchases/build/InAppPurchases.d.ts
+++ b/node_modules/expo-in-app-purchases/build/InAppPurchases.d.ts
@@ -3,7 +3,7 @@ export { InAppPurchase, InAppPurchaseState, IAPResponseCode, IAPErrorCode, IAPIt
 export declare function connectAsync(): Promise<void>;
 export declare function getProductsAsync(itemList: string[]): Promise<IAPQueryResponse>;
 export declare function getPurchaseHistoryAsync(refresh?: boolean): Promise<IAPQueryResponse>;
-export declare function purchaseItemAsync(itemId: string, oldItem?: string): Promise<void>;
+export declare function purchaseItemAsync(itemId: string, purchaseToken?: string): Promise<void>;
 export declare function setPurchaseListener(callback: (result: any) => void): Promise<void>;
 export declare function finishTransactionAsync(purchase: InAppPurchase, consumeItem: boolean): Promise<void>;
 export declare function getBillingResponseCodeAsync(): Promise<number>;
diff --git a/node_modules/expo-in-app-purchases/build/InAppPurchases.js b/node_modules/expo-in-app-purchases/build/InAppPurchases.js
index 75a52ec..d30d1d1 100644
--- a/node_modules/expo-in-app-purchases/build/InAppPurchases.js
+++ b/node_modules/expo-in-app-purchases/build/InAppPurchases.js
@@ -31,11 +31,11 @@ export async function getPurchaseHistoryAsync(refresh) {
     }
     return await ExpoInAppPurchases.getPurchaseHistoryAsync(refresh);
 }
-export async function purchaseItemAsync(itemId, oldItem) {
+export async function purchaseItemAsync(itemId, purchaseToken) {
     if (!connected) {
         throw new ConnectionError(errors.NOT_CONNECTED);
     }
-    await ExpoInAppPurchases.purchaseItemAsync(itemId, oldItem);
+    await ExpoInAppPurchases.purchaseItemAsync(itemId, purchaseToken);
 }
 export async function setPurchaseListener(callback) {
     if (purchaseUpdatedSubscription) {
diff --git a/node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.h b/node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.h
index d0da765..e298b84 100644
--- a/node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.h
+++ b/node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.h
@@ -5,6 +5,7 @@
 #import <UMCore/UMEventEmitterService.h>
 #import <UMCore/UMEventEmitter.h>
 #import <StoreKit/StoreKit.h>
+#import <Sentry/Sentry.h>
 
 @interface EXInAppPurchasesModule : UMExportedModule <UMEventEmitter, UMModuleRegistryConsumer, SKProductsRequestDelegate, SKPaymentTransactionObserver>
 @end
diff --git a/node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m b/node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m
index bdff8fe..97f4495 100644
--- a/node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m
+++ b/node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m
@@ -75,7 +75,7 @@ UM_EXPORT_METHOD_AS(getProductsAsync,
 
 UM_EXPORT_METHOD_AS(purchaseItemAsync,
                     purchaseItemAsync:(NSString *)productIdentifier
-                    replace:(NSString *)oldItem // ignore on iOS
+                    replace:(NSString *)purchaseToken // ignore on iOS
                     resolve:(UMPromiseResolveBlock)resolve
                     reject:(UMPromiseRejectBlock)reject)
 {
@@ -356,7 +356,7 @@ UM_EXPORT_METHOD_AS(disconnectAsync,
 
   return @{
            @"acknowledged": @(acknowledged),
-           @"productId": transaction.payment.productIdentifier,
+           @"productIds": @[transaction.payment.productIdentifier],
            @"orderId": transaction.transactionIdentifier,
            @"purchaseState": @(transaction.transactionState),
            @"purchaseTime": @(transaction.transactionDate.timeIntervalSince1970 * 1000),
diff --git a/node_modules/expo-in-app-purchases/src/InAppPurchases.ts b/node_modules/expo-in-app-purchases/src/InAppPurchases.ts
index e88458b..f9f41c1 100644
--- a/node_modules/expo-in-app-purchases/src/InAppPurchases.ts
+++ b/node_modules/expo-in-app-purchases/src/InAppPurchases.ts
@@ -59,12 +59,12 @@ export async function getPurchaseHistoryAsync(refresh?: boolean): Promise<IAPQue
   return await ExpoInAppPurchases.getPurchaseHistoryAsync(refresh);
 }
 
-export async function purchaseItemAsync(itemId: string, oldItem?: string): Promise<void> {
+export async function purchaseItemAsync(itemId: string, purchaseToken?: string): Promise<void> {
   if (!connected) {
     throw new ConnectionError(errors.NOT_CONNECTED);
   }
 
-  await ExpoInAppPurchases.purchaseItemAsync(itemId, oldItem);
+  await ExpoInAppPurchases.purchaseItemAsync(itemId, purchaseToken);
 }
 
 export async function setPurchaseListener(callback: (result) => void): Promise<void> {
```

**Comment by AlenToma** [comment]
Well I made the changes, will try this out now :)

**Comment by AlenToma** [comment]
Can verify that the patch work.

Note: when you have upgraded `getPurchaseHistoryAsync` return a list of `productId` and not a string anymore and it was changed to `productIds` but the types still says that `productIds` dose not exist. types must also be updated.

**Comment by cruzach** [comment]
# Important!

The patch that @kesha-antonov shared is not correct, **the correct patch can be found in this diff**: https://github.com/expo/expo/commit/d7e0e42a6a01fd1476b1dce54369b86c504a0008

@AlenToma your issue with `productIds` does not exist if you use the correct patch

**Comment by AlenToma** [comment]
Shitt I have wasted my time then :)

**Comment by AlenToma** [comment]
@cruzach I have installed `expo-modules-core` and made the changes that you mention above but now I am getting 

```
D:\Projects\NovelManager\NovelManager.app\node_modules\expo-in-app-purchases\android\src\main\java\expo\modules\inapppurchases\BillingManager.java:37: error: package expo.modules.core does not exist
import expo.modules.core.Promise;
                        ^
D:\Projects\NovelManager\NovelManager.app\node_modules\expo-in-app-purchases\android\src\main\java\expo\modules\inapppurchases\BillingManager.java:38: error: package expo.modules.core.interfaces.services does not exist
import expo.modules.core.interfaces.services.EventEmitter;
                                            ^
D:\Projects\NovelManager\NovelManager.app\node_modules\expo-in-app-purchases\android\src\main\java\expo\modules\inapppurchases\BillingManager.java:58: error: cannot find symbol
  protected static final HashMap<String, Promise> promises = new HashMap<>();

```

**Comment by AlenToma** [comment]
Nevermind I imported them from `umodules` instead and it worked.

**Comment by kesha-antonov** [comment]
> # Important!
> The patch that @kesha-antonov shared is not correct, **the correct patch can be found in this diff**: [d7e0e42](https://github.com/expo/expo/commit/d7e0e42a6a01fd1476b1dce54369b86c504a0008)
> 
> @AlenToma your issue with `productIds` does not exist if you use the correct patch

But still we use it few months already in production and people buy or in apps)

**Comment by cruzach** [comment]
`expo-in-app-purchases@11.0.0` is published with the update 👍

**Comment by AlenToma** [comment]
Yes, I have got the same problem when I implemented this. 

the current `expo.modules.core` dose not containe those objects, I have checked it when I installed the latest version of `expo.modules.core`

So the solution I made was to use `unimodules`

```
import org.unimodules.core.Promise;
import org.unimodules.core.interfaces.services.EventEmitter;
```
instead of 

```
import expo.modules.core.Promise;
import expo.modules.core.interfaces.services.EventEmitter;
```

**Comment by cruzach** [comment]
Or you could install the new `expo-modules-core` package that these are being imported from: https://github.com/expo/expo/tree/master/packages/expo-modules-core

**Comment by AlenToma** [comment]
And Why, All Expo contains `unimodules` why the change ?

**Comment by cruzach** [comment]
https://github.com/expo/expo/pull/12718

**Comment by AugustinasMK** [comment]
> Or you could install the new `expo-modules-core` package that these are being imported from: https://github.com/expo/expo/tree/master/packages/expo-modules-core


@cruzach, installing the package does nothing. Errors are still thrown.

**Comment by AugustinasMK** [comment]
> Or you could install the new `expo-modules-core` package that these are being imported from: https://github.com/expo/expo/tree/master/packages/expo-modules-core

@cruzach sadly it does not work. Still getting the same errors. This is because of 2 things, which I mentioned in my PR #14024. 
The first one is fixed (missing dependency), but I'm not sure how to fix the second one (Gradle running IAP command ahead of modules-core).

**Comment by xdajay** [comment]
EAS build also failing after upgrading to new IAP version **for Android** and EAS build for iOS is working

**Comment by AugustinasMK** [comment]
> EAS build also failing after upgrading to new IAP version **for Android** and EAS build for iOS is working

@xdajay that's because for whatever reason iOS still used the old imports from unimodules. Android, on the other hand, imports from expo-modules-core.

**Comment by cruzach** [comment]
`expo-in-app-purchases@11.0.1` published and no longer relies on `expo-modules-core`

**Comment by xdajay** [comment]
@cruzach with expo-in-app-purchases@11.0.1 EAS build is working flawlessly, without any extra imports 🚀
Thanks for the speedy update 😇

**Comment by ecklf** [comment]
As of today, it seems Google blocked releasing using the old billing library.

![image](https://user-images.githubusercontent.com/8146736/131787617-0147e22a-f9e1-4f48-aced-608fe33fb96d.png)

Any plans to release this under `latest` tag?

**Comment by cruzach** [comment]
11.0.1 is now `latest`

**Comment by rikkster** [comment]
Hello! I using expo-in-app-purchases v11.0.1 but google console says me: “This app uses an unsupported version of Play Billing. To publish it, update the Payments library to version 3 or later”. I’m confused…How can I get billing to work? P.S.: sorry for my bad eng

**Comment by wenchiutts** [comment]
Hi @cruzach  , i'm using v11.0.1 on android project and calling getPurchaseHistoryAsync with argument(boolean) will get the error message: 

> Argument of an incompatible class: class java.lang.Boolean cannot be passed as an argument to parameter expecting interface org.unimodules.core.arguments.ReadableArguments.

I'm wondering is there any change of the usage?  Thanks!

**Comment by devGuerra** [comment]
@rikkster you can fix it ?

**Comment by lnCrew** [comment]
Hi ! Same problem here with expo-in-app-purchases 13.0.0. 
Any solution to do upgrade the Google Play Billing library on expo ?
