### ISSUE TITLE
Expo app stuck on slash screen in apk and published app

### ISSUE THREAD

**Issue by hahahatrick** [expo/expo#1226]
Hello,

When running expo in local environment everything works fine but when running app after publishing or using the standalone apk the app is stuck on splash screen.
  
Unchecking development mode and running the app works.

**Comment by jimmylee** [comment]
Hi @hahahatrick, assigning @jesseruder to help take a look with his android expertise, but it would be useful to have more information about your problem. 

Do you have an example code & repository we could look at?

**Comment by mnemotiv** [comment]
same issue here for some time, all deps are latest ones, though previously before updating deps with npm - it didn't work too

**Comment by ozankasikci** [comment]
My published expo app is stuck on splash screen both on android and ios. Tried upgrading expo client version on my phone, deleting the project and republishing. Nothing seems to work.

The app works fine on XDE locally though.

**Comment by bkdev98** [comment]
I just got the same problem. In my case, `rm -rf node_modules`, `yarn add uglify-es@3.2.2` and recompile fix the issue.
More discussion here [https://github.com/facebook/react-native/issues/17348](https://github.com/facebook/react-native/issues/17348).
Hope it will help.

**Comment by andrioid** [comment]
This is also causing problems for me. I've tried the suggested work-arounds without luck.

I can confirm that my local node_modules installs v3.2.2 of uglify-es, but I can't say what the Expo build service does.

My app is completely stuck at splash-screen, only on Android. Unable to reproduce with the Expo Client or on iOS stand-alone.

See forum post here: https://forums.expo.io/t/frozen-splash-screen-on-sdk-25-android-stand-alone/7046

**Comment by ozankasikci** [comment]
@andrioid i followed the instructions on the topic facebook/react-native#17348. installed uglify-es via adding 3.2.2 to resolutions on package.json and it worked.

In my case it was being stuck on Android and IOS. Your case might be something else?

**Comment by andrioid** [comment]
@ozankasikci: Quite possible. It's only on Android and only in stand-alone for me. I'll keep the forum post updated, in case this happens to someone else.

**Comment by arrygoo** [comment]
Having the same issue on Android, SDK 23, detached app. Everything was fine but after a push we're getting stuck on splash screen in our staging server. As others mentioned, I can't reproduce the same issue locally. This

**Comment by andrioid** [comment]
@arrygoo: Maybe see #1388 - I moved my push-registration so that it asks later in the process, instead of during init. That works for now.

**Comment by arrygoo** [comment]
@andrioid I did check that but we don't have `Notification` from expo imported or used in our codebase. Since it's a detached app we've been using OneSignal, but I wonder if something similar is silently failing.

**Comment by arrygoo** [comment]
Our freeze seemed to be from a breaking minor update by `https://github.com/zmxv/react-native-sound` which changed the behavior their `Sound.setCategory` API. 
Leaving this comment for anyone else looking potentially with the same issue.

**Comment by esamelson** [comment]
Hi there, it's really hard to reproduce and root cause this issue unfortunately, but we've fixed a couple of things that might be causing it. Fixes will be out in SDK 26, which should be out soon, hopefully. Please let us know if you continue to see this issue after upgrading to 26.

**Comment by aroff** [comment]
Same for me.. stuck on splashscreen on Android Expo 25

**Comment by richnavarro** [comment]
Same issue here. Works fine in development mode, but exp publish and exp build:android both output unworking versions of the app that do not progress beyond the splash screen. I don't have an iPhone to test it out in iOS.
https://expo.io/@rnavarro/crazyrides
https://github.com/richnavarro/CrazyRides

**Comment by andrioid** [comment]
@aroff @richnavarro 
What Expo specific APIs are you using (if any) during init?

**Comment by richnavarro** [comment]
@andrioid Expo specific - AppLoading, Asset, and Font.

**Comment by esamelson** [comment]
Hi @richnavarro - you can try running your project with `exp start --no-dev --minify` which is closer to what you'd see in a production bundle. That might help you narrow down any JS errors that are happening early on in the app lifecycle.

**Comment by richnavarro** [comment]
@esamelson Thanks! That brought up errors that were not previously shown in dev mode. My solution to these random errors was downgrading to npm 5.0.3 (5.3 didn't work either) and now the app works fine. Thanks again!
exp - 50.0.5
npm - 5.0.3
node - 8.10.0

**Comment by esamelson** [comment]
@richnavarro - glad to hear it! Sorry for the difficulty in finding the actual error. We'll work on making that less opaque.

**Comment by deot** [comment]
same issue. I solved it by  network proxy([Charles](https://www.charlesproxy.com/)).(Some app requests come from `https://exp.host`); 

As long as you use it once, you can open it later.But it is just an emergency plan

**Comment by esamelson** [comment]
Going to close this for now as it seems the issue is resolved. Please open a new issue if you're having this issue and none of the solutions here work.

**Comment by stefdelec** [comment]
Hum I am having the same issue. App freeze on splash screen in IOS only on some device.

**Comment by sakhmedbayev** [comment]
I have the same issue. I do not even know what causes the splash screen to hung. My app works as expected on both android and ios simulator while in local dev environment. It does not work however if open the app from my expo account.

**Comment by stefdelec** [comment]
HAve you updated the expo sdk to 28 ?

**Comment by sakhmedbayev** [comment]
Thank you @stefdelec! Yes, I have updated it but my app still cannot go beyond splash screen.

**Comment by craig1123** [comment]
@sakhmedbayev My app is doing the exact same thing, but I do not have push notifications. I've also updated to expo 28

**Comment by masiamj** [comment]
+1 I am also encountering this issue with Android production builds.

**Comment by nextstudioal** [comment]
Having the same issue after updating to SDK 29. Will try if it is related to #1388. I will try to post an update later

**Comment by HyveMynd** [comment]
Experiencing the same on SDK 28. I have removed all code related to push notifications to ensure it is not because of #1388. Still only seeing the splash screen on android. 
An interesting find is when `AppLoading` component's `onFinish` updates the state to allow rendering the rest of the app, I am not seeing any further render calls. There is only 1 render call showing the `AppLoading`, and does not get called again even after state updates.

**Comment by jesseruder** [comment]
Hi @masiamj @nextstudioal and @HyveMynd. This is an old issue, please see this new issue: https://forums.expo.io/t/standalone-apk-freezes-at-launch-screen/11879/18 and https://github.com/expo/expo/issues/2038#issuecomment-408501154.
