### ISSUE TITLE
expo-camera bar code scanner not working on web and no error is reported

### ISSUE THREAD

**Issue by jer-sen** [expo/expo#12270]
### Summary

QR Code scanner does not work and no error is reported.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

40.0.1

### Environment

Expo CLI 4.3.0 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

My code looks like this https://snack.expo.io/R91DT_VxJ but everything works fine with Snack.
I think the issue comes from here: https://github.com/alewin/useWorker/issues/105
So the issue does not come from Expo but `expo-camera` should not ignore `useWebQRScanner` errors but log them: https://github.com/expo/expo/blob/9c26fbc09d2ec8c7b48d5e7d79bf99631b7b84cc/packages/expo-camera/src/ExponentCamera.web.tsx#L56

**Comment by alewin** [comment]
i released the version `4.0.1` that removes `isoworker` for the moment  https://github.com/alewin/useWorker/releases/tag/4.0.1 this should solve the issue

**Comment by jer-sen** [comment]
Note that `expo-camera` dependencies must be updated for this fix to work (currently `"@koale/useworker": "^3.2.1"`).

**Comment by neats-returns** [comment]
Is it possible to manually update the sub-dependency to fix the issue ?

**Comment by neats-returns** [comment]
I have forked expo-camera, update the package dependency to ^4.0.1 but the camera still not detect the barcode on web

**Comment by neats-returns** [comment]
> Note that `expo-camera` dependencies must be updated for this fix to work (currently `"@koale/useworker": "^3.2.1"`).
I have forked expo-camera, update the package dependency to ^4.0.1 but the camera still not detect the barcode on web

**Comment by neats-returns** [comment]
> Note that `expo-camera` dependencies must be updated for this fix to work (currently `"@koale/useworker": "^3.2.1"`).


I have forked expo-camera, update the package dependency to ^4.0.1 but the camera still not detect the barcode on web
