### ISSUE TITLE
BarCodeScanner doesn't work on Android Tablet (Samsung Galaxy A6 7", Huawei Mediapad T3)

### ISSUE THREAD

**Issue by tiendv89** [expo/expo#1481]
I used BarCodeScanner to scan some QR codes but it doesn't work on Android Tablets (it does work on Iphone, Ipad, or Samsung J7 Prime)

Seems like the auto-focus feature does not work as well.

I am using SDK 24.0.0, and the issue happens with both expo client and standalone app.
(The QR Code Scanner app downloaded from Play Store does work on those devices)

Any support is much appreciated!

**Comment by terribleben** [comment]
@aalices is this possibly a duplicate of https://github.com/expo/expo/issues/1461?

@tiendv89 can you produce a [snack](https://snack.expo.io) that demonstrates the issue so that we can make sure we're testing the same case?

**Comment by huy-lv** [comment]
@terribleben Its just the sample code same the example in [BarCodeScanner document](https://docs.expo.io/versions/latest/sdk/bar-code-scanner.html), i put it on snack here: https://snack.expo.io/@huylv177/demo-barcodescanner
I think the its not a duplicate of #1461, the problem here is camera autoFocus feature seems not work. 
I run this snack on Samsung Galaxy S6 or LG Gpro2 or Iphone 6, its work fine. But on Samsung Galaxy Tab A6, the camera cannot autoFocus so it can not recognize the QRCode.

**Please note that the QRcode we use is in small size (2cm x 2cm). If use another QR Code Scanner app on Google Play, it recognize this QRCode very fast**

**Comment by minhthanh310** [comment]
For me the Camera does not recognize QR code using a Samsung Galaxy J7 Pro (mid-end device). I tried adjusting autoFocus, focusDepth and zoom but it makes no effects.
All works on iOS, seem they are android only issue?

**Comment by ngodinhtao** [comment]
i have faced same problem !!!

**Comment by solonote** [comment]
I have faced same problem. I tested several android devices, all of them doesn't work with QR code. 
BTW. I tried a exp project https://expo.io/@thuongbv/qrcode-reader. Android device works fine to read QR code. There is no source code. I don't know why.

**Comment by solonote** [comment]
After read the expo source, I found something:

QR code scan works fine with SDK 24, Because the qrcode reader is com.google.zxing
Source code:
https://github.com/expo/expo/blob/cc97d38952925b83e11805b91d33e159b754c558/android/expoview/src/main/java/abi24_0_0/host/exp/exponent/modules/api/components/barcodescanner/BarCodeScannerViewFinder.java

QR code scan doesn't work on SDK 25&26, Because  the qrcode reader is com.google.android.gms.vision.barcode

Source code:
https://github.com/expo/expo/blob/28a57f7c86d4e4d998c9f096a7ba78ed2d02c742/android/expoview/src/main/java/abi25_0_0/host/exp/exponent/modules/api/components/barcodescanner/BarCodeScannerModule.java

I guess the reason is that some android doesn't have com.google.android.gms.vision.barcode function. 
Could you guys make it as a param of BarcodeScanner/Camera, such as "barcodeDetector=zxing|googleBarcode" in future version? Thanks!

**Comment by huy-lv** [comment]
@solonote i tried the project you mentioned on Galaxy Tab A6 and doesnt work. Camera cannot focus on small qrcode

**Comment by solonote** [comment]
@huy-lv, I think there are two issues: one is you mentioned about cannot focus on small qrcode, I think it may resolved by change size. 

My real problem is there are so many android devices cannot detect qrcode with SDK 25&26 since the decoder is **com.google.android.gms.vision.barcode**. This function only works with SDK 24 since the decoder is **com.google.zxing**.

If SDK26 could add an option let developer choose the decoder, it will very helpful. Thanks again!

**Comment by solonote** [comment]
i should open a new issue about zxing since this one is about "auto focus"

**Comment by aalices** [comment]
Does SDK 26 resolves this for anyone?

**Comment by mslavik2** [comment]
@terribleben I am still seeing this issue in sdk 28, any update on this?

**Comment by nhuthan** [comment]
same problem on samsung galaxy tab a 2016

**Comment by FiberJW** [comment]
Closing for lack of activity, but if you need further support, please make a topic on our [forums](https://forums.expo.io) :)
