### ISSUE TITLE
ImagePicker.launchImageLibraryAsync() promise does not resolve if modal dismissed from swipe on iOS

### ISSUE THREAD

**Issue by marchingband** [expo/expo#15185]
### Summary

`ImagePicker.launchImageLibraryAsync()` returns `{cancelled:true}` if user clicks the "cancel" button, but, if they dismiss the modal by swiping down on the media library, the promise does not resolve, nothing is returned.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

  Expo CLI 4.12.10 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      expo-cli: 4.12.10
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
let result = await ImagePicker.launchImageLibraryAsync({
        allowsEditing: true,
        aspect: [1, 1],
        quality:0.5
});
console.log(result)
```

**Comment by marchingband** [comment]
Any updates? This bug puts the application in a frozen state, with no known workaround.
Can anyone suggest even a dirty way to get around this, or avoid this?

**Comment by shaverda** [comment]
Can't confirm from personal use, but the changelog says it was fixed in 12.0.1

**Comment by marchingband** [comment]
Applications using ImagePicker must await on this promise while the user picks, and that promise never resolves or times out. It just sits at a dark grey screen forever.

**Comment by marchingband** [comment]
Thanks @shaverda, i assumed the issue would close automatically. Great news.

**Comment by marchingband** [comment]
In SDK 43, if I instal expo-image-picker 12.0.2, this bug persists.
Do I need to upgrade to 44 to get the patch? thanks.

**Comment by barthap** [comment]
Fixed by #15511

> Do I need to upgrade to 44 to get the patch? thanks.

Yes, that fix is applied in SDK 44.
