### ISSUE TITLE
React Navigation modal are glitchy inside Expo go client

### ISSUE THREAD

**Issue by lucasmotta** [expo/expo#15482]
### Summary

React-Navigation modals are glitchy inside a managed Expo app. When the same example is ejected, the modals work as expected (using the same version for all packages).

More information was reported on https://github.com/software-mansion/react-native-screens/issues/932 - but since this issue only occurs inside Expo Go app, I assume it must be something going on with Expo.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43.0.2

### Environment

Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 3.3.1 - /usr/local/bin/fish
    Binaries:
      Node: 16.10.0 - ~/.local/share/nvm/v16.10.0/bin/node
      Yarn: 1.22.15 - ~/.local/share/nvm/v16.10.0/bin/yarn
      npm: 7.24.0 - ~/.local/share/nvm/v16.10.0/bin/npm
      Watchman: 2021.09.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.2 => 43.0.4
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: bare

### Reproducible demo

The demo running as a managed app:
https://github.com/lucasmotta/expo-go-navigation-issue

The same demo, but ejected:
https://github.com/lucasmotta/expo-go-navigation-issue/tree/ejected

### Modal Header issue
**Expo go (bug)**

https://user-images.githubusercontent.com/76673/145291952-54fc2a8f-0346-4f8c-993b-d074414e02b0.mp4

**Ejected (works)**

https://user-images.githubusercontent.com/76673/145292097-333613da-845e-4013-b5af-0b61974989cc.mp4

### Modal Stacking issue
**Expo go (bug)**

https://user-images.githubusercontent.com/76673/145292198-4754418b-e4e7-4f62-ab53-f7ace8a92a9e.mp4

**Ejected (works)**

https://user-images.githubusercontent.com/76673/145292237-c15f5512-b94c-4e40-91db-90a8a80a0f6a.mp4

**Comment by brentvatne** [comment]
it's not clear to me what is happening in the third video, "Modal Stacking issue" in Expo Go - did you possibly upload the incorrect video there?

**Comment by lucasmotta** [comment]
Sorry @brentvatne, indeed I uploaded the wrong video. It's fixed now with the correct video - let me know if you need any more info.

**Comment by brentvatne** [comment]
@lucasmotta - we will look into it! as recommended in the other thread, you can use EAS Build to get around this for now.

**Comment by brentvatne** [comment]
@lukmccall and @EvanBacon have investigated this and haven't been able to find the root cause yet.

**Comment by niemax** [comment]
> Sorry @brentvatne, indeed I uploaded the wrong video. It's fixed now with the correct video - let me know if you need any more info.

Hey! Did you find an alternative way? I would be interested.

**Comment by brentvatne** [comment]
@niemax - this will only occur within Expo Go, we're still not sure why. when you run your build with `eas build` you will not have this problem. I believe it also works as expected if you use expo-dev-client instead of Expo Go.

**Comment by hirbod** [comment]
@brentvatne it is working as expected with expo-dev-client. Just verified it. It is only Expo Go causing this issue.

**Comment by RWOverdijk** [comment]
I just found this issue after experiencing the same issue where scrolling makes the height jump. At first I thought the jumping was the bug, but I now see that the initial height is the problem.

Is there a fix planned for this? Is there any way we can help?

**Comment by hirbod** [comment]
Not stale

**Comment by RWOverdijk** [comment]
Good bot
