### ISSUE TITLE
iOS standalone app can crash when using many video components

### ISSUE THREAD

**Issue by terribleben** [expo/expo#1647]
We have [reports](https://forums.expo.io/t/multiple-video-components/8764) of "The AVPlayerItem instance has failed" followed by a native crash when running multiple videos (e.g. in a list). The report also indicates that `react-native-video` doesn't experience this issue. We should check out whatever they're doing and pull it into Expo.

**Comment by sjchmiela** [comment]
1. The first issue I hit was something along the lines “attempt to insert nil into dictionary from objects[3]”. Turned out that sometimes when `getStatus` was being called, `_player.currentTime` was `nil`, so it couldn't be put via placeholder dictionary that easy. Fix was obvious, to remove the row from placeholder dictionary and put down with `durationMillis` and `playableDurationMillis`.
2. Now I've got
    > Cannot form weak reference to instance (`0x1c43474e0`) of class `ABI26_0_0EXAVPlayerData`. It is possible that this object was over-released, or is in the process of deallocation.
    in `observeValueForKeyPath`. I'll see what I can do about it.

**Comment by sjchmiela** [comment]
Also, the memory usage is going crazy

![zrzut ekranu 2018-04-13 o 17 12 15](https://user-images.githubusercontent.com/1151041/38742841-dcdc5616-3f3d-11e8-900f-c65c0e03dedf.png)

**Comment by sjchmiela** [comment]
As noted in [Stackoverflow answer](https://stackoverflow.com/questions/35991363/why-setting-object-that-is-undergoing-deallocation-to-weak-property-results-in-c#42329741) the behavior noted in [2.](https://github.com/expo/expo/issues/1647#issuecomment-381161936) is a non-standard “deviation from the spec”. In the comments to the question I found a note about `objc_storeWeakOrNil` which would fix this bug, however as it isn't documented anywhere and the only place I found it was [objc-internal.h](https://opensource.apple.com/source/objc4/objc4-706/runtime/objc-internal.h) I doubt that it would be possible for us to use it.

On the other hand, since since I've fixed the bug noted in [1.](https://github.com/expo/expo/issues/1647#issuecomment-381161936), the `cannot form weak reference` bug occurred only once, so maybe it was some very strange coincidence and we don't have to worry about it.

**Comment by alexpareto** [comment]
I get the `cannot form weak reference bug` very often. It appears to be related to unmounting/mounting the Video component (as in order to handle the multiple video component issue one must unmount/mount Videos). Here is the error:
```
objc[54165]: Cannot form weak reference to instance (0x6040001569a0) of class EXAVPlayerData. It is possible that this object was over-released, or is in the process of deallocation.
```

It occurs in `observeValueForKeyPath` as noted by @sjchmiela. Let me know if I can provide any more information to help fix this!

**Comment by alexpareto** [comment]
As un update: calling `unloadAsync` in the componentWillUnmount function does not solve the issue (including as an await).

**Comment by terribleben** [comment]
We landed this change yesterday which fixes issue number 1 mentioned above, and which will ship in our next version: https://github.com/expo/expo/commit/51b7f3c03e51428498c62f547e76900bc094d553

**Comment by terribleben** [comment]
Shipped - give it a try and let us know how things go. :)

**Comment by parkerbossier** [comment]
Thanks for all your hard work, y'all! The video-related crashes have largely dropped in frequency, but they still occur too frequently for me to ship.

For the time being, I've reverted back to rendering .gif images. That used to crash my app as well, but with SDK 27, everything seems stable. It's way less efficient in terms of download size, but caching helps.

I'd love it if you could take another look! Running my snack (https://snack.expo.io/@parkerbossier/expo.video-crash) in SDK 27 consistently results in a crash a few seconds after load. This example is admittedly non-optimal since in production I was restricting the number of concurrent videos rendered (I've tried 3 through 8 with similar results).

I'm getting the same type of crash data I was before:
`Incident Identifier: 536217EB-68C8-47A1-A674-D9F90A9D43D7
CrashReporter Key:   ea84f348e0fbc60f887ae39374a50e1e2cb383ab
Hardware Model:      iPhone8,1
Process:             Exponent [9524]
Path:                /private/var/containers/Bundle/Application/B7CA7E19-E9B4-4056-A04B-D4D1D3C5D3F8/Exponent.app/Exponent
Identifier:          host.exp.Exponent
Version:             2.5.0.1014284 (2.5.0)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           host.exp.Exponent [3154]


Date/Time:           2018-04-27 17:36:22.2195 -0700
Launch Time:         2018-04-27 17:30:09.0949 -0700
OS Version:          iPhone OS 11.3 (15E216)
Baseband Version:    4.56.00
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace OBJC, Code 0x1
Triggered by Thread:  0`

**Comment by terribleben** [comment]
Merged the fix internally. It will ship with our next release.

**Comment by terribleben** [comment]
Oops, I referenced the wrong issue in the commit, the fix is this: https://github.com/expo/expo/commit/732c25559860e72ad07ce0ceef80fdb0b9ee6724

**Comment by terribleben** [comment]
The latest release has this fix. Tentatively closing again, let us know if you're still seeing issues.

**Comment by parkerbossier** [comment]
Congrats on the release! I'll give it a shot. Thanks!

**Comment by ami9000** [comment]
I'm on Expo v28 and still getting @parkerbossier's error reported on May 7 when I have multiple Expo Video components in a flatlist - with the difference of: "Exception Type:  EXC_CRASH (SIGABRT)". If it helps, the error hits at around 15+ videos rendered in the list.
