### ISSUE TITLE
expo-image-picker crashes on Android after image is picked SDK 44

### ISSUE THREAD

**Issue by Redxlll** [expo/expo#16749]
### Summary

When picking an image on a standalone build (EAS), the app will crash/restart.
The issue can be replicated in Expo Go when viewing the Snack by enabling the Developer Options > Don't keep activities' option.

The docs mention that Android likes to kill background processes and suggests to use ImagePicker.getPendingResultAsync() but offers no example on how this should be implemented.
I've tried to implement it in a useEffect hook, before/after the image picking but the result is always the same, a crashed app.

Thanks in advance!

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

Doesn't matter as the problem is reproducible in Snack but here's my local info.

expo-env-info 1.0.2 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
      npm: 8.5.4 - ~/.nvm/versions/node/v14.18.2/bin/npm
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 0.48.0
      expo-cli: 5.3.0
    Expo Workflow: managed

### Reproducible demo

https://snack.expo.dev/@redxlll/image-picker

The Snack uses the exact same example code from the docs.
Please note: Although this Snack uses Expo SDK 43 and expo-image-picker 11.0.3, the issue remains with SDK 44 and expo-image-picker 12.0.1.

**Comment by mnightingale** [comment]
Remove allowEditing until next release with fix #16615

**Comment by Redxlll** [comment]
Thanks for your reply! The issue is also apparent when not allowing for editing, I'll adjust the Snack to remove this option.
It's worth mentioning also that even backing out/cancelling image picking will cause the same problem.

**Comment by Redxlll** [comment]
The github issue you mentioned is one I had read through and seems very similar to the situation I'm in, it was unfortunately marked as stale so no solution was come across.

I imagine being able to use getPendingResultAsync on app-reload but as you say it's always an empty array.

Of course I could disable that developer option to stop the issue which would have the process work as expected but for whatever reason the standalone build of an app that utilizes this functionality will always act as if this option is enabled, even on a high end device or Emulator when it previously hadn't done so in Expo SDK 41 which is what I had upgraded from.

**Comment by mnightingale** [comment]
I tried with a [EAS APK build](https://docs.expo.dev/build-reference/apk/) on SDK 44 and didn’t crash in the emulator (picked a jpeg downloaded from Google images).

It didn’t work and I also displayed the contents of getPendingResultAsync which was an empty array.

As far as I can tell if you’re forcing the activity to close you’d have to rely on getPendingResultAsync and indeed some devices could be more aggressive in closing suspended applications which suggests to me the pending result issue should be investigated.

**Comment by mnightingale** [comment]
https://github.com/expo/expo/issues/11103#issuecomment-734232657 and https://github.com/expo/expo/issues/11103#issuecomment-734233943 are relevant.

With the dev option for destroying activities on, `activity === experienceActivity` is false which as @lukmccall said that isn't what I'd expect.

I've tried ejecting to a bare workflow and If I copy in what experienceActivity's initialiser does, then `weak` is null, but `activity` and `experienceActivity` are both not null but not equal, I'm not sure what's going on to cause that.

```kotline
private fun shouldHandleOnActivityResult(activity: Activity, requestCode: Int): Boolean {
  val weak = WeakReference(mActivityProvider.currentActivity).get()
  return experienceActivity != null &&
```

Hopeing @lukmccall sees this and has some idea with what's going on.

---

Ignoring the above, changing the check to allow REQUEST_LAUNCH_CAMERA and REQUEST_LAUNCH_IMAGE_LIBRARY to set pending works however I am seeing a warning for a unhandled promise but I can't make much sense of why that is.

> Possible Unhandled Promise Rejection (id: 1):
> Error: Unable to deactivate keep awake. However, it probably is deactivated already.

**Comment by Redxlll** [comment]
Yes those comments seem almost directly related to the same issue.
Appreciate the look into the native code output, I'm not sure what to look for in those files, that's why I use expo/react-native!

I also built a standalone build of the example snack (`eas build`) and I get a crash as I expected, but only once picking an image as opposed to backing out/cancelling.

Here's the logcat output of when the crash happens.
```
03-28 11:06:47.908  8756  8756 E AndroidRuntime: FATAL EXCEPTION: main
03-28 11:06:47.908  8756  8756 E AndroidRuntime: Process: com.redxlll.snacka79ceb68c1f74a8ea9b2760408249e83, PID: 8756
03-28 11:06:47.908  8756  8756 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:10034 flg=0x1 }} to activity {com.redxlll.snacka79ceb68c1f74a8ea9b2760408249e83/com.redxlll.snacka79ceb68c1f74a8ea9b2760408249e83.MainActivity}: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter mImageLoader
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5857)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5896)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2434)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8633)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter mImageLoader
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at expo.modules.imagepicker.exporters.CompressionImageExporter.<init>(Unknown Source:2)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at expo.modules.imagepicker.ImagePickerModule.handleOnActivityResult(ImagePickerModule.kt:397)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at expo.modules.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.kt:315)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at expo.modules.adapters.react.services.UIManagerModuleWrapper$4.onActivityResult(UIManagerModuleWrapper.java:165)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:305)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:762)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:113)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at expo.modules.ReactActivityDelegateWrapper.onActivityResult(ReactActivityDelegateWrapper.kt:103)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:69)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8651)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5850)
03-28 11:06:47.908  8756  8756 E AndroidRuntime: 	... 13 more
```

One interesting thing I checked out is when building the app using the legacy `expo build:android` command, the issue is resolved and it no longer crashes on my phone though I couldn't say why but clearly something to do with the ejecting during the `eas build` process.

**Comment by AdrianJakubcik** [comment]
Yeah, I'm encountering exactly the same problem as you are. When debugging in the Expo Go app android works as intended with no problem, but as soon as I've built an archive using `eas build` the app crashes upon picking any image with exactly the same stack trace as yours. Can't seem to find a way around it, nor did the `getPendingResultAsync()` help me, or better said maybe I've implemented it the wrong way. I can't tell since I couldn't find much documentation about its implementation...

Pretty much the `expo-image-picker` is unusable in my situation after building the app for android and an alternative the react-native-image-picker ain't working with Expo. I do really wonder if there is no workaround whatsoever even a temporary one until it gets fixed.

**Comment by mnightingale** [comment]
I'm not sure why it's necessary, I guess expo-image-picker should have a dependency on it but you should be able to fix it with:

```
npm install expo-image-loader
```

**Comment by AdrianJakubcik** [comment]
> I'm not sure why it's necessary, I guess expo-image-picker should have a dependency on it but you should be able to fix it with:
> 
> ```
> npm install expo-image-loader
> ```

Thanks for the suggestion will try it out later today, for now, I used a hacky way with `DocumentPicker`, yeah so anybody wondering if there is any workaround in a limited way you can use the `DocumentPicker` like so 
```javascript
result = await DocumentPicker.getDocumentAsync({
      type: ['image/*', 'video/*', 'application/x-mpegURL'],
      copyToCacheDirectory: true
    });
```
And then you can handle the cancel event and the processing of the picked media files. It works for me just fine.
Although I'm still contemplating the fact that it seems like both of them are some kind of `Native File Pickers` yet only one gives you the desired outcome for now.

Also, I had one question is there a way in Expo either using `Image Picker` or any other expo package to let user pic pictures directly from camera roll like from the gallery app or something like that, for example in Instagram if you want to choose picture it either creates it's own modal to display all your albums and camera roll itself, or there is a way to do it with expo package?

**Comment by Redxlll** [comment]
> I'm not sure why it's necessary, I guess expo-image-picker should have a dependency on it but you should be able to fix it with:
> 
> ```
> npm install expo-image-loader
> ```

Thanks, I will give this a go!

I managed to at least move past the block by using a different library for the build which doesn't work with the Expo Go client.
So I have an `if(__DEV__)` statement for the live development which uses `expo-image-picker` and for a build it uses `react-native-image-picker`.

I wonder what's different in the native files for the expo library to error but the non-expo library to work as expected.

**Comment by GeorgiIvanovPXL** [comment]
Issue still exists! Expo Go is crashing after selecting the desired image file.

**Comment by reverend-insanity** [comment]
Expo go crashes after picking image

**Comment by chrisdrifte** [comment]
I'm also seeing this in my standalone build (expo 48.0.20, expo-image-picker 14.1.1, expo-image-loader 4.1.1). The app crashes on my android test device while interacting with the media library.


> Failure delivering result ResultInfo{who=null, request=186834875, result=204, data=Intent { (has extras) }} to activity {com.xxx.xxx.xxx/com.xxx.xxx.xxx.MainActivity}: java.lang.IllegalArgumentException: Required value was null.


Installing `expo-image-loader` and rebuilding the app didn't fix the issue.

**Comment by Alomgir27** [comment]
I facing the same issue. App performance is okay on Expo Go but after eas build whenever I try to pick the image it crashes. How to solve this issue?  I tried every possibility to downgrade SDK 49 to 48, try different versions of expo-image-picker, install expo-image-loader and many more but nothing working.

@chrisdrifte @GeorgiIvanovPXL @reverend-insanity @Redxlll @mnightingale @byCedric @AdrianJakubcik  How you guys solved this issue?

**Comment by MeskLyl** [comment]
I experienced the same issue with SDK 52, however clearing the cache of expo and rebuilding fixed the issue 

> npx expo start -c

As I included permissions checks which I reckon it had a hand in this.
