### ISSUE TITLE
borderRadius does not work as expected on expo-blur

### ISSUE THREAD

**Issue by nicoboy11** [expo/expo#18615]
### Summary

After updating to version 11 (coming from 8) (expo 40 to 45) The borderRadius on expo blur only seem to work in the inner gradient not in the whole view as shown in the image:

![image](https://user-images.githubusercontent.com/14006642/184246774-f1599dad-da54-4523-9bd2-77647cca94a9.png)

This is the code I used for that:
```
        <BlurView
          intensity={90}
          tint="dark"
          style={{ width: 180, height: 180, borderRadius: 90, backgroundColor: 'white', margin: 5  }}
        /> 
```

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 29, 30, 31, 32
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0 
      expo: ^45.0.0 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    Expo Workflow: managed

### Minimal reproducible example

https://snack.expo.dev/wxG-UUYDo

**Comment by nicoboy11** [comment]
@brentvatne thanks! That's a good workaround. I think that works well in the simplest case.But  I still think there is something that can be improved though. If you want to add little more complex borders it does funny stuff for example https://snack.expo.dev/HBTrhbXIW I could probably wrap on yet another view but I thought it was worth giving the heads up here.

**Comment by BrodaNoel** [comment]
I fixed it in this way:

```jsx
<View style={styles.root}>
  <BlurView style={styles.blur} intensity={8}>
    // things there
  </BlurView>
</View>
```

```js
const styles = StyleSheet.create({
  root: {
    borderRadius: 35,
    overflow: 'hidden',
  },
  blur: {
    height: 70,
    width: 100,
    backgroundColor: '#000C',
  },
});
```

**Comment by jimluo123** [comment]
That's not work for me.

**Comment by KlRE** [comment]
What works for me is setting overflow to hidden (android):
`  card: {
    borderRadius: 15,
    overflow: "hidden",
  },`

**Comment by ljukas** [comment]
This is not really a perfect solution, beacuse say you want to add a shadow to this. You would have to add the shadow to the root, which hopefully has a transparent background so that the blur view is solely responsible for the colors. But now we get this warning instead:

```
 WARN  (ADVICE) View #6015 of type RCTView has a shadow set but cannot calculate shadow efficiently. Consider setting a solid background color to fix this, or apply the shadow to a more specific component.
```

**Comment by wallinex** [comment]
Any updates here? Still seeing the borderRadius on my end. Wrapping is not optimal solution.

**Comment by VladShkolnikov** [comment]
Any updates here?
