### ISSUE TITLE
getting error after upgrading to expo SDK 45 to 46

### ISSUE THREAD

**Issue by rahmanharoon** [expo/expo#18766]
### Summary

I have upgraded my expo application which was `expo SDK 45` to `expo SDK 46`.

After upgrading I got this error and trying to figure this for last 4 days. Any help would be helpful..

If I comment out everything from `App.tsx` and added a simple Text in that it will work. If i paste my whole other code it keeps crashing

Here is the error: 
```
Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo/build/errors/ExpoErrorManager.js:25:19 in errorHandler
at node_modules/expo/build/errors/ExpoErrorManager.js:30:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
```

Steps I followed: 

 1. Upgraded Expo SDK into 45 and compiled successfully and then upgraded again into SDK 46
 2. Tried registerRootComponent from a file named main.js [refernce from expo](https://docs.expo.dev/versions/latest/sdk/register-root-component/)

 3. Also tried this answer which refers the multiple copies of react-native-safe-area-context [tried this solution also](https://stackoverflow.com/a/67550379/13913053)

### What platform(s) does this occur on?

Android, iOS

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
      Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.9 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      expo-cli: 6.0.5
    Expo Workflow: managed
```

### Minimal reproducible example

* Upgrade a expo SDK 45 project into expo SDK 46 by adding these dependencies in your project and configure all those and use each package

```
 "dependencies": {
    "@apollo/client": "^3.6.9",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-masked-view/masked-view": "^0.2.7",
    "@react-navigation/bottom-tabs": "^6.3.2",
    "@react-navigation/elements": "^1.3.4",
    "@react-navigation/material-bottom-tabs": "^6.2.2",
    "@react-navigation/material-top-tabs": "^6.2.2",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/stack": "^6.2.2",
    "apollo-link-schema": "^1.2.5",
    "axios": "^0.27.2",
    "expo": "^46.0.0",
    "expo-app-loading": "~2.1.0",
    "expo-constants": "~13.2.3",
    "expo-file-dl": "^2.0.0",
    "expo-file-system": "~14.1.0",
    "expo-firebase-recaptcha": "~2.3.0",
    "expo-font": "~10.2.0",
    "expo-image-picker": "~13.3.1",
    "expo-linear-gradient": "~11.4.0",
    "expo-location": "~14.3.0",
    "expo-media-library": "~14.2.0",
    "expo-modules-core": "~0.11.3",
    "expo-notifications": "~0.16.1",
    "expo-permissions": "~13.2.0",
    "expo-print": "~11.3.0",
    "expo-secure-store": "~11.3.0",
    "expo-status-bar": "~1.4.0",
    "expo-updates": "~0.14.4",
    "firebase": "^9.9.3",
    "formik": "^2.2.9",
    "graphql": "^16.6.0",
    "graphql-tools": "^8.3.3",
    "hermes-engine": "^0.11.0",
    "lodash.isequal": "^4.5.0",
    "lottie-react-native": "5.1.3",
    "moment": "^2.29.4",
    "moti": "^0.18.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.4",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-google-places-autocomplete": "^2.4.1",
    "react-native-maps": "0.31.1",
    "react-native-pager-view": "5.4.24",
    "react-native-paper": "^4.12.4",
    "react-native-phone-number-input": "^2.1.0",
    "react-native-reanimated": "~2.9.1",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-secure-storage": "^0.1.2",
    "react-native-smooth-pincode-input": "^1.0.9",
    "react-native-svg": "12.3.0",
    "react-native-tab-view": "^3.1.1",
    "react-native-web": "~0.18.7",
    "react-native-webview": "11.23.0",
    "recoil": "^0.7.5",
    "styled-components": "^5.3.5",
    "unimodules-permissions-interface": "^6.1.0",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.18.6",
    "@types/react": "~18.0.0",
    "@types/react-native": "~0.69.1",
    "@types/styled-components-react-native": "^5.1.3",
    "react-native-svg-transformer": "^1.0.0",
    "typescript": "^4.6.3"
  },
```

**Comment by Slapbox** [comment]
Is that the only error you get? Are you certain there's not another behind it in the logbox?

**Comment by rahmanharoon** [comment]
> Is that the only error you get? Are you certain there's not another behind it in the logbox?

I was getting ViewPropTypes deprecated error along with that..


I fixed this by referring [this](https://github.com/psycheangel/deprecated-with-module-resolver/blob/master/README.md)

**Comment by hirehouse** [comment]
Same here I'm getting the same error after I upgraded to version 46.0.0. Like the other user I was getting the `ViewPropTypes` error but I suppressed it temporarily with LogBox. (https://stackoverflow.com/questions/71702392/viewproptypes-will-be-removed-from-react-native-migrate-to-viewproptypes-export). Any ideas?

**Comment by Slapbox** [comment]
This isn't an Expo issue. Use `patch-package` to fix your third party dependencies if the developers aren't updating them.

See this thread/comment: https://github.com/facebook/react-native/issues/33557#issuecomment-1220101776

**Comment by jarapamikaella** [comment]
hi @rahmanharoon, up until now I'm still facing this issue, did you really resolved this one?

**Comment by rahmanharoon** [comment]
@jarapamikaella yes i had resolved this issue by following this [link](https://github.com/psycheangel/deprecated-with-module-resolver/blob/master/README.md)

**Comment by victorbamikole** [comment]
@rahmanharoon I'm currently facing the same issue.

**Comment by rahmanharoon** [comment]
for me it was causing by deprecated ViewPropTypes..after fixing this am able to run the app @victorbamikole
