### ISSUE TITLE
expo-print not setting paper height/width (issue since SDK 42)

### ISSUE THREAD

**Issue by borkanee** [expo/expo#19207]
### Summary

This seems to have been an issue since SDK 42. Please, does anyone have a solution?

### What platform(s) does this occur on?

iOS

### Environment

System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
      Android SDK:
        API Levels: 29
        Build Tools: 29.0.2
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

Pass height or width to method _printAsync_

**Comment by borkanee** [comment]
Still running expo sdk 42 due to this issue, is there any idea on when this might be solved? Thanks!

**Comment by Simek** [comment]
This issue should be solved by #20046.

**Comment by borkanee** [comment]
@Simek is this released? Can't seem to get it to work in sdk 47.

**Comment by borkanee** [comment]
@Simek Unfortunately not, tried patching but running into same issue again when using the printAsync method.

**Comment by hotaryuzaki** [comment]
i already use 2.2.1 but why am i still cannot define custom width and height??
we tried in android, is it only works in iOS??

```
await Print.printAsync({ html: response.data, height: 595, width: 842 });
```
