### ISSUE TITLE
SDK47 Beta: cannot build prebuilt iOS app locally due to linking error (not present in SDK46)

### ISSUE THREAD

**Issue by romanonthego** [expo/expo#19808]
### Summary

While trying to upgrade existing Bare App from SDK 46 to SDK 47 Beta I've encountered error building iOS app localy:
```
❌  Undefined symbols for architecture arm64
┌─ Symbol: _objc_msgSend$storyboardWithName:bundle:
└─ Referenced from: l001 in EXSplashScreen(EXSplashScreenViewNativeProvider.o)

❌  ld: symbol(s) not found for architecture arm64

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

› 3 error(s), and 0 warning(s)

CommandError: Failed to build iOS project. "xcodebuild" exited with error code 65.
```

Rollback to SDK46 fixes the issue, so I've just assumed this is something wrong with my app.

But this also persist with newly created and prebuilded app: ` EXPO_BETA=1 expo-cli init` => picked template `blank (Typescript)` => `EXPO_BETA=1 expo-cli prebuild` => `yarn ios`;

### What platform(s) does this occur on?

iOS

### Environment

 ```bash
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.0 - /opt/homebrew/opt/node@16/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - /opt/homebrew/opt/node@16/bin/npm
      Watchman: 2022.10.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/lib/ruby/gems/3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.0-beta.7 => 47.0.0-beta.7
      react: 18.1.0 => 18.1.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.70.4 => 0.70.4
      react-native-web: ~0.18.9 => 0.18.9
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.6
    Expo Workflow: bare
```

### Minimal reproducible example

Repo is here: https://github.com/romanonthego/expo-sdk-47-ios-build-example

this is an "empty" repo, result of:

```bash
EXPO_BETA=1 expo-cli init

EXPO_BETA=1 expo-cli prebuild

yarn ios
```

**Comment by Kudo** [comment]
hi there! we published the prebuilt module with xcode 14. in case you are in xcode 13, please try to add `$ExpoUseSources = ['expo-splash-screen']` in _ios/Podfile_ and try to pod install, build again.

reference for building modules from source: https://expo.fyi/prebuilt-modules

**Comment by romanonthego** [comment]
Will try, thank you.

Will XCode14 be a requirement from now on?

**Comment by Kudo** [comment]
xcode 14 is not a hard requirement, but it looks like the prebuilt binary is incompatible between xcode 13 and xcode 14. in this case we will suggest building all modules from source.

**Comment by lindan4** [comment]
The full version of SDK 47 was released and this error is still present when running `npx eas build`. Has any attempt been made to fix the issue?

**Comment by jamsch** [comment]
Having the same issue on Expo 47.0.3, running EAS on remote.

Command: `eas build -p ios`

package.json:
```json
{
    "dependencies": {
        "expo": "~47.0.3",
        "expo-splash-screen": "~0.17.4"
    }
}
```

EAS build log:
```
› Linking   AppName
❌  Undefined symbols for architecture arm64
┌─ Symbol: _objc_msgSend$storyboardWithName:bundle:
└─ Referenced from: l001 in EXSplashScreen(EXSplashScreenViewNativeProvider.o)

❌  ld: symbol(s) not found for architecture arm64


❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	Ld /Users/expo/Library/Developer/Xcode/DerivedData/<snip>/AppName normal (in target 'AppName' from project 'AppName')
▸ (1 failure)
```

I've added `expo-splash-screen` to `$ExpoUseSources` in the Podfile, but the same issue seems to be cascading to other Expo prebuilds. Is the EAS remote build system up-to-date for Expo 47?

**Comment by giedriusre** [comment]
Same bug here.

**Comment by kouta77** [comment]
I'm having this exact same issue, please let me know when there is a fix or workaround!!

**Comment by giedriusre** [comment]
> I'm having this exact same issue, please let me know when there is a fix or workaround!!

In eas.json scheme under profile ios settings just add: image: „latest“.

Then eas builder will use latest xcode version.

**Comment by kouta77** [comment]
> 

hi @giedriusre I'm also getting this error: "../main.jsbundle: No such file or directory" I tested adding the file ( which exist ) in the target's 'copy bundle resources' section as described by some but no luck...do you know something about it? thank you!

**Comment by mksglu** [comment]
I'm having this exact same issue, any solution? Thanks.

**Comment by qalqi** [comment]
`$ExpoUseSources = [
  'expo-splash-screen','expo-file-system'
]

installer.aggregate_targets.each do |aggregate_target| 
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(SDKROOT)/usr/lib/swift', '$(inherited)'] # or it won't build on apple silicon
          # without explicitly clearing this out, it flaps between excluding arm64 or not
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "" # stop this setting from waffling between arm65/x86_64 machines after pod install
          # Fix some library / linker errors
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES' # only one at a time
          config.build_settings['VALID_ARCHS'] = 'arm64 x86_64' # you need both to work on both CPU archs / release etc
          config.build_settings['EXCLUDED_ARCHS'] = 'i386' # or you get directory not found linker errors
        end
      end
      aggregate_target.user_project.save
    end


` worked for me

**Comment by nandorojo** [comment]
What's the fix for Expo managed projects that are using prebuild with config plugins?

**Comment by nandorojo** [comment]
For what it's worth, I only get this error running `npx expo run:ios -d` and selecting a real device (not simulator). The simulator builds fine.

**Comment by MateuszRostkowski** [comment]
@nandorojo 
I had the same issue and this is what I've done:
1. `npx expo prebuild -p ios --clean`
2. `cd ios && EXPO_USE_SOURCE=1 pod install`
3. Install app on device - I have used xcode to do this, but it should also work with `npx expo run:ios -d`
