### ISSUE TITLE
Typing in TextInput on iOS Simulator will reload the app 

### ISSUE THREAD

**Issue by yonitou** [expo/expo#19911]
### Summary

Hi, 

This is one of my weirdest issues ever but, honestly, one of the most frustrating .. 

For some reason (and the only idea I'm having is an update of Xcode), when I'm typing into a textInput in an iOS Simulator with a development build installed, every time I will type on the "R" key, the app will reload. It's like the text input is not capturing the input and the device did instead. IT NEVER HAPPENED BEFORE ! I literally woke up with this issue ruining my day because the app was reloading by itself every time I'm trying to enter a string with the letter "R" in a text input. 

I really need help here because this is ruining the DX .. 

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

"expo-dev-client": "~1.3.1",
"expo-updates": "~0.14.5"

### Environment

```

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      npm: 8.3.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /Users/yonitouboul/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.8
    Expo Workflow: managed


```

### Reproducible demo

https://github.com/yonitou/je-decide-pour-toi

**Comment by joey-harward** [comment]
I can confirm this is also happening to me. This started happening after upgrading to xCode 14.1

**Comment by rckrueger** [comment]
I was having a pretty good day up until about 30 minutes ago, when I finally upgrade to Xcode 14.1 and am now running simulators with iOS 16.1. Seeing the same issue. I am a professional software engineer with over 60 test accounts, and virtually every one of them starts with the letter 'r'. Thanks a bunch Apple, you have ruined my life - now I am going to walk the Earth like Cain. I can't go on... I can confirm that it does not happen on Xcode 14.0.1.

**Comment by rckrueger** [comment]
Pardon my French but the Apple compiler team "c'est vraiment des abrutis de première" this time around.

**Comment by yonitou** [comment]
Totally agreed => I just downgraded to Xcode 14.0.1 et everything works as before. This is quite an issue though. Don't know if it's linked to React Native itself or Expo but the issue doesn't happen in Expo Go so I guess there is some work to do here ..

**Comment by rckrueger** [comment]
It probably is linked to Expo, we are developing an unmanaged "Expo" project. Clearly Apple does not mind if they clobber the React Native folks with their latest upgrade.

**Comment by Aryk** [comment]
I'm getting this too after my upgrade from 44 -> 47. Not sure if it's related, but running the development version on my simulator. 

I tried killing and reopening the simulator...keeps happening.

**Comment by benazir46** [comment]
Same here. Looking forward to a solution soon

**Comment by rckrueger** [comment]
Right now, I am not sure there is a solution, except to downgrade to Xcode 14.0.1 from 14.1. Alternatively on the simulator you can turn off "Connect Hardware Keyboard" under IO menu on simulator, and use the built in software keyboard instead. I am confident that Expo will fix this issue eventually. Remember that if you are a React Native developer, you are also Apple's redheaded step child as far as they are concerned, i.e. you don't get a lot of love...

**Comment by Aryk** [comment]
I hope it's not too hard to fix...it makes developing and testing a real PITA.

**Comment by rckrueger** [comment]
PITA is a generous acronym

**Comment by dereklucas** [comment]
A coworker had this happen today after upgrading Xcode, while I was not. After some diagnosing we found that pressing “r” while a text input is focused **does not** cause a reload in an iOS 15.5 simulator.
I haven’t tried an iOS 16 simulator, but the 16.1 simulator does still reload.

**Comment by Aryk** [comment]
@dereklucas is there an "easy" way to downgrade to ios 15.5?

**Comment by dereklucas** [comment]
@Aryk yes! Multiple ways according to the docs: https://developer.apple.com/documentation/xcode/installing-additional-simulator-runtimes

I followed the steps under “Install and manage Simulator runtimes in preferences”.

**Comment by rckrueger** [comment]
@dereklucas I think your suggestion to downgrade the simulator to 16.0 is correct. That is a workable solution until Apple and/or Expo fixes this issue.

**Comment by desi-ivanov** [comment]
Apparently, this is caused by this commit https://github.com/expo/expo/commit/85f8c286eca9f6a527902f7e7acebc239af804f4 which removes the `.command` modifier for reloading, making in fact any press of 'r' key to force a reload

**Comment by alephpt** [comment]
is anyone going to fix this?

**Comment by joey-harward** [comment]
I believe this is fixed in `expo-dev-client` v2.0.1

**Comment by ZEAL-MATCH-LTD** [comment]
Experiencing this when focussed on a `<TextInput />` and pressing `r` 

Workaround is using the simulators 'keyboard but that's not ideal.

```
iPhone 14 Pro Max
Version 14.2 (986.5)
SimulatorKit 627
CoreSimulator 857.14
```

**Comment by jackofsometrade** [comment]
I think the easiest workaround is to just type in any other application like textedit, and then copy/paste the content in.  Still hoping for a fix though.

**Comment by troehrkasse** [comment]
Definitely still a problem. Managed expo, development client build, SDK 47. Can't type the letter R into any input field without it reloading the application.

**Comment by cuddeford** [comment]
Such a bizarre problem. My Expo Go was working fine until 30 minutes ago and now pressing R anywhere restarted the app. Then when it comes back I can't click anywhere and the whole app unresponsive. I didn't update or install any packages in this time.

**Comment by mateusw3c** [comment]
Any solution solves the problem?

**Comment by lucksp** [comment]
confirmed, its still an issue , with Xcode 14.2, Expo 46

**Comment by sparga** [comment]
> confirmed, its still an issue , with Xcode 14.2, Expo 46

Which version of `expo-dev-menu` are you using? This is supposed to be [fixed in v2.0.2](https://github.com/expo/expo/blob/main/packages/expo-dev-menu/CHANGELOG.md#202---2022-11-21) which was released after Expo 46.

**Comment by lucksp** [comment]
> > confirmed, its still an issue , with Xcode 14.2, Expo 46
> 
> Which version of `expo-dev-menu` are you using? This is supposed to be [fixed in v2.0.2](https://github.com/expo/expo/blob/main/packages/expo-dev-menu/CHANGELOG.md#202---2022-11-21) which was released after Expo 46.

I don't have `expo-dev-menu`...
We are using ` "expo-dev-client": "~1.3.1",`

**Comment by mcstreilein** [comment]
Not the solution, but if you capitalize each R it works for now

**Comment by finnmerlett** [comment]
Still broken running Expo 48 on simulated iPhone 14 iOS 16.4. Wildly irritating. Why couldn't the cmd-r have been swapped for a cmd-shift-r or a ctrl-r instead or just r?

Lil hack for anyone running into this problem. If you are typing words with r in them, just roll the previous letter into the r, aka make sure you hold down the letter in front of the r until you've pressed the r. If there is no 'all-keys-up' gap between the letter just typed and the r, it doesn't trigger.

Eg. to type the word 'try', type
`<t-down> <r-down> <t-up> <r-up> <y-down> <y-up>`, or
`<t-down> <r-down> <r-up> <t-up> <y-down> <y-up>`

Note that for whatever reason, holding down the letter two-before the r will not work.
Ie. typing 'oar' like this causes a reload:
`<o-down> <a-down> <a-up> <r-down> <o-up> <r-up>`

I also posted this here, on the linked (and open) issue: https://github.com/expo/expo/issues/20233#issuecomment-1619327320

**Comment by JustJoostNL** [comment]
Tried everything, can't type an r. Is anyone going to fix this, since this is very irritating.

**Comment by drdpedroso** [comment]
is there any workaround or solution for this?

**Comment by Aryk** [comment]
should be fixed if you upgrade

**Comment by rafaelsalves** [comment]
Any solution? I created a customized simulator with iOS 15.5 version and works

**Comment by juanbautista0** [comment]
has anyone been able to fix this...?, this problem also occurs in production.
