### ISSUE TITLE
App reloads when pressing "R" on Physical iPad Keyboard

### ISSUE THREAD

**Issue by reececox** [expo/expo#20233]
### Summary

When using a dev client, pressing the R key on a physical keyboard connected to an iPad reloads the application. This happens even when the focus is on a text field. I haven't found a way to disable this.

We use iPad keyboards a lot for development as it improves the experience but it's difficult to code and test the app when typing is involved as pressing the "R" key causes the application to reload.

Moving the reload to Cmd + R would resolve this issue – this would also match the dev menu Cmd + D.

Thanks. Reece

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

expo: 47.0.0
expo-dev-client: 2.0.1

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.15.1 - /usr/local/bin/npm
      Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.3 
      babel-preset-expo: ~9.2.1 => 9.2.2 
      expo: ^47.0.0 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.10 
    Expo Workflow: managed
```

### Reproducible demo

- Build and open a dev-client on an iPad that has a physical keyboard connected
- Press "R" on the keyboard
- The dev-client reloads
- Open an application in the dev-client
- Press "R" on the keyboard
- The application in the dev-client reloads

This happens everywhere in the dev client. Pressing R on the main dev client interface reloads the dev client. Pressing R after you've loaded an application reloads the application

**Comment by ateethk** [comment]
Have been running into this issue on iPhone as well for the past 2 weeks -- never used to happen prior. Pressing R always reloads it, making it very difficult to test and text field inputs.

**Comment by mricho** [comment]
I'm seeing this issue in the iOS Sim, expo-dev-client (1.3.1), while typing "R" into an input box with desktop keyboard

**Comment by johngarcia9110** [comment]
I am also seeing this issue

**Comment by amin79** [comment]
same problem with "expo": "^47.0.6" and "expo-dev-client": "~2.0.1".

**Comment by pwfcurry** [comment]
https://github.com/expo/expo/pull/14590
https://github.com/expo/expo/pull/14202

**Comment by demianscv** [comment]
Might also be fixed in https://github.com/expo/expo/pull/20209

**Comment by lucksp** [comment]
tracked in https://github.com/expo/expo/issues/19911 which is marked closed, but I am replicating it in Expo 46 & Xcode 14.2

**Comment by lucksp** [comment]
this is not fixed with XCode 14.3 either

**Comment by finnmerlett** [comment]
Still broken running Expo 48 on simulated iPhone 14 iOS 16.4. Wildly irritating. Why couldn't the cmd-r have been swapped for a cmd-shift-r or a ctrl-r instead or just r?

**Comment by Albro3459** [comment]
> Still broken running Expo 48 on simulated iPhone 14 iOS 16.4. Wildly irritating. Why couldn't the cmd-r have been swapped for a cmd-shift-r or a ctrl-r instead or just r?
> 
> Lil hack for anyone running into this problem. If you are typing words with r in them, just roll the previous letter into the r, aka make sure you hold down the letter in front of the r until you've pressed the r. If there is no 'all-keys-up' gap between the letter just typed and the r, it doesn't trigger.
> 
> Eg. to type the word 'try', type `<t-down> <r-down> <t-up> <r-up> <y-down> <y-up>`, or `<t-down> <r-down> <r-up> <t-up> <y-down> <y-up>`
> 
> Note that for whatever reason, holding down the letter two-before the r will not work. Ie. typing 'oar' like this causes a reload: `<o-down> <a-down> <a-up> <r-down> <o-up> <r-up>`

Unfortunately Im still having this problem and this workaround doesnt work :(

**Comment by jrdn91** [comment]
This is STILL happening it seems as of the latest SDK 52. iOS 18.1 and xcode version 16.1. I have seen several PR's that look like they allegedly fix this but it still persists. It maintains this behavior in Expo go (using the `expo start --ios` command) as well as running a build build (using the `expo run ios` command).

**Comment by ncesar** [comment]
still happening on ios

**Comment by leonardorb** [comment]
Also having this weird issue.
```
"expo": "^52.0.11",
"expo-dev-client": "^5.0.4",

iOS Simulator 18.0.
```

I believe this issue started when I updated Expo Go.

**Comment by jrdn91** [comment]
Yes it's for sure related to Expo Go

**Comment by mikelmulti460** [comment]
I have the same problem here.

**Comment by correafederico25** [comment]
`  "expo": "~52.0.20",
   
  IPhone 15 PRO - iOS Simulator 17.4
  Version 16.0 (1038)
 SimulatorKit 942
 CoreSimulator 993.7
`

I have the same issue

**Comment by onurravli** [comment]
Same here, in 2025. 😁

**Comment by Demven** [comment]
I have the same issue, please fix it. Can't log in to my app anymore...

**Comment by raywalz** [comment]
> I have the same issue, please fix it. Can't log in to my app anymore...

This issue is a pain and should be fixed but you can work around it by using either the iOS keyboard (can be launched in Simulator with Cmd+K) or by making sure you press down on the R key before letting go of the previous key.

**Comment by carybriel** [comment]
Happening here as well. SDK version 52.0.0.  

The best answer IMO is to add a modifier key to the letter r. Hoping for an update that fixes it. Currently using caps works also, when this is possible in the app, but the problem is very inconvenient and wastes a lot of time dealing with it.

expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
      npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.23 => 52.0.23 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.5 => 0.76.5 
    npmGlobalPackages:
      eas-cli: 12.0.0
    Expo Workflow: bare

**Comment by ReneKrewinkel** [comment]
> > I have the same issue, please fix it. Can't log in to my app anymore...
> 
> This issue is a pain and should be fixed but you can work around it by using either the iOS keyboard (can be launched in Simulator with Cmd+K) or by making sure you press down on the R key before letting go of the previous key.

No, unfortunately this doesn't work (for me). Only thing for me is to hard-code (in this case my email address) the input value so I can at least get some development done.

**Comment by mattsellars123** [comment]
As a short term work around for my team I've added a `yarn patch expo-dev-menu` and updated the file in the Modules/DevMenuExtensions.swift to make the registered input: `reload.registerKeyCommand(input: "r", modifiers: [.control])`

I used control because cmd + r is used to start recording in simulator.

Using yarn patch ensures the change is applied locally for us but we have to make sure to re-patch when we upgrade expo-dev-menu versions.

**Comment by xgenem** [comment]
Why doesn't expo fix this?

**Comment by vonovak** [comment]
Hello and thanks for reporting,
I just had a look at this and wasn't able to reproduce the issue (iOS simulator, as well as iPad simulator).

Reload-while-typing should not happen due to [this check](https://github.com/facebook/react-native/blob/0b1f86200629fa33b56c7a22870dab5cf81cf4a1/packages/react-native/React/Base/RCTKeyCommands.m#L141).

Adding a patch that uses `reload.registerKeyCommand(input: "r", modifiers: [.control])` shouldn't make any difference because of [this handling](https://github.com/facebook/react-native/blob/0b1f86200629fa33b56c7a22870dab5cf81cf4a1/packages/react-native/React/Base/RCTKeyCommands.m#L73).

I'm going to close the issue now because I'm not able to reproduce it and there's no reproducer provided. But if you're running into it, please open a new issue and follow the issue template.

Thank you 🙂
