### ISSUE TITLE
Notification `textInput` not returning `userText` in some cases

### ISSUE THREAD

**Issue by tgxn** [expo/expo#20500]
### Summary

Issue presents with `setNotificationCategoryAsync` and `addNotificationResponseReceivedListener` with certain action configurations:

All actions are setup with the calls to `setNotificationCategoryAsync`; for example:
```js
await Notifications.setNotificationCategoryAsync("submit_reply", [
        {
          identifier: "reply",
          buttonTitle: "Reply",
          textInput: {
            submitButtonTitle: "Reply",
          },
          options: {
            opensAppToForeground: false,
          },
        },
      ]);
```

[Example Git Repo](https://github.com/tgxn/expo-push-example)

[Here is this app, build with google services](https://expo.dev/accounts/tgxn/projects/test/builds/b987977d-eab9-4fd6-ae2e-34db5bcefbfa)

### "submit_reply"

you can see the `notificationResponse.userText` [value](https://github.com/tgxn/expo-push-example/blob/main/App.js#L170) is filled

```js
{
    identifier: "reply",
    buttonTitle: "Reply",
    textInput: {
        submitButtonTitle: "Reply",
    },
    options: {
        opensAppToForeground: false,
    },
}
```
![](https://github.com/tgxn/expo-push-example/raw/main/img/submit_reply.jpg)

### "submit_reply_placeholder"

here, the issue is the `notificationResponse.userText` value gets set to the valu eset in the placeholder.

```js
{
    identifier: "reply",
    buttonTitle: "Reply",
    textInput: {
        submitButtonTitle: "Reply",
        placeholder: "Type a reply...",
    },
    options: {
        opensAppToForeground: false,
    },
}
```
![](https://github.com/tgxn/expo-push-example/raw/main/img/submit_reply_placeholder.jpg)

### "submit_reply_foreground"

here, `notificationResponse.userText` is never populated

```js
{
    identifier: "reply",
    buttonTitle: "Reply",
    textInput: {
        submitButtonTitle: "Reply",
    },
    options: {
        opensAppToForeground: true,
    },
}
```
![](https://github.com/tgxn/expo-push-example/raw/main/img/submit_reply_foreground.jpg)

### "submit_reply_foreground_placeholder",

here, `notificationResponse.userText` is never populated

```js
{
    identifier: "reply",
    buttonTitle: "Reply",
    textInput: {
        submitButtonTitle: "Reply",
        placeholder: "Type a reply...",
    },
    options: {
        opensAppToForeground: true,
    },
}
```
![](https://github.com/tgxn/expo-push-example/raw/main/img/submit_reply_foreground_placeholder.jpg)

### What platform(s) does this occur on?

Android

### Environment

Android Tested Dev Build & Prod APK

```sh
$ npx expo-env-info
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.1.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~47.0.8 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: managed
```

### Minimal reproducible example

Unfortunately, since notification actions didn't work in Snack, I created this example with EAS to demo:

[here is the code](https://github.com/tgxn/expo-push-example) the builds i made are as follows:
 EAS Build [DevClient](https://expo.dev/accounts/tgxn/projects/test/builds/b987977d-eab9-4fd6-ae2e-34db5bcefbfa)

**Comment by oreHGA** [comment]
Thanks for the detailed bug report @tgxn! You just bailed me out after 2hrs of trying to figure this out.

Removing the `placeholder` key in the `textInput` seemed to do the trick for me too.

**Comment by younes0** [comment]
Thanks @oreHGA 
Your solution works, there's a typescript error which you can ignore.
This is a regression, I remenber everything worked fine 2 years ago.

**Comment by thalida** [comment]
Any update on when this can be resolved for Android? 
I sadly don't know enough (yet) to contribute up a fix myself.

**Comment by LucasBourgeois** [comment]
Hi, any update about this ? 
Im setting my notification without setting the placeholder and ignoring the ts error.
But when doing so, the addNotificationResponseReceivedListener() isnt triggered at all..

**Comment by imranbarbhuiya** [comment]
This issue is already fixed in https://github.com/expo/expo/pull/27479, keep the placeholder and it'll work

**Comment by LucasBourgeois** [comment]
Ive more details on my case.
In fact, the placeholder is mandatory.
It's working like a charm on iOS in expoGo and im getting the userText.
But in android in ExpoGo, the userText is undefined. And idk why it's not working on a prod env (maybe a bad configuration, but idk yet)

**Comment by rranjan14** [comment]
> This issue is already fixed in #27479, keep the placeholder and it'll work

Still not working for android. I am using version `0.28.15`

**Comment by mkhoussid** [comment]
Same issue. Removed `placeholder` for android.

**Comment by LucasBourgeois** [comment]
How can you pass no placeholder and still have this working with a setNotificationCategoryAsync rejecting because it requires a string.
It attemps to cast a nil and rejects :
See this https://github.com/expo/expo/issues/20500#issuecomment-2288450313

**Comment by LucasBourgeois** [comment]
I finally managed to debug expo-notifications package java.
It seems that there is no userText in notificationResponse because Intent action is not a TextInputNotificationResponse but a NotificationResponse instead.

in NotificationSerializer.java
`public class NotificationSerializer {
  public static Bundle toBundle(NotificationResponse response) {
    Bundle serializedResponse = new Bundle();
    serializedResponse.putString("actionIdentifier", response.getActionIdentifier());
    serializedResponse.putBundle("notification", toBundle(response.getNotification()));
    if (response instanceof TextInputNotificationResponse) {
      serializedResponse.putString("userText", ((TextInputNotificationResponse) response).getUserText());
    }
    return serializedResponse;
  }`

**Comment by LucasBourgeois** [comment]
Ok ive finally managed to make this works : 
Here the thing : 

We're getting textInput placeholder only when running the app through ExpoGo. On a standealone build, we get the response.

Also, if no userText is setted in the notification response, it's because the native packages is replacing the notification instance type. See in NotificationService.kt => createNotificationResponseBroadcastIntent.kt

Here the fix : If setting the action like so :
```
{
	buttonTitle: tCap('answer'),
	identifier: 'newChatMessage_answer',
	textInput: {placeholder: tCap('answer'), submitButtonTitle: tCap('submit')},
	options: {
		// This allows to retrieve NotificationResponse.userText
		opensAppToForeground: false
	}
}
```

This will works 👍

**Comment by vonovak** [comment]
Hello and thanks for reporting,
I have tried to reproduce the issue but was not able to find the problem.

The `placeholder` parameter is required, otherwise you'll get `Record.TextInput.placeholder: kotlin.String' is required, got nil` error as seen in https://github.com/expo/expo/issues/20500#issuecomment-2288450313.

I'm going to close the issue now, but if this still is a problem for someone, with the latest version of `expo-notifications`, please open a new issue and follow the template.
Thank you 🙂
