### ISSUE TITLE
[SDK 48 beta.2] No native splash screen registered for given view controller

### ISSUE THREAD

**Issue by luluhoc** [expo/expo#21173]
### Summary

After updating to SDK 48, I'm getting the white flash of background when using dark mode on device and the No native splash screen registered for given view controller error, SDK 47

### What platform(s) does this occur on?

Android, iOS

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.0-beta.2 => 48.0.0-beta.2 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.2 => 0.71.2 
    npmGlobalPackages:
      eas-cli: 3.5.2
    Expo Workflow: bare
```

### Minimal reproducible example
app.config.js
```
import { ExpoConfig } from '@expo/config-types';

const LIGHT_SPLASH = {
  image: './assets/splash-s.png',
  backgroundColor: '#FFFFFF',
};

const DARK_SPLASH = {
  image: './assets/cdorfordark.png',
  backgroundColor: '#000000',
};

const SHARED_SPLASH = {
  splash: {
    ...LIGHT_SPLASH,
    dark: {
      ...DARK_SPLASH,
    },
  },
};
export default (): ExpoConfig => {
  return {
    name: "CD'OR",
    slug: 'CDOR',
    scheme: 'com.fidelity.cdor',
    version: '1.0.0',
    orientation: 'portrait',
    jsEngine: 'hermes',
    icon: './assets/icon.png',
    userInterfaceStyle: 'automatic',
    splash: SHARED_SPLASH,
    hooks: {
      postPublish: [
        {
          file: 'sentry-expo/upload-sourcemaps',
          config: {
            organization: 'c-u0',
            project: 'fidelity',
            authToken:
              'zzzzzzz',
          },
        },
      ],
    },
    ios: {
      ...SHARED_SPLASH,
      userInterfaceStyle: 'automatic',
      jsEngine: 'hermes',
      entitlements: {
        'com.apple.developer.networking.wifi-info': true,
      },
      infoPlist: {
        UIUserInterfaceStyle: 'Automatic',
        ITSAppUsesNonExemptEncryption: false,
        NSLocationWhenInUseUsageDescription:
          'This app needs access to your location.',
        NSLocationAlwaysAndWhenInUseUsageDescription:
          'This app needs access to your location.',
        NSLocationAlwaysUsageDescription:
          'This app needs access to your location.',
      },
      bundleIdentifier: 'com.fidelity.cdor',
    },
    android: {
      ...SHARED_SPLASH,
      userInterfaceStyle: 'automatic',
      jsEngine: 'hermes',
      package: 'com.fidelity.cdor',
      googleServicesFile: './android/app/google-services.json',
      permissions: [
        'WRITE_SETTINGS',
        'WRITE_SECURE_SETTINGS',
        'ACCESS_FINE_LOCATION',
        'ACCESS_COARSE_LOCATION',
        'VIBRATE',
        'POST_NOTIFICATIONS',
        'RECEIVE_BOOT_COMPLETED',
        'SCHEDULE_EXACT_ALARM',
      ],
      config: {
        googleMaps: {
          apiKey: 'zzzz-zzzzz',
        },
      },
    },
    updates: {
      fallbackToCacheTimeout: 0,
    },
    runtimeVersion: '1.0.0',
    assetBundlePatterns: ['**/*'],
    web: {
      favicon: './assets/favicon.png',
    },

    plugins: [
      'sentry-expo',
      'expo-localization',
      [
        'expo-build-properties',
        {
          ios: {
            useFrameworks: 'static',
          },
        },
      ],
    ],
    extra: {
      apiUrl: process.env.API_MAC || 'http://zzzzzz:3000/graphql',
      apiUrlBasic: process.env.API_MAC_BASIC || 'http://3zzzz:3000/',
      eas: {
        projectId: 'zzzz',
      },
    },
  };
};
```

**Comment by luluhoc** [comment]
for info i used clean prebuild

**Comment by Nodonisko** [comment]
I am getting similar error for Android:

```
Error: No native splash screen registered for provided activity. Please configure your application's main Activity to call 'SplashScreen.show' (https://github.com/expo/expo/tree/main/packages/expo-splash-screen#-configure-android).
```

I am using only expo modules in bare RN app. This issue appeared after updating to to SDK 48 beta.2 and `expo-splash-screen: 0.18.1`

**Comment by luluhoc** [comment]
I'm also using `"expo-splash-screen": "~0.18.1",`

**Comment by xmflsct** [comment]
Same here

**Comment by brentvatne** [comment]
this should be resolved in the latest `expo@48`

**Comment by luluhoc** [comment]
@brentvatne I updated to 48.0.1 did a clean prebuild and it's still the case for me, can you reopen?

**Comment by brentvatne** [comment]
@luluhoc - can you provide a minimal reproducible example? https://stackoverflow.com/help/minimal-reproducible-example

**Comment by luluhoc** [comment]
@brentvatne 

Here is reproducible example 

https://github.com/luluhoc/no-native-splash-error

Thanks

**Comment by Nodonisko** [comment]
I can confirm it's still happening in latest expo version in bare expo template.

**Comment by xmflsct** [comment]
Why this issue was closed?

**Comment by brentvatne** [comment]
@xmflsct - there is no minimal reproducible example provided: https://stackoverflow.com/help/minimal-reproducible-example

the repository that @luluhoc shared contains about 100 dependencies, which is far from minimal.

**Comment by xmflsct** [comment]
@brentvatne thanks for explaining

**Comment by elitenas** [comment]
Still happening here as well. I can create a minimal repro project and post back here

**Comment by gmartpad** [comment]
@elitenas were you able to create a minimal repo project?

**Comment by elitenas** [comment]
I resolved the issue, the `hideAsync()` line was getting called multiple times for me in `useEffect()` so i fixed that

**Comment by elitenas** [comment]
I can still reproduce the issue... i will post a repro link in a day or two.

**Comment by basbase** [comment]
I was getting this error because I was missing the change to MainActivity.java described here: https://docs.expo.dev/bare/installing-expo-modules/

**Comment by alainib** [comment]
i still get this error 

`Error: No native splash screen registered for provided activity. Please configure your application's main Activity to call 'SplashScreen.show' (https://github.com/expo/expo/tree/main/packages/expo-splash-screen#-configure-android).`

checked all the point marked in the error link

**Comment by dannybit** [comment]
I am also still seeing this error.
 "expo-splash-screen": "^0.18.1" and "expo": "^48.0.7",
