### ISSUE TITLE
[SDK 48] Bare workflow, android release w/ product flavors - "The embedded manifest is invalid or could not be read"

### ISSUE THREAD

**Issue by tylercote** [expo/expo#21382]
### Minimal reproducible example

https://github.com/tylercote/bare-workflow-48

### Summary

1. Clone repo
2. Open in Android Studio
3. Select "developmentRelease" build variant
4. Attempt to build on emulator 
5. The app crashes immediately upon launch with the following logcat output: 
```
Could not get package user id: run-as: package not debuggable: com.barebones.app.dev
The embedded manifest is invalid or could not be read. Make sure you have configured expo-updates correctly in android/app/build.gradle. app.manifest
```

The only details I have changed from a fresh project:
- Adding "app" package (i.e. com.barebones -> com.barebones.app)
- Adding different product flavors, with different applicationId

My apologies if this is a project configuration issue rather than an Expo issue, but I saw the same issue posted elsewhere so I figured I'd try to create a minimal example of it happening.

#21238

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 17.9.1 - ~/.nvm/versions/node/v17.9.1/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v17.9.1/bin/npm
      Watchman: 2023.02.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/tylercote/.rvm/gems/ruby-2.7.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.4 => 48.0.4
      react: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
    npmGlobalPackages:
      eas-cli: 3.7.1
      expo-cli: 6.3.1
    Expo Workflow: bare

**Comment by douglowder** [comment]
@tylercote from the context, it seems as though you want this build to be a debug build. If so, you would need to customize `debuggableVariants` (see https://github.com/tylercote/bare-workflow-48/blob/main/android/app/build.gradle#L25).

**Comment by tylercote** [comment]
Appreciate you taking a look. I actually forgot to mention that I did indeed include the non-release ones there "local", "development", and "production", and was still seeing the issue.

It seemed as if that array wasn't being paid any attention, and it was still trying to build "releaseDevelopment" as a debug version.

**Comment by douglowder** [comment]
Ok thanks @tylercote I'll investigate, and thanks for the repro

**Comment by bebe84** [comment]
Have the same issue when I upgraded to SDK 48, I have build variants as well and manifest is not included, app crashes imdiately in release mode.

**Comment by tylercote** [comment]
I am a little confused by this.  I indeed want expo-updates in my project, and I thought I had added the proper configuration to the [AndroidManifest.xml](https://github.com/tylercote/bare-workflow-48/blob/4548962d1f10008f6d22dda9587a17f5831c18d5/android/app/src/main/AndroidManifest.xml#L13) to enable it.

I think the build variant was automatically named "developmentRelease" due to the combination of my flavor "development" and the predefined "release" build type.

Am I supposed to see information about a URL at android/app/build/generated/assets/expo-updates/development/release/app.manifest?

**Comment by douglowder** [comment]
Just to be clear, are you going to be using EAS Build and Update? If so, did you execute `eas build:configure` and `eas update:configure`?

**Comment by bebe84** [comment]
@douglowder I don't think this is completely true, and IMHO those two issues are connected in Android there is combination of flavour like "staging" and development & release, so for example if I want to created stagingRelease version of the app I am using command like ./gradlew installStagingRelease or assembleStagingRelease to make the package. In both cases manifest app is not presented and I have configured expo-updates correctly. For me issue should be still open.

@tylercote try to change to gradle version classpath('com.android.tools.build:gradle:7.1.1') in android/build.gradle and see if this helps your case.

**Comment by douglowder** [comment]
@tylercote I took a closer look at the `AndroidManifest.xml` in your project, and I see that you have attempted to add a request header manually. Unfortunately, the single quotes need to be HTML-escaped in order to work correctly. That may be the real reason the manifest is not being generated.

I recommend taking a look at the new document we just published: https://docs.expo.dev/eas-update/eas-update-with-local-build/ .

I'll reopen this and do some more testing with your project to make sure that is really the issue.

@bebe84 thanks for your help with this issue, and for the suggestion to try gradle 7.1.1. I am very interested to see if that fixes the issue and if so, why.

**Comment by tylercote** [comment]
@douglowder Thank you for pointing that out. It led me to simplify down to the following configuration, and the app is no longer crashing! I think that including AUTO_SETUP = false may have been the specific line that prevents the crash from occurring. I pushed the latest to main in case you still want to explore, but I appreciate the help and it seems my issue is fixed.

```
<meta-data android:name="expo.modules.updates.EXPO_RUNTIME_VERSION" android:value="1.2.4"/>
<meta-data android:name="expo.modules.updates.EXPO_UPDATE_URL" android:value="https://u.expo.dev/c38a94d3-7845-4469-bfe2-e24b1de157fb"/>
<meta-data android:name="expo.modules.updates.AUTO_SETUP" android:value="false"/>
```

**Comment by douglowder** [comment]
@bebe84 could you try something for me to see if it resolves the issue?

In `node_modules/expo-updates/scripts/create-manifest-android.gradle`, modify line 65 to just be "true".

```diff
diff --git a/packages/expo-updates/scripts/create-manifest-android.gradle b/packages/expo-updates/scripts/create-manifest-android.gradle
index 81138a9e93..8bd5f36cb0 100644
--- a/packages/expo-updates/scripts/create-manifest-android.gradle
+++ b/packages/expo-updates/scripts/create-manifest-android.gradle
@@ -62,7 +62,7 @@ def setupClosure = {
         commandLine(*nodeExecutableAndArgs, "$expoUpdatesDir/scripts/createManifest.js", "android", projectRoot, assetsDir, entryFile)
       }
 
-      enabled config."bundleIn${targetName}" || targetName.toLowerCase().contains("release") || ex_updates_native_debug
+      true
     }
 
     def currentAssetsCopyTask = tasks.create(
```

and see if that fixes the issue.

**Comment by tylercote** [comment]
@bebe84 Can you show what your AndroidManifest.xml looks like? I was able to get my project to not crash, feel free to reference the repo in my issue to see mine.

@douglowder I am however now unable to change the release channel away from 'default'. I have updated the repo here. I am not using any sort of expo prebuild or EAS here.

https://github.com/tylercote/bare-workflow-48/commit/6f94acaeca6312aa9926a01b9d2e00834c6640d9

**Comment by sin2** [comment]
I'm also experiencing this issue, I had to install expo-updates because I am using sentry-expo in my bare expo project. Removing the library fixes the build issue, but sentry-expo cannot be used.

@douglowder your change for create-manifest-android.gradle did not fix the issue for me.

**Comment by bebe84** [comment]
@douglowder Your fix didn't work for me, either. 
@sin2 I have the same situation, I am using expo-sentry and it internally uses expo-updates, I would love to remove the package but it is no go.
@tylercote It is not working for me, still crashing.

I was thinking yesterday about it and maybe path to variants change in newer Gradles and it can't copy the manifest 🤔

**Comment by tylercote** [comment]
@douglowder 
@bebe84 

I am now seeing the crash that you mention @bebe84, as I had previously forgotten to update the native code as mentioned [here](https://docs.expo.dev/bare/installing-updates/#customizing-automatic-setup-for-android). Upon updating the native code, it is returning to crashing on launch. I will update the repro in my original issue to indicate this.

**Comment by douglowder** [comment]
I dug a little deeper into this issue today. I cloned your repo and initialized the project in my own EAS workspace (`eas init`, `eas build:configure`, `eas update:configure`, etc.). I do see the crash you are reporting.

Your Android gradle files seem quite different from the ones in the Expo SDK 48 template that are known to work. I will attempt to create a minimal diff showing the changes needed.

Since you are using React Native 0.71.3, I do recommend that you start with the SDK 48 template if you did not do so.

**Comment by douglowder** [comment]
Ok to make things simpler, I reproduced the issue a different way.

- Execute the following:

```
yarn create expo-app bare-workflow-48 --template blank-typescript
cd bare-workflow-48
eas init
eas update:configure
```

- Modify `app.json` to add request headers for updates:

```json
{
  "expo": {
.
.
.
    "updates": {
      "requestHeaders": {
        "expo-channel-name": "main"
      },
      "url": "https://u.expo.dev/_project_id_"
    }
  }
}
```

- Execute `npx expo prebuild` and select the default package name and bundle identifier (in my case, it was `com.douglowderexpo.bareworkflow48`)
- Build and run the Android app

```
cd android
./gradlew :app:installRelease
```

App will start as expected.

- Now edit `android/app/build.gradle` as follows to add some variants:

```gradle
    flavorDimensions "default"
    productFlavors {
        local {
            applicationId "com.douglowderexpo.bareworkflow48.local"
        }   
        development {
            applicationId "com.douglowderexpo.bareworkflow48.dev"
        }   
        production {
            applicationId "com.douglowderexpo.bareworkflow48"
        }   
    }   
```
- Try building and installing one of the variants:

```
cd android
./gradlew :app:installDevelopmentRelease
```

It will cause the missing manifest crash described in this issue.

I suspect that the build flavors need additional lines in the build files to properly create and package the updates manifest.

**Comment by ken0x0a** [comment]
for sdk 48, that might be related to
https://github.com/expo/expo/blob/11c0cbb32e6867b1e2103353493c452d240c4e98/packages/expo-updates/scripts/create-manifest-android.gradle#LL65C21-L65C22

You can avoid this error by put `project.ext.react` back to "android/app/build.gradle"
```gradle
project.ext.react = [
  bundleInDev: true,
  bundleInYourFlavourInPascalCase: true,
]
```

**Comment by tylercote** [comment]
@ken0x0a This unfortunately did not fix the crash in my case.

**Comment by douglowder** [comment]
@tylercote in sdk 48, we have moved to React Native 0.71, and the gradle process is quite different. The `bundleInDev` and some other properties no longer apply, and the `debuggableVariants` was introduced, among other changes. It is mostly managed by [react-native-gradle-plugin](https://reactnative.dev/docs/react-native-gradle-plugin) now.

**Comment by ken0x0a** [comment]
@douglowder 
Did you read the following code?
https://github.com/expo/expo/blob/11c0cbb32e6867b1e2103353493c452d240c4e98/packages/expo-updates/scripts/create-manifest-android.gradle#LL65C21-L65C22

It's for that and included in `expo-updates@0.16.3` which is for SKD48.

And those lines still works for that version.

**Comment by douglowder** [comment]
@ken0x0a thanks, I am aware of that code, I was the last committer 😄 

Line 65 has been there for a long time, I only added the support for native debug of updates, which unfortunately has no effect on how the flavor variants are built.

I am continuing to work on this issue and will post here again when I make progress.

**Comment by ken0x0a** [comment]
@douglowder yeah, I saw that.

I might misinformed. I'm using `buildType` and not `flavor`.
Without  `bundleInDev`,

```
...
Task :expo-updates:copyDevExpoManifest SKIPPED
...
```

will happen right?
Or, is there another reason for this skip?

As I followed the code, I found that code is the one I was looking for, and `The embedded manifest is invalid or could not be read.` was fixed in my case.

Interesting

**Comment by Johan-dutoit** [comment]
I get the same error (and ultimately crash), but gradle doesn't show it as skipped.

```
[10:31:00]: ▸ > Task :expo-updates:createQaReleaseExpoManifest
[10:31:00]: ▸ Execution optimizations have been disabled for task ':expo-updates:createQaReleaseExpoManifest' to ensure correctness due to the following reasons:
[10:31:00]: ▸ - Gradle detected a problem with the following location: '/home/runner/work/redacted/redacted/android'. Reason: Task ':expo-updates:createQaReleaseExpoManifest' uses this output of task ':app:compileQaReleaseAidl' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[10:31:00]: ▸ - Gradle detected a problem with the following location: '/home/runner/work/redacted/redacted/android'. Reason: Task ':expo-updates:createQaReleaseExpoManifest' uses this output of task ':app:compileQaReleaseRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[10:31:00]: ▸ - Gradle detected a problem with the following location: '/home/runner/work/redacted/redacted/android'. Reason: Task ':expo-updates:createQaReleaseExpoManifest' uses this output of task ':app:compileQaReleaseShaders' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[10:31:00]: ▸ - Gradle detected a problem with the following location: '/home/runner/work/redacted/redacted/android'. Reason: Task ':expo-updates:createQaReleaseExpoManifest' uses this output of task ':app:createBundleQaReleaseJsAndAssets' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[10:31:00]: ▸ - Gradle detected a problem with the following location: '/home/runner/work/redacted/redacted/android'. Reason: Task ':expo-updates:createQaReleaseExpoManifest' uses this output of task ':app:createQaReleaseCompatibleScreenManifests' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[10:31:00]: ▸ - Gradle detected a problem with the following location: '/home/runner/work/redacted/redacted/android'. Reason: Task ':expo-updates:createQaReleaseExpoManifest' uses this output of task ':app:extractDeepLinksQaRelease' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[10:31:00]: ▸ - Gradle detected a problem with the following location: '/home/runner/work/redacted/redacted/android'. Reason: Task ':expo-updates:createQaReleaseExpoManifest' uses this output of task ':app:generateQaReleaseBuildConfig' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[10:31:00]: ▸ - Gradle detected a problem with the following location: '/home/runner/work/redacted/redacted/android'. Reason: Task ':expo-updates:createQaReleaseExpoManifest' uses this output of task ':app:generateQaReleaseResValues' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[10:31:00]: ▸ - Gradle detected a problem with the following location: '/home/runner/work/redacted/redacted/android'. Reason: Task ':expo-updates:createQaReleaseExpoManifest' uses this output of task ':app:javaPreCompileQaRelease' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[10:31:00]: ▸ - Gradle detected a problem with the following location: '/home/runner/work/redacted/redacted/android'. Reason: Task ':expo-updates:createQaReleaseExpoManifest' uses this output of task ':app:mapQaReleaseSourceSetPaths' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[10:31:00]: ▸ - Gradle detected a problem with the following location: '/home/runner/work/redacted/redacted/android'. Reason: Task ':expo-updates:createQaReleaseExpoManifest' uses this output of task ':app:mergeQaReleaseAssets' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[10:31:00]: ▸ - Gradle detected a problem with the following location: '/home/runner/work/redacted/redacted/android'. Reason: Task ':expo-updates:createQaReleaseExpoManifest' uses this output of task ':app:mergeQaReleaseShaders' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[10:31:00]: ▸ - Gradle detected a problem with the following location: '/home/runner/work/redacted/redacted/android'. Reason: Task ':expo-updates:createQaReleaseExpoManifest' uses this output of task ':app:processQaReleaseGoogleServices' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[10:31:00]: ▸ - Gradle detected a problem with the following location: '/home/runner/work/redacted/redacted/android'. Reason: Task ':expo-updates:createQaReleaseExpoManifest' uses this output of task ':app:processQaReleaseMainManifest' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[10:31:00]: ▸ - Gradle detected a problem with the following location: '/home/runner/work/redacted/redacted/android'. Reason: Task ':expo-updates:createQaReleaseExpoManifest' uses this output of task ':app:processQaReleaseManifest' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

**Comment by douglowder** [comment]
Thanks @Johan-dutoit this is extremely helpful 👍

**Comment by Johan-dutoit** [comment]
No idea if this is the right thing to do (or what the ramifications are)... but the following patch stopped my crashing
```patch
diff --git a/node_modules/expo-updates/scripts/create-manifest-android.gradle b/node_modules/expo-updates/scripts/create-manifest-android.gradle
index 81138a9..b5896e4 100644
--- a/node_modules/expo-updates/scripts/create-manifest-android.gradle
+++ b/node_modules/expo-updates/scripts/create-manifest-android.gradle
@@ -86,7 +86,7 @@ def setupClosure = {
       }
 
       // Workaround for Android Gradle Plugin 7.1+ asset directory
-      into ("assets/${variant.name}/merge${targetName}Assets") {
+      into ("assets/${variant.name}") {
         from(assetsDir)
       }
```

**Comment by douglowder** [comment]
@Johan-dutoit your solution is correct! Except that it will break the build if flavor variants are NOT used, as there will be duplicate copy tasks -- but that is easy to fix. Thanks for providing this! 😄 

I think the following patch against SDK 48 should work, @tylercote @ken0x0a @sin2 : 

```diff
diff --git a/node_modules/expo-updates/scripts/create-manifest-android.gradle b/node_modules/expo-updates/scripts/create-manifest-android.gradle
index 81138a9..30b4d3f 100644
--- a/node_modules/expo-updates/scripts/create-manifest-android.gradle
+++ b/node_modules/expo-updates/scripts/create-manifest-android.gradle
@@ -69,6 +69,7 @@ def setupClosure = {
         name: "copy${targetName}ExpoManifest",
         type: Copy) {
       description = "expo-updates: Copy manifest into ${targetName}."
+      duplicatesStrategy = DuplicatesStrategy.INCLUDE
 
       into ("${appProject.buildDir}/intermediates")
       into ("assets/${targetPath}") {
@@ -90,6 +91,11 @@ def setupClosure = {
         from(assetsDir)
       }
 
+      // Workaround for Android Gradle Plugin 7.5+ asset directory (including flavor variants)
+      into ("assets/${variant.name}") {
+        from(assetsDir)
+      }
+
       // mergeAssets must run first, as it clears the intermediates directory
       dependsOn(variant.mergeAssetsProvider.get())
       dependsOn(currentBundleTask)
```

@Kudo

**Comment by Johan-dutoit** [comment]
Thanks @douglowder , I'll give it a test in the morning.  Very much appreciated!

**Comment by Johan-dutoit** [comment]
Can confirm that the patch above works for me.

**Comment by sin2** [comment]
I am still experiencing the same error when making a release build.

**Comment by douglowder** [comment]
@sin2 can you provide some details on your `android/app/build.gradle` and how your build flavors are configured?

**Comment by douglowder** [comment]
@leymytel the fix is now in the SDK 48 maintenance branch. Will post again once a new `expo-updates` point release has been published.

**Comment by douglowder** [comment]
Fixed in `expo-updates@0.16.4`
