### ISSUE TITLE
[expo-image][Android] performance UI fps drop with some specific jpeg images

### ISSUE THREAD

**Issue by zhelezkov** [expo/expo#21491]
### Minimal reproducible example

https://github.com/zhelezkov/expo-image-performance-issue

### Summary

Hey all,
Thanks for releasing expo-image, it's fantastic library and I hope to use it in prod. 

Unfortunately I have faced a major performance issue with `expo-image` and specific combination of jpeg images. I know it might sounds crazy, and I didn't believe my eyes when I found it, **BUT** some specific combination of jpeg images causes a huge performance drop during scroll, from 120 FPS to ~40 FPS.

In repro, I left comment about images that causes a performance drop https://github.com/zhelezkov/expo-image-performance-issue/blob/main/App.js#L20-L21. If you try to comment it out, you'll see that performance is fine. 

I almost certain that the problem is in the `expo-image`, because if I switch to `Image` component from `react-native`, it works pretty well and I don't see such major performance drops. (https://github.com/zhelezkov/expo-image-performance-issue/blob/main/App.js#L30)
Ideally I would expect `expo-image` to work faster or at least with the same performance as default `Image` component from `react-native`.

I have also checked same images with `react-native-fast-image` and it looks fine, no performance drops

<details>
<summary>Please also find video with performance problem. FPS drops from 120 to 40.</summary>

https://user-images.githubusercontent.com/5163918/222594858-3bcb6dfd-6e23-4f8f-a6ad-11d70d81d8a1.MOV
</details>

<details>
<summary>
And same project, but with default Image component from react-native. no performance drop
</summary>

https://user-images.githubusercontent.com/5163918/222594838-5c03e32e-400c-4981-ac55-918e005edb12.MOV
</details>

I have attached minimal repro, you can run it with expo go. 
This problem doesn't reproduce on iOS.

Please lmk if you need any other information

### Environment
```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
      Watchman: 2023.02.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/nz/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: Electric Eel 2022.1.1 Patch 1 Electric Eel 2022.1.1 Patch 1
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.4 => 48.0.4
      react: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
    npmGlobalPackages:
      eas-cli: 3.7.2
    Expo Workflow: managed
```

**Comment by zhelezkov** [comment]
Hmm, interesting, it seems like more general performance problem, not related to `react-native-tab-view`. I'll edit description of this issue, sorry for misleading 🙂

**Comment by alanjhughes** [comment]
Hi,

A couple of things here. I've pulled and ran your repo. There is no need to memoize the `<Second />` component. Also changing to a `<Flatlist />` improves performance but the main issue is the bottom two images are huge. 3024 x 4032. You should use images that are sized appropriately. Changing the size with your style is not enough.

**Comment by alanjhughes** [comment]
I'm seeing the exact same drops using React Natives image

**Comment by zhelezkov** [comment]
Hi @alanjhughes,
Thanks, for checking it. About memoize I agree, but it shouldn't affect anything.

Are you sure that you see the same drops using React Native Image? Because I don't see any drops using it, and I don't see drops using `react-native-fast-image`. 
Please see videos attached in my first post.

**Comment by zhelezkov** [comment]
Just in case, I understand that images are huge and ideally it should be resized, but I don’t think it’s the root cause, because with default Image component and with ‘react-native-fast-image’ it works good with desired performance. 

I have noticed it when I replaced ‘react-native-fast-image’ with ‘expo-image’ in our project

**Comment by alanjhughes** [comment]
Hi @zhelezkov 

I had a look at the CDN you are using and when the images are resized, expo image performs as expected. Maybe it is an issue that it doesn't perform well at those large sizes but I don't think so. The expectation would be for correctly sized images to be used to get optimal performance. I'll leave it to someone from the team to decide that though.

**Comment by zhelezkov** [comment]
Thanks for a quick response,
Yes, I understand that I could resize it and it'll be fine with `expo-image`. But all I want is to highlight that react-native Image component and `react-native-fast-image` performs better on this use case

**Comment by lukmccall** [comment]
Hi everyone, we're aware of this issue. The performance drop is related to the fact that we aren't downscale images on Android. It reduces the number of network/disk reads but affects performance in the case of huge assets. I'm going to investigate the best way of introducing downscaling. However, I'm not going to do that as it's done in `react-native-fast-image`. Their way will break other futures that we care about.

**Comment by FutureFutureTo** [comment]
Awesome that this was fixed, but is there anyway to use this with managed workflow at all? I'm currently waiting on updating and Android app as I don't really have a decent solution for images right now - I can't seem to get React Native Fast Image working.

If not, are there any ideas on when the next SDK will be released? Or does anyone have any other solutions?

Thanks!

**Comment by mirco123** [comment]
On Android, the performance is awful.

No, I am not going to downsize my application's images. That would require programmatically producing additional files, storing them on cloud, keeping track of them, deleting them when necessary, updating them. 

The module is SUPPOSED to do this functionality. Download the original image ONCE, store it locally, keeping downsized copies of the image locally if it needs such functionality for performance.

The first point of module's description is : Designed for speed.

Nope it isn't. 
It works much much worse than vanilla Image element from react-native on android.

If expo is unable to provide a cacheable image module that actually works, please support react-native-fast-image

**Comment by dembal1990** [comment]
+1

**Comment by Neiso** [comment]
+1

**Comment by InkAndSteel** [comment]
This Problem is not fixed. Still experiencing the issue described above.
