### ISSUE TITLE
KeyboardAvoidingView does not work on standalone app [Android].

### ISSUE THREAD

**Issue by gerardo15** [expo/expo#2172]
Hello.

I have taken this code from a premium theme that i bought.

```
<SafeAreaView style={styles.container}>
                <NavHeader title={thread.name} {...{navigation}} />
                <FlatList
                    inverted
                    data={messages}
                    keyExtractor={message => `${message.date}`}
                    renderItem={({ item }) => (
                        <Msg message={item} name={item.me ? name : thread.name} picture={thread.picture} />
                    )}
                />
                <KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : "height"}>
                    <View style={styles.footer}>
                        <TextInput
                            style={styles.input}
                            placeholder="Write a message"
                            value={this.state.message}
                            onChangeText={message => this.setState({ message })}
                            blurOnSubmit={false}
                            returnKeyType="send"
                            onSubmitEditing={this.send}
                            underlineColorAndroid="transparent"
                        />
                        <TouchableOpacity primary transparent onPress={this.send}>
                            <Text style={styles.btnText}>Send</Text>
                        </TouchableOpacity>
                    </View>
                </KeyboardAvoidingView>
            </SafeAreaView>
```

Its a chat View, it works perfect on Expo testing, but as soon as I build APK standalone it does not work, the keyboard will cover the whole screen.

I have tried react-native-keyboard-aware-scroll-view but in order to use its needed to detach the app.

I have searched the whole internet. I'm the only one suffering from this issue?

**Comment by FabianEhringer** [comment]
+ 1
We are experiencing the same issue.
Testing the app in expo on the simulator or on a device, Android and iOS resizes the view as expected, but on the standalone app built on expo the view doesn't resize when opening the keyboard for Android.

We tested an **apk built with expo on the 17th of July** where the resize of views works in the standalone build. Rebuilding with the **same codebase** (from the 17th of July) and the **current expo build process breaks the resizing** of views.

We suspect that the problem originates from the `windowSoftInputMode` that might not be set correctly to `adjustResize` in the AndroidManifest.xml during the expo build or somehow has no effect.

**Comment by freshedgarT** [comment]
+1

We are also faced with this issue.

**Comment by SeiboldDS** [comment]
+1
same here

**Comment by hendra1** [comment]
Me too.. it's very critiical issue..
expo team should fix this issue as soon as possible

**Comment by FabianEhringer** [comment]
I agree. All of our Android users can't see what they are typing at the moment...

**Comment by satya164** [comment]
> I have tried react-native-keyboard-aware-scroll-view but in order to use its needed to detach the app.

Why would you need to detach to use it?

**Comment by gerardo15** [comment]
@satya164 in order to change windowSoftInputMode in the android manifest values you have to detach

**Comment by hendra1** [comment]
It useless using other package 
I have tried but the issue still exist.
Keyboard covering the view and text input

@expo team please fix this issue 
We can’t deliver our apps to play Store

**Comment by esamelson** [comment]
Could someone experiencing this issue provide a fully-working, minimal repro (a [snack](https://snack.expo.io) would be great) that works in the expo client but fails when the same code is built into a standalone app?

**Comment by hendra1** [comment]
Below I attached my login script

and here is my package.json

`
{
  "name": "StrapFlatApp",
  "version": "8.2.0",
  "private": true,
  "devDependencies": {
    "babel-eslint": "7.2.3",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "eslint": "4.4.1",
    "eslint-plugin-flowtype": "2.35.0",
    "eslint-plugin-import": "2.7.0",
    "eslint-plugin-jsx-a11y": "6.0.2",
    "eslint-plugin-prettier": "2.1.2",
    "eslint-plugin-react": "7.1.0",
    "eslint-plugin-react-native": "3.0.1",
    "flow-bin": "0.52.0",
    "flow-typed": "2.1.5",
    "husky": "0.14.3",
    "jest": "20.0.4",
    "jest-expo": "19.0.5",
    "prettier": "1.5.3",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "scripts": {
    "postinstall": "remotedev-debugger",
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "test": "jest && eslint .",
    "precommit": "yarn test"
  },
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!(react-native|lottie-react-native|expo|react-native-maps|react-native-svg|react-native-branch|native-base-shoutem-theme|react-native-easy-grid|react-native-drawer|react-native-vector-icons|react-native-keyboard-aware-scroll-view|react-native-swiper|react-navigation|native-base|@expo|react-native-scrollable-tab-view|react-native-simple-modal|react-native-iphone-x-helper)/)"
    ]
  },
  "dependencies": {
    "color": "1.0.3",
    "jest-cli": "20.0.4",
    "lodash": "4.13.1",
    "moment": "2.13.0",
    "native-base": "2.3.10",
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-native-calendars": "1.5.6",
    "react-native-carousel-view": "^0.5.1",
    "react-native-easy-grid": "0.1.15",
    "react-native-modalbox": "1.4.2",
    "react-native-vector-icons": "4.3.0",
    "react-navigation": "1.2.1",
    "react-redux": "5.0.5",
    "redux": "3.7.2",
    "redux-form": "7.0.3",
    "redux-persist": "4.8.3",
    "redux-thunk": "2.2.0",
    "remote-redux-devtools": "0.5.0",
    "remote-redux-devtools-on-debugger": "^0.8.0"
  }
}

`

[Login.zip](https://github.com/expo/expo/files/2363148/Login.zip)

**Comment by freshedgarT** [comment]
We seem to have found the issue causing the Input to be hidden by the keyboard.
[Here](https://github.com/freshedgarT/expoAndroidInputHiddenByKeyboard) is a repo reproducing the error.

**Comment by freshedgarT** [comment]
We seem to have found the issue causing the failure.
[Here](https://github.com/freshedgarT/expoInputHidden) is a repo reproducing the failure.
The screen resizes properly and keeps the input on top of the keyboard in expo on the simulator.
After building the standalone app for android and running the .apk on the same simulator, the screen doesn't resize and the input is hidden by the keyboard.

Changing `"splash": { "resizeMode": "cover" }` to `"splash": { "resizeMode": "contain" }` in app.json **fixes the issue** we faced.

Is this intentional behavior or a bug with expo build?

**Comment by gerardo15** [comment]
Well @freshedgarT that actually fix my issue!

What is the drawback of using contain there?

**Comment by hounsellal** [comment]
The drawback is that the splash screen will be framed by a white border.

As a temporary workaround I've created a splash screen with a plain white background so it's not as noticeable. Then I adjust this setting before expo build:android and set it back to normal (with usual splash screen) for iOS.

Would be great to have this issue fixed.

**Comment by RobertFischer** [comment]
> We seem to have found the issue causing the failure.
> [Here](https://github.com/freshedgarT/expoInputHidden) is a repo reproducing the failure.
> The screen resizes properly and keeps the input on top of the keyboard in expo on the simulator.
> After building the standalone app for android and running the .apk on the same simulator, the screen doesn't resize and the input is hidden by the keyboard.
> 
> Changing `"splash": { "resizeMode": "cover" }` to `"splash": { "resizeMode": "contain" }` in app.json **fixes the issue** we faced.
> 

It doesn't fix the issue for us -- we already had `contain` for our `resizeMode`, and we're seeing this issue.

**Comment by jalchr** [comment]
+1
Any plans to fix this ?

**Comment by jorgeants** [comment]
+1
I'm with same issue too.

**Comment by schlaxel** [comment]
+1
I have the same issue

**Comment by bellini666** [comment]
+1 here

The workaround proposed by @freshedgarT did solve the issue for me.

@hounsellal the drawback you commented can be easily bypassed by making your splash screen background transparent and defining a `backgroundColor` in the `splash` section.  You can't have a gradient background that way but it's better than a white one =P

@RobertFischer be sure to generate a new apk. That is one of the changes that publish by itself is not enough. I'm saying that because I thought the workaround did not work after publishing, but after building an apk and installing it by hang everything worked great.

obs. I'm using expo sdk 30

**Comment by ljubomir-digihey** [comment]
The workaround by @freshedgarT is not working for me, even after building an APK.

**Comment by ljuborados** [comment]
The workaround isn't working for me, built the new APK but still adjustResize not working at all.

**Comment by andresmtz98** [comment]
+1 same issue :/

**Comment by arrygoo** [comment]
Seeing this again on Expo 31 :(

**Comment by mylo** [comment]
Any news on this ?

**Comment by WulffHunter** [comment]
Getting this issue as well. Looks like it's a problem with Expo not detecting the soft navigation bar's height when it's not been pinned. I tried the `"contain"` fix and... nothing. ¯\_(ツ)_/¯

**Comment by pedramvdl31** [comment]
I had the same issue adding flex: 1 to KeyboardAvoidingView fixed my problem:






                <KeyboardAvoidingView style={{ flex: 1 }} behavior={"padding"} >

                    <ScrollView >

                        <Card>

                            <CardItem header bordered>
                                <Text>Personal Information</Text>
                            </CardItem>

                            <CardItem bordered>

                                <Body>

                                    <Item floatingLabel style={styles.item}>
                                        <Label>Full Name</Label>
                                        <Input />
                                    </Item>

                                    <Item floatingLabel style={styles.item}>
                                        <Label>Headline</Label>
                                        <Input />
                                    </Item>

                                    <Item floatingLabel style={styles.item}>
                                        <Label>Location</Label>
                                        <Input />
                                    </Item>

                                    <Item floatingLabel style={styles.item}>
                                        <Label>Email</Label>
                                        <Input />
                                    </Item>

                                    <Item floatingLabel style={styles.item}>
                                        <Label>Phone Number</Label>
                                        <Input />
                                    </Item>
                                    <Item floatingLabel style={styles.item}>
                                        <Label>Phone Number</Label>
                                        <Input />
                                    </Item>
                                    <Item floatingLabel style={styles.item}>
                                        <Label>Phone Number</Label>
                                        <Input />
                                    </Item>

                                </Body>
                                
                            </CardItem>

                        </Card>

                        <ListItem>

                            <Left>
                                <Text>Make my Profile Public</Text>
                            </Left>

                            <Right>
                                <Switch value={this.state.publicProfileRadioValue}
                                    onValueChange={(value) => this.setState({ publicProfileRadioValue: value })}
                                />
                            </Right>
                            
                        </ListItem>

                    </ScrollView>

                </KeyboardAvoidingView>

**Comment by pyankoff** [comment]
I've got the following combinations of parameters working:

`splash.resizeMode: "cover"` + `<KeyboardAvoidingView bahavior="padding"` Published app works, but DEV is messed up

`splash.resizeMode: "contain"` + `<KeyboardAvoidingView bahavior={undefined}` working in DEV

**Comment by Ripe** [comment]
@pyankoff Your solution worked for me, I added:
`behavior={Constants.manifest.releaseChannel === 'production' ? 'padding' : null}`
to get it working in production (inside app) and dev (inside Expo).

**Comment by MindFreeze** [comment]
I use `behavior = __DEV__ ? null : 'padding'` for Android, and for iOS I use `react-native-keyboard-aware-scroll-view`. Took a lot of trial and error to find this combination.

**Comment by Im10Anish** [comment]
Anyone having a solution?

**Comment by pheuter** [comment]
This is also a problem for [gifted-chat](https://github.com/FaridSafi/react-native-gifted-chat), works on Expo client dev but breaks on standalone apk build. Any solutions for that?

**Comment by ibnukipa** [comment]
is it already solved?

**Comment by Im10Anish** [comment]
not yet solved.. didn't tried much!! Do you have any solution?

**Comment by ibnukipa** [comment]
still no luck ..

**Comment by WulffHunter** [comment]
> @pyankoff Your solution worked for me, I added:
> `behavior={Constants.manifest.releaseChannel === 'production' ? 'padding' : null}`
> to get it working in production (inside app) and dev (inside Expo). Although I didn't have to change `splash.resizeMode` to `contain` for dev.

I tried using this answer from @pyankoff, yet I found that the `ScrollView` now over-scrolls when you have the keyboard open. Could this have something to do with the `splash.resizeMode`? I noticed this is similar behaviour to how the `KeyboardAvoidingView` works on iOS in development mode.

**Comment by sislovesmedotcom** [comment]
+1 experiencing on expo 32.0.0

**Comment by gamier-lester** [comment]
+1
same experience on expo 32.0.0

**Comment by AbdelrahmanNabil96** [comment]
+1
using SDK 31

**Comment by adamsythe** [comment]
I solved this problem with the following hideous hack


```
const CustomKeyBoardAvoidView = ({ children }) => {
  if (Constants.appOwnership === 'expo' && Platform.OS === 'android') {
    return (
      <View>
        {children}
      </View>
    )
  }
  return (
    <KeyboardAvoidingView
      behavior="padding"
      keyboardVerticalOffset={Dimensions.KEYBOARD_OFFSET}
    >
      {children}
    </KeyboardAvoidingView>
  )
}
```

**Comment by joaquinwojcik** [comment]
+1 @expo

**Comment by alexx855** [comment]
+1 @expo

**Comment by swayok** [comment]
Splash screens in expo are quite problematic. That problem with keyboard avoider is definitely because of splash screen (@expo - fix this please).
Currently @MindFreeze solution works fine for both standalone and android emulator.
This is my app.json for reference:
```
"expo": {
        "sdkVersion": "32.0.0",
        "splash": {
            "image": "./assets/images/splash_screen/contained/splash@2x.png",
            "resizeMode": "contain",
            "backgroundColor": "#0076F9"
        },
        "android": {
            "splash": {
                "backgroundColor": "#0076F9",
                "resizeMode": "cover",
                "mdpi": "./assets/images/splash_screen/splash.png",
                "hdpi": "./assets/images/splash_screen/splash@1.5x.png",
                "xhdpi": "./assets/images/splash_screen/splash@2x.png",
                "xxhdpi": "./assets/images/splash_screen/splash@3x.png",
                "xxxhdpi": "./assets/images/splash_screen/splash@4x.png"
            },
        },
        "ios": {
            "splash": {
                "backgroundColor": "#0076F9",
                "resizeMode": "cover",
                "image": "./assets/images/splash_screen/splash@2x.png"
            }
        },
}
```
2x image size is 1440x2560

I used `expo.splash` options because it seems that they actualy affect final result even if you override that options in `android` section. Maybe that is only my imagination but I've been building apks around 15 times already and actually bored of all this waste of time.

Also you will need to compensate status bar and header like this:
```
import {Header} from "react-navigation";
...
<KeyboardAvoidingView
     style={{flex: 1}}
     behavior={__DEV__ ? null : 'padding'}
     keyboardVerticalOffset={20 + Header.HEIGHT}
>
    {this.props.children}
</KeyboardAvoidingView>
```
If you are not using header on some screens - remove `Header.HEIGHT` from `keyboardVerticalOffset` so that only status bar height (20) remains.

**Comment by spyshower** [comment]
+1 experiencing on expo 32.0.0

**Comment by jivanshr** [comment]
For last 2 days i was trying to fix this. Tried many packages, no help. 
Finally this worked for me. 

```
<View style={[styles.flex1]}>
          <KeyboardAvoidingView
            style={{ flex: 1, flexDirection: 'column', justifyContent: 'center' }}
            behavior="padding"
            enabled
            keyboardVerticalOffset={100}
          >
            <ScrollView>
...
```

Note1: it looks fine in apk but not in development mode.
Note2: Tested on android pie with every packages up to date.

**Comment by Abdelrahman-Nabil** [comment]
Still happening in SDK 33.0.0
They actually released a completely new SDK without addressing this issue.
What a mess..

**Comment by markholland** [comment]
The splash fix was working for us in SDK 32 but now that we've upgraded to v33 I can't find a combination that works anymore. Wasn't the fix supposedly supplied by the version of React Native to be included in v33? https://github.com/expo/expo/issues/4154#issuecomment-490511370

**Comment by Slapbox** [comment]
For me this stopped working when I switched from using the `<StatusBar />` component in my app to just defining it in the `app.json` with:

```js

   "androidStatusBar": {
     "backgroundColor": "#FAFAFA",
     "barStyle": "dark-content"
   }
```

**Comment by seanpascoe** [comment]
This is really screwy. I'm on sdk33 and can't figure out a way to solve this. Everything works perfectly in expo, breaks as standalone apk. Building for every debug attempt is horrible.

**Comment by Slapbox** [comment]
@seanpascoe, when you say "standalone apk" do you just mean the output of running `expo publish` ? For some reason Expo needs `undefined` behavior in one environment and `padding` in another for me, but I don't remember which is for DEV and which is for PROD. It should be pretty easy to test.

Please consider opening a bug report for this. It's on my list, but towards the bottom.

**Comment by seanpascoe** [comment]
@Slapbox by "standalone apk" I mean the result of `expo build:android`.

**Comment by Slapbox** [comment]
@seanpascoe 

```js
const behavior = process.env.NODE_ENV === 'production' ? 'padding' : undefined;
return <KeyboardAvoidingView behavior={behavior} />
```

This works for me to have proper behavior in DEV and PROD, but this can't possibly be intentional. If this fixes your issue, please please please open a bug report, otherwise I will when I can, but it could be weeks before I have the time to file the complete issue template and supporting data.

**Comment by seanpascoe** [comment]
@Slapbox I tried something like that, though used `Constants.appOwnership`. The problem is that KAV with 'padding' is not consistent for Android (for me). I am using a `<View/>` for android and it is working fine in expo (shrinks via padding automatically), but not when built. Where do you want me to open a bug report? Is this github issue not enough?

**Comment by Slapbox** [comment]
@seanpascoe this issue pre-dates the current issue (I only know because it worked fine in Expo 31.)

It's possible this is the same issue and it was introduced, removed, and re-introduced in Expo 33, I'm not sure. This issue also uses the word "standalone" confusingly, since it's just a published Expo app, not "standalone" in the context Expo uses it, which might hamper resolution.

**Comment by seanpascoe** [comment]
@Slapbox I created a new issue: #5073. I'm not sure if it aligns exactly with your problem but you can check it out.

**Comment by Mushud** [comment]
FIXED:

I had the same issue but i did some workaround and i fixed it

``` <KeyboardAvoidingView
        style={{flex: 1, justifyContent: 'center'}}
        keyboardVerticalOffset={30}
        behavior={Platform.OS === "ios" ? 'padding' : 'height'}
      >
       ....

</KeyboardAvoidingView>

```
This fixed the issue for the standalone app

**Comment by Mushud** [comment]
I had the same issue, but I fixed it.

```
<KeyboardAvoidingView
        style={{flex: 1, justifyContent: 'center'}}
        keyboardVerticalOffset={30}
        behavior={Platform.OS === "ios" ? 'padding' : 'height'}
      >
```

It worked for the standalone app

**Comment by BBARLOCCO** [comment]
Hi! I had the same issue, on SDK 31 it was working with the "contain" workaround, but now (currently on SDK 33) it's  broken.
The workaround that worked this time was to set splash on android on with "resizeMode":"native" (also added the "padding" behavior on the KeyboardAwareScrollView ), hope this is solved soon, great work with expo!

**Comment by powerpovar** [comment]
Have the same issue.
Any updates?

**Comment by ajrn-riguy** [comment]
@BBARLOCCO - Did you use KeyboardAwareScrollView around the iOS portion as well? Could you show an overview of the code in your component (iOS vs Android setup) please? 🙏I'm running into this issue when using GiftedChat and I can't quite seem to find the right combination (OS specific splash screen setting, to use KAV or KASV, padding behavior, prod/dev etc). The fact that there's so many variables for this is disheartening.

**Comment by dhcmega** [comment]
Using "native" for android fixed the problem but there is no splash in my case. So maybe just any word for resizeMode would work, haven't tested.
So, no splash or no KAView

**Comment by BBARLOCCO** [comment]
hi @ajrn-riguy , im using it  in both Android and iOS, using expo 33, android.splash.resizeMode "native"
this is my kascrollview code:
`<KeyboardAwareScrollView  resetScrollToCoords={{ x: 0, y: 0 }}
					viewIsInsideTabBar={false}
					extraScrollHeight={Platform.OS === "ios" ? 70 : -53}
					contentContainerStyle={[{minHeight: 532},{someOtherStyle},{overflow:"hidden"}]}
					style={[this.IS_IPHONE_X ?{height:88}:Platform.OS === 'ios' ? {height:65}:{},{zIndex:50}]}
					scrollEnabled={true}
					enableAutomaticScroll={true}
					>
					
						{this.showChildren()}
					</KeyboardAwareScrollView>`
hope you find your solution!

**Comment by ajrn-riguy** [comment]
Thanks @BBARLOCCO . On SDK 34, after setting android.splash.resizeMode to "native", I was able to use it with just the basics:
`<KeyboardAvoidingView style={{ flex: 1 }}>
  <GiftedChat
    ...
  />
</KeyboardAvoidingView>`
Thanks for your help! Two days later, a one-word setting change fixed it...🤪

**Comment by michaelAdewunmi** [comment]
> Thanks @BBARLOCCO . On SDK 34, after setting android.splash.resizeMode to "native", I was able to use it with just the basics:
> `<KeyboardAvoidingView style={{ flex: 1 }}> <GiftedChat ... /> </KeyboardAvoidingView>`
> Thanks for your help! Two days later, a one-word setting change fixed it...🤪

This didn't fix it for me. And it's so annoying building APKs for every single change I make. It's frustrating! I hope I get a fix soon.

**Comment by riguy14** [comment]
Hey @michaelAdewunmi, unless you're changing something in `app.json` each time, you could build an APK that points at a development channel and then publish to that channel to do an OTA update for each change you want to test. I was doing the same thing as you and this cut my dev cycle way down.

**Comment by michaelAdewunmi** [comment]
> Hey @michaelAdewunmi, unless you're changing something in `app.json` each time, you could build an APK that points at a development channel and then publish to that channel to do an OTA update for each change you want to test. I was doing the same thing as you and this cut my dev cycle way down.

Hello @riguy14.  I just read about this now after seeing yout comment. You are just about to save a life Bro 😀. I dont know if i understood what I read well but based on what you said and what I read on expo, this is what i need to do **_expo build:android --release-channel {my-channel}_**. 

I will try this now and get back to you. Thanks a lot.

**Comment by michaelAdewunmi** [comment]
> Hi! I had the same issue, on SDK 31 it was working with the "contain" workaround, but now (currently on SDK 33) it's broken.
> The workaround that worked this time was to set splash on android on with "resizeMode":"native" (also added the "padding" behavior on the KeyboardAwareScrollView ), hope this is solved soon, great work with expo!

Hello @BBARLOCCO @riguy14 , Thannks for the help so far. I am presently on SDK 33. I changed my android.splash.resizeMode to "native" but it throws this warning when building the apk - _**Splash resizeMode is set to 'native', but you haven't provided any images for different DPIs. Be aware that your splash image will be used as xxxhdpi asset and its actual size will be different depending on device's DPI.**_ .

It then exits with the error _**Field: splash.resizeMode - should be equal to one of the allowed values. Couldn't publish because errors were found. (See logs above.) Please fix the errors and try again**_. I know I must be missing something. 

Even though I set the values for _**mdpi, hdpi, xhdpi, xxhdpi and xxxhdpi (although to the same png image as when I used "cover"**_ I still got the same error. Please help me with any pointers to know what I could be doing wrong.  Thanks a lot!

**Comment by michaelAdewunmi** [comment]
Hello @BBARLOCCO @riguy14 . I Finally got it to work :smile: thanks to @BBARLOCCO solution with little addition of the "flex:1" to `contentContainerStyle` and `style`. 

This was what worked for me `<KeyboardAwareScrollView resetScrollToCoords={{ x: 0, y: 0 }} viewIsInsideTabBar={false} contentContainerStyle={[{minHeight: 532}, {overflow:"hidden", flex: 1}]} style={[Platform.OS === 'ios' ? {height:65}:{},{zIndex:50, flex: 1}]} scrollEnabled={true} enableAutomaticScroll={true}>RenderChildren()</KeyboardAwareScrollView >`

 I initially have my **_expo.splash.resizeMode_** set to "native" and this was the cause of the initial error. This was a mistake on my part as the required change was supposed to be  done on _**expo.android.splash.resizeMode**_. I hope this helps anyone who might also be making this error. Oh and Thanks @riguy14 for the development channel builds and publishing. It has been a life saver.

Once again, Thanks guys! :thumbsup:

**Comment by Slapbox** [comment]
That craziness is exactly what shouldn't be needed though.

@satya164, @esamelson - Is the cause of this know, and if so, has a specific fix been planned yet? Not trying to rush things, just hoping for an update.

**Comment by MindFreeze** [comment]
Just found out that if the StatusBar is hidden on android it breaks the KeyboardAware stuff. Even the `keyboardDidShow` event reports wrong height for the keyboard, so I can't handle it manually. This is with `"resizeMode"` "contain" or "native"

**Comment by BBARLOCCO** [comment]
hi there, we are having this issue since V31, do you know if its ever going to be fixed? Right now we have to set resizeMode on "native" in order to have keyboard avoiding scrolll.. this is crazy! And many clients want big pictures on their splash, with native is imposible to make this happen in al resolutions without "empty" spaces....

**Comment by pedrinhok** [comment]
Hi there!

I had been facing this problem for a few days and I finally managed to fix it with a simple solution. I had the following KeyboardAvoidingView:
`
<KeyboardAvoidingView
  behavior={Platform.select({ android: null, ios: 'padding' })}
  style={{ flex: 1 }}
>
  <ScrollView
    contentContainerStyle={{ flex: 1 }}
    keyboardShouldPersistTaps='handled'
  >
    {children}
  </ScrollView>
</KeyboardAvoidingView>
`
It was working great on both simulators and devices (through Expo Client). When I built for iOS, it kept working. However, when I built for Android, the view didn't scroll and the keyboard covered the input.

I tested different configurations (as provided in other comments) and the only one that worked for me was setting the behaviour to height on Android:
`
<KeyboardAvoidingView
  behavior={Platform.select({ android: 'height', ios: 'padding' })}
  style={{ flex: 1 }}
>
`

Hope it solves your problem too!

**Comment by pedrinhok** [comment]
Hi there!

I had been facing this problem for a few days and I finally managed to fix it. I had the following:
```
<KeyboardAvoidingView
  behavior={Platform.select({ android: null, ios: 'padding' })}
  style={{ flex: 1 }}
>
  <ScrollView
    contentContainerStyle={{ flex: 1 }}
    keyboardShouldPersistTaps='handled'
  >
    {children}
  </ScrollView>
</KeyboardAvoidingView>
```
It was working great on both simulators and devices (through Expo Client). When I built for iOS, it worked as expected. However, when I built for Android, the view didn't scroll and the keyboard covered the input.

I tested different configurations (as provided in other comments) and the only one that worked for me was setting the behaviour to height on Android:
```
<KeyboardAvoidingView
  behavior={Platform.select({ android: 'height', ios: 'padding' })}
  style={{ flex: 1 }}
>
```

Hope it solves your problem too!

**Comment by pedrinhok** [comment]
Hi there!

I had been facing this problem for a few days and I finally managed to fix it. I had the following:
```
<KeyboardAvoidingView
  behavior={Platform.select({ android: null, ios: 'padding' })}
  style={{ flex: 1 }}
>
  <ScrollView
    contentContainerStyle={{ flex: 1 }}
    keyboardShouldPersistTaps='handled'
  >
    {children}
  </ScrollView>
</KeyboardAvoidingView>
```
It was working great on both simulators and devices (through Expo Client). When I built for iOS, it worked as expected. However, when I built for Android, the view didn't scroll and the keyboard covered the input.

I tested different configurations (as provided in other comments) and the only one that worked for me was setting the behavior to height on Android:
```
<KeyboardAvoidingView
  behavior={Platform.select({ android: 'height', ios: 'padding' })}
  style={{ flex: 1 }}
>
```

Hope it solves your problem too!

**Comment by SimonFricker** [comment]
+1

**Comment by Slapbox** [comment]
This issue thread is become a hundred people posting virtually identical code to workaround this... 

@esamelson @satya164 can you possibly update us on the status of this? It's been open for over a year and it seems really fundamental to me.

**Comment by IamAhsanMani** [comment]
@

> Hi there!
> 
> I had been facing this problem for a few days and I finally managed to fix it. I had the following:
> 
> ```
> <KeyboardAvoidingView
>   behavior={Platform.select({ android: null, ios: 'padding' })}
>   style={{ flex: 1 }}
> >
>   <ScrollView
>     contentContainerStyle={{ flex: 1 }}
>     keyboardShouldPersistTaps='handled'
>   >
>     {children}
>   </ScrollView>
> </KeyboardAvoidingView>
> ```
> 
> It was working great on both simulators and devices (through Expo Client). When I built for iOS, it worked as expected. However, when I built for Android, the view didn't scroll and the keyboard covered the input.
> 
> I tested different configurations (as provided in other comments) and the only one that worked for me was setting the behavior to height on Android:
> 
> ```
> <KeyboardAvoidingView
>   behavior={Platform.select({ android: 'height', ios: 'padding' })}
>   style={{ flex: 1 }}
> >
> ```
> 
> Hope it solves your problem too!

thank you man you save me

**Comment by esamelson** [comment]
Hi all -- I'm sorry that we haven't been responsive to this issue. Apologies for the trouble this is continually causing.

We need a fully reproducible example in order to debug this issue. In the 72 comments on this thread, I have not found a single example I could use to successfully reproduce the issue -- which to be clear is that **`KeyboardAvoidingView` is behaving differently in the Expo client than in standalone apps** -- nor have I been able to find a repro case myself. Pasting code blocks into comments is not helpful in this case as we need the entire context of the app -- including import statements, app.json settings, etc. -- in order to reproduce the issue.

Could someone experiencing this issue please post a full [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces `KeyboardAvoidingView` behaving differently in the Expo client and standalone apps? Either a github repo or a snack (that can be easily copied + pasted and built into a standalone app) would be appropriate. Thank you!

**Comment by freshedgarT** [comment]
> Hi all -- I'm sorry that we haven't been responsive to this issue. Apologies for the trouble this is continually causing.
> 
> We need a fully reproducible example in order to debug this issue. In the 72 comments on this thread, I have not found a single example I could use to successfully reproduce the issue -- which to be clear is that **`KeyboardAvoidingView` is behaving differently in the Expo client than in standalone apps** -- nor have I been able to find a repro case myself. 😞 Pasting code blocks into comments is not helpful in this case as we need the entire context of the app -- including import statements, app.json settings, etc. -- in order to reproduce the issue.
> 
> Could someone experiencing this issue please post a full [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces `KeyboardAvoidingView` behaving differently in the Expo client and standalone apps? Either a github repo or a snack (that can be easily copied + pasted and built into a standalone app) would be appropriate. Thank you!

https://github.com/expo/expo/issues/2172#issuecomment-420216938 
This is my comment from September, in which a fully reproducible demo of the bug was provided. 

Since then in SDK 33 the behavior of `resizeMode: contain` and `resizeMode: cover` was changed. My team and I were not able to get the behavior of SDK 32 back in our production app without completely removing the splash screen on Android.

**Comment by jjg77** [comment]
Love expo, but this bug is seriously annoying.  In my scenario I have messaging app that looks like this:
Fixed Header (height: 80)
FlatList (Flex:1)
Fixed Footer (height: 100), this where my KeyboardAvoidingView and TextInput are located.

For the life of me, I can't get this to work in the standalone Android app, but it works fine when testing in Expo.

I'm basically trying every variation of settings for the KeyboardAvoidingView mentioned in this thread, doing an Android build, installing it on my phone and testing.  Spending many hours on this...

**Comment by stanacton** [comment]
> Love expo, but this bug is seriously annoying. In my scenario I have messaging app that looks like this:
> Fixed Header (height: 80)
> FlatList (Flex:1)
> Fixed Footer (height: 100), this where my KeyboardAvoidingView and TextInput are located.
> 
> For the life of me, I can't get this to work in the standalone Android app, but it works fine when testing in Expo.
> 
> I'm basically trying every variation of settings for the KeyboardAvoidingView mentioned in this thread, doing an Android build, installing it on my phone and testing. Spending many hours on this...
> 
> UPDATED:
> Finally found a fix for my situation. I think the trick for me was to only have the FlatList as Flex:1.
> 
> ```
> Container (flex:1)
>   Header(no flex)
>   FlatList (flex:1)
>   KeyboardAvoidingView (behavior = padding)
>     View (height: 100)
>       Form (flex:1)
> ```

I had the same issue.  I just updated to Expo SDK v37 and it's fixed.  Have you tried updating to version 37?

**Comment by thedentor** [comment]
> I had the same issue. I just updated to Expo SDK v37 and it's fixed. Have you tried updating to version 37?

Thanks @stanacton   upgrade to SDK v37 and everything went back to normal

**Comment by nazreen** [comment]
For those who arrived here, the thing to note is, 
you have to make sure that `flex: 1` is applied to `KeyboardAvoidingView` and then also the element or View that you want to be affected by KeyboardAvoidingView. Otherwise, it won't work. My mistake was that the TextInput I wanted to be keyboard avoided didn't have `flex: 1`. Applying it made it work.

**Comment by tanish4643** [comment]
Anybody still facing this issue may try following code snippet,

Earlier my code looked something like this:

`<KeyboardAwareScrollView contentContainerStyle={{flex:1}}>
          <View></View>
</KeyboardAwareScrollView>`

which I changed to this

`const {height} = Dimensions.get('window');

<KeyboardAwareScrollView contentContainerStyle={{height}}>
          <View></View>
</KeyboardAwareScrollView>`

and it worked comletely fine.

**Comment by tanish4643** [comment]
Anybody still facing this issue may try following code snippet,

Earlier my code looked something like this:

```
<KeyboardAwareScrollView contentContainerStyle={{flex:1}}>
         <View></View>
</KeyboardAwareScrollView>
```

which I changed to this

```
const {height} = Dimensions.get("window")
<KeyboardAwareScrollView contentContainerStyle={{height}}>
         <View></View>
</KeyboardAwareScrollView>
```

and it worked completely fine.
