### ISSUE TITLE
Standalone app build not working without Internet

### ISSUE THREAD

**Issue by daominhsangvn** [expo/expo#228]
I'm trying to make the standalone app build in my project which is detached by using `$ exp detach`.
When i build a release for android and ios build (exported to ipa/apk file), i realized that when i first open the app, my phone need to be connected internet so it can connect Exponent Server to fetch the code.
Can we use without Exponent Server connection because my app is entirely being used for offline purpose.
Thanks!
![img_1361 png](https://cloud.githubusercontent.com/assets/8254183/26758575/6a538e34-490c-11e7-9cdc-982edd435aa4.jpg)

**Comment by terribleben** [comment]
We recently fixed an issue related to this. Can you make sure you have the latest Expo code and let us know if the issue still happens?

**Comment by daominhsangvn** [comment]
Should i need to re-create project with latest version of Expo?

**Comment by brentvatne** [comment]
@daominhsangvn - if you rebuild the standalone app that should fix it -- `exp build:ios`

**Comment by daominhsangvn** [comment]
@brentvatne Sorry i'm using detact version, i cant use `exp` cli anymore, i'm making the build via xCode and Android Studio

**Comment by brentvatne** [comment]
oh ok, I'm not sure what the answer is then, we will need to wait for @terribleben

**Comment by daominhsangvn** [comment]
I think i guess i need to re-create the project with the latest version of Expo XDE. I have just tested by remove current version and download new one from the https://expo.io then try to make a build from xCode/Android Studio as usual, i still got the same issue.

**Comment by daominhsangvn** [comment]
@terribleben I tried to create new project with latest version of Expo. I'm still get the same message that require internet for first loading the app.

**Comment by pchw** [comment]
I also have similar issue on `"sdkVersion": "17.0.0"`.
I published an app that have `"ios": {"isRemoteJSEnabled": false,}`  before(current version).
Yesterday, I published the app's new version that have `isRemoteJSEnabled": false` too.
However the app(current version) got an error cause the code was changed.

![image uploaded from ios](https://cloud.githubusercontent.com/assets/1183484/26776076/b737cc86-4a12-11e7-9e43-ac5b3cb49450.jpg)

**Comment by terribleben** [comment]
@daominhsangvn can you provide the following?

- Sdk version of your project
- [ExpoKit tag](https://github.com/expo/expo/releases) from your `Podfile` (if you are using ExpoKit)
- Expo Client version (if you are not using ExpoKit)

**Comment by daominhsangvn** [comment]
@terribleben 
- SDK version: 17.0.0
- ExpoKit tag: ios/1.16.2

**Comment by daominhsangvn** [comment]
Here what are steps that i'm doing:
1. Create project from Expo Client
2. Then use `$ exp detach`
3. Make iOS/Android Release build. For the iOS i'm using xCode for make Release build
4. Install to the phone and shutdown the internet and open the app

**Comment by terribleben** [comment]
Ah, I understand now. Right now we don't pre-bundle your app's JS with your ExpoKit build. So the behavior you described won't work unless the app has successfully loaded once already. The very first load cannot be offline.

For now, you can pick one of the following:

1. Use `exp build:ios` instead of ExpoKit, which mostly supports first-load-offline, or
2. Manually preload your app's JS and manifest in `shell-app-manifest.json` and `shell-app.bundle` (there's no tool for this, you'd need to roll your own), or
3. File a [feature request](https://expo.canny.io/feature-requests) for preloading app JS with ExpoKit projects, and with any luck we can add support for this soon!

**Comment by daominhsangvn** [comment]
Okay, thanks @terribleben for your time and clarification, i will take the second then if i cant make it i will take the third. I think i will closed this now.

**Comment by nthtran** [comment]
Hey @daominhsangvn, did you manage to get the 2nd approach working?
