### ISSUE TITLE
Did I breake Fast Refresh with my tsconfigPaths ?

### ISSUE THREAD

**Issue by arnaudambro** [expo/expo#23311]
### Minimal reproducible example

https://github.com/arnaudambro/expo-ts-refresh-broken

### Summary

Well just do 
- `npm install`
- `npm run start`
- change anything to `./app/index.tsx`

You'll see that Fast Refresh doesn't work

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.19.1 - ~/Library/Caches/fnm_multishells/55742_1688580993277/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.3 - ~/Library/Caches/fnm_multishells/55742_1688580993277/bin/npm
      Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 30, 31, 32, 33
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
        System Images: android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a
        Android NDK: 21.1.6352462
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0-beta.5 => 49.0.0
      react: 18.2.0 => 18.2.0
      react-native: 0.72.1 => 0.72.1
    npmGlobalPackages:
      eas-cli: 3.13.3
    Expo Workflow: managed

**Comment by hamsterhomka** [comment]
The Same problem. Just installed SDK 49 and fast refresh doesn't work in my ts project.

**Comment by EvanBacon** [comment]
any particular platform?

**Comment by derrysukrie** [comment]
> The same problem. Just installed SDK 49 and fast refresh doesn't work in my ts project.

I'm facing the same issue for iOS

**Comment by devoren** [comment]
@EvanBacon in my case on android and web

**Comment by arnaudambro** [comment]
> any particular platform?

iOS for me - Android is frozen but I'm not sure it's related

**Comment by Scr3nt** [comment]
iOS, Android and web for me, just after the upgrade
I use yarn
On development build

**Comment by GraxMonzo** [comment]
Same problem after migrating to SDK 49 without using any experimental features. On top of that, my console logs don't work, either. IOS

**Comment by devoren** [comment]
@GraxMonzo Yes, you are right! No logs No debugging, hope this gets resolved asap

**Comment by GraxMonzo** [comment]
> @GraxMonzo Yes, you are right! No logs No debugging, hope this gets resolved asap

The only way I could get the console logs to show up was to run the chrome debugger, but I personally find it hard to use

**Comment by derrysukrie** [comment]
Same problem after migrating to SDK 49 without using any experimental features. On top of that, my console logs don't work, either. IOS

Just notice in the first place, i thought something wrong with my codebase

**Comment by arnaudambro** [comment]
Yes, same XP with logs

**Comment by GraxMonzo** [comment]
Removing overrides from `package.json` and `npm i` as mentioned [here](https://docs.expo.dev/routing/installation/#for-expo-sdk-below-49) solves the problem. 🥳

```diff
{
  "name": "expo-49",
  "version": "1.0.0",
  "main": "expo-router/entry",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
- "overrides": {
-   "metro": "0.76.0",
-   "metro-resolver": "0.76.0"
- }
}

```

**Comment by devoren** [comment]
@GraxMonzo I can confirm that issue disappear and logs / FR and HR works fine

**Comment by hamsterhomka** [comment]
> Removing `overrides` and/or `resolutions` from `package.json` and reinstalling as mentioned [here](https://docs.expo.dev/routing/installation/#for-expo-sdk-below-49) solves the problem. 🥳
> 
> ```diff
> {
>   "name": "expo-49",
>   "version": "1.0.0",
>   "main": "expo-router/entry",
>   "scripts": {
>     "start": "expo start",
>     "android": "expo start --android",
>     "ios": "expo start --ios",
>     "web": "expo start --web"
>   },
> - "overrides": {
> -   "metro": "0.76.0",
> -   "metro-resolver": "0.76.0"
> - }
> }
> ```
> 
> Thanks to this commit [EvanBacon/expo-router-instagram-layout@1e2a67a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L36-L43](https://github.com/EvanBacon/expo-router-instagram-layout/commit/1e2a67a6c00b956367142de1fa4b89b7d13857a0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L36-L43)

It worked well

**Comment by sevketaydogdu** [comment]
> Removing `overrides` and/or `resolutions` from `package.json` and reinstalling as mentioned [here](https://docs.expo.dev/routing/installation/#for-expo-sdk-below-49) solves the problem. 🥳
> 
> ```diff
> {
>   "name": "expo-49",
>   "version": "1.0.0",
>   "main": "expo-router/entry",
>   "scripts": {
>     "start": "expo start",
>     "android": "expo start --android",
>     "ios": "expo start --ios",
>     "web": "expo start --web"
>   },
> - "overrides": {
> -   "metro": "0.76.0",
> -   "metro-resolver": "0.76.0"
> - }
> }
> ```
> 
> Thanks to this commit [EvanBacon/expo-router-instagram-layout@1e2a67a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L36-L43](https://github.com/EvanBacon/expo-router-instagram-layout/commit/1e2a67a6c00b956367142de1fa4b89b7d13857a0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L36-L43)

i am working on dev build, i did all of them an rebuild my app but doesnt worked for me.
Stiil fastrefresh is not working

**Comment by BoraALAP** [comment]
Same here removed all the overrides, but still not fast refreshing with code change.

**Comment by BoraALAP** [comment]
I just found that I had metro dependency still in my normal dependencies. I removed that as well now I'm good.

**Comment by artvichi** [comment]
just upgraded to sdk49, never had any overrides or resolutions, it doesn't work for us, any clues?

**Comment by GraxMonzo** [comment]
> just upgraded to sdk49, never had any overrides or resolutions, it doesn't work for us, any clues?

Have you tried clean start with `npx expo start --clear`?

**Comment by asafratzon** [comment]
In case it helps anyone, I had an env var defined as follows in a constants file as follows:
`export const BASE_URL = process.env.EXPO_PUBLIC_BASE_URL as string;`

When I console logged the value of `BASE_URL` it wasn't refreshing, but `process.env.EXPO_PUBLIC_BASE_URL` does refresh as expected.
So I just reference the env var from the process every time and now it works as expected.
**This probably should be fixed or documented.**

**Comment by natanielpaiva** [comment]
here i removed the:
- "overrides": {
-   "metro": "0.76.0",
-   "metro-resolver": "0.76.0"
- }
and add:
"overrides": {
    "react-refresh": "~0.14.0"
  },
  "resolutions": {
    "react-refresh": "~0.14.0"
  },

resolved for me

**Comment by codeacme17** [comment]
```
npx expo install --fix
```
work for me

**Comment by dhatGuy** [comment]
This is still an issue upgrading to expo 50. I did remove the overrides and resolutions but still didn't work

**Comment by dev-aly3n** [comment]
Same here. SDK 50.0.0-preview.10
Fast-refresh isnt working on Android emulator and physical device.
