### ISSUE TITLE
[SDK 49][expo-image][ios] tintColor fails with SVG images

### ISSUE THREAD

**Issue by jozan** [expo/expo#23486]
### Minimal reproducible example

https://github.com/jozan/svg-tint-color-repro

### Summary

`tintColor` doesn't work with svg images.

```tsx
import { Image } from "expo-image"

// usage
<Image source={imgSvg} style={{ tintColor: "orange" }} />
<Image source={imgSvg} tintColor="orange" />
```
the code above should result both images to be orange but it does nothing. i've tested this only on iOS since I don't currently have Android environment set up.

this might be issue with the underlying [SDWebImage](https://github.com/SDWebImage/SDWebImage) but i didn't find any thing in their issues.

screenshot of the [attached minimal repro](https://github.com/jozan/svg-tint-color-repro). both rectangles are expected to be orange but only png image source gets tinted.

<img width="310" alt="image" src="https://github.com/expo/expo/assets/388265/2304b9b6-8285-4e99-9834-8faffb11590d">

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 3.6.1 - /usr/local/bin/fish
    Binaries:
      Node: 19.9.0 - ~/n/bin/node
      Yarn: 3.5.0 - ~/n/bin/yarn
      npm: 9.7.2 - ~/n/bin/npm
      Watchman: 2023.06.26.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.2 => 49.0.2
      react: 18.2.0 => 18.2.0
      react-native: 0.72.1 => 0.72.1
    Expo Workflow: managed
```

**Comment by jozan** [comment]
hold on. this is most likely fixed in https://github.com/expo/expo/pull/23418. @tsapeta can probably confirm.

too bad i probably need to wait for SDK 50 for the fix 乁( ◔ ౪◔)ㄏ

**Comment by tsapeta** [comment]
Yeah, it's been fixed already, but only on iOS. It turned out to be an issue on Android as well 😢 
If we manage to solve it, we'll release it for SDK 49 too.

**Comment by tsapeta** [comment]
The fix for iOS has been released in `expo-image@1.3.2` 😉

**Comment by jozan** [comment]
hooray! this is great! waiting for the required Expo Go update and i'm good to go. this was smooth btw. 😸💛

**Comment by tslater** [comment]
@tsapeta @jozan I just tested 1.3.2 tint is still broken on Android. Would it be ok if I opened a ticket for it, or is there already one I just can't find?

**Comment by jozan** [comment]
> @tsapeta @jozan I just tested 1.3.2 tint is still broken on Android. Would it be ok if I opened a ticket for it, or is there already one I just can't find?

yes, go for it! this one's fixed and closed. 😸
