### ISSUE TITLE
[ios][expo-dev-client] expo-dev-launcher breaks with UIApplicationSceneManifest definition in infoPlist from expo v.48.x 

### ISSUE THREAD

**Issue by banesp** [expo/expo#23536]
### Summary

I'm using `UIApplicationSceneManifest` in infoPlist to define a multiscreen setup on iOS. This is necessary for my application to support CarPlay, and this is working just fine up until upgrading to Expo 48. 

From Expo 48, ExpoDevLauncherAppDelegateSubscriber is throwing a fatalError as it can't find the window from `UIApplication.shared`.

This is were it fails:
```
// ExpoDevLauncherAppDelegateSubscriber
guard let window = UIApplication.shared.windows.filter {$0.isKeyWindow}.first else {
    fatalError("Cannot find the keyWindow. Make sure to call `window.makeKeyAndVisible()`.")
}
```

Expected behaviour:
That expo-dev-launcher is able to filter out the correct window, even with multiscreen configuration. As I said, this is works in Expo 47. I suspect this is due to a deprecation in UIKit.

Might be relevant to this:
https://stackoverflow.com/questions/57134259/how-to-resolve-keywindow-was-deprecated-in-ios-13-0

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

"expo": "~48.0.18",
"expo-status-bar": "~1.4.4",
"react": "18.2.0",
"react-native": "0.71.8",
"expo-dev-client": "~2.2.1",
"expo-splash-screen": "~0.18.2"

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
      npm: 9.8.0 - ~/.nvm/versions/node/v18.16.0/bin/npm
      Watchman: 2023.07.03.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.18 => 48.0.20
      react: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
    npmGlobalPackages:
      eas-cli: 3.15.0
    Expo Workflow: managed

### Reproducible demo

https://github.com/banesp/expo-dev-launcher-keywindow-bug-demo

### Stacktrace (if a crash is involved)

2023-07-14 09:58:40.321431+0200 expodevlauncherkeywindowbugdemo[72205:349185] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
2023-07-14 09:58:40.321468+0200 expodevlauncherkeywindowbugdemo[72205:349185] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
EXDevLauncher/ExpoDevLauncherAppDelegateSubscriber.swift:12: Fatal error: Cannot find the keyWindow. Make sure to call `window.makeKeyAndVisible()`.
2023-07-14 09:58:40.330181+0200 expodevlauncherkeywindowbugdemo[72205:349185] EXDevLauncher/ExpoDevLauncherAppDelegateSubscriber.swift:12: Fatal error: Cannot find the keyWindow. Make sure to call `window.makeKeyAndVisible()`.
(lldb)

**Comment by nixolas1** [comment]
Hi, any update on this? We are having the same problem.

**Comment by keith-kurak** [comment]
Hi all!

To help us reproduce this issue, can you provide the precise steps on how to run the repro? What commands are you running, how should I simulate the multi-screen setup (if that's even needed), what I should see when I run it, etc.

If there's instructions clear enough to reproduce for someone who has never touched a CarPlay interface, who still connects his phone to the stereo with a tape deck adapter because he drives a 20 year old minivan with three corners dented in that makes a loud clunking sound whenever it turns left (not saying that's me or anything), I'm happy to take a closer look.

**Comment by banesp** [comment]
Hey @keith-kurak 

Sorry for not providing a better description initially. I have updated the README for the reproducible demo so now it should hopefully be easier to test for you guys.

You shouldn't need to do anything with CarPlay to run this demo. It just defines a multiscreen/CarPlay setup in `app.json`, and that causes `ExpoDevLauncherAppDelegateSubscriber` to fail with fatal error when you run the demo.

Thank you for having a look at this, let me know if anything else is unclear

**Comment by banesp** [comment]
@keith-kurak @brentvatne Have you had time to look at this yet?

**Comment by banesp** [comment]
This is still very much broken if anyone wants to have a look.

This is very the error is thrown https://github.com/expo/expo/blob/284bb8887638b6c52273aea5d234288478ffff66/packages/expo-dev-launcher/ios/ReactDelegateHandler/ExpoDevLauncherAppDelegateSubscriber.swift#L12

**Comment by gabrieldonadel** [comment]
Hi @banesp, do you have a working example of this? I tried downgrading [expo-dev-launcher-keywindow-bug-demo](https://github.com/banesp/expo-dev-launcher-keywindow-bug-demo) to use SDK 47 but I was still experiencing the same problem. I think this could be related to a misconfiguration of your Info.plist

**Comment by banesp** [comment]
Hi @gabrieldonadel, sorry for the late answer. I have updated the repository with a new branch https://github.com/banesp/expo-dev-launcher-keywindow-bug-demo/tree/bare-with-scene-delegates. I have "ejected" the iOS folder and added a MySceneDelegate class that is added to the configuration in ios/../Info.plist.

The project crashes during startup at `[/ExpoDevLauncherAppDelegateSubscriber.swift](https://github.com/expo/expo/blob/284bb8887638b6c52273aea5d234288478ffff66/packages/expo-dev-launcher/ios/ReactDelegateHandler/ExpoDevLauncherAppDelegateSubscriber.swift#L12)` 

`@interface UIApplication : UIResponder` has some deprecation warnings specifically towards multiple scenes support that might be of relevance.

@property(nullable, nonatomic,readonly) UIWindow *keyWindow API_DEPRECATED("Should not be used for applications that support multiple scenes as it returns a key window across all connected scenes", ios(2.0, 13.0));
@property(nonatomic,readonly) NSArray<__kindof UIWindow *>  *windows API_DEPRECATED("Use UIWindowScene.windows on a relevant window scene instead", ios(2.0, 15.0));

**Comment by caustin24345** [comment]
Using the window from the app delegate fixes this issue. i.e 

`public class ExpoDevLauncherAppDelegateSubscriber: ExpoAppDelegateSubscriber {
  public func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
    if !ExpoDevLauncherReactDelegateHandler.shouldEnableAutoSetup {
      return false
    }
      
    guard let window = UIApplication.shared.delegate?.window else {
      fatalError("Cannot find the scene or application window. Make sure to call `window.makeKeyAndVisible()`.")
    }
      
    EXDevLauncherController.sharedInstance().autoSetupStart(window!)
    return false
  }

  public func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
    if !ExpoDevLauncherReactDelegateHandler.shouldEnableAutoSetup {
      return false
    }

    return EXDevLauncherController.sharedInstance().onDeepLink(url, options: options)
  }
}
`

I am able to build and run the iOS app with a SceneDelegate which handles Carplay capabilities. My understanding is that keyWindow is not compatible with apps that support multiple scenes - but by using the AppDelegate window, and setting up a SceneDelegate which uses that same window it is possible to support multiple scenes. 

**SceneDelegate reference:**
`@implementation SceneDelegate

@synthesize window = _window;
- (void)scene:(UIScene *)scene willConnectToSession:(UISceneSession *)session options:(UISceneConnectionOptions *)connectionOptions {
  AppDelegate *appDelegate = (AppDelegate *)[[UIApplication sharedApplication] delegate];
  self.window = [[UIWindow alloc] initWithWindowScene:(UIWindowScene *)scene];
  self.window.rootViewController = appDelegate.window.rootViewController;
  [self.window makeKeyAndVisible];
}

- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene didConnectInterfaceController:(CPInterfaceController *)interfaceController toWindow:(CPWindow *)window {
  [RNCarPlay connectWithInterfaceController:interfaceController window:window];
}

- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene didDisconnectInterfaceController:(CPInterfaceController *)interfaceController fromWindow:(CPWindow *)window {
  [RNCarPlay disconnect];
}

@end`

**Comment by zackify** [comment]
this same issue happens if you are using a native widget extension, in this case it just needs to return false from the guard and not throw a fatal error, so that the preview window can build.

<img width="848" alt="image" src="https://github.com/expo/expo/assets/449136/902e4ee5-58d8-43c0-a38e-7498c7c8de4e">

**Comment by IWMTom** [comment]
> Using the window from the app delegate fixes this issue. i.e
> 
> ```
> public class ExpoDevLauncherAppDelegateSubscriber: ExpoAppDelegateSubscriber {
>   public func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: 
>   [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
>     if !ExpoDevLauncherReactDelegateHandler.shouldEnableAutoSetup {
>       return false
>     }
>       
>     guard let window = UIApplication.shared.delegate?.window else {
>       fatalError("Cannot find the scene or application window. Make sure to call `window.makeKeyAndVisible()`.")
>     }
>       
>     EXDevLauncherController.sharedInstance().autoSetupStart(window!)
>     return false
>   }
> 
>   public func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
>     if !ExpoDevLauncherReactDelegateHandler.shouldEnableAutoSetup {
>       return false
>     }
> 
>     return EXDevLauncherController.sharedInstance().onDeepLink(url, options: options)
>   }
> }
> ```
> 
> I am able to build and run the iOS app with a SceneDelegate which handles Carplay capabilities. My understanding is that keyWindow is not compatible with apps that support multiple scenes - but by using the AppDelegate window, and setting up a SceneDelegate which uses that same window it is possible to support multiple scenes.
> 
> **SceneDelegate reference:**
> 
> ```
> @implementation SceneDelegate
> 
> @synthesize window = _window;
> - (void)scene:(UIScene *)scene willConnectToSession:(UISceneSession *)session options:(UISceneConnectionOptions *)connectionOptions {
>   AppDelegate *appDelegate = (AppDelegate *)[[UIApplication sharedApplication] delegate];
>   self.window = [[UIWindow alloc] initWithWindowScene:(UIWindowScene *)scene];
>   self.window.rootViewController = appDelegate.window.rootViewController;
>   [self.window makeKeyAndVisible];
> }
> 
> - (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene didConnectInterfaceController:(CPInterfaceController *)interfaceController toWindow:(CPWindow *)window {
>   [RNCarPlay connectWithInterfaceController:interfaceController window:window];
> }
> 
> - (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene didDisconnectInterfaceController:(CPInterfaceController *)interfaceController fromWindow:(CPWindow *)window {
>   [RNCarPlay disconnect];
> }
> 
> @end
> ```

I don't suppose you have a minimal example project do you? I'm having trouble getting react-native-carplay working in an Expo (bare) app without the Maps entitlement and this seems to be the most promising thing I've found in my research :-)

**Comment by banesp** [comment]
> Using the window from the app delegate fixes this issue. i.e
> 
> ```
> public class ExpoDevLauncherAppDelegateSubscriber: ExpoAppDelegateSubscriber {
>   public func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: 
>   [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
>     if !ExpoDevLauncherReactDelegateHandler.shouldEnableAutoSetup {
>       return false
>     }
>       
>     guard let window = UIApplication.shared.delegate?.window else {
>       fatalError("Cannot find the scene or application window. Make sure to call `window.makeKeyAndVisible()`.")
>     }
>       
>     EXDevLauncherController.sharedInstance().autoSetupStart(window!)
>     return false
>   }
> 
>   public func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
>     if !ExpoDevLauncherReactDelegateHandler.shouldEnableAutoSetup {
>       return false
>     }
> 
>     return EXDevLauncherController.sharedInstance().onDeepLink(url, options: options)
>   }
> }
> ```
> 
> I am able to build and run the iOS app with a SceneDelegate which handles Carplay capabilities. My understanding is that keyWindow is not compatible with apps that support multiple scenes - but by using the AppDelegate window, and setting up a SceneDelegate which uses that same window it is possible to support multiple scenes.
> 
> **SceneDelegate reference:**
> 
> ```
> @implementation SceneDelegate
> 
> @synthesize window = _window;
> - (void)scene:(UIScene *)scene willConnectToSession:(UISceneSession *)session options:(UISceneConnectionOptions *)connectionOptions {
>   AppDelegate *appDelegate = (AppDelegate *)[[UIApplication sharedApplication] delegate];
>   self.window = [[UIWindow alloc] initWithWindowScene:(UIWindowScene *)scene];
>   self.window.rootViewController = appDelegate.window.rootViewController;
>   [self.window makeKeyAndVisible];
> }
> 
> - (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene didConnectInterfaceController:(CPInterfaceController *)interfaceController toWindow:(CPWindow *)window {
>   [RNCarPlay connectWithInterfaceController:interfaceController window:window];
> }
> 
> - (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene didDisconnectInterfaceController:(CPInterfaceController *)interfaceController fromWindow:(CPWindow *)window {
>   [RNCarPlay disconnect];
> }
> 
> @end
> ```

@caustin24345 This works very well for debug builds. However, when I run a production build with this implementation of a SceneDelegate, it only renders a black screen. I suspect it is relevant to this line but I'm not a 100% sure:
 `AppDelegate *appDelegate = (AppDelegate *)[[UIApplication sharedApplication] delegate];`
 
My AppDelegate is written in objective-c, inheriting from `EXAppDelegateWrapper`. 

I'm stuck here so any suggestions would be really appreciated.

**Comment by IWMTom** [comment]
> > **SNIP**
> 
> @caustin24345 This works very well for debug builds. However, when I run a production build with this implementation of a SceneDelegate, it only renders a black screen. I suspect it is relevant to this line but I'm not a 100% sure: `AppDelegate *appDelegate = (AppDelegate *)[[UIApplication sharedApplication] delegate];`
> 
> My AppDelegate is written in objective-c, inheriting from `EXAppDelegateWrapper`.
> 
> I'm stuck here so any suggestions would be really appreciated.

I was able to get it (more or less) working. There's still a few issues I've yet to iron out, but the following works in debug and prod builds, to the point I have published to TestFlight and had it approved by app review.

Issues I'm aware of:
- Opening the app via CarPlay if the app isn't open on the device causes a crash (bridge related issues perhaps?)
- Locking the phone screen causes the CarPlay view to stop updating

Hope this is helpful? Was quite painful for me to get this far!

### AppDelegate.h
```
#import <Foundation/Foundation.h>
#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>

#import <Expo/Expo.h>

@interface AppDelegate : EXAppDelegateWrapper <RCTBridgeDelegate>
@property (weak) IBOutlet UIWindow *window;

@end
```

### AppDelegate.mm
```
#import "AppDelegate.h"
#import "SceneDelegate.h"

#import <React/RCTBundleURLProvider.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"main";
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

- (UISceneConfiguration *)application:(UIApplication *)application configurationForConnectingSceneSession:(UISceneSession *)connectingSceneSession options:(UISceneConnectionOptions *)options
{
    UISceneConfiguration *sceneConfiguration = [[UISceneConfiguration alloc] initWithName:@"Default Configuration" sessionRole:connectingSceneSession.role];
    sceneConfiguration.delegateClass = [SceneDelegate class];
    return sceneConfiguration;
}

- (void)application:(UIApplication *)application didDiscardSceneSessions:(NSSet<UISceneSession *> *)sceneSessions
{
}

@end
```

### SceneDelegate.h
```
#import <UIKit/UIKit.h>
#import <CarPlay/CarPlay.h>

@interface SceneDelegate : UIResponder <UIWindowSceneDelegate, CPTemplateApplicationSceneDelegate>

@property (strong, nonatomic) UIWindow * window;

@end
```

### SceneDelegate.mm
```
#import "SceneDelegate.h"
#import "AppDelegate.h"
#import "RNCarPlay.h"
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <EXSplashScreen/EXSplashScreenService.h>

@implementation SceneDelegate

@synthesize window = _window;

- (void)scene:(UIScene *)scene willConnectToSession:(UISceneSession *)session options:(UISceneConnectionOptions *)connectionOptions
{
  if ([scene isKindOfClass:[UIWindowScene class]])
  {
    AppDelegate *appDelegate = (AppDelegate *)[[UIApplication sharedApplication] delegate];
    
    EXSplashScreenService *splashScreenService = (EXSplashScreenService *)[EXModuleRegistryProvider getSingletonModuleForClass:[EXSplashScreenService class]];
    [splashScreenService showSplashScreenFor:appDelegate.window.rootViewController options:EXSplashScreenForceShow];
    
    self.window = [[UIWindow alloc] initWithWindowScene:(UIWindowScene *)scene];
    self.window.rootViewController = appDelegate.window.rootViewController;
  
    
    [self.window makeKeyAndVisible];
  }
}

- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene didConnectInterfaceController:(CPInterfaceController *)interfaceController
{
    [RNCarPlay connectWithInterfaceController:interfaceController window:(UIWindow *)_window];
}

- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene didDisconnectInterfaceController:(CPInterfaceController *)interfaceController
{
    [RNCarPlay disconnect];
}

@end
```

### Info.plist
```
...
    <key>UIApplicationSceneManifest</key>
    <dict>
        <key>UISceneConfigurations</key>
        <dict>
            <key>UIWindowSceneSessionRoleApplication</key>
            <array>
                <dict>
                    <key>UISceneConfigurationName</key>
                    <string>Default Configuration</string>
                    <key>UISceneDelegateClassName</key>
	            <string>SceneDelegate</string>
                </dict>
            </array>
        </dict>
    </dict>
```

**Comment by janwiebe-jump** [comment]
@IWMTom Thanks for sharing your configuration! I am running into the error
`Application does not implement CarPlay template application lifecycle methods in its scene delegate.`
Have you run into this as well? I used exactly your code.
