### ISSUE TITLE
`getInitialURL` returns the incorrect URL on Android

### ISSUE THREAD

**Issue by fhelwanger** [expo/expo#2394]
I have the following `intentFilters` configured in `app.json`.

```
"intentFilters": [
  {
    "action": "VIEW",
    "data": {
      "scheme": "https",
      "host": "www.test.com"
    },
    "category": [
      "BROWSABLE",
      "DEFAULT"
    ]
  }
]
```

When I open `https://www.test.com` it asks to open my app correctly. The problem is that `Linking.getInitialURL()` doesn't return the correct url. Instead, it returns something like `https://expo.io:443/@user/expo-get-initial-url-test`.

### Environment

```
Environment:
  OS: Windows 10
  Node: 8.12.0
  Yarn: 1.10.1
  npm: 6.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5014246

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/desenvolvimento.secullum-5f93cb12-5f03-48ef-94c4-c279dbdc003a.tar.gz
```

Target: standalone android apk.

### Steps to Reproduce

1. `git clone https://github.com/fhelwanger/expo-get-initial-url-test.git`

2. Build an android apk

```
yarn install
expo build:android
```

3. Install the apk

4. Open `https://www.test.com` with `expo-get-initial-url-test` closed:

```
adb shell am start -a android.intent.action.VIEW -d https://www.test.com
```

It will print something like: `https://expo.io:443/@user/expo-get-initial-url-test`

5. Leave the app opened, go back to home screen and open the URL again:

```
adb shell am start -a android.intent.action.VIEW -d https://www.test.com
```

Now, the correct link (`https://www.test.com`) will be received with the `url` event.

### Expected Behavior

Both `getInitialURL` and `url` event should receive `https://www.test.com`.

### Actual Behavior

`getInitialURL` returns `https://expo.io:443/@user/expo-get-initial-url-test` instead of `https://www.test.com`.

<kbd>
  <img src="https://user-images.githubusercontent.com/11396047/46741392-48400900-cc7b-11e8-9f2c-2e14967bdb30.png">
</kbd>

<hr>

<kbd>
  <img src="https://user-images.githubusercontent.com/11396047/46741943-68bc9300-cc7c-11e8-9fd6-a3367a50e6cc.png">
</kbd>

### Reproducible Demo

https://github.com/fhelwanger/expo-get-initial-url-test

**Comment by esamelson** [comment]
Hi @fhelwanger - sorry you're running into this 😞  This bug has already been fixed on master and is just waiting for a minor or major release -- we don't have a set date but there should be one coming pretty soon. I'll update this thread when the fix is released.

**Comment by vikas26294** [comment]
@esamelson I have an application that I need to push live in next 2 days and I am getting this error. Do you know when this issue would be fixed in production mode or if there is any dirty way of fixing it for now until next build goes live?

**Comment by vikas26294** [comment]
@esamelson  Just tried, still not working. Currently my app is using expo version `30.0.0`, should I update it to `30.0.1`?

**Comment by vikas26294** [comment]
Hi @esamelson - Any update when its going to be deployed?

**Comment by vikas26294** [comment]
I built my app again and now its working for me too! 
Thanks!
