### ISSUE TITLE
Expo.Google.logInAsync and server side "offline" Google API access

### ISSUE THREAD

**Issue by thomasw** [expo/expo#241]
After making a successful call to `Expo.Google.logInAsync({'behavior: 'web' ...})`, I am attempting to send the `serverAuthCode` from the result to a web sever and exchange that code for a new auth token to facilitate server side API calls. This always fails. (Here's the relevant documentation for this process for Java Android apps: https://developers.google.com/identity/sign-in/android/offline-access)

My server side implementation looks something like this...

```python
    params = dict(
        code=server_auth_code_from_client,
        client_id=GOOGLE_CLIENT_ID,
        client_secret=GOOGLE_SECRET,
        redirect_uri='postmessage',
        grant_type='authorization_code')

    response = requests.post(
        'https://www.googleapis.com/oauth2/v4/token', data=params)

```

Unfortunately, I always receive an error of the following format when I attempt this. The value of `error_description` is typically `Invalid code.` as below, though it's sometimes different.

```python
{'error': 'invalid_grant', 'error_description': 'Invalid code.'}
```

I initially assumed that the problem was with my sever side implementation. To verify it, I wrote out a simple Google+ JS API example that can successfully use my endpoint to exchange a code for a token. That works just fine.

To troubleshoot my Expo implementation, I've been poring over https://github.com/expo/expo/blob/master/android/app/src/main/java/abi17_0_0/host/exp/exponent/modules/api/GoogleModule.java#L158 to make sense of it. I initially believed that I was encountering this problem because the generated login URL doesn't specify `access_type=offline` and the logInAsync interface doesn't allow for configuring that possibility. I'm skeptical about that conclusion however, because I've unsuccessfully attempted to hack that parameter into the login url by disabling network access, clicking my sign in button, opening the webview popup in Chrome, manually adding the parameter to the URL, re-enabling wifi, and continuing to the modified sign in flow. This procedure results in the same failure I described above.

I then intended to go down the road of testing my setup under the `system` behavior, but I noticed something that seems wrong in the `systemLogIn` method too: https://github.com/expo/expo/blob/master/android/app/src/main/java/abi17_0_0/host/exp/exponent/modules/api/GoogleModule.java#L126 It calls `requestServerAuthCode` but the parameter passed is the current mobile app's client id. According to the documentation for that method, this should instead be the client ID of a web app that will exchange the serverAuthCode for offline access. See https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInOptions.Builder.html#requestServerAuthCode(java.lang.String)

Does anyone out there have offline Google API access working with an Expo generated serverAuthCode? If so, does anything I've said here seem to indicate a misunderstanding on my part about how this is all supposed to work?

SDK Version: 17.0.0 (and 15.0.0, FWIW)
OS: Android 7.1.1 (haven't tested iOS)

**Comment by brentvatne** [comment]
cc @janicduplessis

**Comment by thomasw** [comment]
I ejected and was able to achieve my goal with react-native-google-signin. I'm going to continue down that road for now. The server side implementation I described above worked with one minor modification: I needed to remove `redirect_uri='postmessage',`. That's only necessary for a Google Plus code.

Here are some notes that might be helpful when someone has time to dig further into this:

* I'm pretty sure what I said about `requestServerAuthCode` is correct. Without the corresponding web client ID, Google won't give you a serverAuthCode that can be successfully exchanged using that web client ID. It is still unclear to me whether or not access_type=offline is necessary these days since it doesn't seem like Google's sign in flow explicitly mentions offline access anymore (though it definitely used to).
* I tried to temporarily work around my issues here using a flow like the following: Expo.WebBrowser -> server side login url which redirects to Google's OAuth flow -> Google OAuth login flow -> server side complete url which redirects back to the mobile app passing it an API auth token -> mobile app verifies the API auth token and then subsequently uses it for authenticated API calls. That more or less worked, but I couldn't reasonably hack around an issue I was encountering with Expo.WebBrowser: It seems that if a WebBrowser view navigates to a domain other than the one it was initially pointed at and then is redirected back to the mobile app (`exp://....`), the WebBrowser view will not close automatically. Attempting to close it in a link event listener caused exceptions in certain cases. (This should probably be a separate ticket, but I  didn't investigate it enough for definitive steps to reproduce the issue and stack traces. I'm mentioning it here in case anyone comes across this ticket and has a similarly harebrained ideas. It may also have something to do with a protocol change at some point during the flow.)
* Finally, I also tried to work around this issue by using `Expo.WebBrowser` to hit a custom crafted Google OAuth URL, bypassing the insufficient Expo implementation entirely. Unfortunately, Google heavily restricts acceptable URIs for post-login redirects. The protocol `exp://` is not allowed, for instance. You'd need to have something like host.exp.exponent:/some-path-that-magically-forwards-url-to-your-running-expo-app/ to make this a workable solution during development mode.
* It should be possible to use a WebView to implement the hacks above, but Google's sign in flow blocks WebViews unless you override the user-agent. Given that, it seems like a particularly bad idea.

**Comment by peterpme** [comment]
Hey,

I'm having the same issue. I'm narrowing it down to `web` vs. `system` issues right now because after going through both codebases I'm having trouble finding the "culprit".

Hoping this will provide some context clues:

I've been comparing [React Native Google Signin ios implementation](https://github.com/joonhocho/react-native-google-sign-in/blob/master/ios/RNGoogleSignIn/RNGoogleSignIn.swift) with [Expo Google SignIn](https://github.com/expo/expo/blob/834cc8b2d72e02fd2e8413dbe7d83eb9ab278801/ios/Exponent/Versioned/Modules/Api/EXGoogle.m#L40)

Expo offers two types of behaviors: `web` and `system`.

If you follow the [systemLogInWithClientId](https://github.com/expo/expo/blob/834cc8b2d72e02fd2e8413dbe7d83eb9ab278801/ios/Exponent/Versioned/Modules/Api/EXGoogle.m#L61) you'll notice that we're passing `serverClientID` (setting it to the `clientId` so maybe this is the issue)

react-native-google-sign-in does the same thing, but sets a `clientId` and `serverClientId` separately: https://github.com/joonhocho/react-native-google-sign-in/blob/master/ios/RNGoogleSignIn/RNGoogleSignIn.swift#L45

It looks like `webLogInWithClientId` doesn't use any SDK, but hits an URL instead. This makes me believe that you _should_ be able to recreate this behavior using a normal WebView.

**Comment by peterpme** [comment]
I may have fixed this on the ios side via https://github.com/expo/expo/pull/527 but we'll see! Going to test on my end now.

**Comment by janicduplessis** [comment]
@thomasw When using behavior: web what type of client id are you using? It is mentioned in the Type column of the credentials section on the google developer console.

**Comment by thomasw** [comment]
I used a type=android client id on the expo side of things. The server side implementation uses a type=web token. The Google Plus JS implementation likely used the same type=web token as the server side implementation.

I am now using the same type=android client id I was using with Expo with [react-native-google-signin](https://github.com/devfd/react-native-google-signin), and exchanging the resulting code server side using the type=web token as I expected to be able to do.

I realize it's probably not particularly helpful, but that configuration looks like this for reference:

```js
import { GoogleSignin } from 'react-native-google-signin'

GoogleSignin.configure({
  scopes: [...], 
  offlineAccess: true,
  webClientId: "<Google client_id type=web foo>"
})
```

And then in google-services.json (generated via https://developers.google.com/identity/sign-in/android/start-integrating):

```json
{
  "project_info": {
    "project_number": "...",
    "project_id": "..."
  },
  "client": [
    {
      "client_info": { ... },
      "oauth_client": [
        {
          "client_id": "<Google client_id type=android bar>",
          "client_type": 1,
          "android_info": { ... }
        },
        {
          "client_id": "<Google client_id type=web foo>",
          "client_type": 3
        }
      ],
      "api_key": [
        {
          "current_key": "..."
        }
      ],
      "services":  { ... }
    }
  ],
  "configuration_version": "1"
}
```

The server side implementation is as described above and uses `<Google client_id type=web foo>` and its corresponding secret.

**Comment by janicduplessis** [comment]
@thomasw Thanks for the info, the issue is that we need to use a web client id to get the serverAuthCode but right now we are using the android one. Working on a fix to add an extra option to pass the web client id and use that instead.

**Comment by janicduplessis** [comment]
This should be fixed in sdk 21, we introduced a new parameter called webClientId that should be a client id of type web that will be used to query offline stuff.

**Comment by thomasw** [comment]
Thanks, @janicduplessis. I'll give expo another go when I start working on my next project.

**Comment by absolutpauer** [comment]
@janicduplessis , it looks like sdk 21 addresses the issue for native login, but not for web login. It looks like serverClientId isn't being passed for web login. Is there a plan to address this?

**Comment by mach-kernel** [comment]
I have a feeling my issue is similar to others in this thread but I am unsure. I was previously using `react-native-google-signin` but we are migrating away from native modules in our application. The original works but has different credentials -- we're using the `web` mode now with the Expo bundle identifier to ease testing. I invoke `Expo.Google.logInAsync` with `webClientId`and receive a `serverAuthCode`, but when I attempt to complete the auth flow serverside I receive this response:

```
{ "error": "invalid_grant",
 error_description": "Missing code verifier." }
```

It appears I explicitly need to request `offline` access but do not have the means to do so / the API docs do not show me how. Is there something obvious that I am missing?

Thanks!

**Comment by ArsenyYankovsky** [comment]
I think this should be reopened as it is still reproducible per @absolutpauer comment.

**Comment by marano** [comment]
This is the response I get on the backend when trying to use the returned `serverAuthCode` with the web client id:
```
{
 "error": "invalid_grant",
 "error_description": "Code was already redeemed."
}
```
I did inform my web client ID to `logInAsync`. I'm using the web behavior with SDK 23.

**Comment by aatreya** [comment]
We're having the same issue, and are getting the "Missing code verifier" message on our server.

Has anyone managed to get the serverAuthCode exchange working in full when using the 'web' behavior?

**Comment by marano** [comment]
If anybody comes across this problem, I've solved it by using the `idToken` instead of `serverAuthCode` to verify the user identity and access his data on the server side. It seems a better way to go for most cases.

**Comment by danlin604** [comment]
Can you elaborate on how you are using idToken in place of serverAuthCode?

**Comment by marano** [comment]
The response for `logInAsync` contains a field named `idToken`, which I send to my backend. On the backend, I use `google-id-token` gem to get the user info by informing the `idToken`.

You can check the resolver implementation here:
https://github.com/seedtronic/doctalk-api/blob/master/app/graphql/resolvers/google_login_resolver.rb

This is the google gem:
https://github.com/google/google-id-token

**Comment by marano** [comment]
(Disclaimer: the solution above will let you verify the user identity and get a few fields and low resolution profile photo, but won't let you do anything else on the API using the user credentials)

**Comment by aatreya** [comment]
The idToken allows your server to authenticate the user (which may be sufficient for some use cases), but the serverAuthCode is still necessary if your server wants to be able to access any Google APIs on behalf of the user. Unfortunately, it looks like Expo.Google.logInAsync has a bug where the serverAuthCode isn't even being sent into the 'web' behavior handing code, so there's no way for Google to generate the valid tokens that are needed.

**Comment by danlin604** [comment]
Thanks for response & clarification.

My main issue right is that I want to be able to refresh the access token passed from the client app on server-side. The response is that I am unauthorized. When I request for accessToken and refreshToken, the response will be that the Code has already been redeemed. Is the serverAuthCode being used somewhere in the googleLoginAsync() call?

Here is how I am use the serverAuthCode:
`
const response = await axios.post('https://www.googleapis.com/oauth2/v4/token', 
  qs.stringify({
    code: serverAuthCode,
    client_id: WEB_CLIENT_ID,
    client_secret: WEB_CLIENT_SECRET,
    redirect_url: AUTH_SERVER,
    grant_type: 'authorization_code'
  })
)
`
Response: 
`{ error: 'invalid_grant', error_description: 'Code was already redeemed.' }`

**Comment by jpagex** [comment]
I have the exact same problem ("Code was already redeemed.").
Any news regarding this issue?

**Comment by charlesvinette** [comment]
Hey @jpagex, looking into this. Will report back, thanks!

**Comment by charlesvinette** [comment]
Hello everyone. So I investigated this issue and indeed, in it's current implementation it is not possible to do with the `web` behavior. The Google Module uses AppAuth to handle browser based login when in an Expo Experience. A little while ago, you could pass your webAppId as the client id and it would work, but Google made changes recently and custom schemes URI are not allowed anymore for web client type. You can read more here -> https://stackoverflow.com/questions/42105485/cross-client-google-oauth-get-auth-code-on-ios-and-access-token-on-server?answertab=votes#tab-top

However, I believe I achieved what you are trying to do by using the `AuthSession` Expo module.
Here is the call to Google Auth, which will return the `code` you want to exchange on your backend.

```javascript
let result = await Expo.AuthSession.startAsync({
      authUrl:
        `https://accounts.google.com/o/oauth2/v2/auth?` +
        `&client_id=${googleWebAppId}` +
        `&redirect_uri=${encodeURIComponent(redirectUrl)}` +
        `&response_type=code` +
        `&access_type=offline` +
        `&scope=profile`,
    });
```
Once you have your code, send it to your backend and exchange it, but make sure to set the `redirect_uri` parameter to the same value you used on your client side call to Google.
(Something similar to `https://auth.expo.io/@charlesvinette/your-app-slug`)

And you should then get a response similar to this on your backend :
```json
{ access_token: 'token',
  token_type: 'Bearer',
  expires_in: 3600,
  refresh_token: 'refresh_token',
  id_token: 'id_token' 
}
```

**Comment by jpagex** [comment]
Thank you for your work @charlesvinette. Indeed, I tried `AuthSession` to get the correct code from Google, while you were investigating the issue. Is is working quite well, but lacks the "native" authentication. One difference, is that I use a server endpoint as the `redirect_uri`, and the server redirects back to the app. Any preference on this?

If it is not possible to get a server code on the client, maybe the Expo docs should be updated and redirect to the `AuthSession` module.

**Comment by jpagex** [comment]
Using native in standalone production app seems OK, but the docs lack some explanation. The process to use the native authentication is not easy. We need to provide the `iosStandaloneAppClientId` and the `androidStandaloneAppClientId` but the `webClientId` will be used to get the `serverAuthCode`.

Can we have an example of how to authenticate with the `Google` module in order to get a server code?

Also, the `AuthSession`, although it is quite easy to setup, it is not very nice to use in production because we have the signup authorization message including `expo.io`. This is not OK regarding the users.
It is possible to achieve the same process with `WebBrowser` but it is more complicated.

**Comment by aalices** [comment]
@jpagex we are about to update the docs how to use `AuthSession` to be able to get the token on server side. And it is basically what Charles described above. 

On standalone I think it is better to use the `Google` module as this will work just fine and you won't have to be worried about users seeing any "expo" stuff.
