### ISSUE TITLE
[android] Error `expo.modules.kotlin.jni.JavaCallback.invoke` in `PushTokenModule`

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#24154]
### Minimal reproducible example

I don't have :(

### Summary

I'm getting this crash details in Google Play, but I have no idea how to reproduce it:

```
Exception java.lang.NullPointerException: java.lang.NullPointerException
  at expo.modules.kotlin.jni.JavaCallback.invoke
  at expo.modules.kotlin.jni.JavaCallback.invoke (JavaCallback.kt:24)
  at expo.modules.kotlin.jni.PromiseImpl.reject (PromiseImpl.kt:87)
  at expo.modules.kotlin.PromiseKt$toBridgePromise$1.reject (Promise.kt:41)
  at expo.modules.adapters.react.PromiseWrapper.reject (PromiseWrapper.java:36)
  at expo.modules.notifications.tokens.PushTokenModule$1.onComplete (PushTokenModule.java:72)
  at com.google.android.gms.tasks.zzi.run (com.google.android.gms:play-services-tasks@@18.0.2:1)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6971)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:865)
```

<img width="1123" alt="Screen Shot 2023-08-29 at 06 45 38" src="https://github.com/expo/expo/assets/1837969/d197062f-a23f-45aa-9223-8415f423be0d">

As you can see, this is always happening in background, so, it may not be a problem for the user, but I report it just in case.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.3
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.7 => 49.0.7
      react: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
    npmGlobalPackages:
      eas-cli: 4.1.2
      expo-cli: 6.3.10
    Expo Workflow: managed
```

**Comment by SohelIslamImran** [comment]
I'm facing the same issue on Android at first app startup...

<img width="741" alt="image" src="https://github.com/expo/expo/assets/76745339/3f073faa-f1e6-4d6a-a933-bf74759c1850">
<img width="461" alt="image" src="https://github.com/expo/expo/assets/76745339/5d4f40d8-00c9-478c-b9bd-f00076030df4">

**Comment by leons1767** [comment]
I face the same issue, took me a whole day to troubleshoot. 

iOS has similar issue, but the error message is different and somehow handled. So, unlike Android, it does not cause iOS to crash.
```
ReferenceError: Property 'e' doesn't exist
```
My workaround is to do an eas update even without any code change. Once the device is updated, the error stops. This workaround is good for both Android and iOS, in my case.

**Comment by lukmccall** [comment]
Https://github.com/expo/expo/pull/24442 should fix the problem with Android. 
@leons1767, could you create a new issue and describe the iOS problem in more detail? Thanks in advance.

**Comment by leons1767** [comment]
> [Https://github.com/expo/expo/pull/24442](Https://github.com/expo/expo/pull/24442) should fix the problem with Android. @leons1767, could you create a new issue and describe the iOS problem in more detail? Thanks in advance.

@lukmccall, may I know if you suppress the error globally in the Updates package or just Updates.reloadAsync()? I'm asking because I have the error when running Updates.checkForUpdateAsync() with SDK 49.0.13 and expo-updates 0.18.14.

**Comment by BrodaNoel** [comment]
@lukmccall was this already released? Which package should I update?

**Comment by leons1767** [comment]
> [Https://github.com/expo/expo/pull/24442](Https://github.com/expo/expo/pull/24442) should fix the problem with Android. @leons1767, could you create a new issue and describe the iOS problem in more detail? Thanks in advance.

In the latest expo-updates 0.18.16, the iOS error is gone, but Android checkForUpdateAsync() crash problem remains. I created #24849 for the issue.

**Comment by abumalick** [comment]
this is not included in Expo 49, this is shipped in expo-modules-core 1.8.0
We will probably have this in Expo 50.

ref: https://github.com/expo/expo/blob/main/packages/expo-modules-core/CHANGELOG.md#180--2023-09-15
