### ISSUE TITLE
Translucent status bar behaves differently on Android with release vs debug builds

### ISSUE THREAD

**Issue by erickreutz** [expo/expo#25463]
### Summary

I'd like to use translucent status bars in my app but I'm having trouble getting them to work and appear correctly when building the Android app in release mode.

Below are two screens. The left is a `--variant debug` build and the right is a `--variant release` build. You can see how the status bar is displayed differently. 

| Debug     | Release |
| ----------- | ----------- |
|  <img width="741" alt="image" src="https://github.com/expo/expo/assets/59875/3c6f454e-de92-4219-a38a-fdfdba3bb99e">      | <img width="741" alt="image" src="https://github.com/expo/expo/assets/59875/281d294d-b019-4fc9-8190-e940052a9efe"> |

My working theory is that it has something to do with the presence or absence of `expo-dev-menu` and possibly related to the fact that `expo-dev-menu` has a [custom vendored version](https://github.com/expo/expo/blob/ddb07c3a8cc008620a7bbffcd5c5a8bb27db34ce/packages/expo-dev-menu/android/build.gradle#L97) of `react-native-safe-area-context` that it seems to use?

I also found [this issue](https://github.com/th3rdwave/react-native-safe-area-context/issues/456) upstream which seems to mimic the visual problem I am seeing which may make it an issue of theirs but at the same time I'm wondering why you reimplemented `react-native-safe-area-context` in `expo-dev-menu`?

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android

### Package versions

```json
{
  "name": "my-test-app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~49.0.15",
    "expo-dev-client": "~2.4.12",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-safe-area-context": "4.6.3",
    "expo-splash-screen": "~0.20.5"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
```

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /opt/homebrew/bin/zsh
    Binaries:
      Node: 18.14.1 - ~/.asdf/installs/nodejs/18.14.1/bin/node
      Yarn: 1.22.17 - ~/.asdf/shims/yarn
      npm: 9.3.1 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.11.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/eric/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.17 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.8.0
    Expo Workflow: bare
```

### Reproducible demo

A reproducible demo should be easy to obtain. The only thing you really need is `react-native-safe-area-context`, `expo-dev-client` and to set `androidStatusBar.translucent` to `true` in your app.json.

Then run the following commands to build a `debug` version vs a `release` version. 

```bash
rm -fr android || true && yarn android -d --variant debug --no-build-cache
```

```bash
rm -fr android || true && yarn android -d --variant release --no-build-cache
```

Below is my `App.js`

```javascript
import { StyleSheet, View, Text } from "react-native";
import {
  SafeAreaProvider,
  initialWindowMetrics,
} from "react-native-safe-area-context";
import { StatusBar } from "expo-status-bar";

export default function App() {
  return (
    <SafeAreaProvider initialMetrics={initialWindowMetrics}>
      <StatusBar style="dark" translucent />
      <View style={styles.container}>
        <Text>Hello world!</Text>
      </View>
    </SafeAreaProvider>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "yellow",
  },
});
```

**Comment by erickreutz** [comment]
This [issue](https://github.com/expo/expo/issues/11604) was helpful. Setting`androidStatusBar.translucent` to `true` add:
```xml
<item name="android:windowTranslucentStatus">true</item>
```
to `styles.xml` and 
```xml
  <string name="expo_splash_screen_status_bar_translucent" translatable="false">true</string>
```
to `strings.xml`

If I then write a config plugin to modify `styles.xml` and set `android:windowTranslucentStatus` to `false` the issue is fixed. Cant speak to what is causing the underlying issue though.

**Comment by cyberkaidev** [comment]
I have the same problem

**Comment by jakobvase** [comment]
I'm using expo-router, and I also have this issue. I solved it by setting the `androidStatusBar.translucent` to `false` in app.json, and then adding a `<StatusBar translucent />` component. It seems to me like whatever the `<Statusbar />` component adds is ignored if the value is true in app.json, whether by using the default or setting it explicitly.

Also be aware that you only see the gray status bar if your app or phone is in light mode - in dark mode it works fine.

**Comment by z1haze** [comment]
We have this issue too. Why has this issue been open since november and not fixed yet?

**Comment by naftalimurgor** [comment]
Experiencing the same issue, has anyone been able to fix this problem? or figured out a workaround for the same?

**Comment by mrakus-sofomo** [comment]
Any updates?

**Comment by marcel-mintouge** [comment]
Hi, any updates?
