### ISSUE TITLE
Running `npx eas-cli@next build --platform ios --profile development` gives error `Cannot destructure property 'expoUsername' of 'undefined' as it is undefined.``

### ISSUE THREAD

**Issue by pvinis** [expo/expo#25894]
### Minimal reproducible example

.

### Summary

I have no idea where this `expoUsername` comes from. If I understood, I could check what's up.

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.local/share/rtx/installs/node/18.17.1/bin/node
      Yarn: 1.22.19 - ~/.local/share/rtx/installs/yarn/1.22.19/bin/yarn
      npm: 9.6.7 - ~/.local/share/rtx/installs/node/18.17.1/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.5.2 => 9.5.2
      expo: ^50.0.0-preview.1 => 50.0.0-preview.1
      react: 18.2.0 => 18.2.0
      react-native: 0.73.0 => 0.73.0
    Expo Workflow: managed
```

**Comment by TowhidKashem** [comment]
+1 experiencing the same issue trying to upgrade from expo `^49.0.18` to `^50.0.0-preview.4`. @pvinis did you end up finding a solution to this?

**Comment by corasan** [comment]
@TowhidKashem did you find a solution? Why was this even marked as completed? I'm on `preview.7`.

**Comment by TowhidKashem** [comment]
@corasan nope just waiting till it's out of beta to upgrade, hopefully it will be resolved by then. There were several other issues too along with this one so not worth the trouble to upgrade now imo.

**Comment by Nasseratic** [comment]
Same here

**Comment by pvinis** [comment]
Still here on `preview.8`, just in case anyone is searching for this.

**Comment by Nasseratic** [comment]
I think this will be fixed one of the next versions, seems like leftover from the clasic updates

**Comment by tslater** [comment]
I'm trying 50.0.0-preview.10 and still seeing the issue. Seems like it's just speculation that it's being fixed? Should the issue still be open?

**Comment by wodin** [comment]
What dependencies and devDependencies do you all have installed?

If you have `@expo/config-plugins` or `eas-cli` installed as dependencies/devDependencies, uninstall them.

I am not sure if the above will fix this problem, but you should not have those installed as direct dependencies of your app anyway. `@expo/config-plugins` will be pulled in automatically by `expo` and `eas-cli` should be installed globally

**Comment by wodin** [comment]
Also, is `npx expo-doctor` happy?

**Comment by danieldunderfelt** [comment]
Fixed by deleting `@expo/config-plugins`, then removing node_modules and my lockfile and reinstalling everything. `expo-doctor` complained about some old packages, now it is all green. I hope this helps!

**Comment by julian-gargicevich** [comment]
Still happening with the new stable release, I don't have config-plugins or eas-cli installed

**Comment by DarylBeattie** [comment]
Ouch, I had this happen too.

I had left everything else alone, was using the absolute latest `eas-cli`, but had upgraded `expo-updates` from `~0.18.16` to the latest, where my `package.json` said `^0.24.9`. In my case it might have been triggered by a compatibility issue.

To fix my issue (probably temporarily until I have to update all of Expo) I downgraded it back to `~0.18.16`.

**Comment by Saracevas** [comment]
Thank you @wodin, it was in fact `config-plugins` in our `resolutions` that was causing this. You're a :star:️

**Comment by PiTiLeZarD** [comment]
Hey, so my turn:

I've just upgraded expo 49 -> 50 and I get this now as well. I do not have config-plugins or eas-cli specified in my package.json, eas-cli is version 7.1.2 installed globally, expo-doctor is happy, npx expo install --fix is happy, nothing in resolutions either, I've removed nodes-modules and yarn.lock and re-installed everything. Metro and the web run well, but running:
```
> eas build --profile ios-simulator --platform ios
Loaded "env" configuration for the "ios-simulator" profile: no environment variables specified. Learn more
Cannot destructure property 'expoUsername' of 'undefined' as it is undefined.
    Error: build command failed.
```

Not quite sure what to do now :/ 

the env-info:
```
> npx expo-env-info
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - /opt/homebrew/opt/node@18/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 10.2.3 - /opt/homebrew/opt/node@18/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~19.0.1 => 19.0.1 
      expo: ~50.0.5 => 50.0.5 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
      react-native-web: ~0.19.10 => 0.19.10 
    Expo Workflow: bare
```

Any help would be gratefully appreciated here

**Comment by hbel** [comment]
I am experiencing the same problem after upgrading to eas 7.2.0 (because of the apple developer API bug/change).

this is my expo info (note that I am **not** on 50 yet!)

```expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v20.8.0/bin/yarn
      npm: 10.4.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/hendrikbelitz/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 26, 28, 29, 30, 31, 33
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-29 | Google APIs ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.16 => 48.0.16 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.14 => 0.71.14 
    npmGlobalPackages:
      eas-cli: 7.2.0
    Expo Workflow: managed

**Comment by t0ma5h** [comment]
Same problem.

**Comment by marcshilling** [comment]
Resolved this by `rm -rf node_modules` then running `yarn` again.

**Comment by hbel** [comment]
I was now able to solve this by adding the matching `@expo/config-plugins` to my project although it wasn't needed or there before. Afterwards, eas worked again.

**Comment by PiTiLeZarD** [comment]
> Resolved this by `rm -rf node_modules` then running `yarn` again.

Me: "Come on man, don't you think we all thought of that?"
Also me: "rm -Rf node_modules && yarn... oh shit it worked!" 

Cheers for the reminder mate ;)

**Comment by PiTiLeZarD** [comment]
Just to add to it, I realised I have 2 environments: (in packages.json scripts)
```
        "eas:dev:ios": "eas build --profile ios-simulator --platform ios",
        "eas:dev:androidapk": "eas build --profile android-apk --platform android",
```

and eas.json:
```
{
    "build": {
        "ios-simulator": {
            "developmentClient": true,
            "distribution": "internal",
            "ios": {
                "simulator": true
            }
        },
        "android-apk": {
            "developmentClient": true,
            "distribution": "internal",
            "android": {
                "buildType": "apk",
                "gradleCommand": ":app:assembleRelease"
            }
        }
    }
}
```

The one with ios still gives me the error, the one with android apk doesn't. Not sure if anyone is looking into this? or has found how to set this variable anywhere?

**Comment by wodin** [comment]
> Explicitly adding `@expo/config-plugins` and/or `@expo/config`did not help. Deleting the `node_modules` did not help either.

You should not have those packages as direct dependencies.

@hbel and @PiTiLeZarD, what does your `package.json` look like? Can you upload it to https://gist.github.com and post a link here?

**Comment by Jace-Tech** [comment]
> > Explicitly adding `@expo/config-plugins` and/or `@expo/config`did not help. Deleting the `node_modules` did not help either.
> 
> You should not have those packages as direct dependencies.
> 
> @hbel and @PiTiLeZarD, what does your `package.json` look like? Can you upload it to https://gist.github.com and post a link here?

here's mine [https://gist.github.com/Jace-Tech/c778e34ede859e68e03bf118b4139d58](https://gist.github.com/Jace-Tech/c778e34ede859e68e03bf118b4139d58). I'm having similar issues

**Comment by Jace-Tech** [comment]
> I was now able to solve this by adding the matching @expo/config-plugins to my project although it wasn't needed or there before. Afterwards, eas worked again.

Thanks, this worked for me

**Comment by PiTiLeZarD** [comment]
> > Explicitly adding `@expo/config-plugins` and/or `@expo/config`did not help. Deleting the `node_modules` did not help either.
> 
> You should not have those packages as direct dependencies.
> 
> @hbel and @PiTiLeZarD, what does your `package.json` look like? Can you upload it to https://gist.github.com and post a link here?

sorry, meant to do this and then life!

Here is mine: https://gist.github.com/PiTiLeZarD/5d6dc3b7d5255d9cd1e2d3a2cbd515f4

**Comment by wodin** [comment]
> The one with ios still gives me the error, the one with android apk doesn't. Not sure if anyone is looking into this? or has found how to set this variable anywhere?

@PiTiLeZarD I cloned your project, ran `yarn`, changed the slug, project ID and bundle ID/package. I was then able to build by running your `eas:dev:ios` script. :man_shrugging: 

I don't see anything obviously wrong with your dependencies, but given that you're using Metro for web bundling, you should be able to uninstall `@expo/webpack-config`

Also, `expo-doctor` says this:
```
The package  "@types/react-native" should not be installed directly in your project, as types are included with the "react-native" package.
```
so you should uninstall that too.

While you're at it, you should run `npx expo install --fix` to get the fixes for the iOS privacy manifest stuff:
* [May 2024 iOS privacy manifest requirements tracking issue  #27796](https://github.com/expo/expo/issues/27796)
* [Privacy manifest docs](https://docs.expo.dev/guides/apple-privacy/)

**Comment by PiTiLeZarD** [comment]
@wodin so that's great cuz that means the problem is somewhere else. I just cleaned up the way you said it (funny that something complained about types/react-native being missing, I only recently had to add it) and I still have the issue:
```
❯ yarn eas:dev:ios
yarn run v1.22.18
warning ../../../package.json: No license field
$ eas build --profile ios-simulator --platform ios
★ eas-cli@7.6.2 is now available.
To upgrade, run npm install -g eas-cli.
Proceeding with outdated version.

Loaded "env" configuration for the "ios-simulator" profile: no environment variables specified. Learn more
Cannot destructure property 'expoUsername' of 'undefined' as it is undefined.
    Error: build command failed.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'll try to uninstall expo completely and re-install it maybe that'll fix it?

**Comment by wodin** [comment]
> I'll try to uninstall expo completely and re-install it maybe that'll fix it?

When you say "uninstall expo completely", what do you mean?

> ★ eas-cli@7.6.2 is now available.

What do you get if you run `eas --version`?

Try upgrading `eas-cli` and then run `eas --version` again after that to verify that it now says `7.6.2`

Also maybe try deleting `node_modules` and rerunning `yarn install`

**Comment by PiTiLeZarD** [comment]
So yeah, removed node_modules, yarn.lock and removed eas globally to re-intall it:

```
❯ eas --version
eas-cli/7.8.2 darwin-arm64 node-v18.19.0
❯ yarn eas:dev:ios
yarn run v1.22.18
warning ../../../package.json: No license field
$ eas build --profile ios-simulator --platform ios
Loaded "env" configuration for the "ios-simulator" profile: no environment variables specified. Learn more
Cannot destructure property 'expoUsername' of 'undefined' as it is undefined.
    Error: build command failed.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Same same... ¯\_(ツ)_/¯ not sure where it could come from :/

**Comment by wodin** [comment]
What do you get if you run this in your project?
```console
$ grep -rl expoUsername .
```

**Comment by KristianLentino99** [comment]
Not sure if it can solve the problem also for you but for me it worked. 
Basically I've ran again
`npx expo install expo-updates`

Then again `eas update:configure` and it successfully configured the eas.json file, it seems that it was missing a new line at the bottom, now it seems to work :D

**Comment by IfeOlulesi** [comment]
I also experienced this issue after upgrading from Expo 49 to 50. 

My builds were crashing with the following error:
```TypeError: Cannot destructure property 'expoUsername' of 'undefined' as it is undefined.```

Thanks to the helpful comments in this issue, I ran the following commands and it worked for me:

1. npx expo-doctor
Seems the issue was with @expo/config-plugins. Expected @~7.2.2 but found @8.0.4
2. npx expo install --fix
3. npx expo install --check
4. npx expo-doctor (At this point, all checks were green)🥳

**Comment by agustrocha** [comment]
I'd try everything you said in this post and still having that error when updating expo sdk from 49 to 50. I can't even start the app since then.

```
TypeError: Cannot destructure property 'expoUsername' of 'undefined' as it is undefined.
    at Object.withUpdates (C:\Users\node_modules\@expo\config-plugins\build\android\Updates.js:91:3)
    at withUpdates (C:\Users\node_modules\expo-updates\plugin\build\withUpdates.js:7:53)
    at plugin (C:\Users\node_modules\@expo\config-plugins\build\plugins\withRunOnce.js:49:25)
    at withRunOnce (C:\Users\node_modules\@expo\config-plugins\build\plugins\withRunOnce.js:37:10)
```

Any ideas?

**Comment by mselmany** [comment]
Removing `package-lock.json` and reinstalling with `npm i --legacy-peer-deps`  worked for me.

**Comment by arnabdotpy** [comment]
Fixed this by doing `rm -rf node_modules` and then `npm i` again.

**Comment by sergioisidoro** [comment]
I'm also facing this issue as soon as I add `expo-updates` package on SDK 51 this issue starts appearing. Tried everything here, but nothing helped.

Running expo doctor reveals some issues with config dependencies. Expo fix did not fix any of these. `eas-cli` nor `config-plugins` are installed directly. This may be releated to me using a monorepo. Here's output of expo-doctor.

```
Expected package expo-modules-autolinking@~1.10.0
Found invalid:
  expo-modules-autolinking@1.11.1
  expo-modules-autolinking@1.11.1
  (for more info, run: npm why expo-modules-autolinking)
Expected package @expo/config-plugins@^7.8.0
Found invalid:
  @expo/config-plugins@8.0.5
  @expo/config-plugins@8.0.5
  @expo/config-plugins@8.0.8
  @expo/config-plugins@8.0.8
  @expo/config-plugins@8.0.8
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@^6.7.0
Found invalid:
  @expo/prebuild-config@7.0.6
  @expo/prebuild-config@7.0.6
  (for more info, run: npm why @expo/prebuild-config)
Expected package @expo/metro-config@~0.17.1
Found invalid:
  @expo/metro-config@0.18.7
  @expo/metro-config@0.18.7
  ```

**Downgrading to SDK 50 seems to have fixed the issue, at least for now.**

**Comment by pascalAldavekollie** [comment]
### Issue Resolution: Fixing Version Mismatches and Errors

Hey everyone,

I wanted to share how I resolved the issues I was facing with version mismatches and related errors in my Expo project.

**Steps I Took:**

1. **Removed All Resolutions:**
   I started by removing the entire `"resolutions": {}` block from my `package.json`. The resolutions were causing version conflicts, particularly with core Expo packages.

2. **Updated Expo:**
   After removing the resolutions, I updated Expo to the latest stable version:

 ```bash
   yarn add expo@latest
   yarn add expo@51
```

This ensured that all dependencies aligned with the correct versions expected by Expo.
