### ISSUE TITLE
--web --https does not start web dev server with https

### ISSUE THREAD

**Issue by acdoussan** [expo/expo#26706]
### Summary

`expo start --web --https` with the current default implementation of `npx create-expo-app --template (chose typscript with routing)` does not start a web dev server with https, it stays http.

### What platform(s) does this occur on?

Web

### SDK Version

    "expo": "~50.0.3",

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.10 Amazon Linux 2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.20.1 - ~/.nvm/versions/node/v16.20.1/bin/node
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.1/bin/npm
    npmPackages:
      expo: ~50.0.3 => 50.0.3
      expo-router: ~3.4.5 => 3.4.5
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

### Minimal reproducible example

- `npx create-expo-app --template` (chose typscript with routing)
- update the web script to be `"web": "expo start --web --https",`
- `npm start web`
- get a web dev server of `http://localhost:8081`(wrong) instead of `https://localhost:8081` (expected)

**Comment by acdoussan** [comment]
Looks like the default web bundler is now metro. Metro doesn't appear to have any https configuration option. https://metrobundler.dev/docs/configuration/#server-options

I updated the bundler in the app.json for web to instead be `webpack` and installed the webpack plugin as instructed. Now the dev server starts with https, but webpack fails to bundle the files, I just get the following 3 errors. When the page loads its just blank.

I tried upgrading to nodejs 18, as well as `rm -rf node_modules` and reinstalled, neither made any difference.

```
ERROR in ./node_modules/expo-modules-core/build/uuid/uuid.web.js:9:8
Module not found: Can't resolve 'crypto'
   7 |   const cryptoObject =
   8 |     typeof crypto === 'undefined' || typeof crypto.randomUUID === 'undefined'
>  9 |       ? require('crypto')
     |        ^
  10 |       : crypto;
  11 |
  12 |   if (!cryptoObject?.randomUUID) {

ERROR in ./node_modules/expo-router/_ctx.web.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: <redacted>/node_modules/expo-router/_ctx.web.js: Expected `fromDir` to be of type `string`, got `undefined`
    <stack trace redacted>

ERROR in ./node_modules/expo-router/build/onboard/Tutorial.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: <redacted>/node_modules/expo-router/build/onboard/Tutorial.js: Expected `fromDir` to be of type `string`, got `undefined`
    <stack trace redacted>

web compiled with 3 errors
```

**Comment by EvanBacon** [comment]
Related https://github.com/expo/expo/pull/18415 -- there are a few issues with the native implementation that make this feature hard to support. You could potentially use a tunnel to workaround in the meantime.


@acdoussan you will need to configure webpack to shim Node.js builtins when bundling for the browser. This can be done using the `externals` config option.

**Comment by JPStrydom** [comment]
> Looks like the default web bundler is now metro. Metro doesn't appear to have any https configuration option. https://metrobundler.dev/docs/configuration/#server-options
> 
> I updated the bundler in the app.json for web to instead be `webpack` and installed the webpack plugin as instructed. Now the dev server starts with https, but webpack fails to bundle the files, I just get the following 3 errors. When the page loads its just blank.
> 
> I tried upgrading to nodejs 18, as well as `rm -rf node_modules` and reinstalled, neither made any difference.
> 
> ```
> ERROR in ./node_modules/expo-modules-core/build/uuid/uuid.web.js:9:8
> Module not found: Can't resolve 'crypto'
>    7 |   const cryptoObject =
>    8 |     typeof crypto === 'undefined' || typeof crypto.randomUUID === 'undefined'
> >  9 |       ? require('crypto')
>      |        ^
>   10 |       : crypto;
>   11 |
>   12 |   if (!cryptoObject?.randomUUID) {
> 
> ERROR in ./node_modules/expo-router/_ctx.web.js
> Module build failed (from ./node_modules/babel-loader/lib/index.js):
> TypeError: <redacted>/node_modules/expo-router/_ctx.web.js: Expected `fromDir` to be of type `string`, got `undefined`
>     <stack trace redacted>
> 
> ERROR in ./node_modules/expo-router/build/onboard/Tutorial.js
> Module build failed (from ./node_modules/babel-loader/lib/index.js):
> TypeError: <redacted>/node_modules/expo-router/build/onboard/Tutorial.js: Expected `fromDir` to be of type `string`, got `undefined`
>     <stack trace redacted>
> 
> web compiled with 3 errors
> ```

I'm having this same issue, but we're just running `expo start --web`. We're using Webpack to bundle our application, which works fine on Expo 50 (_we tried the upgrade to Metro for web, but it didn't appear to support live reloading last we checked - we also have a lot of custom web HTML injections (templates) and we haven't seen a migration guide for these_). 

Here's my current Expo env info:
```
 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.9971841
    npmPackages:
      @expo/webpack-config: ^19.0.1 => 19.0.1
      expo: ~50.0.4 => 50.0.4
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.10 => 0.19.10
    Expo Workflow: managed
```

This issue is currently blocking our migration to Expo 50, so any help would be appreciated.

**Comment by oxbits** [comment]
this error is occurring going through the `StickerSmash` app tutorial.

```
› Open in the web browser...
› Press ? │ show all commands
(node:26172) [DEP_WEBPACK_DEV_SERVER_CONSTRUCTOR] DeprecationWarning: Using 'compiler' as the first argument is deprecated. Please use 'options' as the first argument and 'compiler' as the second argument.
(node:26172) [DEP_WEBPACK_DEV_SERVER_LISTEN] DeprecationWarning: 'listen' is deprecated. Please use the async 'start' or 'startCallback' method.
ERROR in ./node_modules/expo-modules-core/build/uuid/uuid.web.js:9:8
Module not found: Can't resolve 'crypto'
   7 |   const cryptoObject =
   8 |     typeof crypto === 'undefined' || typeof crypto.randomUUID === 'undefined'
>  9 |       ? require('crypto')
     |        ^
  10 |       : crypto;
  11 |
  12 |   if (!cryptoObject?.randomUUID) {

web compiled with 1 error
```

on this page of the tutorial:

https://docs.expo.dev/tutorial/build-a-screen/

after adding and using @expo/vector-icons:
```
npx expo install @expo/vector-icons
```

**Comment by SerSerch** [comment]
the same in web
`"expo": "~50.0.5"`

**Comment by Josema** [comment]
Not possible tu build for web after upgrading to `"expo": "~50.0.5"`

```
$ npm run build

> conkis-app@1.1.17 build
> GENERATE_SOURCEMAP=true expo export:web

Exporting with Webpack...
Failed to compile
ModuleNotFoundError: Module not found: Error: Can't resolve 'crypto' in '/home/enzo/projects/conkis/conkis-app/node_modules/expo-modules-core/build/uuid'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }
ModuleNotFoundError: Module not found: Error: Can't resolve 'crypto' in '/home/enzo/projects/conkis/conkis-app/node_modules/expo-modules-core/build/uuid'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }
    at /home/enzo/projects/conkis/conkis-app/node_modules/webpack/lib/Compilation.js:2022:28
    at /home/enzo/projects/conkis/conkis-app/node_modules/webpack/lib/NormalModuleFactory.js:817:13
    at eval (eval at create (/home/enzo/projects/conkis/conkis-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/enzo/projects/conkis/conkis-app/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/home/enzo/projects/conkis/conkis-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/enzo/projects/conkis/conkis-app/node_modules/webpack/lib/NormalModuleFactory.js:448:22
    at /home/enzo/projects/conkis/conkis-app/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /home/enzo/projects/conkis/conkis-app/node_modules/webpack/lib/NormalModuleFactory.js:689:25
    at /home/enzo/projects/conkis/conkis-app/node_modules/webpack/lib/NormalModuleFactory.js:893:8
    at /home/enzo/projects/conkis/conkis-app/node_modules/webpack/lib/NormalModuleFactory.js:1013:5
    at /home/enzo/projects/conkis/conkis-app/node_modules/neo-async/async.js:6883:13
    at /home/enzo/projects/conkis/conkis-app/node_modules/webpack/lib/NormalModuleFactory.js:996:45
    at finishWithoutResolve (/home/enzo/projects/conkis/conkis-app/node_modules/enhanced-resolve/lib/Resolver.js:372:11)
    at /home/enzo/projects/conkis/conkis-app/node_modules/enhanced-resolve/lib/Resolver.js:461:15
    at /home/enzo/projects/conkis/conkis-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/enzo/projects/conkis/conkis-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/enzo/projects/conkis/conkis-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/enzo/projects/conkis/conkis-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/enzo/projects/conkis/conkis-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:89:43
    at /home/enzo/projects/conkis/conkis-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/enzo/projects/conkis/conkis-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/enzo/projects/conkis/conkis-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/enzo/projects/conkis/conkis-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/enzo/projects/conkis/conkis-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/enzo/projects/conkis/conkis-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/enzo/projects/conkis/conkis-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/enzo/projects/conkis/conkis-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/enzo/projects/conkis/conkis-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:89:43
    at /home/enzo/projects/conkis/conkis-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/enzo/projects/conkis/conkis-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/enzo/projects/conkis/conkis-app/node_modules/enhanced-resolve/lib/Resolver.js:519:5
    at eval (eval at create (/home/enzo/projects/conkis/conkis-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/enzo/projects/conkis/conkis-app/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:41:15
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    ```

**Comment by SerSerch** [comment]
new version the same in web
```
npx expo install --check
npx expo-doctor

Didn't find any issues with the project!

"expo": "~50.0.6",
```

**Comment by Kimuel** [comment]
Maybe this might help...

[https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5#answer-65556946](https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5#answer-65556946)

**Comment by Kimuel** [comment]
Maybe this might help...

[https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5#answer-65556946](https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5#answer-65556946)

**Comment by sherlock003** [comment]
Maybe this might help...

[https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5#answer-65556946](https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5#answer-65556946)

**Comment by qfdk** [comment]
The same problem in web
```json
"expo": "^50.0.6"
```

### The solution works for me

#### 1. Install the expo-crypto module:

Use yarn to add `expo-crypto` to your project:
```bash
yarn add expo-crypto
```

#### 2. Create and configure `webpack.config.js`:

In the root directory of your project, create a file named `webpack.config.js`. This file will be used to customize the Webpack configuration for Expo. Add the following code to this file to ensure expo-crypto is used as a fallback for the crypto module in the web environment:

```js
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function (env, argv) {
    const config = await createExpoWebpackConfigAsync(env, argv);
    config.resolve.fallback = {
        ...config.resolve.fallback,
        crypto: require.resolve('expo-crypto'),
    };
    return config;
};
```

#### 3. Restart your project:
Save all changes and restart your project. This should resolve the compilation issue related to the crypto module when running on a web platform.


Happy coding :)

**Comment by fremontmj** [comment]
In my case, when running in browser, I get the "can't resolve crypto"  but my app runs. _However_, it doesn't reload at all when I modify my code.

@qfdk's solution solves this problem. Thanks!

**Comment by SerSerch** [comment]
`expo-crypto` with `@expo/webpack-config`

Bundle with webpack

Deprecated: In SDK 50 and above, Expo Webpack has been deprecated in favor of [Expo Router](https://docs.expo.dev/router/introduction). Learn how to [migrate from Expo Webpack to Expo Router](https://docs.expo.dev/router/migrate/from-expo-webpack).

**Comment by SerSerch** [comment]
migrate web to SDK 50

```
npx expo install --check
npx expo-doctor
```

1) remove `@expo/webpack-config`
2) if you have `expo.web.bundler` in [`app.json`](https://docs.expo.dev/archive/customizing-webpack/) - remove it
3) add [@expo/metro-runtime](https://docs.expo.dev/workflow/web/#getting-started)
4) create file `.env`
5) add in [env](https://docs.expo.dev/guides/monorepos/#change-default-entrypoint) `EXPO_USE_METRO_WORKSPACE_ROOT=1`

**Comment by Bi0max** [comment]
> Related #18415 -- there are a few issues with the native implementation that make this feature hard to support. You could potentially use a tunnel to workaround in the meantime.
> 
> @acdoussan you will need to configure webpack to shim Node.js builtins when bundling for the browser. This can be done using the `externals` config option.

@EvanBacon, could you please tell how to use a tunnel? Can I redirect locally from http://localhost to https://localhost using some npm library?

**Comment by 0reo** [comment]
> > Related #18415 -- there are a few issues with the native implementation that make this feature hard to support. You could potentially use a tunnel to workaround in the meantime.
> > @acdoussan you will need to configure webpack to shim Node.js builtins when bundling for the browser. This can be done using the `externals` config option.
> 
> In my opinion, HTTPS for localhost is still an important feature. Because many things, like cookies still do not work on HTTP localhost.
> 
> @EvanBacon, could you please tell how to use a tunnel? Can I redirect locally from http://localhost to https://localhost using some npm library?

npm install @expo/ngrok^4.1.0
npx expo --tunnle 

will generate a url for you with https

**Comment by JPStrydom** [comment]
> migrate web to SDK 50
> 
> ```
> npx expo install --check
> npx expo-doctor
> ```
> 
> 1. remove `@expo/webpack-config`
> 2. if you have `expo.web.bundler` in [`app.json`](https://docs.expo.dev/archive/customizing-webpack/) - remove it
> 3. add [@expo/metro-runtime](https://docs.expo.dev/workflow/web/#getting-started)
> 4. if you have monorepo [like me](https://github.com/mobile-blockly/react-blockly/tree/main/examples/native-example) - create file `.env`
> 5. add in [.env](https://docs.expo.dev/guides/monorepos/#change-default-entrypoint) `EXPO_USE_METRO_WORKSPACE_ROOT=1`

This is fine if you have a simple project, but if you have a mature project with lot's of custom web and server logic in `web/index.html`, `web/serve.json`, and `webpack.config.js` and lots of existing screens and navigation logic, switching out one's entire navigation framework and moving to the navigation file/folder structure Expo Router requires, is not a simple task. 

Is it not possible for expo to support React Navigation for the web metro builder?

**Comment by nandorojo** [comment]
I tried all the suggestions here, but I'm still getting this on SDK 51. Have people solved this with the metro workaround?

**Comment by Leonardocezar** [comment]
access the patch package [here](https://www.npmjs.com/package/patch-package) and follow instructions to install

access the file ./node_modules/expo-modules-core/build/uuid/uuid.web.js within your project
change from
`? require('crypto')`
to
` ? requireDynamic('crypto')`

and save the file.

run the command
yarn patch-package expo-modules-core
rm -rf node_modules && yarn
run the project and the error should be fixed

**Comment by iranaahsanali** [comment]
I am facing same issue!

**Comment by thealonemusk** [comment]
this issue is still persistent for even after trying all the above methods.

**Comment by BoTime** [comment]
> > > Related #18415 -- there are a few issues with the native implementation that make this feature hard to support. You could potentially use a tunnel to workaround in the meantime.
> > > @acdoussan you will need to configure webpack to shim Node.js builtins when bundling for the browser. This can be done using the `externals` config option.
> > 
> > 
> > In my opinion, HTTPS for localhost is still an important feature. Because many things, like cookies still do not work on HTTP localhost.
> > @EvanBacon, could you please tell how to use a tunnel? Can I redirect locally from http://localhost to https://localhost using some npm library?
> 
> ```
> npm install @expo/ngrok^4.1.0
> npx expo --tunnle 
> ```
> 
> will generate a url for you with https

The solution from @0reo worked for me. My Expo version is "~51.0.25".

Commands I used:
```powershell
npm i --save-dev @expo/ngrok
npx expo --tunnel
``` 
Choose "Web", then a URL in the format of "https://******.exp.direct/" will be launched in the browser.

**Comment by claudio-park-here** [comment]
Same for me. When I run
npx expo start --web --https it runs a regular http localhost

I think https localhost is strictly necessary since many different scenarios needs an https.
For example we embed the app in MsTeams and it uses iframe and the url must to be an iframe.

I created a proxy with express in order to serve this https but still there are some case where the proxy doesn't work properly when we perform some redirect to perform an OAuth2 url redirect.

Anyway if it can help someone this is the script to run the proxy that connect to the metro http://localhost:8081
you need to create your SSL localhost certificate for your machine in order to run it properly
You will find some instructions here https://stackoverflow.com/a/60516812/694577

```
const https = require('https');
const fs = require('fs');
const express = require('express');
const { createProxyMiddleware } = require('http-proxy-middleware');

const certPath = './certs/localhost.crt';
const keyPath = './certs/localhost.key';

// Check if the certificate and key files exist
if (!fs.existsSync(certPath) || !fs.existsSync(keyPath)) {
  console.error('Files not found. Please generate an SSL certificate for localhost and place it in the cert directory of the project.');
  process.exit(1);
}


const app = express();

// Configura il proxy
app.use('/', createProxyMiddleware({
  target: 'http://localhost:8081',
  changeOrigin: true,
  secure: false,
  ws: true
}));

const options = {
  key: fs.readFileSync(keyPath),
  cert: fs.readFileSync(certPath),
};

const server = https.createServer(options, app);
server.listen(19006, () => {
  console.log('Secure server on https://localhost:19006');
});

```

**Comment by claudioviola** [comment]
Same for me. When I run
npx expo start --web --https it runs a regular http localhost

I think https localhost is strictly necessary since many different scenarios needs an https.
For example we embed the app in MsTeams and it uses iframe and the url must to be an iframe.

I created a proxy with express in order to serve this https but still there are some case where the proxy doesn't work properly when we perform some redirect to perform an OAuth2 url redirect.

Anyway if it can help someone this is the script to run the proxy that connect to the metro http://localhost:8081
you need to create your SSL localhost certificate for your machine in order to run it properly
You will find some instructions here https://stackoverflow.com/a/60516812/694577

const https = require('https');
const fs = require('fs');
const express = require('express');
const { createProxyMiddleware } = require('http-proxy-middleware');

const certPath = './certs/localhost.crt';
const keyPath = './certs/localhost.key';

// Check if the certificate and key files exist
if (!fs.existsSync(certPath) || !fs.existsSync(keyPath)) {
  console.error('Files not found. Please generate an SSL certificate for localhost and place it in the cert directory of the project.');
  process.exit(1);
}


const app = express();

// Configura il proxy
app.use('/', createProxyMiddleware({
  target: 'http://localhost:8081',
  changeOrigin: true,
  secure: false,
  ws: true
}));

const options = {
  key: fs.readFileSync(keyPath),
  cert: fs.readFileSync(certPath),
};

const server = https.createServer(options, app);
server.listen(19006, () => {
  console.log('Secure server on https://localhost:19006');
});

**Comment by davidjbng** [comment]
Here is my current workaround using [Caddy](https://caddyserver.com/docs/) to proxy the dev server via https:

## 1. Setup Caddy

### Create a Caddyfile
```Caddyfile
https://localhost:8082 {
	tls internal
	reverse_proxy localhost:8081
}
```
You can extend the Caddyfile to forward other APIs on localhost your app needs to connect to which required when running when running on https.

### Run the Proxy with 

```sh
caddy run --config Caddyfile
```

## 2. Patching Expo Devtools

In my case I had to patch expo devtools to use `wss` instead of `ws` when connecting to from https:
```patch
diff --git a/node_modules/expo/src/devtools/DevToolsPluginClient.ts b/node_modules/expo/src/devtools/DevToolsPluginClient.ts
index c19962b..6a72587 100644
--- a/node_modules/expo/src/devtools/DevToolsPluginClient.ts
+++ b/node_modules/expo/src/devtools/DevToolsPluginClient.ts
@@ -113,7 +113,8 @@ export abstract class DevToolsPluginClient {
   protected connectAsync(): Promise<WebSocket> {
     return new Promise((resolve, reject) => {
       const endpoint = 'expo-dev-plugins/broadcast';
-      const ws = new WebSocketWithReconnect(`ws://${this.connectionInfo.devServer}/${endpoint}`, {
+      const wsProtocol = this.connectionInfo.sender === 'browser' && window.location.protocol === 'https:' ? 'wss' : 'ws';
+      const ws = new WebSocketWithReconnect(`${wsProtocol}://${this.connectionInfo.devServer}/${endpoint}`, {
         binaryType: this.options?.websocketBinaryType,
         onError: (e: unknown) => {
           if (e instanceof Error) {
```

**Comment by EvanBacon** [comment]
The `--https` flag has been deprecated in favor of our free tunneling service. This is reflected in the docs for more information on how to use it https://docs.expo.dev/more/expo-cli/#tunneling

We may add back insecure https support in the future but it'll require some pretty big changes to Expo Go, dev clients, and React Native code-loading.
