### ISSUE TITLE
[SDK 50] expo-file-system - `uploadAsync` Error: Unable to upload the file (cancelled)

### ISSUE THREAD

**Issue by Jackman3005** [expo/expo#26750]
I am getting this error when we try to upgrade to Expo 50. Nothing I change seems to alter the effect. I investigated a lot of the commits in `expo-file-system` in the last few months and didn't see anything suspicious that caught my attention. I'm pretty stumped as to what could be happening here...

Here is what I see when I print the error thrown by `uploadAsync`:
```
[Error: Unable to upload the file: 'Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://api.cloudinary.com/v1_1/questmate-testing/auto/upload, NSErrorFailingURLKey=https://api.cloudinary.com/v1_1/questmate-testing/auto/upload, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "BackgroundUploadTask <8403A4A5-8290-4773-A91B-58832FF985F0>.<12>",
    "LocalUploadTask <8403A4A5-8290-4773-A91B-58832FF985F0>.<12>"
), _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundUploadTask <8403A4A5-8290-4773-A91B-58832FF985F0>.<12>, NSLocalizedDescription=cancelled}']
```

If I stringify the error it prints:
```
{"code":"ERR_FILESYSTEM_CANNOT_UPLOAD"}
```

Our call to `uploadAsync` looks like the following (where parameters is a `Record<string, string>`):
```typescript
const uploadResult = await uploadAsync(url, mediaItem.uri, {
    httpMethod: "POST",
    sessionType: FileSystemSessionType.BACKGROUND,
    uploadType: FileSystemUploadType.MULTIPART,
    fieldName: "file",
    parameters,
});
```

We double checked the config we pass everything looks good. Plus we did not change any code in this area during the upgrade from Expo 49 to Expo 50.

We are using `"expo-file-system": "16.0.5"`

_Originally posted by @Jackman3005 in https://github.com/expo/expo/issues/26508#issuecomment-1913536491_

**Comment by younes0** [comment]
Note that this issue occurs only with `FileSystemUploadType.MULTIPART` option which should be the most used one (multer.js doesn't support binary uploads).

**Comment by Jackman3005** [comment]
I tried downgrading to `"expo-file-system": "15.4.3"` which is the version we were using before upgrading to Expo 50. But it did not compile for the following reason. [Looks like references to `bundleAssets` were removed in `16.0.0`](https://github.com/expo/expo/blob/main/packages/expo-file-system/CHANGELOG.md#1600--2023-12-12) so we will try that version and see if there is any effect on the cancelled error.

```
Compiling expo-file-system Pods/EXFileSystem » NSData+EXFileSystem.m

› Compiling expo-file-system Pods/EXFileSystem » EXTaskHandlersManager.m

› Compiling expo-file-system Pods/EXFileSystem » EXSessionUploadTaskDelegate.m

› Compiling expo-file-system Pods/EXFileSystem » EXSessionTaskDispatcher.m

› Compiling expo-file-system Pods/EXFileSystem » EXSessionTaskDelegate.m

› Compiling expo-file-system Pods/EXFileSystem » EXSessionResumableDownloadTaskDelegate.m

› Compiling expo-file-system Pods/EXFileSystem » EXSessionHandler.m

› Compiling expo-file-system Pods/EXFileSystem » EXSessionDownloadTaskDelegate.m

› Compiling expo-file-system Pods/EXFileSystem » EXSessionCancelableUploadTaskDelegate.m

› Compiling expo-file-system Pods/EXFileSystem » EXFileSystemLocalFileHandler.m


⚠️  (../../../../../ios/EXFileSystem/EXFileSystem.h:23:49)

- (NSString *)generatePathInDirectory:(NSString *)directory withExtension:(NSString *)extension;
                                                ^ pointer is missing a nullability type specifier [-Wnullability-completeness]

› Compiling expo-file-system Pods/EXFileSystem » EXFileSystemAssetLibraryHandler.m

› Compiling expo-file-system Pods/EXFileSystem » EXFileSystem.m

› Compiling expo-file-system Pods/EXFileSystem » EXFileSystem-dummy.m

› Compiling expo-file-system Pods/EXFileSystem » EXFilePermissionModule.m


❌  (/Users/expo/workingdir/build/app/node_modules/expo-file-system/ios/EXFileSystem/EXFilePermissionModule.m:42:42)

  40 |   }
  41 | 
> 42 |   NSString *bundleDirectory = fileSystem.bundleDirectory;
     |                                          ^ property 'bundleDirectory' not found on object of type '__strong id<EXFileSystemInterface>'
  43 |   if (bundleDirectory != nil && [path hasPrefix:[bundleDirectory stringByAppendingString:@"/"]]) {
  44 |     return EXFileSystemPermissionRead;
  45 |   }

› Compiling expo-file-system Pods/EXFileSystem » NSData+EXFileSystem.m

› Compiling expo-file-system Pods/EXFileSystem » EXTaskHandlersManager.m

⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » QuestmateDev/QuestmateDev » Build Phases » 'Upload Debug Symbols to Sentry'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script

▸ ** BUILD FAILED **

▸ The following build commands failed:

▸ 	CompileC /Users/expo/workingdir/build/app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/EXFileSystem.build/Objects-normal/x86_64/EXFilePermissionModule.o /Users/expo/workingdir/build/app/node_modules/expo-file-system/ios/EXFileSystem/EXFilePermissionModule.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'EXFileSystem' from project 'Pods')

▸ (1 failure)

** BUILD FAILED **

The following build commands failed:

	CompileC /Users/expo/workingdir/build/app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/EXFileSystem.build/Objects-normal/x86_64/EXFilePermissionModule.o /Users/expo/workingdir/build/app/node_modules/expo-file-system/ios/EXFileSystem/EXFilePermissionModule.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'EXFileSystem' from project 'Pods')

(1 failure)

Exit status: 65
```

**Comment by Jackman3005** [comment]
We are still receiving the same error when using `"expo-file-system": "16.0.0"`.

**Comment by remziz4** [comment]
Getting this same error after upgrading to Expo 50

**Comment by brentvatne** [comment]
> I tried downgrading to `"expo-file-system": "15.4.3"` which is the version we were using before upgrading to Expo 50. But it did not compile for the following reason. [Looks like references to `bundleAssets` were removed in `16.0.0`](https://github.com/expo/expo/blob/main/packages/expo-file-system/CHANGELOG.md#1600--2023-12-12)

the `bundledAssets` change would be unrelated - this was a very Expo-specific concept that was only related to "classic builds", [which were sunset in 2023](https://blog.expo.dev/turtle-goes-out-to-sea-d334db2a6b60)

**Comment by brentvatne** [comment]
@Jackman3005 @remziz4 @younes0 - would one of you be able to provide a minimal reproducible example please?

**Comment by RRaideRR** [comment]
Hey @brentvatne ,

I made a minimal reproducible example. 

However, I'm not quite sure if its the exact same problem because I do not receive the same error message. [You can check it here.](https://github.com/expo/expo/issues/26789)

**Comment by ApluUalberta** [comment]
Some additional info that might be helpful:

This is an issue that only pertains to iOS at the moment as the Android upload seems to work.

iOS file uri:
```
"uri": "file:///var/mobile/Containers/Data/Application/80CB0E0A-957D-4A4C-A1E3-86391F0773A8/Library/Caches/ExponentExperienceData/<companyname>/<appname>/ImagePicker/E6F2CB1C-8E2E-4650-99C2-456D9E9BC191.jpg"
```
Android file uri (Working totally fine):

```
"uri": "file:///data/user/0/com.heyauto.glovebox/cache/ImagePicker/eed7742d-b840-461e-ae42-0504037392b4.jpeg"
```

I'm not sure whether or not the uri could be affecting the upload of the ios file, but this may be helpful! I"m not sure if the parsing of the iOS file picker in expo 49 would yield a different uri and therefore a different result.

**Comment by Jackman3005** [comment]
Yeah, good thinking @ApluUalberta. For some reason I get the impression that it may not be `expo-file-system` being the root cause of the issue.

**Comment by ApluUalberta** [comment]
> Some additional info that might be helpful:
> 
> This is an issue that only pertains to iOS at the moment as the Android upload seems to work.
> 
> iOS file uri:
> 
> ```
> "uri": "file:///var/mobile/Containers/Data/Application/80CB0E0A-957D-4A4C-A1E3-86391F0773A8/Library/Caches/ExponentExperienceData/<companyname>/<appname>/ImagePicker/E6F2CB1C-8E2E-4650-99C2-456D9E9BC191.jpg"
> ```
> 
> Android file uri (Working totally fine):
> 
> ```
> "uri": "file:///data/user/0/com.heyauto.glovebox/cache/ImagePicker/eed7742d-b840-461e-ae42-0504037392b4.jpeg"
> ```
> 
> I'm not sure whether or not the uri could be affecting the upload of the ios file, but this may be helpful! I"m not sure if the parsing of the iOS file picker in expo 49 would yield a different uri and therefore a different result.

Spotted in the community discord:
![image](https://github.com/expo/expo/assets/39037565/95119a9b-0499-48b2-945b-ed1d01174685)

This would suggest that it may not be an ios URI issue as I suggested earlier

**Comment by Jackman3005** [comment]
@brentvatne I was able to create a minimal reproduction [here](https://github.com/questmate/expo-file-system-upload-async-bug-repro). Hopefully you're able to get the same issue on your machine.

Note that this isn't exactly what we're doing in our codebase and I can't expose the parameters we usually pass with the `uploadAsync` command. However, it is showing resulting in the same error we are getting in our app, so it should be sufficient. If you get past this error and receive errors from Cloudinary, then I think those will be related to the missing parameters I mentioned.

Let me know if I can help further!

**Comment by brentvatne** [comment]
@Jackman3005 - do we need to register a cloudinary account or do any other set up here to make this work? please let us know exact steps to repro with that example

**Comment by Jackman3005** [comment]
@brentvatne Nope nope. You should be able to:
1.  Clone the repo
1.  `npm install`
1.  `npm run ios`
1.  Click "Choose an image"
1.  Choose some image
1.  (see chosen image)
1.  Click "Upload Image"
1.  View logs to see the error message shown

Here is a short video of me demonstrating this:

https://github.com/expo/expo/assets/1906988/f4905696-bb32-4e7b-800e-98012c410535

**Comment by brentvatne** [comment]
thank you @Jackman3005! this is very helpful

**Comment by AlexNodex** [comment]
> @brentvatne Nope nope. You should be able to:
> 
>     1. Clone the repo
> 
>     2. `npm install`
> 
>     3. `npm run ios`
> 
>     4. Click "Choose an image"
> 
>     5. Choose some image
> 
>     6. (see chosen image)
> 
>     7. Click "Upload Image"
> 
>     8. View logs to see the error message shown
> 
> 
> Here is a short video of me demonstrating this:
> Screen.Recording.2024-02-01.at.12.12.58.pm.mov

This is the exact same error I am receiving. The upload endpoint is not relevant, any endpoint will generate the same error.

**Comment by RRaideRR** [comment]
Has anyone found a way to work around this issue for the moment? I tried it with the normal fetch API but could not get it to work.

**Comment by younes0** [comment]
@RRaideRR 
```tsx
const _fileSystemUpload = async ({
  jwtAccessToken,
  endpoint,
  mimeType,
  params = {},
  uri,
}: {
  jwtAccessToken: string;
  endpoint: UploadEndpoint;
  mimeType?: string;
  params?: Record<string, string>;
  uri: string;
}) => {
  if (Platform.OS === "ios") {
    // WARNING: expo 50 FileSystem.uploadAsync doesn't work on iOS
    const formData = new FormData();
    const uriParts = uri.split(".");
    const fileType = uriParts[uriParts.length - 1];

    // @ts-ignore
    formData.append("file", {
      uri,
      name: `file.${fileType}`,
      type: `image/${fileType}`,
    });

    for (const param in params) {
      formData.append(param, params[param]);
    }

    return fetch(`${apiHost}/api/upload/${endpoint}`, {
      method: "POST",
      body: formData,
      headers: {
        Authorization: `Bearer ${jwtAccessToken}`,
        "Content-Type": "multipart/form-data",
      },
    });
  } else {
    return FileSystem.uploadAsync(`${apiHost}/api/upload/${endpoint}`, uri, {
      fieldName: "file",
      parameters: params,
      uploadType: FileSystem.FileSystemUploadType.MULTIPART,
      mimeType,
      headers: {
        Authorization: `Bearer ${jwtAccessToken}`,
      },
    });
  }
};
```

**Comment by remziz4** [comment]
@alanjhughes Woo! Thanks for the quick fix.

Any idea when we can expect it in a new release?

**Comment by ApluUalberta** [comment]
> @alanjhughes Woo! Thanks for the quick fix.
> 
> Any idea when we can expect it in a new release?

As per the PR: https://github.com/expo/expo/pull/26880

![image](https://github.com/expo/expo/assets/39037565/9e0df555-ebb0-46fe-bc52-107ef0b43263)

**Comment by mcrstudio** [comment]
I am right to assume that this fix wouldn't be present in Expo Go yet, correct? I have the latest Expo SDK and the latest expo-file-system and it doesn't work on Expo Go.

**Comment by remziz4** [comment]
@mcrstudio I would imagine if you're on expo version `50.0.6` it should work regardless of Expo Go vs dev build

**Comment by brentvatne** [comment]
> I am right to assume that this fix wouldn't be present in Expo Go yet, correct? I have the latest Expo SDK and the latest expo-file-system and it doesn't work on Expo Go.

correct, we have not yet rolled out a new version of Expo Go with this change

**Comment by AlexNodex** [comment]
The issue is fixed on 50.0.6Update expo and it should be fine On 8 Feb 2024, at 17:50, MCR Studio ***@***.***> wrote:﻿
I am right to assume that this fix wouldn't be present in Expo Go yet, correct? I have the latest Expo SDK and the latest expo-file-system and it doesn't work on Expo Go.

**Comment by hamzawii** [comment]
Can someone confirm that the uploadAsync works well on iOS? For me it doesn't work on version 51.0.8 ?

Here is my code : 

```
public static async uploadVideoInBackground(file: ImagePicker.ImagePickerAsset) {

        console.log("******** uploadVideoInBackground started")

        //get signedUrl from GCP
        const signedURL = await FileUploader.getResumableUploadSession(file, "video")
        // example url : https://storage.googleapis.com/thewide-video-dev/video/9aa9ca64-01d3-44c8-8c03-bc00f06790f0.mp4?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=...

        console.log({ signedURL })
        console.log(file.uri)

        const uploadTask = FileSystem.createUploadTask(signedURL, file.uri, {
            fieldName: file.fileName ?? 'file',
            httpMethod: 'PUT',
            uploadType: FileSystem.FileSystemUploadType.BINARY_CONTENT,
            headers: {
                "Content-Type": file.mimeType ?? 'video/mp4',
                origin: APP_ORIGIN
            }
        }, ({ totalBytesSent, totalBytesExpectedToSend }) => {
            const progress = parseFloat((totalBytesSent / (totalBytesExpectedToSend || 1)).toFixed(2));
            console.log(progress)
        });

        uploadTask.uploadAsync().then(() => {
            Toast.show("Upload done", {
                duration: Toast.durations.LONG,
            });
        }).catch((err) => {
            console.log(JSON.stringify(err))
            Toast.show("Error uploading the video file", {
                duration: Toast.durations.LONG,
            });
        });
    }
```

This code works well on Android but on IOS i get this error : 
`{"code":"ERR_FILESYSTEM_CANNOT_UPLOAD"}`

And full error :
```
[Error: Unable to upload the file: 'Error Domain=NSPOSIXErrorDomain Code=40 "Message too long" UserInfo={_NSURLErrorFailingURLSessionTaskErrorKey=BackgroundUploadTask <030030DF-ACC8-438D-83B7-F1B7B54394D3>.<1>, _kCFStreamErrorDomainKey=1, NSErrorPeerAddressKey={length = 28, bytes = 0x1c1e01bb 00000000 2a001450 40060808 ... 0000201b 00000000 }, _kCFStreamErrorCodeKey=40, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "BackgroundUploadTask <030030DF-ACC8-438D-83B7-F1B7B54394D3>.<1>",
    "LocalUploadTask <030030DF-ACC8-438D-83B7-F1B7B54394D3>.<1>"
)}']
```

**Comment by LuanGabrielFauthDavila** [comment]
This upload error continues to occur at EXPO 51 with `"expo-file-system": "~17.0.1"`.

Can anyone explain to me if it has been resolved?

**Comment by juanzero000** [comment]
This error is still happening on "expo": "~51.0.38", and "expo-file-system": "~17.0.1". Any idea when it will be definitely fixed?

**Comment by LuanGabrielFauthDavila** [comment]
@juanzero000 to resolve this i create a new hook.

```
export interface IFile {
  uuid: string;
  originalname: string;
  filename: string;
  mimetype: string;
  size: number;
  permanent: boolean;
  url: string;
  created_at: Date;
}

//SERVICES
import { api } from "@/services/api";


export function useStorage() {
  async function submitFile(
    file_uri: string, 
    token: string,
    filename?: string,
    type: "DOCUMENT" | "OTHER" = "OTHER"
  ) {
    const file_name = type == "DOCUMENT" ? (
      filename
    ) : (
      file_uri.split('/')[file_uri.split('/').length - 1]
    )
    const file_data = await (await fetch(file_uri)
    .then(res => res)
    .catch(err => {
      throw new Error(`HTTP error! status: ${err.response.status}`);
    })).blob()
    const file_type = file_data.type
    const form = new FormData()
    const fileAppend = {
      name: file_name,
      uri: file_uri,
      type: file_type
    }
    // @ts-ignore
    form.append('file', fileAppend)
    form.append('permanent', 'false')


    const uploaded: IFile = await api.postForm("files/", form, {
      headers: {
        "Authorization": `Bearer ${token}`
      }
    })
    .then(({ data }) => data)
    .catch(err => {
      console.error('storage upload error:', err);
      if (err.response) {
        console.log(err.response.data)
      }
      return undefined
    })
    return {
      file_name,
      uploaded
    }
  }

	return {
		submitFile
	}
}
```

**Comment by manuelmhtr** [comment]
I have a similar error:
```
[Error: Unable to upload the file: 'Error Domain=NSPOSIXErrorDomain Code=40 "Message too long" UserInfo={_NSURLErrorFailingURLSessionTaskErrorKey=BackgroundUploadTask <C0DFA51E-94A5-4EB4-8D71-E24BBB671270>.<1>, _kCFStreamErrorDomainKey=1, NSErrorPeerAddressKey={length = 16, bytes = 0x100201bbacd9039b0000000000000000}, _kCFStreamErrorCodeKey=40, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "BackgroundUploadTask <C0DFA51E-94A5-4EB4-8D71-E24BBB671270>.<1>",
    "LocalUploadTask <C0DFA51E-94A5-4EB4-8D71-E24BBB671270>.<1>"
)}']
```
However it happens only in the simulator (iOS), it works fine in the device.
