### ISSUE TITLE
`Location.startLocationUpdatesAsync` fails on Android because of foreground permissions not found in the manifest

### ISSUE THREAD

**Issue by choutianxius** [expo/expo#28767]
### Minimal reproducible example

https://github.com/choutianxius/test-background-location

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

`startLocationUpdatesAsync` fails after upgrading to Expo SDK 51. When calling this method, the following error is thrown:

Error: Call to function 'ExpoLocation.startLocationUpdatesAsync' has been rejected.
-> Caused by: Couldn't start the foreground service. Foreground service permissions were not found in the manifest

The example is created with `npx create-expo-app@latest`. I have followed the example code snippet in the `expo-task-manager` [doc](https://docs.expo.dev/versions/latest/sdk/task-manager/#example) and added a button to start the background location service in the home page. and my `app.json` file is only modified to include

~~~json
      [
        "expo-location",
        {
          "locationAlwaysAndWhenInUsePermission": "Allow $(PRODUCT_NAME) to use your location.",
          "isAndroidBackgroundLocationEnabled": true,
          "isAndroidForegroundServiceEnabled": true
        }
      ]
~~~

in the `expo.plugins` section.

Perhaps this is something related to  #26846

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 4.1.0 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.4.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-231.9392.1.2311.11330709
    npmPackages:
      expo: ~51.0.2 => 51.0.2 
      expo-router: ~3.5.11 => 3.5.11 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.10 => 0.19.11
    Expo Workflow: managed

### Expo Doctor Diagnostics

WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by TechhDan** [comment]
I updated my SDK from 50 to 51 and I am now having the same issue. I was not having this issue previous to the update. I did 

```
npm install expo@latest 
npm expo install --fix
````

**Comment by choutianxius** [comment]
Hi for those experiencing the same issue, I fixed my problem by downgrading Expo SDK to 50.0.18 and using the development build. I used JDK 17. Here are some related package versions:

~~~
    "expo": "^50.0.18",
    "expo-dev-client": "~3.3.11",
    "expo-location": "^16",
    "expo-task-manager": "~11.7.3",
    "react-native": "0.73.6",
~~~

Still, as mentioned by @shuo-hiwintech , the `startLocationUpdatesAsync` method won't work with Expo SDK 51 even with the development build, so this issue is probably not resolved for the latest versions of related packages (`expo`, `expo-location` and `expo-task-manager`).

**Comment by brentvatne** [comment]
@shuo-hiwintech - make sure to use the `isAndroidForegroundServiceEnabled` property in the config plugin: https://docs.expo.dev/versions/latest/sdk/location/#configurable-properties

**Comment by TechhDan** [comment]
@brentvatne I'm having the same issue as @shuo-hiwintech. Even after moving from expo go to a  development build my ```startLocationUpdatesAsync``` is no longer working. I know it was working on SDK 50. The documentation said the need to add ```isAndroidForegroundServiceEnabled``` is not needed if ```isAndroidBackgroundLocationEnabled``` is set to true which did work as stated on SDK 50.

On SDK 51 this functionality broke and I also tried adding both flags to my app.json ```isAndroidBackgroundLocationEnabled, isAndroidForegroundServiceEnabled``` and it still does not work.

**Comment by choutianxius** [comment]
> @shuo-hiwintech - make sure to use the `isAndroidForegroundServiceEnabled` property in the config plugin: https://docs.expo.dev/versions/latest/sdk/location/#configurable-properties
> 
> @choutianxius - did you enable the `isAndroidForegroundServiceEnabled` field? it looks like you did in the original post. can you run `npx expo prebuild -p android` and share your AndroidManifest? i've verified on a new project that it adds the permission as expected.

Yes, I kept the `app.json` contents and the permissions seem to be successfully created.

```json
{
  "expo": {
    "android": {
      "permissions": [
        "android.permission.ACCESS_COARSE_LOCATION",
        "android.permission.ACCESS_FINE_LOCATION",
        "android.permission.ACCESS_BACKGROUND_LOCATION",
        "android.permission.FOREGROUND_SERVICE",
        "android.permission.FOREGROUND_SERVICE_LOCATION"
      ]
    },
    "plugins": [
      [
        "expo-location",
        {
          "locationAlwaysAndWhenInUsePermission": "Allow $(PRODUCT_NAME) to use your location.",
          "isAndroidBackgroundLocationEnabled": true,
          "isAndroidForegroundServiceEnabled": true
        }
      ]
    ]
  }
}
```

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
  <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
  <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
  <uses-permission android:name="android.permission.FOREGROUND_SERVICE_LOCATION"/>
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
  <uses-permission android:name="android.permission.VIBRATE"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
  <queries>
    <intent>
      <action android:name="android.intent.action.VIEW"/>
      <category android:name="android.intent.category.BROWSABLE"/>
      <data android:scheme="https"/>
    </intent>
  </queries>
  <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="true" android:theme="@style/AppTheme">
    <meta-data android:name="expo.modules.updates.ENABLED" android:value="false"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_CHECK_ON_LAUNCH" android:value="ALWAYS"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_LAUNCH_WAIT_MS" android:value="0"/>
    <activity android:name=".MainActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|screenLayout|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize" android:theme="@style/Theme.App.SplashScreen" android:exported="true" android:screenOrientation="portrait">
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="myapp"/>
        <data android:scheme="com.anonymous.testbackgroundlocation"/>
      </intent-filter>
    </activity>
    <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" android:exported="false"/>
  </application>
</manifest>
```

The task seems to be correctly registered, as can be verified with `TaskManager.getRegisteredTasksAsync`. The problem is the callback registered in `TaskManager.defineTask` never receives data. With `expo` 50.0.18, `expo-location` 16.5.5 and `expo-task-manager` 11.7.3, the location data are indeed received.

**Comment by shuo-hiwintech** [comment]
> > @shuo-hiwintech - make sure to use the `isAndroidForegroundServiceEnabled` property in the config plugin: https://docs.expo.dev/versions/latest/sdk/location/#configurable-properties
> > @choutianxius - did you enable the `isAndroidForegroundServiceEnabled` field? it looks like you did in the original post. can you run `npx expo prebuild -p android` and share your AndroidManifest? i've verified on a new project that it adds the permission as expected.
> 
> Yes, I kept the `app.json` contents and the permissions seem to be successfully created.
> 
> ```json
> {
>   "expo": {
>     "android": {
>       "permissions": [
>         "android.permission.ACCESS_COARSE_LOCATION",
>         "android.permission.ACCESS_FINE_LOCATION",
>         "android.permission.ACCESS_BACKGROUND_LOCATION",
>         "android.permission.FOREGROUND_SERVICE",
>         "android.permission.FOREGROUND_SERVICE_LOCATION"
>       ]
>     },
>     "plugins": [
>       [
>         "expo-location",
>         {
>           "locationAlwaysAndWhenInUsePermission": "Allow $(PRODUCT_NAME) to use your location.",
>           "isAndroidBackgroundLocationEnabled": true,
>           "isAndroidForegroundServiceEnabled": true
>         }
>       ]
>     ]
>   }
> }
> ```
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android">
>   <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
>   <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
>   <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
>   <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
>   <uses-permission android:name="android.permission.FOREGROUND_SERVICE_LOCATION"/>
>   <uses-permission android:name="android.permission.INTERNET"/>
>   <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
>   <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
>   <uses-permission android:name="android.permission.VIBRATE"/>
>   <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
>   <queries>
>     <intent>
>       <action android:name="android.intent.action.VIEW"/>
>       <category android:name="android.intent.category.BROWSABLE"/>
>       <data android:scheme="https"/>
>     </intent>
>   </queries>
>   <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="true" android:theme="@style/AppTheme">
>     <meta-data android:name="expo.modules.updates.ENABLED" android:value="false"/>
>     <meta-data android:name="expo.modules.updates.EXPO_UPDATES_CHECK_ON_LAUNCH" android:value="ALWAYS"/>
>     <meta-data android:name="expo.modules.updates.EXPO_UPDATES_LAUNCH_WAIT_MS" android:value="0"/>
>     <activity android:name=".MainActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|screenLayout|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize" android:theme="@style/Theme.App.SplashScreen" android:exported="true" android:screenOrientation="portrait">
>       <intent-filter>
>         <action android:name="android.intent.action.MAIN"/>
>         <category android:name="android.intent.category.LAUNCHER"/>
>       </intent-filter>
>       <intent-filter>
>         <action android:name="android.intent.action.VIEW"/>
>         <category android:name="android.intent.category.DEFAULT"/>
>         <category android:name="android.intent.category.BROWSABLE"/>
>         <data android:scheme="myapp"/>
>         <data android:scheme="com.anonymous.testbackgroundlocation"/>
>       </intent-filter>
>     </activity>
>     <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" android:exported="false"/>
>   </application>
> </manifest>
> ```
> 
> The task seems to be correctly registered, as can be verified with `TaskManager.getRegisteredTasksAsync`. The problem is the callback registered in `TaskManager.defineTask` never receives data. With `expo` 50.0.18, `expo-location` 16.5.5 and `expo-task-manager` 11.7.3, the location data are indeed received.

Yes, it works fine after adding permissions in AndroidManifest.xml!

But on Android I don't get the data from the TaskManager.defineTask callback, whereas on IOS I get the information from the TaskManager.defineTask callback. (initialization phase)

So tomorrow I will try to change the location on foot to test if the location can be updated in real time.

Do I still need to use Location.watchPositionAsync if I want to receive real-time location updates in both the foreground and background?

**Comment by tknuts** [comment]
Why is this issue closed? I'm having issues in my production app. The `Location.startLocationUpdatesAsync`, is never returning on execution.

**Comment by santibernas** [comment]
> Why is this issue closed? I'm having issues in my production app. The `Location.startLocationUpdatesAsync`, is never returning on execution.

I'm also having issues with my production app. I'm thinking of downgrading my app to the previous SDK, as it worked just fine, and wait for this to be resolved.

**Comment by brentvatne** [comment]
@tknuts - the issue is closed because the subject line of the issue is resolved / it was never actually an issue, as far as i know. "Location.startLocationUpdatesAsync fails on Android because of foreground permissions not found in the manifest" - if you are seeing this exact error message then you need to ensure `isAndroidForegroundServiceEnabled` is set in the config plugin, or you have added the appropriate permissions to your AndroidManifest.xml manually.

@santibernas - can you create a new issue with a minimal reproducible example?

**Comment by santibernas** [comment]
@brentvatne - I just created a basic project using Expo 51 so you can check. I have only tested on android devices. 
The implementation is pretty similar to what I use in my production app and if you check out the service is being started as the permanent notification is present in the notifications bar. But the task defined is never called.

Link for the sample repo [https://github.com/santibernas/expo-issue-28767](url)

**Comment by Bashin** [comment]
I created a new issue referencing the sample posted above:
https://github.com/expo/expo/issues/28959

**Comment by federicogomezlara** [comment]
Our app is never tracking user's location in the background on production and it's heavily impacting us since it's vital to our product, the plugin is configured properly

````
"expo-location",
        {
          "locationAlwaysAndWhenInUsePermission": "For safety purposes we ask you to enable your location. We will use it to know your current position only within the facility; your position will be monitored in the background. You can revoke the access at any time through your profile settings",
          "locationWhenInUsePermission": "For safety purposes, we ask you to enable your location. We will use it to know your current position only within the facility. You can revoke access at any time through your profile settings",
          "isIosBackgroundLocationEnabled": true,
          "isAndroidBackgroundLocationEnabled": true,
          "isAndroidForegroundLocationEnabled": true
        }
 ````
 
 And the thing is we are on Expo 50, not 51 so we obviously can't roll back to 50
 ````
 "expo": "^50.0.17"
 "expo-location": "~16.5.5"
 "expo-task-manager": "~11.7.3"
 ````

**Comment by lluisandreu** [comment]
I also have this issue on my ejected Expo app using SDK 51. "Foreground service permissions were not found in the manifest". It was working fine in the latest SDKs.

**Comment by geikobogdan** [comment]
same issue

**Comment by IggsGrey** [comment]
I disabled proguard in release builds and it started to work for me.

```
...
"plugins": [
      [
        "expo-build-properties",
        {
          "android": {
            "enableProguardInReleaseBuilds": false
          }
        }
      ],
      
```

**Comment by rinaldycodes** [comment]
> I disabled proguard in release builds and it started to work for me.
> 
> ```
> ...
> "plugins": [
>       [
>         "expo-build-properties",
>         {
>           "android": {
>             "enableProguardInReleaseBuilds": false
>           }
>         }
>       ],
>       
> ```

okay , i wanna try

**Comment by div02-afk** [comment]
> > I disabled proguard in release builds and it started to work for me.
> > ```
> > ...
> > "plugins": [
> >       [
> >         "expo-build-properties",
> >         {
> >           "android": {
> >             "enableProguardInReleaseBuilds": false
> >           }
> >         }
> >       ],
> >       
> > ```
> 
> okay , i wanna try

Did it work?

**Comment by IggsGrey** [comment]
@div02-afk you might get a faster response if you try it too.

**Comment by rrdsdevelopers** [comment]
> I disabled proguard in release builds and it started to work for me.
> 
> ```
> ...
> "plugins": [
>       [
>         "expo-build-properties",
>         {
>           "android": {
>             "enableProguardInReleaseBuilds": false
>           }
>         }
>       ],
>       
> ```

I also disabled enableProguardInReleaseBuilds and it worked, thank you very much.  @IggsGrey
