### ISSUE TITLE
Unable to run on iPhone 8 after updating to Expo 51

### ISSUE THREAD

**Issue by dih7** [expo/expo#28838]
### Summary

After updating to Expo 51, my iPhone 8 is no longer accessible when running `npx expo run:ios --device`. I have checked the entire list outputted by the command, and it's not on there.

This happens on a fresh new project with prebuild, as per the reproduction below. It's still visible on the device list on v50 and in Expo Orbit, however.

The iPhone 8 is running iOS 16.7.7, which should be supported. 

### What platform(s) does this occur on?

iOS

### SDK Version

51

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.6.2 - ~/.nvm/versions/node/v21.6.2/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v21.6.2/bin/npm
      Watchman: 2024.05.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 32, 34
        Build Tools: 33.0.1, 34.0.0
        System Images: android-30 | Intel x86_64 Atom, android-34 | Google Play Intel x86_64 Atom
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.5 => 51.0.5
      expo-router: ~3.5.12 => 3.5.12
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.10 => 0.19.11
    npmGlobalPackages:
      eas-cli: 9.0.0
    Expo Workflow: bare

### iPhone 8 missing:

```
npx create-expo-app@latest expo-51 --template tabs@51
npx expo prebuild
npx expo run:ios --device
```
Output:

```
❯   iPhone 15 Plus (17.4)
    iPhone 15 Pro (17.4)
    iPhone 15 Pro Max (17.4)
    iPad Air (5th generation) (17.4)
    iPad (10th generation) (17.4)
    iPad mini (6th generation) (17.4)
    iPad Pro (11-inch) (4th generation) (17.4)
    iPad Pro (12.9-inch) (6th generation) (17.4)
    iPhone 8 (14.4)
    iPhone 8 Plus (14.4)
  ↓ iPhone 11 (14.4)
```

### iPhone 8 visible:

```
npx create-expo-app@latest expo-50 --template tabs@50
npx expo prebuild
npx expo run:ios --device
```
Output: 

```
❯   🔌 iPhone 8 (16.7.7)
    iPhone 15 Plus (17.4)
    iPhone 15 Pro (17.4)
    iPhone 15 Pro Max (17.4)
    iPad Air (5th generation) (17.4)
    iPad (10th generation) (17.4)
    iPad mini (6th generation) (17.4)
    iPad Pro (11-inch) (4th generation) (17.4)
    iPad Pro (12.9-inch) (6th generation) (17.4)
    iPhone 8 (14.4)
  ↓ iPhone 8 Plus (14.4)
```

**Comment by byCedric** [comment]
Hi @dih7, thanks for the issue report. It might be related to #28781, which we fixed but have not released yet. Can you give us the output of running `DEBUG=expo:apple-device npx expo run:ios --device`?

**Comment by brentvatne** [comment]
hey @dih7 - give expo@51.0.6 a try, that includes @byCedric's fix for #28781

**Comment by dih7** [comment]
The device now shows on Expo@51.0.6, thanks! I'll close this issue.

**Comment by NoriyukiIchijo** [comment]
The same thing still happens on Expo@51.0.8 for iPad and iPod running iOS 15.8.2.
The output to `DEBUG=expo:apple-device npx expo run:ios --device` is
expo:apple-device Unknown usbmuxd platform (needs to be added to Expo CLI): iPad
and
expo:apple-device Unknown usbmuxd platform (needs to be added to Expo CLI): iPod

I thought 15.8 is not supported anymore but [this](https://docs.expo.dev/versions/latest/#support-for-android-and-ios-versions) said minimum OS is 13.4+.
