### ISSUE TITLE
[SDK 51] [IOS] expo-file-system readAsStringAsync() is throwing 'File is not readable' error

### ISSUE THREAD

**Issue by roys000** [expo/expo#29058]
### Minimal reproducible example

[https://github.com/roys000/testapp](https://github.com/roys000/testapp)

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

No (only happens in a standalone build)

### Summary

On iOS, after updating app through `eas update`, readAsStringAsync() is throwing `Calling the 'readAsStringAsync' function has failed -> Caused by: File '/var/mobile/Containers/Data/Application/...' is not readable` (See image below). File seems to also exists in the path as checked using `getInfoAsync()`

Android is fine and the problem does not occur on Expo Go nor development build. It only happens on preview/production build. Problem also seems to have surfaced on SDK 51 as it was working fine before (as tested on SDK 49 & 50).

**Steps to replicate**

1. Copy `App.js` and `assets` directory from the minimal reproducible example into a new project
2. Setup project with eas update and create a standalone preview build for IOS (created through eas build)
3. On launch of application, you should see that it loaded the HTML file properly.
4. Under `App.js`, change the require asset from `test2.html` to `test.html`
5. Publish an update through `eas update`
6. Re-launch application on device to pull the update, the error will be shown.

**Comment by NilsBaumgartner1994** [comment]
Having the same bug.

**Comment by mahaaoo** [comment]
the same bug

**Comment by NilsBaumgartner1994** [comment]
Any updates?

**Comment by NilsBaumgartner1994** [comment]
Is it related to: https://github.com/expo/expo/issues/23288 ?

They solved it by using this?

```
export async function readAssetFile({ file }: { file: any}) {
  const [{ localUri, name, hash, type }] = await Asset.loadAsync(file);
  let uri = localUri ?? '';
  if (!uri?.startsWith('file://')) {
    if (Platform.OS === 'android') {
      uri = `${cacheDirectory}ExponentAsset-${hash}.${type}`;
    }
  }
  return readAsStringAsync(uri, { encoding: 'base64' });
}

const imgRequire = require('./assets/test-image.png');
const imgBase64 = await readAssetFile({file: imgRequire});
```

**Comment by NilsBaumgartner1994** [comment]
@roys000 seems like you are missing an `app.json` file having the plugin `expo-asset`defined with the asset folder?

**Comment by NilsBaumgartner1994** [comment]
@roys000 thanks for clarification. Since i am exceriencing the same issue, i just wanted to double check.

My "workaround" currently is to put the base64 or file content into a function...

@brentvatne +1

**Comment by douglowder** [comment]
I followed the repro instructions, and find that the file is not readable even before doing the update.

Prebuild is showing me warnings like

```
`.html` is not a supported asset type
```

So I will try this with a supported file type for the asset, and see if I can reproduce the original issue.

**Comment by douglowder** [comment]
OK after debugging, it appears that the file system utils in `expo-modules-core` do not include the application support directory when checking for file permissions of files within the app.

@roys000 @NilsBaumgartner1994 the patch below seems to work for me, could you see if this fixes the issue?

```patch
diff --git a/node_modules/expo-modules-core/ios/FileSystemUtilities/FileSystemLegacyUtilities.swift b/node_modules/expo-modules-core/ios/FileSystemUtilities/FileSystemLegacyUtilities.swift
index 5481a53..59f04b4 100644
--- a/node_modules/expo-modules-core/ios/FileSystemUtilities/FileSystemLegacyUtilities.swift
+++ b/node_modules/expo-modules-core/ios/FileSystemUtilities/FileSystemLegacyUtilities.swift
@@ -10,17 +10,22 @@ public class FileSystemLegacyUtilities: NSObject, EXInternalModule, EXFileSystem
   @objc
   public var cachesDirectory: String
 
+  @objc
+  public var applicationSupportDirectory: String
+
   var isScoped: Bool = false
 
   @objc
-  public init(documentDirectory: String, cachesDirectory: String) {
+  public init(documentDirectory: String, cachesDirectory: String, applicationSupportDirectory: String) {
     self.documentDirectory = documentDirectory
     self.cachesDirectory = cachesDirectory
+    self.applicationSupportDirectory = applicationSupportDirectory
     self.isScoped = true
 
     super.init()
     ensureDirExists(withPath: self.cachesDirectory)
     ensureDirExists(withPath: self.documentDirectory)
+    ensureDirExists(withPath: self.applicationSupportDirectory)
   }
 
   required public override init() {
@@ -30,9 +35,14 @@ public class FileSystemLegacyUtilities: NSObject, EXInternalModule, EXFileSystem
     let cachesPaths = NSSearchPathForDirectoriesInDomains(.cachesDirectory, .userDomainMask, true)
     self.cachesDirectory = cachesPaths[0]
 
+    let applicationSupportDirectoryPaths =
+    NSSearchPathForDirectoriesInDomains(.applicationSupportDirectory, .userDomainMask, true)
+    self.applicationSupportDirectory = applicationSupportDirectoryPaths[0]
+
     super.init()
     ensureDirExists(withPath: self.cachesDirectory)
     ensureDirExists(withPath: self.documentDirectory)
+    ensureDirExists(withPath: self.applicationSupportDirectory)
   }
 
   public static func exportedInterfaces() -> [Protocol] {
@@ -84,7 +94,7 @@ public class FileSystemLegacyUtilities: NSObject, EXInternalModule, EXFileSystem
 
   @objc
   public func getInternalPathPermissions(_ url: URL) -> EXFileSystemPermissionFlags {
-    let scopedDirs: [String] = [cachesDirectory, documentDirectory]
+    let scopedDirs: [String] = [cachesDirectory, documentDirectory, applicationSupportDirectory]
     let standardizedPath = url.standardized.path
     for scopedDirectory in scopedDirs {
       if standardizedPath.hasPrefix(scopedDirectory + "/") || standardizedPath == scopedDirectory {
diff --git a/node_modules/expo-modules-core/ios/Interfaces/FileSystem/EXFileSystemInterface.h b/node_modules/expo-modules-core/ios/Interfaces/FileSystem/EXFileSystemInterface.h
index 629c67e..fca4649 100644
--- a/node_modules/expo-modules-core/ios/Interfaces/FileSystem/EXFileSystemInterface.h
+++ b/node_modules/expo-modules-core/ios/Interfaces/FileSystem/EXFileSystemInterface.h
@@ -13,6 +13,7 @@ typedef NS_OPTIONS(unsigned int, EXFileSystemPermissionFlags) {
 
 @property (nonatomic, readonly) NSString *documentDirectory;
 @property (nonatomic, readonly) NSString *cachesDirectory;
+@property (nonatomic, readonly) NSString *applicationSupportDirectory;
 
 // TODO: Move permissionsForURI to EXFileSystemManagerInterface
 - (EXFileSystemPermissionFlags)permissionsForURI:(NSURL *)uri;
```

**Comment by NilsBaumgartner1994** [comment]
@douglowder thanks for the quick fix. I haven't testet it but i hope to see that fix soon in the expo core version.

**Comment by peterpme** [comment]
Hello @douglowder! We're also facing this issue at Backpack. I will try to patch your fix and release a build shortly.

I can consistently recreate this issue in our iOS production app (we have a shared slack too) so I will let you know what happens.

Thank you!

**Comment by peterpme** [comment]
Confirmed this works. Thanks!

**Comment by http-samc** [comment]
Hey quick question here. I see this is merged into main and I installed Expo 51.0.9 (latest I saw on npm). Still have there error. Is there a way I can install a nightly release to get this patch?

**Comment by kamil6311** [comment]
Still have there error with expo 51.0.10

**Comment by LukasB-DEV** [comment]
I still have the same issue. I use 
"react-native": "^0.74.2",
"expo-file-system": "^17.0.1",
"expo": "^51.0.14",

in bare workflow.

**Comment by NilsBaumgartner1994** [comment]
The problem still persists @brentvatne

**Comment by NilsBaumgartner1994** [comment]
```
"Calling the 'readAsStringAsync' function has failed\n→ Caused by: File '/var/mobile/Containers/Data/Application/F497DB31-E3D7-43C3-A4B4-7B82EAA0CDB0/Library/Application Support/.expo-internal/d95d69fa8a7dfe391399e22c0c45e203.png' is not readable"
```

**Comment by kamil6311** [comment]
https://github.com/expo/expo/issues/29759 
The issue has been mentioned here

**Comment by mluiten** [comment]
I'm still experiencing this issue when trying to load assets (using [`Asset.loadAsync`](https://docs.expo.dev/versions/latest/sdk/asset/#loadasyncmoduleid) to get the URI) -- error is the same except it it will complain about the asset directory instead of the Application Support directory. Does the asset directory need a similar patch?!

expo 51.0.18 btw

**Comment by NilsBaumgartner1994** [comment]
Still facing the same problem.Beste Grüße,Nils BaumgartnerAm 05.07.2024 um 11:55 schrieb Menno Luiten ***@***.***>:﻿
I'm still experiencing this issue when trying to load assets (using Asset.loadAsync to get the URI) -- error is the same except it it will complain about the asset directory instead of the Application Support directory. Does the asset directory need a similar patch?!
expo 51.0.18 btw

**Comment by Hosam-hsm** [comment]
Hello, I'm receiving this error now

`{"code":"ERR_FILE_NOT_WRITABLE"}`

when using 

```
const chunk = await FileSystem.readAsStringAsync(filePath, {
          encoding: FileSystem.EncodingType.Base64,
          length,
          position,
        });
```

I had upgraded to the latest versions and it was working fine before the upgrade

Current versions:
    "expo": "~51.0.20",
    "expo-file-system": "~17.0.1",
    "expo-dev-client": "~4.0.20"

**Comment by tiagotwistag** [comment]
We still have this issue in our apps, when calling **readAsStringAsync**
```js
await FileSystem.readAsStringAsync(fileUri, {
    encoding: FileSystem.EncodingType.Base64,
})
```

Error:
```
[Error: Calling the 'readAsStringAsync' function has failed
→ Caused by: File '/var/mobile/Media/DCIM/148APPLE/IMG_8518.PNG' is not readable]
```

FileSystem.getInfoAsync
```
{"exists": true, "isDirectory": false, "md5": "9c9ee65f9066d43a6cc605cc693289e1", "modificationTime": 1721906185.4745755, "size": 251522, "uri": "file:///var/mobile/Media/DCIM/148APPLE/IMG_8518.PNG"}
```

Versions:
```
"expo": "51.0.24",
"expo-dev-client": "4.0.19",
"expo-file-system": "17.0.1"
```

**Comment by paulmckee** [comment]
I am also running into this:  development build works fine, production build on iOS (v16.7 or v17.6 on iPad) errors out because an asset isn't readable.  I have not tried Android.

```
import { Asset } from 'expo-asset';
import * as FileSystem from 'expo-file-system';

  const asset = Asset.fromModule(require('@/assets/myFile.zip'));
  await asset.downloadAsync();
  // The following line throws an exception with code ERR_FILE_NOT_READABLE
  const zipFileBase64 = await FileSystem.readAsStringAsync(asset.localUri, { encoding: 'base64' });
```

Note that the error is ERR_FILE_NOT_READABLE, not ERR_FILE_NOT_EXISTS.  The asset file is there inside the .ipa file.

The value of `asset.localUri` is something like `file:///var/containers/Bundle/Application/xxxxxxxx-xxx-xxx-xxx-xxxxxxxxxxxx/myapp.app/assets/assets/myFile.zip`.

I'm using the default metro configuration (in which, I believe, .zip files are supported as assets) and the following:
```
    "expo": "~51.0.22",
    "expo-asset": "~10.0.10",
    "expo-file-system": "~17.0.1",
    "react": "18.2.0",
    "react-native": "0.74.3",
```

Any thoughts or workarounds?

**Comment by thespacemanatee** [comment]
@douglowder @brentvatne we are also facing this after recent bumps in expo dependencies. It will take us sometime to bisect and figure out which was the exact package that did it, but I think you guys need to take a look at this asap!

**Comment by douglowder** [comment]
@thespacemanatee we will take a look. This should have been fixed in `expo@51.0.9` and later: the change (#29184) is in `expo-modules-core@1.12.12` and later. Thanks very much for your work bisecting to figure out what broke it again!

**Comment by thespacemanatee** [comment]
@douglowder thanks for the quick response. I have another update, we dug deeper into our codebase and realised that we were using our version of Audio Recorder which was saving the recording in a `**/tmp` folder. I am in the process of migrating to `expo-av` which seems to have resolved the issue. I consider it resolved for our use case so this issue is no longer a priority for us (`expo-notifications` is more important 😄). Thanks again for the quick turnaround!

**Comment by arthuralee** [comment]
Just encountered a similar issue with `react-native-image-crop-picker` which stores images in the tmp directory as well. The tmp directory path comes from the `NSTemporaryDirectory()` call (https://github.com/ivpusic/react-native-image-crop-picker/blob/4d9cb70b02b34333dda44e1c0c85c9c505d6fccf/ios/src/ImageCropPicker.m#L231C30-L231C52) which is an acceptable place to store temporary files https://developer.apple.com/documentation/foundation/1409211-nstemporarydirectory.

Would it make sense to add the temporary directory to `FileSystemLegacyUtilities` as well?

**Comment by helferleinsoftware** [comment]
I still have the error using

```
"expo": "51.0.26",
"expo-file-system": "17.0.1"
```

(as a side note: also `copyAsync` fails with the same error, both errors happen on iOS only)

**Comment by davetodd** [comment]
@arthuralee I had the same `react-native-image-crop-picker` error. #30540 fixed the issue for me. I used the following patch in expo-modules-core since it's still unreleased:

```
diff --git a/node_modules/expo-modules-core/ios/FileSystemUtilities/FileSystemLegacyUtilities.swift b/node_modules/expo-modules-core/ios/FileSystemUtilities/FileSystemLegacyUtilities.swift
index 0463a6d..ec44d45 100644
--- a/node_modules/expo-modules-core/ios/FileSystemUtilities/FileSystemLegacyUtilities.swift
+++ b/node_modules/expo-modules-core/ios/FileSystemUtilities/FileSystemLegacyUtilities.swift
@@ -110,10 +110,11 @@ public class FileSystemLegacyUtilities: NSObject, EXInternalModule, EXFileSystem
       return []
     }
     var filePermissions: EXFileSystemPermissionFlags = []
-    if FileManager.default.isReadableFile(atPath: url.absoluteString) {
+    // fixed with https://github.com/expo/expo/pull/30540
+    if FileManager.default.isReadableFile(atPath: url.path) {
       filePermissions.insert(.read)
     }
-    if FileManager.default.isWritableFile(atPath: url.absoluteString) {
+    if FileManager.default.isWritableFile(atPath: url.path) {
       filePermissions.insert(.write)
     }
     return filePermissions
```

**Comment by brentvatne** [comment]
hey folks, i've released expo@51.0.27 which includes expo-modules-core changes from https://github.com/expo/expo/pull/30981 that should resolve this issue. please let me know if it persists

**Comment by christophercarr** [comment]
I'm still running into the issue, with the following dependencies:
- "expo": "51.0.28"
- "expo-asset": "~10.0.10"
- "expo-file-system": "~17.0.1"
- "expo-updates": "~0.25.22"
- "react": "18.2.0"
- "react-native": "0.74.5"

It happily returns values for these two calls to retrieve info for a file bundled into the project:
`const sourceAsset = await Asset.fromModule(require('./somePathAndFile.Ext')).downloadAsync()`
`const sourceInfo = await FileSystem.getInfoAsync(sourceAsset.localUri, {md5: true, size: true});`

But, the copy call fails (first attachment):
`await FileSystem.copyAsync({from: sourceInfo.uri, to: someTargetFileLocation})`

When I check the development information of the application (second attachment), it is showing ExpoGo SDK of 51.0.0, despite my entry in the package.json.  Is there a way to force the client to use an explicit major.minor.patch version?

![copyAsyncErrorDialog](https://github.com/user-attachments/assets/63c73073-ecef-454f-b29f-1243ea106f1b)

![ExpoGoVersionInfo](https://github.com/user-attachments/assets/6f80103f-e7cf-4df1-8bfd-50e934767dab)

**Comment by arthuralee** [comment]
Thanks, upgrading to the latest expo fixed it for us (with `react-native-image-crop-picker` writing to the tmp directory)

**Comment by AurelienJt** [comment]
Hello, sadly I have encountered the original issue as well. Any workarounds?

I get:
` FileSystem.getInfoAsync(uri).exists = true`
However:
'FileSystem.readAsStringAsync(uri)`
` Unable to read data: Error: Calling the 'readAsStringAsync' function has failed
→ Caused by: 'uri' is not readable`

**Comment by stefanlenoach** [comment]
Bump, I'm also running into this issue.

**Comment by Nilomiranda** [comment]
Started an expo project yesterday, fresh install of everything and I'm also running into this

**Comment by McCulloughRT** [comment]
Also seeing this issue with expo version 51.0.31 (not related to react-native-crop-picker)

**Comment by iwiszhou-wb** [comment]
{
"expo": "51.0.38",
"expo-av": "^14.0.7",
}

If we try to record multiple audio (in iOS), we would see randomly error `ERR_FILE_NOT_EXISTS` error .

![Screenshot 2024-10-24 at 6 07 42 PM](https://github.com/user-attachments/assets/6db1ef0e-691f-496c-b751-5fb094e7b3f4)

**Comment by kylebme** [comment]
I'm still seeing this issue, with expo 51.0.38 and expo-file-system 17.0.1.

**Comment by sebaferreras** [comment]
@christophercarr did you find any workarounds? We're trying to do exactly the same (copying a .db file using `FileSystem.copyAsync()`) but we're getting the same `ERR_FILE_NOT_READABLE` error on iOS.

**Comment by FlawaCLV** [comment]
Oddly I have this bug on the production build only, not on my development build.
Anyone having the same issue?

**Comment by FlawaCLV** [comment]
Oddly I have this bug on the production build only, not on my development build.
Anyone having the same issue?

**Comment by 0plus1** [comment]
I am experiencing the same, ```getInfoAsync``` returns file as existing, while even simply reading it (```readAsStringAsync```) returns ```ERR_FILE_NOT_READABLE``` on iOS. Very weird, would love to know why.

**Comment by Nikita2k** [comment]
Same problem here with  "expo": "52.0.37"

**Comment by FlawaCLV** [comment]
I solved my problem when I found that my file, in production, was missing the extension `.png` thus the `ERR_FILE_NOT_READABLE`. When I add the extension, problem solved!

**Comment by robhadfield** [comment]
I found that using the `base64` option solved it for me.

```
let result = await ImagePicker.launchImageLibraryAsync({
  mediaTypes: 'Images' as ImagePicker.MediaTypeOptions.Images,
  quality: 0.75,
  selectionLimit: 10,
  allowsMultipleSelection: true,
  base64: true, // this option here made the file 'readable'
});
```

**Comment by Pechente** [comment]
Did anyone find a proper fix for this? None of the suggestions in this thread have worked. It seems readAsStringAsync is simply broken right now :/ I'm not using an image picker and audio recording but readAsStringAsync fails every time while other file methods work fine.

Running the code in simulator and logging the URI even allows me to open the file locally without issues.
