### ISSUE TITLE
Vercel server deployment crashes in latest build

### ISSUE THREAD

**Issue by younes200** [expo/expo#29431]
### Minimal reproducible example

https://github.com/younes200/expo-router-issue

### Which package manager are you using? (Yarn is recommended)

bun

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

The recent deployment of our project on Vercel encountered difficulties, leading to a crash and displaying a 500 Internal Server Error.

```
Unhandled Rejection: TypeError: The argument 'headers' is invalid. Received [ [ 'content-type', 'text/plain' ] ]
at ServerResponse.writeHead (node:_http_server:373:15)
at ServerResponse.n.writeHead (/opt/rust/nodejs.js:7:2831)
at respond (/var/task/node_modules/@expo/server/build/vendor/vercel.js:62:9)
at /var/task/node_modules/@expo/server/build/vendor/vercel.js:16:16
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at Server.<anonymous> (/opt/rust/nodejs.js:1:10455)
at Server.<anonymous> (/opt/rust/nodejs.js:7:3709) {
code: 'ERR_INVALID_ARG_VALUE'
}
Node.js process exited with exit status: 128. The logs above can help with debugging the issue.
```

Steps to replicate:

- Export the project with the "output" set to "server" : `expo export -p web`.
- Deploy to Vercel following the [documentation](https://docs.expo.dev/router/reference/api-routes/#vercel) using `vercel deploy -prod`

Vercel deployment : https://expo-router-issue-muji978j0-launchtrack.vercel.app/

By removing the nested array provided by vercel solve the issue :  [#29259 ]

### Environment

```
 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /Users/younes/.gem/ruby/3.3.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 7.5.0
    Expo Workflow: managed
```

**Comment by ammubhave** [comment]
Same issue here

**Comment by ammubhave** [comment]
I did [.....].flat() instead and that worked.

**Comment by ammubhave** [comment]
Yes I did. I looked into the code and it might be because path files for tabs may not be handled correctly. Try a vanilla page.

**Comment by Pathetic27** [comment]
I'm having the exact same issue. Is it even possible to alter node packages when you deploy to Vercel? The whole thing seems pretty hopeless.

I followed [this video](https://www.youtube.com/watch?v=2P0q1EdH_oQ&ab_channel=Theo-t3%E2%80%A4gg) to the tee with a fresh create-expo-app and I'm still encountering the same issue. Looks like i'll be converting to Nextjs lol.

**Comment by bradleyayers** [comment]
A release of @expo/server that includes this patch would be amazing if anyone gets a chance 🙏

**Comment by dnlgrgly** [comment]
Note for yarn users: [Vercel only supports yarn v1](https://vercel.com/docs/deployments/builds/package-managers), so using `yarn patch` won't do anything. :(

**Comment by dnlgrgly** [comment]
As this is breaking all deployments on Vercel I think it'd be important to have this fix released ASAP @kitten  🙏

**Comment by bradleyayers** [comment]
> Note for yarn users: [Vercel only supports yarn v1](https://vercel.com/docs/deployments/builds/package-managers), so using `yarn patch` won't do anything. :(

Yes it's annoying they only support Yarn v1, here's an example of how to use pnpm https://github.com/haohao-how/haohao.how/blob/90dddbc274334e0e17d6cd3b0b3ec1f7d212780a/projects/app/api/package.json

**Comment by karlhorky** [comment]
Looks like a canary version `@expo/server@0.4.4-canary-20240628-1ba8152` has been published, containing the change:

- https://github.com/expo/expo/pull/29616#issuecomment-2230772231

**Comment by MarchewkaMatthew** [comment]
It seems that the bug still occurs in the newest @expo/server 0.4.4. I've made a fresh create-expo-app yesterday (11.09.2024) and set up the API route as in the [docs](https://docs.expo.dev/router/reference/api-routes/). Then I tried to host it on vercel but every endpoint returns the earlier mentioned headers issue. With this patch I was able to successfuly host the endpoints:

```
diff --git a/node_modules/@expo/server/build/vendor/vercel.js b/node_modules/@expo/server/build/vendor/vercel.js
index bf59a82..4360187 100644
--- a/node_modules/@expo/server/build/vendor/vercel.js
+++ b/node_modules/@expo/server/build/vendor/vercel.js
@@ -59,7 +59,7 @@ function convertRequest(req, res) {
 exports.convertRequest = convertRequest;
 async function respond(res, expoRes) {
     res.statusMessage = expoRes.statusText;
-    res.writeHead(expoRes.status, expoRes.statusText, [...expoRes.headers.entries()]);
+    res.writeHead(expoRes.status, expoRes.statusText, [...expoRes.headers.entries()].flat());
     if (expoRes.body) {
         await (0, node_1.writeReadableStreamToWritable)(expoRes.body, res);
     }
```

## Versions

"expo": "~51.0.28",
"expo-router": "~3.5.23",

<img width="677" alt="image" src="https://github.com/user-attachments/assets/dc720c4e-babd-4499-a5b8-12783febf5d6">

**Comment by IlirEdis** [comment]
> @MarchewkaMatthew it's working with `"@expo/server": "0.5.0-canary-20240814-ce0f7d5",`

Any plan to merge this into production soon?

**Comment by thomasmorice** [comment]
> @MarchewkaMatthew it's working with `"@expo/server": "0.5.0-canary-20240814-ce0f7d5",`

This works but creates a new issue where I have a request using "Content-Type": "multipart/form-data" which does not work anymore...

**Comment by thomasmorice** [comment]
> @expo/server@0.4.4-canary-20240628-1ba8152

Forget about that, it was related to a completely different issue. My bad.

**Comment by karlhorky** [comment]
`@expo/server@0.5.0` was released 🎉 It includes the fix:

- `@expo/server@0.5.0`: [`/build/vendor/vercel.js`](https://unpkg.com/browse/@expo/server@0.5.0/build/vendor/vercel.js)

```js
async function respond(res, expoRes) {
    res.statusMessage = expoRes.statusText;
    res.writeHead(expoRes.status, expoRes.statusText, [...expoRes.headers.entries()].flat());
```
