### ISSUE TITLE
Loading Assets very slow after update SDK to 31.0.6

### ISSUE THREAD

**Issue by mauriciord** [expo/expo#2952]
Hi,

After i update to SDK 31.0.6, it's showing me:

Assets are load after the below warnings are completely shown after update sdk version to 31.0.0
```
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```

I know that exists another one that is similar to this issue. I had to do a modification on the file `require`, as @redpandatronicsuk said. Check it out here: https://github.com/expo/expo/issues/2578#issuecomment-435713216

The issue is closed, then i had to open a new issue because my SDK version is more up-to-date than the referenced issue.

Thank you

**Comment by brentvatne** [comment]
hi @mauriciord! are you sure that you're using 31.0.6? check your yarn.lock or npm-lock.json. as @ide pointed out, 31.0.3 and higher include a fix where we silence some of these warnings from react-native. https://github.com/expo/expo/issues/2578#issuecomment-436039466

**Comment by mauriciord** [comment]
![code](https://user-images.githubusercontent.com/1128701/49756371-1827dd00-fca1-11e8-8cff-409c22f92abe.png)

Hey @brentvatne , i removed `node_modules`, `lock files` and used `yarn` to install, after that:

![warnings](https://cl.ly/23be7c4bcb0d/%255Bcc3ca82b5c12b09e3c561e33d68e2593%255D_Screen%252520Shot%2525202018-12-10%252520at%25252017.30.43%2525201.png)

**Node:** v. 10.13.0
**NPM:** v. 6.4.1

Check the `node_modules/metro/src/lib/polyfills/require.js`:
![code require](https://cl.ly/cbdbe326d328/%255B3e348487bb4711f2021032f081ae602a%255D_Screen%252520Shot%2525202018-12-10%252520at%25252017.39.39.png)

**Comment by mauriciord** [comment]
@brentvatne I think that even with any warning, the assets loading be slow

**Comment by ide** [comment]
Try commenting out the warning code (under node_modules) and rebuilding the project (use `expo start -c` to clear the cache) -- I suspect assets will load at the expected speed. As you've found, the warning comes from `node_modules/metro` which is not something the Expo team manages nor something that can be corrected by the `react-native` package.

**Comment by mauriciord** [comment]
hey @ide , as i said above, i already commented the line 109. With this workaround, assets loaded in the expected speed. But commenting the line 109, removes all warning of require cycle and this file is inside of `node_modules/metro`.

The real problem is: **if i have any require cycle warning (not only in my node_modules packages), my assets will load slowly**

https://github.com/facebook/metro/issues/287#issuecomment-446185036

**Comment by mauriciord** [comment]
Any updates in this case, i'm running expo v32.0.0 now and the problem still persists.

**Comment by brentvatne** [comment]
i need a reproducible example because i do not have this issue when i create a new project with `expo init`. please share

**Comment by mauriciord** [comment]
@brentvatne Did you try to add an `<Animated.Image />` on your project with `expo init`?

**Comment by mauriciord** [comment]
Any updates @jordanbb and @charlesRmajor ?

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. I wasn't able to reproduce this just now on SDK 35. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions. Thanks!
