### ISSUE TITLE
[SDK 51] Xcode 16 compilation fails on pegged Sentry version

### ISSUE THREAD

**Issue by chriszs** [expo/expo#30117]
### Minimal reproducible example

https://github.com/getsentry/sentry-cocoa/issues/4050

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

I recently upgraded to MacOS Sequoia. It requires Xcode 16. Compiling Sentry's iOS integration fails with a [known bug](https://github.com/getsentry/sentry-cocoa/issues/4050), which they fixed and then pulled into @sentry/react-native with [5.24.1](https://github.com/getsentry/sentry-react-native/releases/tag/5.24.1). Expo pins a prior version of Sentry, so I have to override that to successfully build.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.3 - ~/.asdf/installs/nodejs/18.20.3/bin/node
      Yarn: 1.22.22 - ~/.asdf/installs/nodejs/18.20.3/bin/yarn
      npm: 10.7.0 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2024.03.25.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/admin/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: 16.0/16A5171r - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 10.0.2
    Expo Workflow: bare

### Expo Doctor Diagnostics

n/a

**Comment by victorfob** [comment]
I recently encountered [this issue](https://github.com/getsentry/sentry-react-native/issues/4100#issuecomment-2358977520) due to Xcode 16 being the default version now. The Sentry team informed me that the issue is resolved in version 5.31.0 and later. However, when I run `npx expo-doctor@latest`, Expo still recommends downgrading to version `~5.22.0`:

```bash
The following packages should be updated for best compatibility with the installed expo version:
  @sentry/react-native@5.32.0 - expected version: ~5.22.0
```

I'm concerned that using a newer version of Sentry (5.31.0 or higher) might introduce other compatibility issues, given that Expo recommends an older version. I'm unsure whether to follow Sentry's fix or stick with the version recommended by Expo to avoid potential problems.

**Comment by angelprzz** [comment]
@victorfob @chriszs I have the same problem too. Hopefully Expo will release a new version in the next few days fixing this issue.

**Comment by chriszs** [comment]
I have this in my `package.json`:
```js
  "expo": {
    "install": {
      "exclude": [
        "@sentry/react-native"
      ]
    }
  }
```

**Comment by JoaoPauloCMarra** [comment]
still happens on Xcode 16
https://github.com/getsentry/sentry-react-native/issues/4095#issuecomment-2368442609

**Comment by JoaoPauloCMarra** [comment]
@brentvatne could we have another bump on sentry version?

**Comment by fbeccaceci** [comment]
Using version 5.33.1 everything builds correctly but i cannot get the js/ts sourcemaps to be uploaded automatically when building on ios

**Comment by chrisl777** [comment]
> Using version 5.33.1 everything builds correctly but i cannot get the js/ts sourcemaps to be uploaded automatically when building on ios

Having the same issue, where the sourcemap upload fails: 

```
❌  error: sentry-cli - To disable source maps auto upload, set SENTRY_DISABLE_AUTO_UPLOAD=true in your environment variables. Or to allow failing upload, set SENTRY_ALLOW_FAILURE=true


❌  error: sentry-cli -   INFO    2024-10-15 09:03:38.492199 -07:00 Loaded file referenced by SENTRY_PROPERTIES (sentry.properties)
```

**Comment by navy774989** [comment]
I have same issue too
<img width="791" alt="Screenshot 2024-10-25 at 5 49 24 pm" src="https://github.com/user-attachments/assets/2db84c94-b4e6-4196-9f48-44b68692e691">

**Comment by landonwjohnson** [comment]
I am also getting this.

**Comment by landonwjohnson** [comment]
> I recently encountered [this issue](https://github.com/getsentry/sentry-react-native/issues/4100#issuecomment-2358977520) due to Xcode 16 being the default version now. The Sentry team informed me that the issue is resolved in version 5.31.0 and later. However, when I run `npx expo-doctor@latest`, Expo still recommends downgrading to version `~5.22.0`:
> 
> ```shell
> The following packages should be updated for best compatibility with the installed expo version:
>   @sentry/react-native@5.32.0 - expected version: ~5.22.0
> ```
> 
> I'm concerned that using a newer version of Sentry (5.31.0 or higher) might introduce other compatibility issues, given that Expo recommends an older version. I'm unsure whether to follow Sentry's fix or stick with the version recommended by Expo to avoid potential problems.

does this fix it? I will let you guys know if it fixed mine

**Comment by chriszs** [comment]
In SDK 52 with that change seems to be fixed.

**Comment by chriszs** [comment]
Closing based on upgrade in SDK52.
