### ISSUE TITLE
[expo-video][Android] crashes with proguard enabled

### ISSUE THREAD

**Issue by RRaideRR** [expo/expo#30267]
### Minimal reproducible example

https://github.com/RRaideRR/expo-video-proguard

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

When I set `enableProguardInReleaseBuilds: true` and `enableShrinkResourcesInReleaseBuilds: true`, the app crashes on app opening. 

When I try to retrieve the native logs, I'll get
```
07-08 10:14:26.446  1124  1124 E qdmetadata: paramType 2048 not supported
07-08 10:14:26.512  1124  1124 I chatty  : uid=1000(system) composer@2.4-se identical 4 lines
07-08 10:14:26.530  1124  1124 E qdmetadata: paramType 2048 not supported
07-08 10:14:26.542 11952 11988 E ReactNativeJS: Error: Exception in HostObject::get for prop 'VideoPlayer': java.lang.IllegalArgumentException: Class declares 0 type parameters, but 2 were provided., js engine: hermes
07-08 10:14:26.544 11952 11988 I ReactNativeJS: Running "main
07-08 10:14:26.545 11952 11988 E ReactNativeJS: Invariant Violation: "main" has not been registered. This can happen if:
07-08 10:14:26.545 11952 11988 E ReactNativeJS: * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
07-08 10:14:26.545 11952 11988 E ReactNativeJS: * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
07-08 10:14:26.546  1124  1124 E qdmetadata: paramType 2048 not supported
07-08 10:14:26.551 11952 11989 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
07-08 10:14:26.551 11952 11989 E AndroidRuntime: Process: com.raider.ExpoVideoSdk51, PID: 11952
07-08 10:14:26.551 11952 11989 E AndroidRuntime: com.facebook.react.common.JavascriptException: Error: Exception in HostObject::get for prop 'VideoPlayer': java.lang.IllegalArgumentException: Class declares 0 type parameters, but 2 were provided., js engine: hermes, stack:
07-08 10:14:26.551 11952 11989 E AndroidRuntime: anonymous@1:694652
07-08 10:14:26.551 11952 11989 E AndroidRuntime: loadModuleImplementation@1:18311
07-08 10:14:26.551 11952 11989 E AndroidRuntime: guardedLoadModule@1:17859
07-08 10:14:26.551 11952 11989 E AndroidRuntime: metroRequire@1:17481
07-08 10:14:26.551 11952 11989 E AndroidRuntime: anonymous@1:693086
07-08 10:14:26.551 11952 11989 E AndroidRuntime: loadModuleImplementation@1:18311
07-08 10:14:26.551 11952 11989 E AndroidRuntime: guardedLoadModule@1:17859
07-08 10:14:26.551 11952 11989 E AndroidRuntime: metroRequire@1:17481
07-08 10:14:26.551 11952 11989 E AndroidRuntime: anonymous@1:692298
07-08 10:14:26.551 11952 11989 E AndroidRuntime: loadModuleImplementation@1:18311
07-08 10:14:26.551 11952 11989 E AndroidRuntime: guardedLoadModule@1:17859
07-08 10:14:26.551 11952 11989 E AndroidRuntime: metroRequire@1:17481
07-08 10:14:26.551 11952 11989 E AndroidRuntime: anonymous@1:24345
07-08 10:14:26.551 11952 11989 E AndroidRuntime: loadModuleImplementation@1:18311
07-08 10:14:26.551 11952 11989 E AndroidRuntime: guardedLoadModule@1:17816
07-08 10:14:26.551 11952 11989 E AndroidRuntime: metroRequire@1:17481
07-08 10:14:26.551 11952 11989 E AndroidRuntime: global@1:17033
07-08 10:14:26.551 11952 11989 E AndroidRuntime:
07-08 10:14:26.551 11952 11989 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(Unknown Source:75)
07-08 10:14:26.551 11952 11989 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-08 10:14:26.551 11952 11989 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:154)
07-08 10:14:26.551 11952 11989 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:19)
07-08 10:14:26.551 11952 11989 E AndroidRuntime: 	at com.facebook.jni.NativeRunnable.run(Native Method)
07-08 10:14:26.551 11952 11989 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
07-08 10:14:26.551 11952 11989 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-08 10:14:26.551 11952 11989 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
07-08 10:14:26.551 11952 11989 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:250)
07-08 10:14:26.551 11952 11989 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
07-08 10:14:26.551 11952 11989 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)

```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
      Watchman: 2024.04.29.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/opt/ruby/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11709847
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.17 => 51.0.18 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
    npmGlobalPackages:
      eas-cli: 10.1.1
      expo-cli: 6.3.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by nanqic** [comment]
fixed.by keep expo class

**Comment by JustJoostNL** [comment]
I can confirm it’s crashing for me too with Proguard enabled. Can you give some more detail s on how you’ve solved this @nanqic?

**Comment by nanqic** [comment]
> I can confirm it’s crashing for me too with Proguard enabled. Can you give some more details on how you’ve solved this @nanqic?

[
        "expo-build-properties",
        {
          "ios": {
            "newArchEnabled": true
          },
          "android": {
            "newArchEnabled": true,
            "useLegacyPackaging": true,
            "enableProguardInReleaseBuilds": true,
            "extraProguardRules": "-keep class expo.modules.** { *; }",
            "packagingOptions": {
              "exclude": [
                "lib/x86/**",
                "lib/x86_64/**",
                "lib/armeabi-v7a/**"
              ]
            }
          }
        }
      ]

this is my app.json, hope useful for you.

**Comment by JustJoostNL** [comment]
Thanks for the temporary solution! Hopefully a fix for expo-video can be brought out later on so we can remove this. 🙁

**Comment by JustJoostNL** [comment]
@nanqic I've just tried the solution, but unfortunately, I'm still facing the same error:

`Exception in HostObject::get for prop 'VideoPlayer': java.lang.IllegalArgumentException: Class declares 0 type parameters, but 2 were provided.`
