### ISSUE TITLE
[expo-notifications] Channel is ignored when the app is not in foreground

### ISSUE THREAD

**Issue by javier2409** [expo/expo#30762]
### Minimal reproducible example

https://github.com/javier2409/expo-notifications-bug-test

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Hello, I was trying to implement push notifications for a project I'm working on. The notifications arrive well, but I noticed that on Android they don't show up as a floating notification like in other apps when the app is backgrounded, they only show up as an icon in the status bar, and I have to swipe down to see the full content.

If I go to the app's notification settings, there is a "Miscellaneous" category which has the "Pop on screen" option disabled by default. If I enable this setting, the floating notifications start showing well, the thing is that the notifications always fall in this category when the app is backgrounded, ignoring the channel/s I created with `setNotificationChannelAsync` and the one that I set in the Expo Push Notification Tool. _NOTE: the "Default" category in the app settings does have that option enabled by default but notifications don't seem to fall in this category when the app is backgrounded_

This behavior makes it mandatory for the user to go to the app settings and enable the "Pop on screen" option to get floating notifications, but I don't remember having to do this for any other app where I get those.

Steps to reproduce:
- Get notification permissions when the app launches and get the Expo Push Token
- Use `setNotificationChannelAsync` to create the "default" channel
- Check the app settings for the created channel, that it has the "Pop on screen" option enabled
- Send the app to foreground
- Send a notification to the device using the Expo Notification Tool setting the channel ID to "default"
- Check that the notification arrived
- Disable the "default" channel notifications from the app's settings
- Send the app to foreground
- Send another notification to the device with the "default" channel
- Check the notification doesn't arrive. This means the channel is not getting ignored with the app in foreground.
- Send the app to background
- Send another notification to the device "default" channel
- The notification arrives even with the "default" channel disabled because it is sent to the "Miscellaneous" category.
- Enable the "Pop on screen" for the Miscellaneous category
- Send another notification to the "default" channel
- Now the notification pops up

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.13.1/bin/yarn
      npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
      Watchman: 2024.05.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.24 => 51.0.24 
      expo-router: ~3.5.20 => 3.5.20 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.2.2
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check native tooling versions

Didn't find any issues with the project!

**Comment by nguyenthanhtruongntt85** [comment]
Crash on android 14: Could not put 'class android.os.UserHandle' to WritableMap

Detail: https://gns-slug.sentry.io/share/issue/160070f7ee3a4d1e891fb7d423e94a4e/

Using
"expo": "~51.0.9",
"react-native": "0.74.1",
"react": "18.2.0",
"expo-notifications": "~0.28.14",

**Comment by douglowder** [comment]
@javier2409 thanks for the VERY detailed repro steps. We are tracking this in ENG-12759 and working on a fix.

**Comment by javier2409** [comment]
> @javier2409 thanks for the VERY detailed repro steps. We are tracking this in [ENG-12759](https://linear.app/expo/issue/ENG-12759) and working on a fix.

Thank you!

**Comment by EthanDM** [comment]
Thanks @javier2409 for the write up. I spent the better half of the day trying to figure out why the Android heads-up (i.e. banner or pop-up) notifications were not showing with the app backgrounded.

I can confirm this issue is present on my managed bare, production build app. It is not possible to properly target channels and the default/miscellaneous channel has pop-ups disabled by default.

Will be following for a resolution, thanks.

**Comment by wen-kai** [comment]
We are also experiencing this on Android bare project. Notifications do not pop up on the lock screen nor as a banner when foregrounded. The notifications only silently appear in the notifications tray. This only started happening recently, we hadn't changed anything with our notifications configuration. We are using default channel with max importance and high priority payloads.

**Comment by pedroayres** [comment]
We are experiencing the same issue here. This issue is impacting around 40,000 daily users in my system. How can we get it prioritized?

@expo-bot @expbot

**Comment by akgoode** [comment]
I am also experiencing this with these package versions:

npmPackages:
    "expo": "~51.0.32",
    "expo-constants": "~16.0.2",
    "expo-device": "~6.0.2",
    "expo-notifications": "~0.28.16",
    "expo-router": "~3.5.23",

Any information or progress on a fix would be greatly appreciated!  Also very much willing to provide feedback on any provided fixes.

Thanks in advance!

**Comment by douglowder** [comment]
We are actively working on this issue, and will be making adjustments to both the client and the Expo push service. We will post again once fixes are ready.

**Comment by vonovak** [comment]
Hello,
Thank you for your comments and patience. I'm actively working on resolving this and will have a fix for channel ids not being propagated (when using the expo push service) soon. 

Additionally: there's 

https://github.com/expo/expo/commit/c7e7205369a46b546828ed5bf50c8458628e96da

Which resolves issue with sound not taking into account channel ID.

**Comment by mickytroxxy** [comment]
My app can't receive notifications anymore, haven't touched anything on my code, Everything stopped but I can see that the notifications are being sent but the device is not receiving them.

export const sendPushNotification = async (to: string | null | undefined, title: string, body: string, data: {route:string,user:any}): Promise<void> => {
  if (to) {
    const message = {to,sound: 'default',title,body,data,priority: 'high',useFcmV1:true};
    try {
      const response = await fetch('https://exp.host/--/api/v2/push/send', {
        method: 'POST',
        headers: {
          Accept: 'application/json',
          'Accept-encoding': 'gzip, deflate',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(message),
      });
      console.log(JSON.stringify(response))
    } catch (error) {
      console.log(error, 'error guys')
    }
  }
};

I get status okay and the ID

**Comment by vonovak** [comment]
Hello and thanks for reporting,
Previously linked https://github.com/expo/expo/commit/c7e7205369a46b546828ed5bf50c8458628e96da should fix channel information not being taken into account for sounds in foreground.

Also, channel behavior in background was incorrectly handled by our push backend service. That issue is now resolved and does not require updating the expo-notifications package. You should now see channels working also when the app is in not in foreground

I hope this resolves the original issue.

@mickytroxxy unfortunately it's not something that I can reproduce. I can consistently deliver notifications via the expo push service. Would you mind opening another issue and list as much details as possible?

Thank you 🙂

**Comment by mickytroxxy** [comment]
Thanks for the info,

Is it possible if we can have a google meet, maybe show you my code?

**Comment by basti4557** [comment]
> Hello and thanks for reporting, Previously linked [c7e7205](https://github.com/expo/expo/commit/c7e7205369a46b546828ed5bf50c8458628e96da) should fix channel information not being taken into account for sounds in foreground.
> 
> Also, channel behavior in background was incorrectly handled by our push backend service. That issue is now resolved and does not require updating the expo-notifications package. You should now see channels working also when the app is in not in foreground
> 
> I hope this resolves the original issue.
> 
> @mickytroxxy unfortunately it's not something that I can reproduce. I can consistently deliver notifications via the expo push service. Would you mind opening another issue and list as much details as possible?
> 
> Thank you 🙂

Hey vonovak, 

thanks for your investigations in this issue! 

Is this release already live on your expo servers ? I tested it out in my app about 2 minutes ago, at my site the behaviour with the channels still exists in production 🤔

**Comment by vonovak** [comment]
@basti4557 

> > Hello and thanks for reporting, Previously linked [c7e7205](https://github.com/expo/expo/commit/c7e7205369a46b546828ed5bf50c8458628e96da) should fix channel information not being taken into account for sounds in foreground.
> > Also, channel behavior in background was incorrectly handled by our push backend service. That issue is now resolved and does not require updating the expo-notifications package. You should now see channels working also when the app is in not in foreground
> > I hope this resolves the original issue.
> > @mickytroxxy unfortunately it's not something that I can reproduce. I can consistently deliver notifications via the expo push service. Would you mind opening another issue and list as much details as possible?
> > Thank you 🙂
> 
> Hey vonovak,
> 
> thanks for your investigations in this issue!
> 
> Is this release already live on your expo servers ?

Yes, it is live. This is the kind of notification request that I'm sending:

```
{
  url: 'https://exp.host/--/api/v2/push/send',
  options: '{"httpMethod":"post","body":[{"to":"ExponentPushToken[abcd]","title":"This is a test notification","subtitle":"Expo subtitle","body":"This is a test notification","channelId":"testAppWithSound"}]}'
}
```

You can tweak the sound in the Settings app, when you open the settings for your application. I suggest you set distinctive sounds there and then try to send notifications.
When app is killed / in bg it should follow the channel settings. When in foreground, it'll depend on whether you have changes from https://github.com/expo/expo/commit/c7e7205369a46b546828ed5bf50c8458628e96da integrated.

If you're not seeing the expected behavior please open an issue with a reproducer application and also the request you're using to trigger the notification.

thank you

**Comment by vonovak** [comment]
> Thanks for the info, Is it possible if we can have a google meet, maybe show you my code?


@mickytroxxy unfortunately, we don't offer this kind of support. Please share detailed reproduction steps that would allow me to investigate.

Thank you

**Comment by basti4557** [comment]
> @basti4557
> 
> > > Hello and thanks for reporting, Previously linked [c7e7205](https://github.com/expo/expo/commit/c7e7205369a46b546828ed5bf50c8458628e96da) should fix channel information not being taken into account for sounds in foreground.
> > > Also, channel behavior in background was incorrectly handled by our push backend service. That issue is now resolved and does not require updating the expo-notifications package. You should now see channels working also when the app is in not in foreground
> > > I hope this resolves the original issue.
> > > @mickytroxxy unfortunately it's not something that I can reproduce. I can consistently deliver notifications via the expo push service. Would you mind opening another issue and list as much details as possible?
> > > Thank you 🙂
> > 
> > 
> > Hey vonovak,
> > thanks for your investigations in this issue!
> > Is this release already live on your expo servers ?
> 
> Yes, it is live. This is the kind of notification request that I'm sending:
> 
> ```
> {
>   url: 'https://exp.host/--/api/v2/push/send',
>   options: '{"httpMethod":"post","body":[{"to":"ExponentPushToken[abcd]","title":"This is a test notification","subtitle":"Expo subtitle","body":"This is a test notification","channelId":"testAppWithSound"}]}'
> }
> ```
> 
> You can tweak the sound in the Settings app, when you open the settings for your application. I suggest you set distinctive sounds there and then try to send notifications. When app is killed / in bg it should follow the channel settings. When in foreground, it'll depend on whether you have changes from [c7e7205](https://github.com/expo/expo/commit/c7e7205369a46b546828ed5bf50c8458628e96da) integrated (it's not yet released).
> 
> If you're not seeing the expected behavior please open an issue with a reproducer application and also the request you're using to trigger the notification.
> 
> thank you

The strange behavior is that both Channels are not created explicit by me. The only Channel set by my App is the default Channel, the other two are created when First receiving the notification in Background/front. On a fresh Install only default exists after agreeing the notification permission. So i cant really reproduce how this two channels get created (which wasnt the case before).. I will try later If i find the time to make an test repo.

**Comment by javier2409** [comment]
> Hello and thanks for reporting, Previously linked [c7e7205](https://github.com/expo/expo/commit/c7e7205369a46b546828ed5bf50c8458628e96da) should fix channel information not being taken into account for sounds in foreground.
> 
> Also, channel behavior in background was incorrectly handled by our push backend service. That issue is now resolved and does not require updating the expo-notifications package. You should now see channels working also when the app is in not in foreground
> 
> I hope this resolves the original issue.
> 
> @mickytroxxy unfortunately it's not something that I can reproduce. I can consistently deliver notifications via the expo push service. Would you mind opening another issue and list as much details as possible?
> 
> Thank you 🙂

Hello! I can confirm the issue seems to be solved from what i've been testing and now the pop-up notifications are showing with the app in background.

**Comment by basti4557** [comment]
I could reproduce the source of my issue [#310502](https://github.com/expo/expo/issues/31502)
The backend server set "channelId" to default before when no channel id was sent, this behaviour changed. After sending explicitly the parameter "channelId" over my backend server to the expo servers the notifications get routed again through default.

**Comment by vonovak** [comment]
> After sending explicitly the parameter "channelId" over my backend server to the expo servers the notifications get routed again through default.

@basti4557 can you please expand on this? It's not clear what value you have provided as `channelId` and how. Please provide details of how you're sending the request to expo servers, otherwise I cannot help. It's hard to help if I don't have a complete picture.
Thank you

**Comment by basti4557** [comment]
> #310502

@vonovak sorry for that, i added a comment to explain it a little bit more detailed

**Comment by 8QuadTech** [comment]
I am still facing the same issue as well.
When I enable banner notifications under Miscellaneous, I start seeing the notifs when app is not in foreground but else it doesn't create the alert drop down.

In the notfi data I am receiving, I am able to see the proper channelId ie main_channel. PFA corresponding notif data.
Notification received: 
{"request":{"trigger":{"remoteMessage":{"originalPriority":1,"sentTime":1726905042521,"notification":{"usesDefaultVibrateSettings":false,"color":null,"channelId":"main_channel","visibility":null,"sound":null,"tag":null,"bodyLocalizationArgs":null,"imageUrl":null,"title":"Test","vibrateTimings":null,"ticker":null,"eventTime":null,"body":"Test","titleLocalizationKey":null,"notificationPriority":null,"icon":null,"usesDefaultLightSettings":false,"sticky":false,"link":null,"titleLocalizationArgs":null,"bodyLocalizationKey":null,"usesDefaultSound":false,"clickAction":null,"localOnly":false,"lightSettings":null,"notificationCount":null},"data":{"channelId":"main_channel","message":"Test","title":"Test","body":"{\"key\":\"value\"}","scopeKey":"_dummy_","experienceId":"_dummy_","projectId":"_dummy_"},"to":null,"ttl":2419200,"collapseKey":"host.exp.exponent","messageType":null,"priority":1,"from":"367315174693","messageId":"0:1726905042531516%0ac519e60ac519e6"},"channelId":"main_channel","type":"push"},"content":{"title":"Test","badge":null,"autoDismiss":true,"data":{"key":"value"},"body":"Test","sound":"default","sticky":false,"subtitle":null},"identifier":"0:1726905042531516%0ac519e60ac519e6"},"date":1726905042521}

**Comment by vonovak** [comment]
Hello and thanks for reporting,
the original issue of channel being ignored when the app was not in foreground is resolved (as [confirmed](https://github.com/expo/expo/issues/30762#issuecomment-2353195669)).

There's a "spin-off" issue #310502.

If you're still seeing the issue, please open a new issue and follow the issue template. @8QuadTech please open a new issue. the channel id is present in the notification, as you've shown so this seems to be a different problem.

Thank you 🙂
