### ISSUE TITLE
[expo-video][Android] contentFit="cover" got overlap when videos placed next to each other on Android

### ISSUE THREAD

**Issue by hohoaisan** [expo/expo#31722]
### Minimal reproducible example

https://github.com/hohoaisan/react-native-video-resize-cover-android-bug/tree/expo-51-video

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

On Android, when videos with [contentFit](https://docs.expo.dev/versions/latest/sdk/video/#contentfit)="cover" place next to each other, the part of video that out of view still got rendered when touching another video views and overlap them, setting `overflow: hidden` on parent does not fully hide the out of view part.

### Environment
![Screenshot_1727378530](https://github.com/user-attachments/assets/86cc5e69-4908-49b3-afe4-ae37625c033a)

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.15.0 - ~\AppData\Local\nvs\default\node.EXE
      Yarn: 1.22.22 - ~\AppData\Local\nvs\default\yarn.CMD
      npm: 10.7.0 - ~\AppData\Local\nvs\default\npm.CMD
    IDEs:
      Android Studio: AI-241.18034.62.2411.12169540
    npmPackages:
      expo: ~51.0.28 => 51.0.34
      expo-router: ~3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK
```

**Comment by hohoaisan** [comment]
Reported the same bug with react-native-video https://github.com/TheWidlarzGroup/react-native-video/issues/4202
Is it strongly related to underlying ExoPlayer?

**Comment by jonelvinnaorbe** [comment]
Any updates on this guys? Thank you.

**Comment by jonelvinnaorbe** [comment]
> @hohoaisan Most likely, I'll try to fix it 😄 

Please update here when it is fixed, thank you

**Comment by behenate** [comment]
@jonelvinnaorbe Hi, as mentioned in the `react-native-video` thread this is strictly an  [ExoPlayer Bug](https://github.com/androidx/media/issues/1107) and afaik there is nothing we can do to fix it on the `expo-video` side 😕  I've tried some suggestions but nothing worked correctly (using a texture view for video rendering would work, but it is a lot less performant).

**Comment by ChristopherGabba** [comment]
Just stumbled across this issue, and I posted the same thing (basically duplicates): https://github.com/expo/expo/issues/33789 

This is a brutal issue for me as my UI is heavily dependent on this as well. Seems like its a problem with the underlying component still? Any updates?

**Comment by jonelvinnaorbe** [comment]
> Just stumbled across this issue, and I posted the same thing (basically duplicates): https://github.com/expo/expo/issues/33789 
> 
> 
> 
> This is a brutal issue for me as my UI is heavily dependent on this as well. Seems like its a problem with the underlying component still? Any updates?

Same here, I am still finding a solution to this issue.

**Comment by ChristopherGabba** [comment]
react-native-vision-camera handles this by exposing a property called:

```typescript
    androidPreviewViewType="texture-view"
````

See docs: 
https://react-native-vision-camera.com/docs/guides/preview#overlays-and-masks

Maybe this is a potential workaround where Expo could create this option for us?

**Comment by dr-thca** [comment]
I could write a PR that adresses this in the docs. Is this something that is wanted? Its a very annoying bug, and I assume many other will face it as well

**Comment by behenate** [comment]
Hi! We will add the feature of switching `VideoView` surface types between a texture view and a surface view in sdk 53! It's basically ready, I just have to create a PR, I'm just a preoccupied with some other things right now.

**Comment by ChristopherGabba** [comment]
Good afternoon @behenate, out of curiosity, is there a rough timeline on this? Is this available in Expo 53? Thanks again, in the meantime the patch is working fine for me.

**Comment by behenate** [comment]
@ChristopherGabba It will be available with the beta release next week, probably, and in the stable release once its out (a few weeks tops)

**Comment by hoang-van-nhat** [comment]
@behenate there is no plan on bringing surfaceType support to expo-video on SDK52? 

or is there an alpha version that compatible with SDK52

**Comment by behenate** [comment]
@hoang-van-nhat You should be able to use `expo-video` meant for SDK53 (2.1.9) in SDK52 with no issues. I'm not 100% sure as I didn't test it, but to my best knowledge it should work just fine.

**Comment by behenate** [comment]
Also closing the issue as it was fixed by the PR above

**Comment by theisgroenbech** [comment]
@behenate Thank you so much for the fix!

We cannot build with expo-video 2.1.X for android using SDK52. I suspect that [this PR](https://github.com/expo/expo/pull/34176) might be the reason?

**Comment by theisgroenbech** [comment]
@behenate Thank you so much for the fix!

We cannot build with expo-video 2.1.X for android using SDK52. I suspect that [this change](https://github.com/expo/expo/pull/34176) might be the reason?

```
Task failed with an exception.
-----------
* Where:
Script '/Users/user/Documents/project/node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle' line: 94 * What went wrong:
A problem occurred configuring project ':expo'.
> Could not get unknown property 'release' for SoftwareComponent container of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.
```

**Comment by shuo-hiwintech** [comment]
"react-native": "0.79.5",
"expo": "~53.0.0",
"expo-video": "~2.2.2",

This problem is not fixed.

**Comment by burhanyilmaz** [comment]
> // patches/expo-video+2.0.6.patch
> 
> diff --git a/node_modules/expo-video/android/src/main/java/expo/modules/video/VideoView.kt b/node_modules/expo-video/android/src/main/java/expo/modules/video/VideoView.kt
> index 6e60960..80d7e8a 100644
> --- a/node_modules/expo-video/android/src/main/java/expo/modules/video/VideoView.kt
> +++ b/node_modules/expo-video/android/src/main/java/expo/modules/video/VideoView.kt
> @@ -24,12 +24,26 @@ import expo.modules.video.utils.applyAutoEnterPiP
>  import expo.modules.video.utils.applyRectHint
>  import expo.modules.video.utils.calculateRectHint
>  import java.util.UUID
> +import android.util.Xml
> +
>  
>  // https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide#improvements_in_media3
>  @androidx.annotation.OptIn(androidx.media3.common.util.UnstableApi::class)
>  class VideoView(context: Context, appContext: AppContext) : ExpoView(context, appContext), VideoPlayerListener {
>    val id: String = UUID.randomUUID().toString()
> -  val playerView: PlayerView = PlayerView(context.applicationContext)
> +
> +
> +    val attrs = context.resources.getXml(R.xml.texture_view_layout).let {
> +    try {
> +      it.next()
> +      it.nextTag()
> +    } catch (e: Exception) {
> +    }
> +    Xml.asAttributeSet(it)
> +  }
> +  val playerView: PlayerView = PlayerView(context.applicationContext, attrs) 
> +
> +
>    val onPictureInPictureStart by EventDispatcher<Unit>()
>    val onPictureInPictureStop by EventDispatcher<Unit>()
>    val onFullscreenEnter by EventDispatcher<Unit>()
> diff --git a/node_modules/expo-video/android/src/main/res/xml/texture_view_layout.xml b/node_modules/expo-video/android/src/main/res/xml/texture_view_layout.xml
> new file mode 100644
> index 0000000..2d6ae96
> --- /dev/null
> +++ b/node_modules/expo-video/android/src/main/res/xml/texture_view_layout.xml
> @@ -0,0 +1,8 @@
> +<?xml version="1.0" encoding="utf-8"?>
> +<androidx.media3.ui.PlayerView android:id="@+id/texture_view_player_view"
> +  app:surface_type="texture_view"
> +  android:layout_width="match_parent"
> +  android:layout_height="match_parent"
> +  xmlns:android="http://schemas.android.com/apk/res/android"
> +  xmlns:app="http://schemas.android.com/apk/res-auto"
> +/> 
> \ No newline at end of file

thank you save my time!
