### ISSUE TITLE
Local iOS build errors with "No module named 'ExpoModulesCore' found"

### ISSUE THREAD

**Issue by nickpwhite** [expo/expo#32637]
### Summary

When attempting to build a fresh Expo project for iOS (on a simulator or device) I get this error repetitively:
> No module named 'ExpoModulesCore' found, parent module must be defined before the submodule

This is happening with the latest Expo versions and the latest version of XCode with the iOS 18.1 SDK.

I followed the steps [here](https://docs.expo.dev/get-started/create-a-project/) to create the project and [here](https://docs.expo.dev/get-started/set-up-your-environment/?platform=ios&device=physical&mode=development-build&buildEnv=local) to attempt to build. I also had to set `ENABLE_USER_SCRIPT_SANDBOXING = NO` for the hermes and React-Codegen pods to get past earlier build errors.

I was successfully able to build this project on EAS.

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

iOS

### Package versions

package.json
```json
{
  "name": "my-app",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "reset-project": "node ./scripts/reset-project.js",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "test": "jest --watchAll",
    "lint": "expo lint"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-navigation/native": "^6.0.2",
    "expo": "~51.0.28",
    "expo-constants": "~16.0.2",
    "expo-font": "~12.0.9",
    "expo-linking": "~6.3.1",
    "expo-router": "~3.5.23",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.7",
    "expo-web-browser": "~13.0.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.5",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-web": "~0.19.10",
    "expo-dev-client": "~4.0.28"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/jest": "^29.5.12",
    "@types/react": "~18.2.45",
    "@types/react-test-renderer": "^18.0.7",
    "jest": "^29.2.1",
    "jest-expo": "~51.0.3",
    "react-test-renderer": "18.2.0",
    "typescript": "~5.3.3"
  },
  "private": true
}
```

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.2.37 - /opt/homebrew/bin/bash
    Binaries:
      Node: 18.20.3 - ~/src/asdf/installs/nodejs/18.20.3/bin/node
      npm: 10.7.0 - ~/src/asdf/plugins/nodejs/shims/npm
      Watchman: 2024.11.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/nick/src/asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12483815
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.38
      expo-router: ~3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.13
    npmGlobalPackages:
      eas-cli: 13.0.1
    Expo Workflow: bare
```
```


### Reproducible demo

https://github.com/nickpwhite/expo-modules-core-bug-repro

### Stacktrace (if a crash is involved)

```text
Truncated error output (the full error is too long)

❌  Pods/EXSplashScreen: No module named 'ExpoModulesCore' found, parent module must be defined before the submodule
   └─[app]/ExpoModulesCore/ExpoModulesCore.modulemap:3:8
❌  Pods/EXSplashScreen: No module named 'ExpoModulesCore' found, parent module must be defined before the submodule
   └─[app]/ExpoModulesCore/ExpoModulesCore.modulemap:9:8
❌  Pods/EXSplashScreen: Redefinition of module 'Swift'
   └─[app]/ExpoModulesCore/ExpoModulesCore.modulemap:9:24
...
❌  Pods/EXSplashScreen: Redefinition of module 'Swift'
   └─[app]/ExpoModulesCore/ExpoModulesCore.modulemap:9:24
❌  Pods/EXSplashScreen: No module named 'ExpoModulesCore' found, parent module must be defined before the submodule
   └─[app]/ExpoModulesCore/ExpoModulesCore.modulemap:15:8
❌  Pods/EXSplashScreen: Redefinition of module 'Swift'
   └─[app]/ExpoModulesCore/ExpoModulesCore.modulemap:15:24
❌  Pods/EXSplashScreen: Could not build module 'Foundation'
   └─[app]/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/NSString+UserNotifications.h:8:9
❌  Pods/EXSplashScreen: Could not build module 'UIKit'
   └─[app]/ios/Pods/Target Support Files/EXSplashScreen/EXSplashScreen-prefix.pch:2:9
› Executing expo-constants Pods/EXConstants » [CP-User] Generate app.config for prebuilt Constants.manifest

❌  (/Users/nick/Library/Developer/Xcode/DerivedData/myapp-hbljxwdoiuilsrdkkdilydchrnfb/Build/Products/Debug-iphoneos/ExpoModulesCore/ExpoModulesCore.modulemap:9:8)

   7 |
   8 |
>  9 | module ExpoModulesCore.Swift {
     |        ^ no module named 'ExpoModulesCore' found, parent module must be defined before the submodule
  10 |   header "/Users/nick/Library/Developer/Xcode/DerivedData/myapp-hbljxwdoiuilsrdkkdilydchrnfb/Build/Products/Debug-iphoneos/ExpoModulesCore/Swift Compatibility Header/ExpoModulesCore-Swift.h"
  11 |   requires objc
  12 | }


❌  (/Users/nick/Library/Developer/Xcode/DerivedData/myapp-hbljxwdoiuilsrdkkdilydchrnfb/Build/Products/Debug-iphoneos/ExpoModulesCore/ExpoModulesCore.modulemap:9:24)

   7 |
   8 |
>  9 | module ExpoModulesCore.Swift {
     |                        ^ redefinition of module 'Swift'
  10 |   header "/Users/nick/Library/Developer/Xcode/DerivedData/myapp-hbljxwdoiuilsrdkkdilydchrnfb/Build/Products/Debug-iphoneos/ExpoModulesCore/Swift Compatibility Header/ExpoModulesCore-Swift.h"
  11 |   requires objc
  12 | }


❌  (/Users/nick/Library/Developer/Xcode/DerivedData/myapp-hbljxwdoiuilsrdkkdilydchrnfb/Build/Products/Debug-iphoneos/ExpoModulesCore/ExpoModulesCore.modulemap:15:8)

  13 |
  14 |
> 15 | module ExpoModulesCore.Swift {
     |        ^ no module named 'ExpoModulesCore' found, parent module must be defined before the submodule
  16 |   header "/Users/nick/Library/Developer/Xcode/DerivedData/myapp-hbljxwdoiuilsrdkkdilydchrnfb/Build/Products/Debug-iphoneos/ExpoModulesCore/Swift Compatibility Header/ExpoModulesCore-Swift.h"
  17 |   requires objc
  18 | }


❌  (/Users/nick/Library/Developer/Xcode/DerivedData/myapp-hbljxwdoiuilsrdkkdilydchrnfb/Build/Products/Debug-iphoneos/ExpoModulesCore/ExpoModulesCore.modulemap:15:24)

  13 |
  14 |
> 15 | module ExpoModulesCore.Swift {
     |                        ^ redefinition of module 'Swift'
  16 |   header "/Users/nick/Library/Developer/Xcode/DerivedData/myapp-hbljxwdoiuilsrdkkdilydchrnfb/Build/Products/Debug-iphoneos/ExpoModulesCore/Swift Compatibility Header/ExpoModulesCore-Swift.h"
  17 |   requires objc
  18 | }


❌  (/Users/nick/Library/Developer/Xcode/DerivedData/myapp-hbljxwdoiuilsrdkkdilydchrnfb/Build/Products/Debug-iphoneos/ExpoModulesCore/ExpoModulesCore.modulemap:3:8)

  1 |
  2 |
> 3 | module ExpoModulesCore.Swift {
    |        ^ no module named 'ExpoModulesCore' found, parent module must be defined before the submodule
  4 |   header "/Users/nick/Library/Developer/Xcode/DerivedData/myapp-hbljxwdoiuilsrdkkdilydchrnfb/Build/Products/Debug-iphoneos/ExpoModulesCore/Swift Compatibility Header/ExpoModulesCore-Swift.h"
  5 |   requires objc
  6 | }


❌  (/Users/nick/Library/Developer/Xcode/DerivedData/myapp-hbljxwdoiuilsrdkkdilydchrnfb/Build/Products/Debug-iphoneos/ExpoModulesCore/ExpoModulesCore.modulemap:9:8)

   7 |
   8 |
>  9 | module ExpoModulesCore.Swift {
     |        ^ no module named 'ExpoModulesCore' found, parent module must be defined before the submodule
  10 |   header "/Users/nick/Library/Developer/Xcode/DerivedData/myapp-hbljxwdoiuilsrdkkdilydchrnfb/Build/Products/Debug-iphoneos/ExpoModulesCore/Swift Compatibility Header/ExpoModulesCore-Swift.h"
  11 |   requires objc
  12 | }


❌  (/Users/nick/Library/Developer/Xcode/DerivedData/myapp-hbljxwdoiuilsrdkkdilydchrnfb/Build/Products/Debug-iphoneos/ExpoModulesCore/ExpoModulesCore.modulemap:9:24)

   7 |
   8 |
>  9 | module ExpoModulesCore.Swift {
     |                        ^ redefinition of module 'Swift'
  10 |   header "/Users/nick/Library/Developer/Xcode/DerivedData/myapp-hbljxwdoiuilsrdkkdilydchrnfb/Build/Products/Debug-iphoneos/ExpoModulesCore/Swift Compatibility Header/ExpoModulesCore-Swift.h"
  11 |   requires objc
  12 | }


❌  (/Users/nick/Library/Developer/Xcode/DerivedData/myapp-hbljxwdoiuilsrdkkdilydchrnfb/Build/Products/Debug-iphoneos/ExpoModulesCore/ExpoModulesCore.modulemap:15:8)

  13 |
  14 |
> 15 | module ExpoModulesCore.Swift {
     |        ^ no module named 'ExpoModulesCore' found, parent module must be defined before the submodule
  16 |   header "/Users/nick/Library/Developer/Xcode/DerivedData/myapp-hbljxwdoiuilsrdkkdilydchrnfb/Build/Products/Debug-iphoneos/ExpoModulesCore/Swift Compatibility Header/ExpoModulesCore-Swift.h"
  17 |   requires objc
  18 | }


❌  (/Users/nick/Library/Developer/Xcode/DerivedData/myapp-hbljxwdoiuilsrdkkdilydchrnfb/Build/Products/Debug-iphoneos/ExpoModulesCore/ExpoModulesCore.modulemap:15:24)

  13 |
  14 |
> 15 | module ExpoModulesCore.Swift {
     |                        ^ redefinition of module 'Swift'
  16 |   header "/Users/nick/Library/Developer/Xcode/DerivedData/myapp-hbljxwdoiuilsrdkkdilydchrnfb/Build/Products/Debug-iphoneos/ExpoModulesCore/Swift Compatibility Header/ExpoModulesCore-Swift.h"
  17 |   requires objc
  18 | }
```
```

**Comment by tommycbird** [comment]
Stuck with the same issue

**Comment by dipssit** [comment]
I am also facing the same issue.

**Comment by etonnelier** [comment]
This happened to me. I had to downgrade to macOS Sonoma (v14) and my problem was solved

**Comment by teemukostamo** [comment]
Had the same issue. For me it seems `npx expo install expo-modules-core` did the trick. The module is a critical part of the Expo infrastructure that bridges React Native JavaScript code with native iOS functionality, and for some reason is not installed when initializing a new app with Expo.

**Comment by hmirza1** [comment]
> Had the same issue. For me it seems `npx expo install expo-modules-core` did the trick. The module is a critical part of the Expo infrastructure that bridges React Native JavaScript code with native iOS functionality, and for some reason is not installed when initializing a new app with Expo.

This worked for me.

**Comment by immi-10** [comment]
> Had the same issue. For me it seems `npx expo install expo-modules-core` did the trick. The module is a critical part of the Expo infrastructure that bridges React Native JavaScript code with native iOS functionality, and for some reason is not installed when initializing a new app with Expo.

The issue persists for me doing: `npx expo install expo-modules-core`
Any help?
