### ISSUE TITLE
Stack navigation shows white background despite transparent contentStyle

### ISSUE THREAD

**Issue by mazeincoding** [expo/expo#33040]
### Minimal reproducible example

https://github.com/mazeincoding/expo-router-transparent-bg-bug

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

## Expected Behavior
When setting `contentStyle: { backgroundColor: "transparent" }` on the Stack navigator, the Stack's background should be completely transparent, allowing the ImageBackground component to be fully visible underneath the Stack's content.

## Actual Behavior
On iOS:
1. The Stack navigator adds a solid white background layer
2. This white layer appears between the ImageBackground and the Stack's content
3. The white background persists regardless of:
   - Setting `contentStyle: { backgroundColor: "transparent" }`
   - Setting `presentation: "transparentModal"`
   - Setting transparent backgrounds on all child components
   - Setting `headerStyle: { backgroundColor: "transparent" }`

The issue is consistently reproducible on:
- iOS with Expo Go (iPhone 11, iOS 18.1)

This makes it impossible to achieve a transparent Stack navigation over a background image.

Notice: I only verified the issue on iOS. I have not had a chance to test Android.

### Environment

```text
System:
  OS: Windows 11 10.0.22631
Binaries:
  Node: 22.11.0
  Yarn: 1.22.22
  npm: 10.8.1
IDEs:
  Android Studio: Version 3.6.0.0 AI-192.7142.36.36.6200805
npmPackages:
  expo: ~52.0.7 => 52.0.7
  expo-router: ~4.0.6 => 4.0.6
  react: 18.3.1 => 18.3.1
  react-dom: 18.3.1 => 18.3.1
  react-native: 0.76.2 => 0.76.2
  react-native-web: ~0.19.13 => 0.19.13
Expo Workflow: managed
```

**Comment by marklawlor** [comment]
Can people please try this patch for `@react-navigation/native-stack`

```
diff --git a/node_modules/@react-navigation/native-stack/lib/commonjs/views/NativeStackView.native.js b/node_modules/@react-navigation/native-stack/lib/commonjs/views/NativeStackView.native.js
index 12f2167..d5c0ab9 100644
--- a/node_modules/@react-navigation/native-stack/lib/commonjs/views/NativeStackView.native.js
+++ b/node_modules/@react-navigation/native-stack/lib/commonjs/views/NativeStackView.native.js
@@ -342,9 +342,6 @@ function NativeStackView({
     return acc;
   }, {});
   return /*#__PURE__*/(0, _jsxRuntime.jsx)(_elements.SafeAreaProviderCompat, {
-    style: {
-      backgroundColor: colors.background
-    },
     children: /*#__PURE__*/(0, _jsxRuntime.jsx)(_reactNativeScreens.ScreenStack, {
       style: styles.container,
       children: state.routes.concat(state.preloadedRoutes).map((route, index) => {
```

The issue appears to be an upstream issue with React Navigation 7. Your `backgroundColor` option is being correctly passed to the `<Screen />`, however it is wrapped in a `<SafeAreaView />` that has a hard-coded background color of your theme (white in light mode / black in dark mode)

**Comment by mibaloch** [comment]
For me, the expo-system-ui package's setBackgroundColorAsync() also stopped working in SDK 52, and I see white flashes while navigating between screens in a stack (Android only).

**Comment by marklawlor** [comment]
This should be fixed in `@react-navigation/native-stack@7.1.1`

@mibaloch That seems like a different issue than what is being reported here. Please create a new issue so It can be correctly assigned to an Expo team member

**Comment by Illusion47586** [comment]
Not sure if this is the correct way to fix this, but this solved the issue for me
```js
const theme = useTheme();
theme.colors.background = 'transparent';
```
expo 52, ios.

**Comment by hirbod** [comment]
Upgrade Expo Router to 4.0.9 - the issue was fixed. No need for this hack :)

**Comment by Code-Victor** [comment]
> For me, the expo-system-ui package's setBackgroundColorAsync() also stopped working in SDK 52, and I see white flashes while navigating between screens in a stack (Android only).

Me too! Please, where you able to find a fix?

**Comment by marklawlor** [comment]
@Code-Victor The issue was resolved in React Navigation and Expo Router. Please update your dependencies to the latest version. If you are still having an issue please create a new issue

**Comment by Bum-Ho12** [comment]
The issue is fixed. To avoid the issue, set in screenOptions, presentation mode to be transparentModal

**Comment by prashanFOMO** [comment]
I am still seeing this issue I think. I am using `presentation: "transparentModal"` 

When the modal fully expands, I still see a white background in the area outside of `SafeAreaView`.

I have tried the useTheme workaround mentioned above and setting `contentStyle.backgroundColor`. Neither fixes this issue.

I'm on:
```
├─┬ expo-router@4.0.19
│ ├─┬ @react-navigation/native-stack@7.2.0
```

**Comment by fanatII1** [comment]
> transparentModal

@Bum-Ho12  this worked thanks

**Comment by aonawale** [comment]
Configure your app's background color using any of these
https://docs.expo.dev/versions/latest/config/app/#backgroundcolor or https://docs.expo.dev/versions/latest/sdk/system-ui/

**Comment by mustafadede** [comment]
Hi, 

I am still having this issue.
Here is my app.json : 

```
 "expo-router": "~6.0.21",
 "expo": "~54.0.30",
```

Also I give backgroundColor to every Stack etc. Like this: 
```

 <Stack
      screenOptions={{
        headerShown: false,
        contentStyle: {
          backgroundColor:
            colorScheme === "dark" ? Colors.dark.cGradient2 : "#f2f2f2",
        },
      }}
    >
      <Stack.Screen
        name="index"
        options={{ title: t("login.title"), headerShown: false }}
      />
      <Stack.Screen
        name="reset"
        options={{
          headerStyle: {
            backgroundColor:
              colorScheme === "dark" ? Colors.dark.cGradient2 : "#f2f2f2",
          },
          headerTintColor:
            colorScheme === "dark" ? Colors.dark.cWhite : "black",
          animation: "ios_from_right",
          title: t("reset.title"),
          headerShown: true,
          headerBackTitle: t("headerbacktitle.title"),
        }}
      />
      <Stack.Screen
        name="(tabs)"
        options={{
          headerShown: false,
          headerStyle: {
            backgroundColor:
              colorScheme === "dark" ? Colors.dark.cGradient2 : "#f2f2f2",
          },
          headerBackVisible: false,
          animation: "ios_from_right",
          headerTintColor:
            colorScheme === "dark" ? Colors.dark.cWhite : "black",
          headerTransparent: true,
          headerTitle: "",
          headerTitleAlign: "center",
          headerTitleStyle: {
            fontWeight: "600",
            fontSize: 24,
          },
        }}
      />
      <Stack.Screen
        name="createpost"
        options={{
          headerStyle: {
            backgroundColor:
              colorScheme === "dark" ? Colors.dark.cGradient2 : "#f2f2f2",
          },
          animation: "ios_from_right",
          headerTintColor:
            colorScheme === "dark" ? Colors.dark.cWhite : "black",
          headerTitle: t("createpost.title"),
          headerShadowVisible: false,
          headerShown: true,
          headerBackTitle: "Ana sayfa",
        }}
      />
      <Stack.Screen
        name="searchdetail"
        options={{
          headerShown: true,
          headerTransparent: true,
          headerTitleAlign: "center",
          headerStyle: {
            backgroundColor: "transparent",
          },
          headerTintColor:
            colorScheme === "dark" ? Colors.dark.cWhite : "black",
          headerTitle: "",
          animation: "ios_from_right",
          headerBackTitle: t("headerbacktitle.title"),
        }}
      />
      <Stack.Screen name="ResetToRoot" />
    </Stack>

```
Also transparentModal doesn't work :'(

**Comment by Keireira** [comment]
@Illusion47586 
> Not sure if this is the correct way to fix this, but this solved the issue for me
> 
> import { useTheme } from '@react-navigation/native';
> 
> const theme = useTheme();
> theme.colors.background = 'transparent';
> expo 52, ios.

You're a savior! May 2026, `expo@55.0.18`, `expo-router@55.0.13`, `@react-navigation/native@7.2.2`, and yet I still had that thing somehow, and the "correct" fix involving changing `backgroundColor` inside `app.json` didn't work for me - nor did `contentStyle` or `transparentModal` but this did
