### ISSUE TITLE
[SDK52] 'jsinspector-modern/InspectorInterfaces.h' file not found

### ISSUE THREAD

**Issue by IlirEdis** [expo/expo#33066]
### Minimal reproducible example

https://github.com/IlirEdis/issue-reproduce

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

I know this is a duplicate of https://github.com/expo/expo/issues/28209 but i didn't see any concise fix there and this is happening with the latest updates.

I have been trying almost everything i have been reading online and this was my last try to bring this project back on track.
Been trying deleting `node_modules` and `/ios` folders and `package-lock.json` file then running `npm install` from scratch and then building the project with `npx expo prebuild --clean` but didnt work.

Also i have been trying

```bash
cd ios
pod deintegrate
pod cache clean --all
rm -rf ~/Library/Developer/Xcode/DerivedData
```
not working either.

I still get:

```bash
❌  (node_modules/react-native/ReactCommon/cxxreact/JSExecutor.h:15:10)

  13 | #include <cxxreact/NativeModule.h>
  14 | #include <folly/dynamic.h>
> 15 | #include <jsinspector-modern/InspectorInterfaces.h>
     |          ^ 'jsinspector-modern/InspectorInterfaces.h' file not found
  16 | #include <jsinspector-modern/ReactCdp.h>
  17 | 
  18 | #ifndef RN_EXPORT
```

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.11.0 - /usr/local/bin/node
      npm: 10.9.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.3
    IDEs:
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.7 => 52.0.7 
      expo-router: ~4.0.6 => 4.0.6 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check if the project meets version requirements for submission to app stores
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check native tooling versions
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by douglowder** [comment]
This appears to be the same issue as https://github.com/expo/expo/issues/33091 , as your repro also uses the JSC Javascript engine. With Hermes engine, the problem does not occur. Closing this as a duplicate. I am actively working the other issue.

**Comment by douglowder** [comment]
@IlirEdis  I took another look at your repro project, and realized that you had defined `"jsEngine": "hermes"` in the top level of `app.json`, but defined `"jsEngine": "jsc"` in the "ios" property. If you remove the jsc setting and do a clean prebuild, the problem should be resolved.

**Comment by IlirEdis** [comment]
Hi @douglowder . Actually i just did this synchronously while you were writing this :) and it worked!!! Thanks a lot! 
So, the SDK52 will not work with `"jsEngine": "jsc"`?

**Comment by douglowder** [comment]
@IlirEdis with SDK 52:
- There is a bug on iOS when using JSC and old architecture, mentioned above. I'm working on fixing that
- The new architecture requires Hermes, you cannot use JSC with it
- I would recommend moving to Hermes in any case (newer dev tooling requires it), unless you have a specific use case that requires JSC

**Comment by arthurshir** [comment]
@enisze When I ran into this error, upgrading the expo SDK fixed it for me `npx expo upgrade`

**Comment by caiodias** [comment]
Any way to solve this issue without use `Expo`?

I'm using `Hermes`, not JSC and don't have both declared.
Still facing the same issue.

Because this issue is not the same as https://github.com/expo/expo/issues/33091

**Comment by KushaanKapoor** [comment]
@caiodias did you manage to solve this issue in a non expo application? I am also facing the same issue @RN 0.79.1

**Comment by caiodias** [comment]
Sorry @KushaanKapoor I have not solved it. I just dropped the project and started a new one.

**Comment by noway** [comment]
For non-Expo folks: make sure `React-cxxreact` and `React-jsinspector` are both dynamic frameworks. That fixed it for me.

**Comment by socialcoachjordan** [comment]
> For non-Expo folks: make sure `React-cxxreact` and `React-jsinspector` are both dynamic frameworks. That fixed it for me.

Hey do you mind elaborating on how you did this?

**Comment by noway** [comment]
@socialcoachjordan something along the lines of
```ruby
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name == 'React-cxxreact' || pod.name == 'React-jsinspector'
      def pod.build_type
        Pod::BuildType.dynamic_framework
      end
    end
  end
end
```
in your Podfile.
