### ISSUE TITLE
Expo Router 4: Forced navigation to the same route with different parameters doesn’t work

### ISSUE THREAD

**Issue by mlukasik-dev** [expo/expo#33175]
### Minimal reproducible example

https://github.com/mlukasik-dev/expo-router-repro

### Which package manager are you using? (Yarn is recommended)

pnpm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When using `router.push` or `<Link push />` to navigate to the current route with new parameters, the router does not push a new route. Instead, it updates the parameters of the existing route.

### Environment

```text
expo-env-info 1.2.1 environment info:
  System:
    OS: macOS 15.1.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
  Managers:
    CocoaPods: 1.15.2 - /Users/me/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
  IDEs:
    Android Studio: 2024.2 AI-242.23339.11.2421.12550806
    Xcode: 16.1/16B40 - /usr/bin/xcodebuild
  Expo Workflow: bare
```

**Comment by mlukasik-dev** [comment]
@marklawlor, I'm really sorry for pinging you. I just want to make sure that such an important issue does not get lost.
I'm sure other apps in production are also affected by this unnoticed bug.

**Comment by markmccoid** [comment]
In your _layout.tsx file are you using the getId prop?  I found that has helped me with a similar issue.

```
    <Stack>
      <Stack.Screen
        name="index"
        options={{
          headerShown: true,
        getId={({ params }) => params.showId}
      />
    </Stack>
```

**Comment by mlukasik-dev** [comment]
> In your _layout.tsx file are you using the getId prop? I found that has helped me with a similar issue.
> 
> ```
>     <Stack>
>       <Stack.Screen
>         name="index"
>         options={{
>           headerShown: true,
>         getId={({ params }) => params.showId}
>       />
>     </Stack>
> ```

It helped! Thank you, @markmccoid!!

**Comment by stephentuso** [comment]
I'm surprised this hasn't gotten more attention, this was stopping me from pushing my app to production with router v4. I've fixed it in #33430, hopefully that can be merged soon. [Patch here](https://gist.github.com/stephentuso/36eb23dfcd755518897dcaf87979b82c) in the meantime

**Comment by dhruvpvx** [comment]
thanks you so much @stephentuso I was about to stop upgrading my app do sdk 52 and downgrade to 51
but your patch continued my process 🐱

**Comment by mrkpatchaa** [comment]
It's not stale ;) We are still waiting for the fix to be released.

**Comment by softov** [comment]
> In your _layout.tsx file are you using the getId prop? I found that has helped me with a similar issue.
> 
> ```
>     <Stack>
>       <Stack.Screen
>         name="index"
>         options={{
>           headerShown: true,
>         getId={({ params }) => params.showId}
>       />
>     </Stack>
> ```

I have something like menu tree.

/menu?menu_id=XX

This `getId` does the trick.

Seen like pushing a screen with the same path does not really push. It uses the current screen and update the parameters.

**Comment by hanclang** [comment]
Hi, team, Any updates? the issue still exists when use "expo": "~52.0.46" and "expo-router": "~4.0.21",

**Comment by karlito40** [comment]
This issue is still present in `expo-router ~5.1.4` / `expo SDK 53`.
The getId trick doesn’t work either.

Here’s a minimal reproduction:

``` javascript
// index file
const router = useRouter();
const { modalId } = useLocalSearchParams();
const openModal = () => router.push('/?modalId=1')
const closeModal = () => router.back()

return (
  <View>
    <Button onPress={openModal}>Trigger modal</Text>
    {modalId && (
        <Text>Modal</Text>
        <Button onPress={closeModal}>Close</Text>
    )
  }
  </View>
)
```

``` javascript
// layout
<Tabs.Screen
  name="index"
  getId={({ params }) => `index-${params?.modalId || 'root'}`}
/>
```

In this example, `closeModal` closes the app instead of going back to `/` . The stack history is not push but replace using `router.push('/?modalId=1')`

-----

The patch may not have been applied to `Tabs.Screen`
