### ISSUE TITLE
ScreenOrientation.addOrientationChangeListener() Freezes iOS Devices in Expo SDK 52

### ISSUE THREAD

**Issue by costa-rica** [expo/expo#33853]
### Summary

The ScreenOrientation.addOrientationChangeListener() method in the SDK 52 expo-screen-orientation module has a problem on iOS devices. Specifically the ScreenOrientation.addOrientationChangeListener() is not working correctly. 

I have created a demo that shows the point where the iOS device fails to respond to this method. The implementation functions as expected on Android, but it fails to respond on iOS. Additionally, switching the orientation to landscape causes the iOS emulator or physical device (e.g., iPhone 13 mini) to freeze.

I have implemented this with a screen containing two buttons:

1. One button unlocks the device orientation using ScreenOrientation.unlockAsync().
2. The second button activates ScreenOrientation.addOrientationChangeListener().

As demonstrated in the video linked in my GitHub repo’s README, this setup works on Android. However, on iOS, the second button fails to activate the listener, and switching orientation results in freezing.

I tested this with various configurations in app.json (e.g., "orientation": "portrait", "default", "ALL", "DEFAULT") but encountered the same issue consistently.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

{
  "name": "expo-screen-orientation-issue-demo",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~52.0.23",
    "expo-screen-orientation": "~8.0.2",
    "expo-status-bar": "~2.0.0",
    "react": "18.3.1",
    "react-native": "0.76.5"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v22.11.0/bin/yarn
      npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.23 => 52.0.23 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.5 => 0.76.5 
    npmGlobalPackages:
      eas-cli: 13.3.0
      expo-cli: 6.3.12
    Expo Workflow: managed
```

### Reproducible demo

https://github.com/costa-rica/expo-screen-orientation-issue-demo

Here is a video of the issue. The video shows the code in the github demo using an iOS and Android emulator. I've run this on an Apple iPhone 13 with the same results as you see in the iOS emulator.

https://github.com/user-attachments/assets/9a47017a-aa7d-403d-8f59-c5a70ecf324b

**Comment by pranshulantz01** [comment]
I am having the same issue if i remove the listener ( ScreenOrientation.addOrientationChangeListener) then no problem.

**Comment by kennethCarl** [comment]
+1

**Comment by supryan** [comment]
+1

**Comment by pjdemers** [comment]
PR submitted for review, https://github.com/expo/expo/pull/33867

**Comment by pranshulantz01** [comment]
> PR submitted for review, #33867

if i use your code and replace it in node_modules it should work right? not working

**Comment by jameswilddev** [comment]
This is a big problem as useWindowDimensions is currently also broken and the only workaround seems to be to measure the device orientation and swap the window dimensions if the aspect ratio is inverse to that expected.  Glad a fix is on the way!

**Comment by JustJoostNL** [comment]
> > PR submitted for review, #33867
> 
> if i use your code and replace it in node_modules it should work right? not working
> 
> Edit - never mind learned that's not how it works.

Yeah, you should create a patch and rebuild your development client.

**Comment by BoavistaLudwig** [comment]
I am having the same issue.

**Comment by chrfalch** [comment]
This one should've been fixed and merged now in #33867 - I've also merged this back into sdk-52 so it will be released as soon as possible.

**Comment by BoavistaLudwig** [comment]
great! noobi question: when can we expect access to it?

**Comment by chrfalch** [comment]
I think `8.0.3` should be released and available now - please let us know if everything works as expected.

**Comment by BoavistaLudwig** [comment]
yes, and it works. Thanks!!!

**Comment by kennethCarl** [comment]
Not working on my end.

**Comment by kennethCarl** [comment]
> yes, and it works. Thanks!!!

you tested in iPhone?

**Comment by chrfalch** [comment]
@kennethCarl Make sure you're working with the latest version of `expo-screen-orientation` - in a development build and not in Expo Go (which might not be published with this fix yet)

**Comment by kennethCarl** [comment]
> @kennethCarl Make sure you're working with the latest version of `expo-screen-orientation` - in a development build and not in Expo Go (which might not be published with this fix yet)

oh I see. Thank you for that.

**Comment by kennethCarl** [comment]
> @kennethCarl Make sure you're working with the latest version of `expo-screen-orientation` - in a development build and not in Expo Go (which might not be published with this fix yet)

The error is fixed but the ScreenOrientation.addOrientationChangeListener does not triggered anymore in development build. I'm confused how this works for expo go and development build.

**Comment by kennethCarl** [comment]
> > @kennethCarl Make sure you're working with the latest version of `expo-screen-orientation` - in a development build and not in Expo Go (which might not be published with this fix yet)
> 
> The error is fixed but the ScreenOrientation.addOrientationChangeListener does not triggered anymore in development build. I'm confused how this works for expo go and development build.

Turns out I was working on the older version when I experienced this issue. So the cause of my problem is that I set the initialOrientation to 'PORTRAIT' in app.json plugin config. When I changed it to 'DEFAULT' and rebuild then it works. Thanks for the good documentation. 

Hope this helps anyone having the same issue.

**Comment by costa-rica** [comment]
Thank you for sharing, but I am still having trouble. 

I have created a new project. Then copied my App.js and screens/ from the Reproducible demo repo. Then `yarn install`. 

At this point, I can now see `"expo-screen-orientation": "~8.0.3",` in my package.json. 

In my app.json I made sure I have `"orientation": "DEFAULT",` (but I also tried `"orientation": "default",`).

I am still getting the same problem I displayed in the video above. Anything I am missing? Is it possible for someone to share a repo that the correct implementation.

I am doing `yarn start` which is `expo start`. Then clicking `i` for my ios Emulator. I have tried on an iPhone as well. Same issue.

**Comment by chrfalch** [comment]
Are you running expo-go or a development build? See previous comments.

**Comment by BoavistaLudwig** [comment]
I installed the latest Expo, checked the deps and installed those dependencies, incl. expo-screen-orientation, and then I had to rebuild my custom dev client. Not it works, like previously.

**Comment by chrfalch** [comment]
If you are still having issues with this - please create a small repro (a new project) showing the errors so that we can debug.

**Comment by kennethCarl** [comment]
The documentation will help. https://docs.expo.dev/versions/latest/sdk/screen-orientation/#example-appjson-with-config-plugin

**Comment by costa-rica** [comment]
Thank you @chrfalch and team.
I see, yes. I was building on Expo Go. Based on my research it seems I would need to set up a development build. I have not done that.

Do we have any idea how long these changes might take to reach the Expo Go environment? Like is this a matter of days or months?

**Comment by chrfalch** [comment]
@costa-rica  Thanks for the kind words - they are appreciated. We constantly push new versions of Expo Go so it should be a matter of days - depending on the AppStore / Google Play review times.

**Comment by aliceni81** [comment]
Many thanks!
You guys save my day!
