### ISSUE TITLE
EAS fingerprint fails when using file-based secrets

### ISSUE THREAD

**Issue by mrkpatchaa** [expo/expo#33852]
### Summary

EAS fingerprint validation fails when using file-based secrets due to path differences between GitHub CI environment and EAS build environment.
Related issued on Expo Github Actions https://github.com/expo/expo-github-action/issues/315 

I found a workaround for my builds to pass, which is to ignore fingerprint check on the whole expo config. 
https://github.com/expo/expo/blob/main/packages/%40expo/fingerprint/src/sourcer/SourceSkips.ts#L40
As mentioned in the readme https://www.npmjs.com/package/@expo/fingerprint 
But it's not the solution because it can lead to issues
```
  /**
   * Skip the whole ExpoConfig.
   * Prefer the other ExpoConfig source skips when possible and use this flag with caution.
   * This will potentially ignore some native changes that should be part of most fingerprints.
   * E.g., adding a new config plugin, changing the app icon, or changing the app name.
   */
```

### What platform(s) does this occur on?

Android, iOS

### SDK Version

52

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
      npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
      Android SDK:
        API Levels: 34, 35
        Build Tools: 33.0.1, 34.0.0, 35.0.0
        System Images: android-34 | Google APIs ARM 64 v8a, android-35 | Google Play ARM 64 v8a, android-UpsideDownCakePrivacySandbox | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2412.12266719
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.23 => 52.0.23 
      expo-router: ~4.0.15 => 4.0.15 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.5 => 0.76.5 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 14.2.0
    Expo Workflow: managed
```

### Minimal reproducible example

https://github.com/mrkpatchaa/fingerprint-file-based-secrets

**Comment by mrkpatchaa** [comment]
@Kudo if you check the comment here https://github.com/expo/expo-github-action/issues/315#issuecomment-2564382463 I made some changes locally to "fix" the issue. 
I don't know if this has some edge cases not covered. 
Anyway, thanks for taking a look at it. If you need someone to test changes I will do.

**Comment by Kudo** [comment]
thanks for sharing the insight. i would leave my comment at https://github.com/expo/expo-github-action/issues/315 given there were some context already.

**Comment by mrkpatchaa** [comment]
@yonitou try to add the android folder in your `.fingerprintignore` file ? 
```
# Ignore the entire android folder
/android/**/*
```

**Comment by yonitou** [comment]
Weird because I don't have one on my local computer
Is it generated during EAS build which can explain the diff ?

**Comment by Kudo** [comment]
@yonitou the source appears on eas because we generate fingerprint after prebuild and ignore `android/**/*`. however, the source has `"hash": null`, it won't conclude a different final fingerprint hash. if you have different fingerprint hash between local and eas, it should be some other sources than this android directory.

**Comment by yonitou** [comment]
Sorry I forgot to say that it happens when I'm using the policy "fingerprint" on my app.json file. It results in an error on my EAS Build saying that the fingerprints mismatch between local machine and EAS servers.

**Comment by yonitou** [comment]
But yes sorry, you're right, there is also another source error (which I can't understand). It's another issue :) 

´´´
[
 {
  "op": "changed",
  "beforeSource": {
   "type": "file",
   "filePath": "package.json",
   "reasons": [
    "expoConfigPlugins"
   ],
   "hash": "8b4f03dbc0a4b6057d59936f3d2b500e0dd18145"
  },
  "afterSource": {
   "type": "file",
   "filePath": "package.json",
   "reasons": [
    "expoConfigPlugins"
   ],
   "hash": "d2e3ad1b1938a13d586ae4dc22b259dc5d9caaec"
  }
 },
´´´

**Comment by Kudo** [comment]
@yonitou interesting case. not sure how package.json could be included by config-plugins. would you mind to share your package.json and eas build url?

**Comment by yonitou** [comment]
Maybe because I'm in an NX monorepo ? 
I saw that you talked about it in this issue : https://github.com/expo/expo/issues/21128
I'm in the exact same case with 4 different problems : 

- The Android prebuild directory I mentioned earlier but you answered to it by adding `android` directory to `.fingerprintignore`
- The file based secrets addressed by this issue
- The `expoConfigPlugins` source we just talked about (I'll share my EAS build link below, the `package.json` is shown in the logs) 
- The last issue is because of the SVP of NX Monorepo. 
The `node_modules` are stored in the root folder of the workspace which means that when EAS is generating a fingerprint BEFORE uploading the bundle to EAS servers, the path of `node_modules` source are something like : `../../node_modules`
But then, when EAS is generating a fingerprint during the build, the node_modules are located in the project root folder (because there is an `npm install` command followed by a `symlink` script) : `./node_modules` which results in a different `fingerprint` hash. 

The EAS build link : https://expo.dev/accounts/alvie1/projects/hygo/builds/c6d184d9-063c-41e2-ad76-8c74e3e60c0c

**Comment by Kudo** [comment]
interesting! it could be NX monorepo. i don't have much experience of NX. could you share more information with me? i don't quite understand why the `./node_modules` symlink was not there in your local environment but then will have the symlink on EAS.
would be super helpful if there are any existing minimal NX monoreo example that i can test on my side.

**Comment by yonitou** [comment]
I can't tell you exactly why because I didn't dig enough into NX run commands but my guess is that it's handled by React Native since 0.73 (https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#stable-symlink-support-in-metro) => The `metro.config.js` is setup in [this file](https://github.com/nrwl/nx/blob/master/packages/expo/plugins/with-nx-metro.ts) in their repository and looks like that `watchFolders` property is setup to read node_modules at the workspace level which explains that there's no need for symlink before build step

**Comment by yonitou** [comment]
I understood the problem for the `expoConfigPlugins` source that changed the fingerprint : it happens when the `version` field in the `package.json` is updated (I use `semver`). Why ? Is there a way to fix it ? It's quite problematic because my version is bumped very often and the fingerprint is changing as well

**Comment by yonitou** [comment]
Yes I can help of course :) What do you need exactly ? A `blank` NX Monorepo with an Expo app inside with the minimum configuration ?

**Comment by brentvatne** [comment]
@yonitou - as long as that reproduces the issue! more information here: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by yonitou** [comment]
Alright, here is the repository : https://github.com/yonitou/mre-expo

The two issues that you will see (if we exclude the `android` prebuild folder which is not really an issue and the `file-based` secrets addressed by this thread) : 

### `node_modules` path issue :
- You can generate a `fingerprint` : `npx @expo/fingerprint ./apps/test-expo  > fingerprint.json`
- You will see that the `node_modules` path is something like : `../../node_modules`. It's correct because this is how NX handles dependencies but the problem is that when the fingerprint is running on EAS, the fingerprint will be : `./node_modules`

### `expoConfigPlugins` issue :
- You can see that in my `app.config.js` file, I'm doing something like : 
```
version: `${version.split('.')[0]}.0.0`,
```
- This is the same implementation I'm having on my private repository which enables me to get only the `major` of the `package.json` version and use it for the _user-facing version_ (for the context, I'm using `semantic-release`)
- From my understanding, the fingerprint must change **only**  if the `major` part is changing : for example, if you update the `version` from `package.json` to `1.4.1`
- The issue is that even if you are updating the `minor` or the `patch` (`0.5.2` for example), you will see the following issue when comparing the 2 fingerprints : 
```
[
  {
    "op": "changed",
    "beforeSource": {
      "type": "file",
      "filePath": "package.json",
      "reasons": [
        "expoConfigPlugins"
      ],
      "hash": "7ad53dafa0eb9bf038c1e06182c5c1eaf9f35207"
    },
    "afterSource": {
      "type": "file",
      "filePath": "package.json",
      "reasons": [
        "expoConfigPlugins"
      ],
      "hash": "43323757df9ed0d9447b97e0d80dbfc03e03a175"
    }
  }
]
```

I think you should have everything you need @Kudo  :) If you need anything, just ping me !

**Comment by yonitou** [comment]
Did you guys have a look at the monorepo above ?

**Comment by yonitou** [comment]
Hey
Sorry to comment on this issue about another problem but I'm trying to find a way to notify you guys. There is an action needed in the `expo-github-action` repository (it doesn't seem really active in the Issues / PR panel, that's why I'm commenting here) :

The `actions/cache` action needs to be updated because the `expo/expo-github-action/fingerprint` is not working anymore for 2 days now (=> https://github.com/actions/cache/discussions/1510)
I know I'm not the only one having the issue because I noticed that your workflow PR labeler on your own `expo/expo` repository is failing too in the `post-run` action : https://github.com/expo/expo/actions/runs/13327389659/job/37223563462 with the error below:

```Failed to save: Unable to reserve cache with key fingerprint-db, another job may be creating this cache. More details: Cache already exists. Scope: refs/heads/main, Key: fingerprint-db, Version: 30a065c722796dde573d8ae372ea626e255e02bafec65597fe70a1d3b666fbb0```

**Comment by ghasemikasra39** [comment]
I still don't understand how fingerprints gonna work with file-based secrets on EAS: these secrets are always present in our local machines as actual files, but never exist on EAS builds. Files such as `GoogleService-Info.plist`. Putting `GoogleService-Info.plist` into `.fingerprintignore` also does not make sense, since each environment needs its own `GoogleService-Info.plist` file.

**Comment by erickreutz** [comment]
I'm running into this as well. Using the `process.env.GOOGLE_SERVICE_JSON` which is a file typed env var on expo.dev and then comparing the two fingerprints in the dashboard the only diff is the file path for that env var.

<img width="1224" alt="Image" src="https://github.com/user-attachments/assets/b50361f6-2145-452b-a3ac-9247212fcaf7" />

@Kudo I see your changes here https://github.com/ONLYHUMN/expo/commit/f879b8a7cfe0600021039c3ea287571e56b04f25 handle deleting `googleServiceFile`. How can we accomplish the same with expo plugins that asks for the file?

UPDATE

Ended up doing this:
```ts
/**
 * Expo Fingerprint Configuration
 * 
 * Excludes dynamic customerio-expo-plugin googleServicesFile paths from fingerprint calculation.
 * The customerio-expo-plugin uses GOOGLE_SERVICES_JSON environment variable which contains 
 * file paths that change with each CI run, causing different fingerprints even when no 
 * actual code changes.
 * 
 * @see https://docs.expo.dev/versions/latest/sdk/fingerprint/#advanced-customize-sources-before-fingerprint-hashing
 */

const assert = require('node:assert');

/** @type {import('@expo/fingerprint').Config} */
const config = {
  fileHookTransform: (source, chunk, isEndOfFile, encoding) => {
    // Remove dynamic googleServicesFile paths from customerio-expo-plugin
    if (source.type === 'contents' && source.id === 'expoConfig') {
      assert(isEndOfFile, 'contents source is expected to have single chunk.');
      const config = JSON.parse(chunk);
      
      // Remove googleServicesFile from customerio-expo-plugin config
      if (config.plugins) {
        config.plugins = config.plugins.map((plugin) => {
          if (Array.isArray(plugin) && plugin[0] === 'customerio-expo-plugin') {
            const [pluginName, pluginConfig] = plugin;
            const cleanedConfig = { ...pluginConfig };
            
            if (cleanedConfig.android?.googleServicesFile) {
              cleanedConfig.android = { ...cleanedConfig.android };
              delete cleanedConfig.android.googleServicesFile;
            }
            
            return [pluginName, cleanedConfig];
          }
          return plugin;
        });
      }
      
      return JSON.stringify(config);
    }

    // For other sources, just return the chunk
    return chunk;
  },
};

module.exports = config;
```

**Comment by mrkpatchaa** [comment]
@Kudo can this be closed?

**Comment by Snehil-Shah** [comment]
This issue is still there in some form. I was able to solve it by manually ignoring the env directories that is created locally vs on EAS servers.

**.fingerprintignore**:
```
# HACK: Fix issues with the dynamic `GOOGLE_SERVICES_JSON` file. It exists in different directories when run inside an EAS worker vs locally or in CI environments.
.eas/.env/*
**/eas-environment-secrets/*
```

**Comment by erickreutz** [comment]
@Kudo this should not be closed.

**Comment by mrkpatchaa** [comment]
@Kudo any update?
