### ISSUE TITLE
Expo ImagePicker orientation

### ISSUE THREAD

**Issue by R3dC0d3** [expo/expo#342]
Hi guys, I'm trying to use the ImagePicker from expo to take pictures and upload them, I got the system working the only problem I'm having is that the image is always on Portrait mode, even if the photo was taken on landscape it will rotate it to show as portrait, I've researched everywhere I can think of and I can't seem to find a setting that would fix that.
Code that I'm using:

> let result = await ImagePicker.launchCameraAsync({
 >           // allowsEditing: true,
  >          // aspect: [4, 3],
>        });

Do you guys know any solution to this?

**Comment by nikki93** [comment]
@R3dC0d3 Hey! What kind of device is this on? (iOS or Android? If Android which Android device?) Also which version of Expo SDK are you using (17, 18, ...)?

**Comment by arrygoo** [comment]
I believe this was fixed on v18 for Android

**Comment by nikki93** [comment]
@R3dC0d3 as noted, we tried fixing this on SDK 18. Could you update us on whether you still have this issue? Otherwise will close the issue soon.

**Comment by nikki93** [comment]
Closing for now due to no response.

**Comment by dithom** [comment]
Still having this issue on SDK 25 on iOS iPad Air 2. When I started the project everything worked fine, but it seems since the "no-more-barcode-on-iOS"-update of the Expo client rolled out., this issue started to appear again. I'm trying to open the ImagePicker modal in landscape, but its opening in portrait mode. The app itself stays landscape though, its weird because its only the content of the modal being in the wrong orientation. The ImagePicker modal even moves up from bottom correctly.

    let result = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: "Images",
        base64: true,
        quality: 1
    });
