### ISSUE TITLE
Status Bar & Header Overlap on Android SDK < 35 with Expo SDK 53 (Edge-to-Edge Issue?)

### ISSUE THREAD

**Issue by prateekkaramchandani** [expo/expo#36685]
### Minimal reproducible example

https://github.com/expo/expo/tree/main/templates/expo-template-tabs

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in Expo Go

### Summary

Hi Expo team,

After upgrading to Expo SDK 53, I’ve noticed that on Android devices running Android SDK 34 and below, there is an overlap between the status bar and the app header. However, this issue does not occur on devices running Android SDK 35 and above — everything looks fine there. Additionally, the status bar appears black on app startup,

Interestingly, if I change the screen orientation to landscape and then back to portrait, the overlap gets fixed.

For context, I’m using the Expo create-app router template (with Expo Router) with no changes.

Since Expo SDK 53 introduced Android edge-to-edge support, I suspect this might be related to that change.

I've attached a screencast showing the issue for clarity.

Would appreciate it if the team could take a look at this!

https://github.com/user-attachments/assets/8596f693-b709-43cd-9c60-0815d940947d

### Environment

```text
expo-env-info 1.3.3 environment info:
    System:
      OS: Linux 6.10 Fedora Linux 40 (Workstation Edition)
      Shell: 5.9 - /usr/bin/zsh
    Binaries:
      Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.15.1/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
    npmPackages:
      expo: ~53.0.8 => 53.0.8 
      expo-router: ~5.0.6 => 5.0.6 
      react: 19.0.0 => 19.0.0 
      react-dom: 19.0.0 => 19.0.0 
      react-native: 0.79.2 => 0.79.2 
      react-native-web: ~0.20.0 => 0.20.0 
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
15/15 checks passed. No issues detected!
```

**Comment by codebyanubhav** [comment]
Same issue, please provide resolution.
Thank you very much

**Comment by Luke-lsm** [comment]
+1

**Comment by pedromchd** [comment]
Got the same issue, it "solves" itself in runtine when you manually switch the device theme, but the the issue persists.

**Comment by behenate** [comment]
Hi everyone! This seems to be a `react-native-navigation`/`react-native-screens` issue related to bugs in their edge-to-edge support implementations. I'm in contact with their teams to resolve the issue as soon as possible!

**Comment by behenate** [comment]
Fixed by https://github.com/expo/expo/pull/36829

**Comment by brentvatne** [comment]
@prateekkaramchandani - i deployed @behenate's fix for expo go, install the latest version from expo cli or via [this link](https://expo.dev/go?sdkVersion=53&platform=android&device=false). i've submitted this version to the play store for review and it should be available there soon.

@ShoeBoom - can you create a new issue with a minimal reproducible example? this works fine for me with expo-dev-client.

<img width="436" alt="Image" src="https://github.com/user-attachments/assets/9d1c78eb-7f54-4913-bbc1-64400962b06b" />

<img width="436" alt="Image" src="https://github.com/user-attachments/assets/7ae0c0eb-1fa0-4a1f-b0dc-e85de2fd417f" />

**Comment by ShoeBoom** [comment]
@brentvatne  
I ended up fixing it by 
- setting `edgeToEdgeEnabled: true` in app.json
- installing react native edge to edge
- Replacing Expo router's Status bar with react native edge to edge's SystemBars

I'll hopefully have some time to try and repo it tomorrow

**Comment by brentvatne** [comment]
@ShoeBoom - if you set `edgeToEdgeEnabled: true` then there is no need to install react-native-edge-to-edge, it has the exact same behavior - we pull the library in and use the config plugin. similarly, expo-status-bar and expo-navigation-bar both call into react-native-edge-to-edge.

**Comment by behenate** [comment]
@avishekdev "edgeToEdgeEnabled " is only for SDK 53 onwards! For SDK52 you'll have to install `react-native-edge-to-edge` and configure the `react-native-edge-to-edge` config plugin.

**Comment by avishekdev** [comment]
> [@avishekdev](https://github.com/avishekdev) "edgeToEdgeEnabled " is only for SDK 53 onwards! For SDK52 you'll have to install `react-native-edge-to-edge` and configure the `react-native-edge-to-edge` config plugin.

@brentvatne I am still facing the issue, using their `<SystemBars style="dark" />` component instead of the `StatusBar`. Can you help me out with this?

```
                <SafeAreaProvider>
                  <BottomSheetModalProvider>
                    <SafeAreaView style={styles.container}>
                      <SystemBars style="dark" />
                      <RootNavigator />
                      {/* <UpdateNotifierSheet /> */}
                    </SafeAreaView>
                  </BottomSheetModalProvider>
                </SafeAreaProvider>
```

![Image](https://github.com/user-attachments/assets/8d9f44a7-a3f8-4e52-99fc-a62cf901f2d3)

**Comment by behenate** [comment]
@avishekdev Assuming you are using a development build, the issue you are encountering has to be different than the reported issue (it was reported in expo go). Can you make a minimal reproducible example and open a new issue? It's hard to figure anything out from short code samples.

**Comment by brentvatne** [comment]
> @brentvatne Is edgeToEdgeEnabled: true only available in Expo 52? I'm getting an error if I add it to my Expo 52 project.

sdk 53
