### ISSUE TITLE
[expo-mail-composer] On Android opens plain text copy share screen on some Androids

### ISSUE THREAD

**Issue by aayla-secura** [expo/expo#37740]
### Minimal reproducible example

https://github.com/aayla-secura/expo-mail-composer-issue

### Steps to reproduce

# Issue

Even though `isAvailableAsync` returns `true`, and there is a configured email client on the device, I find that on my physical Android device `composeAsync` opens a plain text sharing screen with no option to select a mail app (see screenshot below).

A plain "mailto:" link on my Android device correctly opens the mail app picker. Setting a default map app (always open) doesn't make a difference: `MailComposer` still opens the plain text copy share sheet. It works fine on iOS as well as on a Pixel 8a simulator. Unfortunately I don't have another physical Android device to test.

# Devices tested

I tested on a physical iPhone, an Android Pixel 8a simulator and a physical Android. The issue happens only on my physical Android device:

❌ Samsung Galaxy S24, Android 15, API 35: Does not work (open plain text copy share sheet)
✅ Android simulator, Pixel 8a, Android 16, API 36: works fine (opens Gmail)
✅ Physical iPhone X: works fine (opens Gmail)

The Android device does have a configured mail client app. In fact two of them. I tried having Gmail set as the default one and also clearing defaults so that it normally prompts me to choose a mail app. No difference.

<img src="https://github.com/user-attachments/assets/68c95fb6-41b2-421e-90c7-b2d7cfe6c9f3" width="300"/>

### Environment

```text
expo-env-info 1.3.3 environment info:
    System:
      OS: Linux 6.6 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
      npm: 11.1.0 - ~/.nvm/versions/node/v20.18.0/bin/npm
    npmPackages:
      expo: ~53.0.13 => 53.0.13
      react: 19.0.0 => 19.0.0
      react-native: 0.79.4 => 0.79.4
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
15/15 checks passed. No issues detected!
```

**Comment by tindery** [comment]
We're having the same issue on Samsung Galaxy Z Flip 4

**Comment by mretiinteractivebrokers** [comment]
Hi! Having the same issue on Samsung Galaxy S23, Android 15

**Comment by aayla-secura** [comment]
@behenate @brentvatne , any idea when this might get looked into?

**Comment by brentvatne** [comment]
@aayla-secura - @behenate will look at it when he has some time but it isn't a top priority. if you want to investigate it and try to figure out what is happening, we could fix it when you do!

**Comment by aayla-secura** [comment]
@brentvatne  I tried looking into this, but unfortunately I'm very unfamiliar with expo plugin development and native Android/Java, and I couldn't figure out how to rebuild the plugin after making some modifications to `android/src/main/java/expo/modules/mailcomposer/MailComposerModule.kt`. It was still using the prebuilt jar files. Can you give me some guidance on how to rebuild the plugin?

On another note, `getClients` returns the correct list of mail clients on my devices, so something in composeAsync's intents is losing those... Perhaps the intent type?

**Comment by KalebLenfest** [comment]
Still getting this issue, specifically on a Galaxy Tab A9+

**Comment by TonchoLozev** [comment]
@brentvatne Changing the mainIntent from ACTION_SEND_MULTIPLE to ACTION_SENDTO in MailIntentBuilder fixes the issue.

I am not a native dev, so i won't start opening PRs here, but with the help of AI this is what i found that it should be working as expected and i hope it help resolving the problem sooner:

```
companion object {
    private const val MAILTO_URI = "mailto:"
  }

  // ✅ Use ACTION_SENDTO for simple emails, ACTION_SEND_MULTIPLE only when we really have attachments
  private val mailIntent: Intent =
    if (!options.attachments.isNullOrEmpty()) {
      Intent(Intent.ACTION_SEND_MULTIPLE).apply {
        // Optional but recommended: give the intent a MIME type
        type = "*/*"
      }
    } else {
      Intent(Intent.ACTION_SENDTO).apply {
        data = Uri.parse(MAILTO_URI)
      }
    }
```

On Android, composeAsync discovers email clients using an ACTION_SENDTO + mailto: intent, but then it launches those same components with ACTION_SEND_MULTIPLE and no data/type.
This makes the system treat the intent as a generic share, resulting in the “Sharing text” / “Select something to share” sheet instead of opening the email compose UI.

**Comment by TonchoLozev** [comment]
Before:

https://github.com/user-attachments/assets/484dd52a-f78c-4cbb-b1f7-0008d655ef96

After(the strange thing is back button goes to gmail app): 

https://github.com/user-attachments/assets/f5121215-8d0e-4c67-92ab-ebfb7ee131ae

**Comment by tiagocorreiaboostinc** [comment]
I'm also facing this issue on Samsung Galaxy A05s

**Comment by tiagocorreiaboostinc** [comment]
Hi, I'm still facing this issue on Samsung A60 (Android 15)
Package versions:
- expo-mail-composer: 15.0.8
- expo: 54.0.29
- react-native: 0.81.5

Is the fix yet to be released?
