### ISSUE TITLE
Android build is failing (Resource compilation failed)

### ISSUE THREAD

**Issue by loick** [expo/expo#37853]
### Minimal reproducible example

https://github.com/loick/expo-android-53.0.17

### Steps to reproduce

Hi there, 

As explained on this [PR](https://github.com/expo/expo/pull/37507#issuecomment-3032207731) (but it might not be the right place so I'm moving it here), we're noticing an issue with the latest version and I assume it's related to this change: 
- On the `53.0.15` everything works as expected.
- On the `53.0.16`, the Android build is failing (and still failing with the `53.0.17`): 

```
Failed to flatten XML for resource 'my_translation_key' with error: Invalid unicode escape sequence in string
"{str}"
```

The translations are imported within the app.config.ts file:

```ts
locales: {
      en: '../../packages/i18n/files/en-GB.json',
      fr: '../../packages/i18n/files/fr-FR.json',
      nl: '../../packages/i18n/files/nl-BE.json',
},
```

I took a close look at the translation key failing, and it appeared all of them were including a straight apostrophe. One the other hand, the translations using the curly apostrophe was not problematic at all. 

Curly apostrophe:`’`
Straight apostrophe: `'`

See the apostrophe difference here (I know it's not easy to catch but...):
```json
{
  "not_working": "t’encourageons",
  "working": "t'encourageons",
}
```

On the reproduction repository, if you run `eas build --platform android`, it will fail. 

### Environment

```text
expo-env-info 1.3.4 environment info:
    System:
      OS: macOS 15.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.17.0 - ~/.volta/tools/image/node/22.17.0/bin/node
      Yarn: 1.22.22 - ~/.volta/tools/image/yarn/1.22.22/bin/yarn
      npm: 10.9.2 - ~/.volta/tools/image/node/22.17.0/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.4, iOS 18.4, macOS 15.4, tvOS 18.4, visionOS 2.4, watchOS 11.4
    IDEs:
      Xcode: 16.3/16E140 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~53.0.17 => 53.0.17 
      react: 19.0.0 => 19.0.0 
      react-native: 0.79.5 => 0.79.5 
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
15/15 checks passed. No issues detected!
```

**Comment by huextrat** [comment]
@loick this has been fixed with https://github.com/expo/expo/pull/37828

Also please check https://github.com/expo/expo/pull/37202#issuecomment-3032996477 if you are using locales for iOS only

**Comment by loick** [comment]
Okay thanks! No I'm using translations for both iOS and Android 👍

**Comment by whidrubeld** [comment]
Described a solution with internationalization and Android build problem
https://github.com/expo/expo/issues/37480#issuecomment-3178923732

**Comment by loick** [comment]
I'm still experiencing issues on Android build when trying to bump 53.0.11 to 53.0.20, with the following error in EAS on each translation key: 

```
Error: "translation_key" is translated here but not found in default locale [ExtraTranslation]
```

I don't know if this is related to the fix 🤔

**Comment by gobzila** [comment]
This issue is still occurring, and I’m encountering a build failure on Android with Expo 53.0.20.

**Comment by gobzila** [comment]
Hey @aleqsio! The issue here is related to [this PR](https://github.com/expo/expo/pull/37202). Do you have any plans to fix this soon? The workaround suggested [here](https://github.com/expo/expo/issues/37480#issuecomment-3178923732) works in EAS, but we’re still encountering the issue when building the app locally.

**Comment by aleqsio** [comment]
Hi @gobzila , apologies for the issues - you can nest your localization strings in the locale object under `ios` and `android` keys to avoid this problem as per the localization docs

https://docs.expo.dev/guides/localization/#translating-app-metadata

If this doesn't work I'm happy to help, apologies for the breaking change mid cycle!

**Comment by gobzila** [comment]
Hey @aleqsio, thank you so much! I missed this alternative in the docs.

@loick You could also try updating your JSON files to add the translations under the `ios` and `android` keys, as described in the [docs](https://docs.expo.dev/guides/localization/#translating-app-metadata) @aleqsio shared. This should work on the latest Expo version, and I believe the issues can be closed.

**Comment by antoinerey** [comment]
Hey! 👋 

I'm trying to bump from Expo v53.0.11 to v53.0.22, and the problem persists. I double-checked everything, and it all seems to be defined as expected. I'm not sure what could be the cause of the issue.

In our `app.config.ts`, we have configured the translations as follow:

```ts
export default function init() {
  return {
    // ...
    
    ios: {
      // ...

      infoPlist: {
        // ...
        CFBundleAllowMixedLocalizations: true,
      },
    },

    locales: {
      en: '../../packages/i18n/files/en-GB.native.json',
      fr: '../../packages/i18n/files/fr-FR.native.json',
      nl: '../../packages/i18n/files/nl-BE.native.json',
    },
  }
}
```

And all three i18n files references above share the same structure. The paths to these files are correct, and the translations are indeed found during the build.

```json5
{
  "android": {
    // ...
    "ios_shortcuts_search_title": "Search",
    "ios_shortcuts_search_description": "The research object",
    "ios_shortcuts_search_dialog": "What item are you looking for?"
  },
  "ios": {
    // ...
    "ios_shortcuts_search_title": "Search",
    "ios_shortcuts_search_description": "The research object",
    "ios_shortcuts_search_dialog": "What item are you looking for?"
  }
}

```

Note that the development builds are working fine. However, our preview builds are crashing with the following message:

```
/home/expo/workingdir/build/apps/mobile/android/app/src/main/res/values-b+en/strings.xml:8: Error: "ios_shortcuts_search_title" is translated here but not found in default locale [ExtraTranslation]
  <string name="ios_shortcuts_search_title">"Search"</string>

          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/home/expo/workingdir/build/apps/mobile/android/app/src/main/res/values-b+en/strings.xml:9: Error: "ios_shortcuts_search_description" is translated here but not found in default locale [ExtraTranslation]
  <string name="ios_shortcuts_search_description">"The research object"</string>

          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/home/expo/workingdir/build/apps/mobile/android/app/src/main/res/values-b+en/strings.xml:10: Error: "ios_shortcuts_search_dialog" is translated here but not found in default locale [ExtraTranslation]
  <string name="ios_shortcuts_search_dialog">"What item are you looking for?"</string>
```

Any idea/pointers/help would be greatly appreciated 😇

**Comment by Benjythebee** [comment]
Same issue as @antoinerey, made a comment in the issue about that specific translation error
https://github.com/expo/expo/issues/38860#issuecomment-3398265294

**Comment by eduardfarkas** [comment]
Still happening on expo 54
