### ISSUE TITLE
[expo-video] Unable to find the native shared object associated with given JavaScript object

### ISSUE THREAD

**Issue by rafakwolf** [expo/expo#39427]
### Minimal reproducible example

https://github.com/rafakwolf/expo-video-error

### Steps to reproduce

Clone the reproducible example and run it; you'll see the error below.
 
Also attached screenshots of the error in the repo README.

[Masterworks.debug.dylib] 🟠 FunctionCallException: Calling the 'play' function has failed (at ExpoModulesCore/SyncFunctionDefinition.swift:137)
[Masterworks.debug.dylib] 🟠 → Caused by: NativeSharedObjectNotFoundException: Unable to find the native shared object associated with given JavaScript object (at
ExpoModulesCore/DynamicSharedObjectType.swift:58)

### Environment

```text
expo-env-info 1.3.4 environment info:
    System:
      OS: macOS 15.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.19.2 - ~/.nvm/versions/node/v20.19.2/bin/node
      npm: 11.5.2 - ~/.nvm/versions/node/v20.19.2/bin/npm
      Watchman: 2025.09.01.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
    IDEs:
      Android Studio: 2024.3 AI-243.26053.27.2432.13536105
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: 53.0.19 => 53.0.19
      expo-router: 5.1.3 => 5.1.3
      react: 19.1.0 => 19.1.0
      react-dom: 19.1.0 => 19.1.0
      react-native: 0.79.5 => 0.79.5
      react-native-web: 0.20.0 => 0.20.0
    npmGlobalPackages:
      eas-cli: 16.18.0
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✖ Check that packages match versions required by installed Expo SDK
The following packages should be updated for best compatibility with the installed expo version:
  @react-native-async-storage/async-storage@2.2.0 - expected version: 2.1.2
  @sentry/react-native@6.17.0 - expected version: ~6.14.0
  @shopify/flash-list@1.8.3 - expected version: 1.7.6
  expo@53.0.19 - expected version: 53.0.22
  expo-image@2.3.2 - expected version: ~2.4.0
  expo-mail-composer@14.1.5 - expected version: ~14.1.6
  expo-router@5.1.3 - expected version: ~5.1.5
  expo-secure-store@14.2.3 - expected version: ~14.2.4
  expo-system-ui@5.0.10 - expected version: ~5.0.11
  react@19.1.0 - expected version: 19.0.0
  react-dom@19.1.0 - expected version: 19.0.0
  react-native-gesture-handler@2.27.1 - expected version: ~2.24.0
  react-native-reanimated@4.0.0 - expected version: ~3.17.4
  react-native-svg@15.12.0 - expected version: 15.11.2
  react-native-webview@13.15.0 - expected version: 13.13.5
  @types/react@19.1.8 - expected version: ~19.0.10
  jest-expo@53.0.9 - expected version: ~53.0.10
  @react-navigation/bottom-tabs@7.4.2 - expected version: ^7.3.10
  @react-navigation/native@7.1.14 - expected version: ^7.1.6
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
```

**Comment by marosstudenic** [comment]
I had same issue whenI migrated to Expo 53, 
i managed to solve it with this 

```

 const { status } = useEvent(videoPlayer, "statusChange", {
    status: videoPlayer.status,
  });
...
{status === "readyToPlay" && (
          <VideoView
            style={styles.video}
            player={videoPlayer}
            allowsFullscreen
          />
        )}
```

when i was showing it without this conditional rendering i only got empty video player preview
EDIT:
never mind, still broken

**Comment by eyedroot** [comment]
same

**Comment by ezesimeoni** [comment]
same issue here

**Comment by lorenzpfei** [comment]
same here

**Comment by kosso** [comment]
The reproducible example provided is attempting to use a YouTube URL as the player uri. 

`expo-video` (as far as I know) does not support YouTube URLs as a VideoSource 

Try with a URL to an MP4 video, or HLS Stream.

eg: 
https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8  (HLS)
https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4  (MP4)

**Comment by rafakwolf** [comment]
@kosso the yt video was only used for the example, but we are using Contenful videos, and the same issue happens

**Comment by kosso** [comment]
@rafakwolf Which platform are you having issues with? 

I'm now using `expo-video` on TV apps (tvOS, Android TV and Fire TV) and everything seems fine. (Though it took some time to migrate from `expo-av` due to their differences).

OK.. I just tried your example and replaced the Video uri with an MP4 URL.
I also gave the `VideoView` some style (width & height)

.. and everything worked fine on iOS and Android. (Tested on iPhone 16 Plus iOS 18.6 simulator and an Android 15 phone.)

Here's the main App.js I used: 

```
import { StatusBar } from "expo-status-bar";
import { VideoView, useVideoPlayer } from "expo-video";
import { useEffect } from "react";
import { StyleSheet, Text, View } from "react-native";

export default function App() {
  const player = useVideoPlayer(
    { uri: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" },
    (player) => {
      player.loop = true;
      player.timeUpdateEventInterval = 1;
    }
  );

  useEffect(() => {
    player.play();
  }, []);

  return (
    <View style={styles.container}>
      <Text>Video error testing</Text>

      <VideoView style={{ width: 400, height: 230, margin: 20, borderWidth: 2, borderColor: 'red' }} player={player} />

      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});

```

Hope this helps.

**Comment by janwirth** [comment]
Had the same issue with expo-audio installed on SDK 53, I had to downgrade expo-audio to 0.4.x from 1.1.x.

This seems to be due to version mismatches.

**Comment by behenate** [comment]
Hi everyone. This seems to be caused by a race condition between our internal shared object auto-releasing solution and using the player in useEffect(() => {}, []). 

_**I only managed to reproduce it during a fast refresh caused by changing the uri inside `useVideoPlayer` - the initial load works for me. Let me know if you experience issues on the initial load, or any situation which doesn't include a fast-refresh.**_

While I'm working on the issue, if you want to do just auto-play have you tried doing the following:

```
  const player = useVideoPlayer(
    { uri: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" },
    (player) => {
      player.loop = true;
      player.timeUpdateEventInterval = 1;
      player.play() // <-- Notice that we can start playback in the post-create method of the constructor
    }
  );
```

or

```
  useEventListener(player, 'statusChange', (e) => {
    if (e.status === 'readyToPlay') {
      player.play();
    }
  });
```

**Comment by behenate** [comment]
Hi everyone, I have prepared a fix for this issue. Since this is in a quite sensitive part of our API I'd appreciate if you could test it in your projects.  You can test it out by modyfing `node_modules/expo-modules-core/src/hooks/useReleasingSharedObject.ts` to contain the following:

```
'use client';

import { DependencyList, useRef, useMemo, useEffect } from 'react';

import type { SharedObject } from '../ts-declarations/SharedObject';

/**
 * Returns a shared object, which is automatically cleaned up when the component is unmounted.
 */
export function useReleasingSharedObject<TSharedObject extends SharedObject>(
  factory: () => TSharedObject,
  dependencies: DependencyList
): TSharedObject {
  const objectRef = useRef<TSharedObject | null>(null);
  const isFastRefresh = useRef(false);
  const previousDependencies = useRef<DependencyList>(dependencies);

  if (objectRef.current == null) {
    objectRef.current = factory();
  }

  const object = useMemo(() => {
    let newObject = objectRef.current;
    const dependenciesAreEqual =
      previousDependencies.current?.length === dependencies.length &&
      dependencies.every((value, index) => value === previousDependencies.current[index]);

    // If the dependencies have changed, release the previous object and create a new one, otherwise this has been called
    // because of an unrelated fast refresh, and we don't want to release the object.
    if (!newObject || !dependenciesAreEqual) {
      objectRef.current?.release();
      newObject = factory();
      objectRef.current = newObject;
      previousDependencies.current = dependencies;
    }
    return newObject;
  }, dependencies);

  useMemo(() => {
    isFastRefresh.current = true;
  }, []);

  useEffect(() => {
    isFastRefresh.current = false;

    return () => {
      // This will be called on every fast refresh and on unmount, but we only want to release the object on unmount.
      if (!isFastRefresh.current && objectRef.current) {
        objectRef.current.release();
      }
    };
  }, []);

  return object;
}
```

I'd really appreciate if you let me know if this has fixed your expo-video / expo-audio issues and if it didn't cause any other issues for you!

**Comment by kosso** [comment]
@behenate  Hi. I eventually did find that I'd see the issue when using a small video preview player on focus (with a delay), on a grid of thumbnails.

```
const PreviewPlayer = (({ source, setPreview }: PreviewPlayerProp) => {
    const player: VideoPlayer = useVideoPlayer(source, player => {
        player.loop = false;
    })
    useEventListener(player, 'statusChange', ({ status, error }) => {
        if (status === 'readyToPlay') {
            player.play()
        }
    })
    useEventListener(player, 'playToEnd', async () => {
        if (player) {
            await player.replaceAsync(null)
        }
        setPreview(false)
    })
    return (
        <VideoView player={player} contentFit="cover" nativeControls={false} style={[{ position: 'absolute', zIndex: 99, top: 0, left: 0, width: item_width, aspectRatio: '16/9', borderRadius: 6 * scaleModifier, borderWidth: 3, borderColor: 'white' }]}></VideoView>
    )
})
```

I tried editing the file you provided and performing a full clean rebuild. But still seeing a lot of these warnings:  (The AudioSession ones possibly being caused by the tvOS Simulator) 

```
[AudioSession]     SessionAPIUtilities.h:176   AudioSessionGetProperty (kMXSessionProperty_HasEchoCancelledInput) failed with error: -50
(sessionID: 0x0)
[AudioSession]     SessionAPIUtilities.h:176   AudioSessionGetProperty (kMXSessionProperty_HasEchoCancelledInput) failed with error: -50
(sessionID: 0x0)
[AudioSession]     SessionAPIUtilities.h:176   AudioSessionGetProperty (kMXSessionProperty_HasEchoCancelledInput) failed with error: -50
(sessionID: 0x0)
[AudioSession]     SessionAPIUtilities.h:176   AudioSessionGetProperty (kMXSessionProperty_HasEchoCancelledInput) failed with error: -50
(sessionID: 0x0)
[AudioSession]     SessionAPIUtilities.h:176   AudioSessionGetProperty (kMXSessionProperty_HasEchoCancelledInput) failed with error: -50
(sessionID: 0x0)
[********.debug.dylib] 🟡 Trying to send event 'availableSubtitleTracksChange' to Optional<SharedObject>, but the JS object is no longer
associated with the native instance
[********.debug.dylib] 🟡 Trying to send event 'availableAudioTracksChange' to Optional<SharedObject>, but the JS object is no longer
associated with the native instance
[********.debug.dylib] 🟡 Trying to send event 'subtitleTrackChange' to Optional<SharedObject>, but the JS object is no longer associated with
the native instance
[********.debug.dylib] 🟡 Trying to send event 'statusChange' to Optional<SharedObject>, but the JS object is no longer associated with the
native instance
[********.debug.dylib] 🟡 Trying to send event 'sourceLoad' to Optional<SharedObject>, but the JS object is no longer associated with the
native instance
```

**Comment by behenate** [comment]
@kosso What you are seeing are just warnings, I'll work on these eventually, but you shouldn't be concerned with them too much as they do not affect the functionality. The fix is meant to fix an error like this:

<img width="300"  alt="Image" src="https://github.com/user-attachments/assets/b50cbd42-06d8-4aa7-8539-7543b543c276" />

**Comment by janwirth** [comment]
I just did test my application with expo-audio on a real device (expo go) and the application crashes, apparently because I call play() too soon. If I hit play manually (instead of using the skip to next function and playing straight away) it doesn't crash. So it seems to be some sort of race condition also here.

**Comment by danieloquelis** [comment]
@behenate thanks for the fix proposal. I did try modifying locally the file as you suggested but unfortunately I still face the same error (the implementation is following the documentation here https://docs.expo.dev/versions/latest/sdk/video/)

Any other ideas?

**Comment by sdjg113** [comment]
> Had the same issue with expo-audio installed on SDK 53, I had to downgrade expo-audio to 0.4.x from 1.1.x.
> 
> This seems to be due to version mismatches.

yes, just go back to 0.4.X for epxo 53.

**Comment by dccarmo** [comment]
I'm still seeing this issue even after updating `expo-modules-core` to `3.0.26` (which seems to contain @behenate fix) and forcing it using `pnpm-workspace.yaml`: 

```
overrides:
  "expo-modules-core": "3.0.26"
```

<img width="368" height="800" alt="Image" src="https://github.com/user-attachments/assets/f6fc7af9-fc22-477c-9ee8-547e9f3d93bc" />

**Comment by devloop11** [comment]
Hello, I am still having such issues even on prod builds IOS. We have reports in Sentry for prod build and it is not a single issues with but a bunch of issues that related to miscommunication between JS and the native side the native object can't be found.

We have a list of videos (TikTok-like feed) but the source is not updated, and the list items are Pure components.

We had cases when player methods were called after the component was unmounted (async, debounce, setTimeout calls) and we fixed it with such a check. Maybe it helps someone. But still, we have crashes

```
export const useIsUnmounted = () => {
  const isComponentUnmounted = useRef(false);

  useEffect(() => {
    return () => {
      isComponentUnmounted.current = true;
    };
  }, []);

  return isComponentUnmounted;
};

/// before calling player methods or getting fields

if (isComponentUnmounted.current) return;

player.pause();
```

**Comment by steelzeh** [comment]
@behenate Hey, why is this ticket closed? The issue unfortunately is still present. 

```
FunctionCallException: Calling the 'play' function has failed (at ExpoModulesCore/SyncFunctionDefinition.swift:137)
→ Caused by: NativeSharedObjectNotFoundException: Unable to find the native shared object associated with given JavaScript object (at ExpoModulesCore/DynamicSharedObjectType.swift:58)
```

Are we doing something wrong, is there something else we should update to fix this issue?

**Comment by martinxsliu** [comment]
I am also seeing this error when using the `useImage` hook from `expo-image`

```
FunctionCallException: Calling the 'get' function has failed (at ExpoModulesCore/SyncFunctionDefinition.swift:137)
→ Caused by: NativeSharedObjectNotFoundException: Unable to find the native shared object associated with given JavaScript object (at ExpoModulesCore/DynamicSharedObjectType.swift:58)
```

* `expo-image@3.0.10`
* `expo-modules-core@3.0.26`
* `expo@54.0.24`

**Comment by MoritzCooks** [comment]
For me this issue appears due to `<StrictMode>` being active. 
Once I remove `StrictMode` from my `App.tsx`, the app can play videos again.
