### ISSUE TITLE
[expo-image-picker] launchCameraAsync doesn’t open the camera on Android after the 2025-09-05 security update

### ISSUE THREAD

**Issue by deka0106** [expo/expo#39480]
### Minimal reproducible example

https://github.com/deka0106/expo-image-picker-test

### Steps to reproduce

After applying the Android security patch 2025-09-05, calling `launchCameraAsync()` from `expo-image-picker` does not show the camera UI immediately.
The camera only appears after the app is backgrounded and then resumed. 

It can be reproduced with the following steps:

- Clone reproducible example
- Run `pnpm install` 
- Run `pnpm run android`
- Tap "Open Camera"

When tapping "Open Camera", logcat outputs the following:

```
Activity                com.example.expoimagepickertest      V  No requestable permission in the request.
```

I’ve confirmed the issue reproduces in the following environments:

- Device: Pixel 8, Pixel 7a, Pixel 6
- Android OS: 16
- Security Update: 2025-09-05

### Environment

```text
expo-env-info 1.3.4 environment info:
    System:
      OS: macOS 15.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.16.0 - ~/.local/share/mise/installs/node/22.16.0/bin/node
      Yarn: 1.22.22 - ~/.local/share/mise/installs/node/22.16.0/bin/yarn
      npm: 10.9.2 - ~/.local/share/mise/installs/node/22.16.0/bin/npm
      Watchman: 2025.09.01.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /Users/kuramoto/.local/share/mise/installs/ruby/3.4.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
      Android SDK:
        API Levels: 34, 35, 36
        Build Tools: 33.0.1, 34.0.0, 35.0.0, 35.0.1, 36.0.0
        System Images: android-36 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2025.1 AI-251.25410.109.2511.13665796
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~53.0.22 => 53.0.22 
      react: 19.0.0 => 19.0.0 
      react-native: 0.79.6 => 0.79.6 
    npmGlobalPackages:
      eas-cli: 16.17.4
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
15/17 checks passed. 2 checks failed. Possible issues detected:
Use the --verbose flag to see more details about passed checks.

✖ Check for app config fields that may not be synced in a non-CNG project
This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: orientation, icon, userInterfaceStyle, splash, ios, android. 


✖ Check that packages match versions required by installed Expo SDK
The following packages should be updated for best compatibility with the installed expo version:
  react-native@0.79.6 - expected version: 0.79.5
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice:
Use 'npx expo install --check' to review and upgrade your dependencies.
To ignore specific packages, add them to "expo.install.exclude" in package.json. Learn more: https://expo.fyi/dependency-validation

2 checks failed, indicating possible issues with the project.
```

**Comment by deka0106** [comment]
I suspect the cause is that when the permission has already been granted, the `askForPermissions` call doesn’t return a response (i.e., it never resolves).

As a quick test, I ran the code below. The `status` remained `pending`, and it only changed to `granted` after I sent the app to the background once and then came back.

```tsx
  const [status, setStatus] = useState<'granted' | 'denied' | 'pending'>();
  const requestPermission = async () => {
    setStatus('pending');
    const result = await ImagePicker.requestCameraPermissionsAsync();
    setStatus(result.granted ? 'granted' : 'denied');
  }

  return (
    <View style={styles.container}>
      <Button title="Request Permission" onPress={requestPermission} />
      {status && <Text>{status}</Text>}
    </View>
  );

```

I observed the same behavior with `expo-camera`’s `useCameraPermissions` and with `expo-location`’s `useForegroundPermissions`.

**Comment by deka0106** [comment]
Not sure if relevant, but this might be related:
https://android.googlesource.com/platform/packages/modules/Permission/%2B/5dca0ccb26f2b99d706a1d3e9402f851e849c913

**Comment by sidpatel93** [comment]
I am also having similar issue as you mentioned above with expo SDK 52 and Android version 16.

**Comment by Jdifederico** [comment]
Same issue, Android version 16

**Comment by deka0106** [comment]
I can reproduce the same behavior with `notifee.requestPermissions()` as well.

**Comment by odexvy** [comment]
Hello, same issue, Pixel 6a, 7a, 9a android 16 (security update august 2025), expo sdk 51 & 53, on expo camera and expo av/audio.
The camera is relaunching just once after lock and unlock the phone.
I have the same problem with android 16 beta 4.1 (play services update october 2025)

**Comment by sarah-mrvx** [comment]
Hello, same issue here on android 16.

**Comment by Baart** [comment]
Same since security update 2025-09-05

**Comment by goneale** [comment]
This is effecting apps in production, if we can get an answer asap

**Comment by arun-arexperts** [comment]
Facing the same issue, has anyone got anyother workarounds or tried using other packages ?

**Comment by Pap36** [comment]
Hello, maybe this helps someone until the issue gets fixed. We had the same problems when using `Location.requestForegroundPermissionAsync` and `Location.requestBackgroundPermissionAsync` from `expo-location`. In our case, we managed to kind of work around it by always calling `Location.getForegroundPermissionAsync` or `Location.getBackgroundPermissionAsync` before requesting it. Also, we'd check the `status` and `canAskAgain` values of the response and programatically direct the user to `AppSettings` if needed.

It looks like `getPermission` does resolve even after the initial permission request resolved without the need of sending the app to background so at least it should unblock the normal use cases of most apps which deal with this.

It is not an ideal solution, but maybe it can help others get around the issue.

**Comment by AugustHA-Iterator** [comment]
Same experience here, in expo-location and requestPermission from useForegroundPermissions :-)..

**Comment by nico-kovacs** [comment]
Same here, haven’t found a fix yet. Luckily most users are still on Android 15, but it’s definitely something to look into soon...

**Comment by Tech-Homnisur** [comment]
Same here :/ app has to be backgrounded and refocused to make it work. There are as many camera opening as failures once the app is refocused.
Will follow closely.

**Comment by returnMarcco** [comment]
FWIW, I've attempted to try out a new library to try and isolate the issue. The above issue also occurs with the following library:
https://www.npmjs.com/package/react-native-image-crop-picker/v/0.42.0

**Comment by goneale** [comment]
For now, I switched to `expo-camera` and implemented the CameraView myself. This worked for me.

**Comment by returnMarcco** [comment]
In the meantime, I've switched to `react-native-permissions` for handling permissions, and `react-native-image-crop-picker` (both conditionally based on OS type and version).

I found that gaining access to the `Gallery` worked solely by switching to `react-native-permissions`, but for the camera itself, Expo's `launchCameraAsync` was not working.

**Comment by p-cauty** [comment]
Hi! Same issue here with expo-image-picker@17.0.8, expo@54.0.8 and Android 16 on a Pixel 8a. I already switched from always using requestCameraPermissionsAsync() to useCameraPermissions(), but the issue still remains.

refocusing the app after requesting the camera UI to launch does work most of the time.

For me it's working perfectly when my app is running inside Expo Go, but as soon as I build a development or a preview build, this issue appears.

**Comment by aroonsekar** [comment]
> For now, I switched to `expo-camera` and implemented the CameraView myself. This worked for me.

Hi, does 'expo-camera' work well with development and production builds ? Cause it works for me well in the Expo Go App, but it crashed in dev-build. I read there was a compatibility issue between the expo-camera and expo-dev-client packages. But my production build also crashes on launch.

**Comment by returnMarcco** [comment]
Does anybody think its a deeper issue with how Android 16 handles permissions? I can't find anything in the Android dev docs stating changes to Camera or Location permissions.

**Comment by mc-pivanov** [comment]
For non-expo app with `expo-camera` and `expo-media-library` I was able to fix the issue by using [PermissionsAndroid](https://reactnative.dev/docs/permissionsandroid) instead.

**Comment by SaverioGrisorio** [comment]
Switching to `react-native-image-crop-picker` fixed it for me - it's even better!

**Comment by MartinCura** [comment]
> In our case, we managed to kind of work around it by always calling `Location.getForegroundPermissionAsync` or `Location.getBackgroundPermissionAsync` before requesting it. Also, we'd check the `status` and `canAskAgain` values of the response and programatically direct the user to `AppSettings` if needed.

Thanks for the idea @Pap36 ! We found that `ImagePicker.requestCameraPermissionsAsync()` never returns in Android 16 (Expo SDK 52) so now instead of directly requesting permissions i first check if we already have them, with `ImagePicker.getCameraPermissionsAsync()`, and this workaround seems to work fine.

**Comment by flyingbarbarian** [comment]
I have same issue on Pixel 6 and Android 16.

**Comment by goodpickle** [comment]
> > In our case, we managed to kind of work around it by always calling `Location.getForegroundPermissionAsync` or `Location.getBackgroundPermissionAsync` before requesting it. Also, we'd check the `status` and `canAskAgain` values of the response and programatically direct the user to `AppSettings` if needed.
> 
> Thanks for the idea [@Pap36](https://github.com/Pap36) ! We found that `ImagePicker.requestCameraPermissionsAsync()` never returns in Android 16 (Expo SDK 52) so now instead of directly requesting permissions i first check if we already have them, with `ImagePicker.getCameraPermissionsAsync()`, and this workaround seems to work fine.

This was really helpful. We did this, but also added a delay for opening the camera if they chose take picture instead of choose from gallery:

```
  // Check and request camera permissions
  // First check current permission status (Android 16 workaround)
  let cameraPermissionResult = await ImagePicker.getCameraPermissionsAsync();

  // Only request permissions if we don't already have them
  if (!cameraPermissionResult.granted) {
    cameraPermissionResult = await ImagePicker.requestCameraPermissionsAsync();
  }
```
...
```
      // Android 16 workaround: Add small delay before launching camera
      // This helps with the background camera issue
      if (Platform.OS === 'android') {
        await new Promise(resolve => setTimeout(resolve, 200));
      }

      const result = await ImagePicker.launchCameraAsync(defaultImagePickerOptions);
```

**Comment by webdevmario** [comment]
@goodpickle I'm curious how you got that small delay to work. I just tested off a physical Pixel 6 with a development build and it still hangs when it gets to `launchCameraAsync`.

**Comment by goodpickle** [comment]
> @goodpickle I'm curious how you got that small delay to work. I just tested off a physical Pixel 6 with a development build and it still hangs when it gets to `launchCameraAsync`.

I meant to get back on here and update. It appeared to work locally but after deploy I still ended up with the same issue. 😓

**Comment by webdevmario** [comment]
> > @goodpickle I'm curious how you got that small delay to work. I just tested off a physical Pixel 6 with a development build and it still hangs when it gets to `launchCameraAsync`.
> 
> I meant to get back on here and update. It appeared to work locally but after deploy I still ended up with the same issue. 😓
> 
> 

No worries! Just making sure I wasn't crazy.

**Comment by iyarsius** [comment]
Same issue here on pixel 8 and android 16. lauchCameraAsync is called but nothing happen unless i open gallery and close it. Then all the camera instances pops.

**Comment by Pap36** [comment]
@SaverioGrisorio thanks! While my idea of checking for permissions first and only request them if necessary fixed the issues related to `expo-location` it did not really help with `launchCameraAsync`. Using `react-native-image-crop-picker` seems to work well though!

**Comment by MarcosCrespin98** [comment]
Same issue, Android version 16

**Comment by cr3spo9** [comment]
We are having the same issue on our app, trying to request the camera permission when its already denied doesnt resolve. Please fix it asap!

**Comment by kywq** [comment]
This is impacting my production apps , fix or even a suggested workaround would be greatly appreciated.

**Comment by SandraLarrosa** [comment]
Same problem here. We have users using Android 16, and the camera permissions aren't working. Any workarounds or any idea when this issue will be fixed? Thanks!

**Comment by AugustHA-Iterator** [comment]
With expo-location requestPermission from useForegroundPermissions, I moved to PermissionsAndroid instead:
      PermissionsAndroid.requestMultiple([
        'android.permission.ACCESS_FINE_LOCATION',
        'android.permission.ACCESS_COARSE_LOCATION',
      ]);

So just made a check if the OS is android then use permissionAndroid or else use requestPermission from useForegroundPermissions.

This seems to work, but should only be until this issue with permission is fixed :-)..

**Comment by JayStringer** [comment]
> Same issue here on pixel 8 and android 16. lauchCameraAsync is called but nothing happen unless i open gallery and close it. Then all the camera instances pops.

Same behaviour for me with Pixel 6 on Android 16

**Comment by Joshandrews43** [comment]
For anyone wondering how to solve, checking the permissions first solved it for me and then you never call `requestCameraPermissionsAsync` if it's already been granted. 

```
const requestPermissions = async () => {
      const { granted } = await Camera.getCameraPermissionsAsync();
      if (granted) {
        setHasPermission(true);
        return;
      }
      const { status } = await Camera.requestCameraPermissionsAsync();
      setHasPermission(status === 'granted');
    };
```

**Comment by efstathiosntonas** [comment]
hey guys, this patch worked for me: 

`expo-image-picker+17.0.8.patch`

<details>
  <summary><del>Click to reveal patch, hacky solution</del></summary>
  
```patch
diff --git a/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt b/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt
index ba07483..c2cb132 100644
--- a/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt
+++ b/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt
@@ -29,8 +29,10 @@ import expo.modules.kotlin.modules.Module
 import expo.modules.kotlin.modules.ModuleDefinition
 import expo.modules.kotlin.weak
 import kotlinx.coroutines.Dispatchers
+import kotlinx.coroutines.TimeoutCancellationException
 import kotlinx.coroutines.suspendCancellableCoroutine
 import kotlinx.coroutines.withContext
+import kotlinx.coroutines.withTimeout
 import java.io.File
 import kotlin.coroutines.resume
 import kotlin.coroutines.resumeWithException
@@ -268,8 +270,57 @@ class ImagePickerModule : Module() {
     }
   }
 
-  private suspend fun ensureCameraPermissionsAreGranted(): Unit = suspendCancellableCoroutine { continuation ->
+  private suspend fun ensureCameraPermissionsAreGranted(): Unit {
+    // Check if permission is already granted to avoid Android 16+ callback hang
+    val currentCameraPermission = ContextCompat.checkSelfPermission(context, Manifest.permission.CAMERA)
+    val currentStoragePermission = if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
+      ContextCompat.checkSelfPermission(context, Manifest.permission.WRITE_EXTERNAL_STORAGE)
+    } else {
+      PackageManager.PERMISSION_GRANTED
+    }
+
+    if (currentCameraPermission == PackageManager.PERMISSION_GRANTED &&
+        currentStoragePermission == PackageManager.PERMISSION_GRANTED) {
+      android.util.Log.d("ImagePickerModule", "Permissions already granted, skipping broken Android 16+ request flow")
+      return
+    }
+
+    android.util.Log.d("ImagePickerModule", "Permissions not granted, using fixed request flow...")
+
+    try {
+      // Add timeout to prevent hanging due to Android 16+ permission session changes
+      // Reference: https://android.googlesource.com/platform/packages/modules/Permission/+/5dca0ccb26f2b99d706a1d3e9402f851e849c913
+      withTimeout(8000L) { // 8 second timeout
+        ensureCameraPermissionsAreGrantedInternal()
+      }
+    } catch (e: TimeoutCancellationException) {
+      android.util.Log.w("ImagePickerModule", "Permission request timed out due to Android session hang, retrying...")
+      // Reset any stuck permission state by checking a different permission first
+      try {
+        context.checkSelfPermission(Manifest.permission.ACCESS_NETWORK_STATE)
+      } catch (ignored: Exception) { }
+
+      // Retry with shorter timeout
+      try {
+        withTimeout(5000L) {
+          ensureCameraPermissionsAreGrantedInternal()
+        }
+      } catch (e2: TimeoutCancellationException) {
+        android.util.Log.e("ImagePickerModule", "Permission request failed twice, Android 16+ permission system is broken")
+        // If permission is actually granted but callback hangs, proceed anyway
+        val retryCheck = ContextCompat.checkSelfPermission(context, Manifest.permission.CAMERA)
+        if (retryCheck == PackageManager.PERMISSION_GRANTED) {
+          android.util.Log.w("ImagePickerModule", "Permission granted but callback hung - proceeding anyway")
+          return
+        }
+        throw UserRejectedPermissionsException()
+      }
+    }
+  }
+
+  private suspend fun ensureCameraPermissionsAreGrantedInternal(): Unit = suspendCancellableCoroutine { continuation ->
     val permissions = appContext.permissions ?: throw ModuleNotFoundException("Permissions")
+    android.util.Log.d("ImagePickerModule", "Requesting camera permissions...")
 
     permissions.askForPermissions(
       { permissionsResponse ->
@@ -277,6 +328,7 @@ class ImagePickerModule : Module() {
           if (permissionsResponse[Manifest.permission.CAMERA]?.status == PermissionsStatus.GRANTED) {
             continuation.resume(Unit)
           } else {
+            android.util.Log.w("ImagePickerModule", "Camera permission denied")
             continuation.resumeWithException(UserRejectedPermissionsException())
           }
         } else if (

```

</details>

EDIT: 
<details>
  <summary>Click to reveal patch, cleaner solution</summary>
  
  ```patch
diff --git a/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt b/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt
index ba07483..873606d 100644
--- a/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt
+++ b/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt
@@ -29,8 +29,10 @@ import expo.modules.kotlin.modules.Module
 import expo.modules.kotlin.modules.ModuleDefinition
 import expo.modules.kotlin.weak
 import kotlinx.coroutines.Dispatchers
+import kotlinx.coroutines.TimeoutCancellationException
 import kotlinx.coroutines.suspendCancellableCoroutine
 import kotlinx.coroutines.withContext
+import kotlinx.coroutines.withTimeout
 import java.io.File
 import kotlin.coroutines.resume
 import kotlin.coroutines.resumeWithException
@@ -268,8 +270,28 @@ class ImagePickerModule : Module() {
     }
   }
 
-  private suspend fun ensureCameraPermissionsAreGranted(): Unit = suspendCancellableCoroutine { continuation ->
+  private suspend fun ensureCameraPermissionsAreGranted(): Unit {
+    // Android 16+ fix: Check permissions directly instead of using broken askForPermissions callback
+    // Reference: https://android.googlesource.com/platform/packages/modules/Permission/+/5dca0ccb26f2b99d706a1d3e9402f851e849c913
+    val cameraGranted = ContextCompat.checkSelfPermission(context, Manifest.permission.CAMERA) == PackageManager.PERMISSION_GRANTED
+    val storageGranted = if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
+      ContextCompat.checkSelfPermission(context, Manifest.permission.WRITE_EXTERNAL_STORAGE) == PackageManager.PERMISSION_GRANTED
+    } else {
+      true // Not needed on Android 10+
+    }
+
+    if (cameraGranted && storageGranted) {
+      return // All required permissions are granted
+    }
+
+    // Only use the old flow if permissions are actually missing
+    // This prevents the callback hang when Android thinks permissions are granted
+    ensureCameraPermissionsAreGrantedInternal()
+  }
+
+  private suspend fun ensureCameraPermissionsAreGrantedInternal(): Unit = suspendCancellableCoroutine { continuation ->
     val permissions = appContext.permissions ?: throw ModuleNotFoundException("Permissions")
+    android.util.Log.d("ImagePickerModule", "Requesting camera permissions...")
 
     permissions.askForPermissions(
       { permissionsResponse ->
@@ -277,6 +299,7 @@ class ImagePickerModule : Module() {
           if (permissionsResponse[Manifest.permission.CAMERA]?.status == PermissionsStatus.GRANTED) {
             continuation.resume(Unit)
           } else {
+            android.util.Log.w("ImagePickerModule", "Camera permission denied")
             continuation.resumeWithException(UserRejectedPermissionsException())
           }
         } else if (
  ```
</details>



this is how I use permissions if that matters to someone: 

<details>

<summary>click me</summary>


```ts
import { useCallback } from 'react';

import { Asset } from '#/typings';
import {
  getCameraPermissionsAsync,
  requestCameraPermissionsAsync
} from 'expo-image-picker';

import { checkCameraPermission } from '@functions/image';

import { useForegroundNotification } from '@hooks/useForegroundNotification';

import { cameraPermissionsError } from '@utils/commonAlerts';
import { crop, openCamera } from '@utils/picker';
import { sleep } from '@utils/utils';

type CameraOptions = {
  errorContext?: string;
  onError?: (e: any) => void;
  skipCropOnAndroid?: boolean;
};

/**
 * A hook for handling camera operations with consistent error handling
 * @returns A function to open camera and process the image
 */
export const useCamera = () => {
  // this foreground notification makes sure the app never closes or killed from OS
  const { startForegroundService, stopForegroundService } = useForegroundNotification(
    {
      alert: false,
      onServiceErrorCallBack: () => {
        console.warn('Foreground service error');
      }
    },
    {
      ServiceType: 'dataSync',
      icon: 'ic_launcher',
      importance: 'low',
      message: 'App will stay alive during capture',
      setOnlyAlertOnce: true,
      title: 'Camera Active',
      visibility: 'secret'
    }
  );

  const handleCameraCapture = useCallback(
    async <T>(
      onSuccess: (image: Asset) => T | Promise<T>,
      options: CameraOptions = {}
    ): Promise<T | undefined> => {
      const { errorContext = 'CameraCapture', onError } = options;

      try {
        await startForegroundService();
        /* Add small delay to let foreground service stabilize */
        await sleep(100);
        await checkCameraPermission();
        const { status } = await getCameraPermissionsAsync();
        if (status !== 'granted') {
          const perm = await requestCameraPermissionsAsync();
          if (perm.status !== 'granted') {
            throw new Error('Required permission not granted');
          }
        }
        const img = await openCamera();

        /* Add delay after camera capture, similar to gallery */
        await sleep(500);

        const croppedImage = await crop(img.uri);

        if (croppedImage) {
          return await onSuccess(croppedImage);
        }

        return undefined;
      } catch (e: any) {
        console.log(e);
        if (onError) {
          onError(e);
        } else {
          cameraPermissionsError(e, errorContext);
        }
        return undefined;
      } finally {
        await stopForegroundService();
      }
    },
    [startForegroundService, stopForegroundService]
  );

  return { handleCameraCapture };
};
```

</details>

**Comment by CarlosZiegler** [comment]
Can you share the useForegroundNotification logic ?

**Comment by efstathiosntonas** [comment]
@CarlosZiegler saw that coming 😄 so I just created this repo: https://github.com/efstathiosntonas/expo-foreground-service

**Comment by efstathiosntonas** [comment]
@CarlosZiegler don't know if you applied the patch above or not but I added a 2nd, cleaner patch, just fyi.

**Comment by lukmccall** [comment]
Thanks for all your reports!

I was able to fix this issue. Unfortunately, some upstream changes to React Native were required - you can find the PR [here](https://github.com/facebook/react-native/pull/53898). I'll try to land it as soon as possible, and we will likely backport it to older SDKs. However, I can't promise you any timeline since it will require action from the Meta team.

**Comment by efstathiosntonas** [comment]
@lukmccall hi, I've built rn from source with the PR patch applied and still can't launch the camera, expo 54, rn@0.81.4, paper, bare rn with expo-modules

**Comment by lukmccall** [comment]
@efstathiosntonas I didn't test it on the old arch. Let me see if I can fix it there, too.

**Comment by lukmccall** [comment]
@efstathiosntonas now it should work - I've updated my PR.

**Comment by efstathiosntonas** [comment]
Works as a charm. Thank you @lukmccall for the proper fix!

<details>
  <summary>Show patch</summary>

`react-native+0.81.4.patch`
  
 ```patch
diff --git a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactActivityDelegate.java b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactActivityDelegate.java
index 12793d9..3ca6c66 100644
--- a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactActivityDelegate.java
+++ b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactActivityDelegate.java
@@ -21,6 +21,7 @@ import com.facebook.infer.annotation.Assertions;
 import com.facebook.infer.annotation.Nullsafe;
 import com.facebook.react.bridge.Callback;
 import com.facebook.react.bridge.ReactContext;
+import com.facebook.react.common.LifecycleState;
 import com.facebook.react.interfaces.fabric.ReactSurface;
 import com.facebook.react.internal.featureflags.ReactNativeNewArchitectureFeatureFlags;
 import com.facebook.react.modules.core.PermissionListener;
@@ -246,15 +247,32 @@ public class ReactActivityDelegate {
   }
 
   public void onRequestPermissionsResult(
-      final int requestCode, final String[] permissions, final int[] grantResults) {
-    mPermissionsCallback =
-        args -> {
-          if (mPermissionListener != null
+          final int requestCode, final String[] permissions, final int[] grantResults) {
+    Callback permissionsCallback = args -> {
+      if (mPermissionListener != null
               && mPermissionListener.onRequestPermissionsResult(
-                  requestCode, permissions, grantResults)) {
-            mPermissionListener = null;
-          }
-        };
+              requestCode, permissions, grantResults)) {
+        mPermissionListener = null;
+      }
+    };
+
+    LifecycleState lifecycle;
+    if (isFabricEnabled()) {
+      ReactHost reactHost = getReactHost();
+      lifecycle = reactHost != null ? reactHost.getLifecycleState() : LifecycleState.BEFORE_CREATE;
+    } else {
+      ReactInstanceManager instanceManager = getReactInstanceManager();
+      lifecycle = instanceManager.getLifecycleState();
+    }
+
+    // If the permission request didn't show a dialog to the user, we can call the callback immediately.
+    // Otherwise, we need to wait until onResume to call it.
+    if (lifecycle == LifecycleState.RESUMED) {
+      permissionsCallback.invoke();
+      return;
+    }
+
+    mPermissionsCallback = permissionsCallback;
   }
 
   protected Context getContext() {
```

</details>

**Comment by DanielDanaee** [comment]
@lukmccall im on RN 0.79.5 (Expo 53). Is your patch expected to work there as well? Cause i applied it but it did not make a difference. ImagePicker.launchCameraAsync still is unresponsive on Android 16 (security update 5th of Sept).

**Comment by efstathiosntonas** [comment]
@DanielDanae are you building react-native from source? Just applying the patch with patch-package won’t make any difference.

**Comment by DanielDanaee** [comment]
@efstathiosntonas why would it not? You are saying i need to build the react-ative package after? would it not get overwritten after every install?

**Comment by efstathiosntonas** [comment]
read this on how to build from source: https://reactnative.dev/contributing/how-to-build-from-source

don’t know if this is possible with expo. My project has bare rn with expo modules so I can patch it.

**Comment by Dony2100** [comment]
I’m experiencing the same issue: the camera doesn’t launch even after granting permission.
I first noticed this after upgrading from Expo SDK 50 to 53.
I then upgraded again to Expo SDK 54.0.0, hoping it would resolve the problem, but the camera is still not working.

**Comment by redbluenat** [comment]
So the only solution is to move from Expo Image Picker to react-native-image-crop-picker? I have react native 0.76 and expo 0.52

**Comment by Dony2100** [comment]
> So the only solution is to move from Expo Image Picker to react-native-image-crop-picker? I have react native 0.76 and expo 0.52

expo sdk 52 doesn't support android API 35, so you will need to upgrade it to expo 53.

**Comment by glebourgeois** [comment]
Same issue here, that is very annoying...

**Comment by Dony2100** [comment]
@alanjhughes Could you provide an estimated timeline for when this issue can be fixed? This will help me plan the next steps and align testing accordingly.

**Comment by alanjhughes** [comment]
@Dony2100 as mentioned above, the issue requires a fix in react native core. You can track the status here https://github.com/facebook/react-native/pull/53898

**Comment by efstathiosntonas** [comment]
Hey guys, if you can't wait this hacky way fixes it for now: https://github.com/expo/expo/issues/39480#issuecomment-3322702647

you can use patch-package on it.

**Comment by jamsch** [comment]
Whew, thought this was an issue in my library (`expo-speech-recognition`) and assumed it was a software update related to the android speech recognizer. 

Looks like you'll need to fetch the current permissions before requesting any, e.g. this is what I've done in client code:

```ts
let microphonePermissions = await ExpoSpeechRecognitionModule.getMicrophonePermissionsAsync();

if (!microphonePermissions.granted && microphonePermissions.canAskAgain) {
  microphonePermissions = await ExpoSpeechRecognitionModule.requestMicrophonePermissionsAsync();
}

if (!microphonePermissions.granted) {
  // throw an error
}
```

**Comment by igghera** [comment]
Same issue here, production is broken right now

**Comment by jasonrastovski** [comment]
We are currently experiencing the issue with `ImagePicker.launchCameraAsync` mentioned at the beginning of this thread (camera doesn't open until the app is backgrounded and then resumed). I have a temporary workaround that seems to be working well for us.  

Basically using `setTimeout` to wait 500ms, and then using the `Linking.openURL` function to "re-open" the current app (we have the app SCHEME stored in our environment file because we have a different scheme for each environment).

Snippet of our code:

```typescript
      // this is a temporary workaround for a bug in the expo-image-picker library
      // see: https://github.com/expo/expo/issues/39480
      // the gist of the bug is that due to an Android security update, the camera does not
      // open until the app is backgrounded and then resumed.
      // so for now, we'll simulate that by opening the app's scheme URL after a short delay
      if (Platform.OS === "android") {
        setTimeout(() => {
          Linking.openURL(`${process.env.SCHEME}://`);
        }, 500);
      }

      const imagePickerResult = await ImagePicker.launchCameraAsync({ mediaTypes: ["images"] });
```

**Comment by MasatoDev** [comment]
The same issue also exists with expo-camera’s requestCameraPermissionsAsync, right?

**Comment by chuckjrussell** [comment]
Hey all, just wanted to reach out and see if there was a timeline yet on getting this https://github.com/facebook/react-native/pull/53898 PR merged in? We have production apps that are currently down and it is affecting our end users. I've made an attempt to integrate the patches but compiling from source isn't as straightforward as just patching packages.

In the mean time, if there are any better resources for enabling source compilation so that I can test the patches and get my users back up and running, that would be great.

**Comment by chuckjrussell** [comment]
> So the only solution is to move from Expo Image Picker to react-native-image-crop-picker? I have react native 0.76 and expo 0.52

@redbluenat Did you have any luck with `react-native-image-crop-picker`? I might give it a shot to see if it can get us back up and running while `expo-image-picker` gets resolved, but I wasn't sure if there was anything in it to suggest that it would be any different given that the bug is in react native's core.

**Comment by redbluenat** [comment]
@chuckjrussell Yes, go for it! After the migration, the camera works without issues.

**Comment by JayStringer** [comment]
@chuckjrussell I've also switched over successfully, it was pretty painless and doesn't exhibit the same problems that expo-image-picker does.

**Comment by chuckjrussell** [comment]
@redbluenat  @jamsch cheers legends!

**Comment by lucasbourgeois-dotcom** [comment]
it seems that `Camera.getCameraPermissionsAsync()` is always resolving with permissionStatus.
I workedaround the `Camera.requestCameraPermissionsAsync()` not resolving after giving permission like so

```typescript
let hasGranted = false;

// always resolving with status
const {status} = await Camera.getCameraPermissionsAsync();

hasGranted = status === PermissionStatus.GRANTED;

if (status !== PermissionStatus.GRANTED) {
	// resolving only the firstTime
	const {status: askedPermissionStatus} = await Camera.requestCameraPermissionsAsync();
	hasGranted = status === PermissionStatus.GRANTED;
}

// keeps going on depending on hasGranted
```

Tested and working 👍

**Comment by jean-ben-guigui** [comment]
> We are currently experiencing the issue with `ImagePicker.launchCameraAsync` mentioned at the beginning of this thread (camera doesn't open until the app is backgrounded and then resumed). I have a temporary workaround that seems to be working well for us.
> 
> Basically using `setTimeout` to wait 500ms, and then using the `Linking.openURL` function to "re-open" the current app (we have the app SCHEME stored in our environment file because we have a different scheme for each environment).
> 
> Snippet of our code:
> 
>       // this is a temporary workaround for a bug in the expo-image-picker library
>       // see: https://github.com/expo/expo/issues/39480
>       // the gist of the bug is that due to an Android security update, the camera does not
>       // open until the app is backgrounded and then resumed.
>       // so for now, we'll simulate that by opening the app's scheme URL after a short delay
>       if (Platform.OS === "android") {
>         setTimeout(() => {
>           Linking.openURL(`${process.env.SCHEME}://`);
>         }, 500);
>       }
> 
>       const imagePickerResult = await ImagePicker.launchCameraAsync({ mediaTypes: ["images"] });

That helped a lot. The same strategy can be applied to ImagePicker.requestCameraPermissionsAsync().

**Comment by chuckjrussell** [comment]
@redbluenat @JayStringer Yes you all are life savers! This package was almost a direct drop in that just worked instantly, thanks so much!

**Comment by i-can-code-this** [comment]
Greetings, after installing the package and building the project the resulting apk file wont install to any of my android emulators with the react-native-image-crop-picker package. @redbluenat @JayStringer @chuckjrussell

**Comment by igghera** [comment]
@i-can-code-this can you share the error you get when trying to install it on your emulators? I had no problem whatsoever with react-native-image-crop-picker and replaced successfully expo-camera to fix this open issue, like many others.

**Comment by i-can-code-this** [comment]
So I got the build to work it was a matter of going to bed and waking up the next day. However when I build and deploy on the emulator its the same issue still with the react-native-image-crop-picker package, I try to open the camera and once again I have to get the app into the background then out again to access the camera. Mab'ye I got to sleep and wake up again @igghera

**Comment by igghera** [comment]
@i-can-code-this in my case I replaced

```
import * as ImagePicker from "expo-image-picker";
let result = await ImagePicker.launchCameraAsync({});
```

with

```
import ImagePicker from "react-native-image-crop-picker";
let result = await ImagePicker.openCamera({})
```

and it just worked. Are you doing like this? Can you share some code?

**Comment by i-can-code-this** [comment]
Solved @igghera 
Issue in addition to launchCameraAsync was this 
```
    const { status } = await requestCameraPermissionsAsync();
```
I had to remove that from my function, or conditional for iOS
I @!#@%#@$^$# hate expo and will never use the scam of a framework again or make sure I get paid millions before I touch it. I hear react-native forces people to uses expo so they can get screwed into paying for it is that true, what a 2#$^@$^#$ shame cost me soo much in time, effort and relationships.


---------------------------------------------------------------------------------
However say if the user opens the camera but sets don't allow the 2nd time they are prompted that the need to give permission, but if they deny a 3rd time after that the prompt does not appear no error message occurs and the users will need to be smart enough to go to app settings to enable the permission or reinstall the app. What about this edge case? I made a ticket https://github.com/ivpusic/react-native-image-crop-picker/issues/2214

**Comment by gautamj-ctrl** [comment]
I’m still encountering the same issue while using Expo Image Picker. Could you please let me know when this issue is expected to be resolved?

**Comment by goodpickle** [comment]
~Updating to expo 54 worked for us.~

~We switched to using `react-native-image-crop-picker` after watching this issue for 3 few weeks. This worked okay for Android, but we weren't able to get it to work for iOS. We were able to get `expo-camera` working for iOS, but those two branches were not compatible with each other.~

~We went back to updating to Expo 54 which we failed at previously due to some animation issues Gluestack was having. However, this time we were able to get everything updated and working.~

Update:

It looks like updating to expo 54 wasn't the solution we hoped for. Unsure how we tested this and found it as a fix yesterday. 😢 We will have to go back to `react-native-image-crop-picker` for Android.

**Comment by Dony2100** [comment]
@alanjhughes, @lukmccall  it seems the issue was closed. could you explain what the solution is?

**Comment by hariDasu** [comment]
unbelievable @expo-bot why is this closed??? its not fixed

**Comment by nathalia-rus** [comment]
not fixed!

**Comment by DzmitryITGlue** [comment]
why it is marked as fixed? do we have published version of expo-image-picker with applied fix?

**Comment by hariDasu** [comment]
my guess its marked as 'closed' since people are using https://github.com/ivpusic/react-native-image-crop-picker instead of expo-image-picker.. i am using this on android for now it is "working"

**Comment by goodpickle** [comment]
Upgrading to react-native 0.81.5 fixes this issue. It was released yesterday afternoon.

**Comment by gboudreau** [comment]
I am still on Expo 53 (and thus react-native 0.79).  
I tried to create a patch for the .java file as detailed in the commit for react-native 0.81.5 [here](https://github.com/facebook/react-native/pull/53898/files?w=1). That doesn't seem to resolve the original issue, where calling `launchCameraAsync` only works after manually putting the app in background, and coming back to it, irrelevant of if the app has been granted permission to do that.

**Comment by Dony2100** [comment]
Expo 54, and react-native 0.81.5 resolved the issue.

**Comment by rogeonee** [comment]
Still the same issue - Expo 52, RN 0.76.3, and latest Android 16

**Comment by TilliboyF** [comment]
@rogeonee I can confirm, that the patch mentioned in the [comment](#issuecomment-3322702647) above works perfectly fine and helped my team and me to get prod back up working - Expo 52, RN 0.76.9, expo-image-picker 16.0.6

**Comment by gboudreau** [comment]
> [@rogeonee](https://github.com/rogeonee) I can confirm, that the patch mentioned in the [comment](#issuecomment-3322702647) above works perfectly fine and helped my team and me to get prod back up working - Expo 52, RN 0.76.9, expo-image-picker 16.0.6

@TilliboyF It resolves the issue with `launchCameraAsync` too, not just with permissions?  
Reading that patch, it seems to apply only to permissions, nothing appears relted to `launchCameraAsync`, which has the same issue as the permissions prompts..?

**Comment by TilliboyF** [comment]
@gboudreau I left everything as it was. That's an example call:
```js
const crop = imageCrop ? { aspect: [1, 1] } : {}
let result = await ImagePicker.launchCameraAsync({
        mediaTypes: ['images', 'livePhotos', 'videos'],
        allowsEditing: true,
        quality: 0.5,
        videoMaxDuration: 30,
        ...crop
    })
```
I am testing on a pixel 7 with the latest updates. After applying the patch and doing a fresh build via expo, I can take photos and videos like before.

How I understand the issue is that with the android update the permission state isn't resolving correctly. If you call launchCameraAsync, it is stuck getting permissions it already has. That's what the patch fixes. For now, that's fine until the update cycle of my team is updating to sdk54. Then we have to look, if the issue is resolved in some update of RN or the library itself.

**Comment by i-can-code-this** [comment]
This is stupid can someone point out the code responsible for making sure the app doesn't need to go to the background in order for the camera to be shown. Or is some PR move from expo when the whole framework is broken smh

**Comment by GoodSir42** [comment]
react native fixed that issue in 0.81.5 if I see that correctly. this is a dependency of one of the recent expo updates. https://github.com/facebook/react-native/releases/tag/v0.81.5 Everything seems to work fine with this again and we could undo our temporary fixes in our project.

**Comment by DzmitryITGlue** [comment]
> react native fixed that issue in 0.81.5 if I see that correctly. this is a dependency of one of the recent expo updates. https://github.com/facebook/react-native/releases/tag/v0.81.5 Everything seems to work fine with this again and we could undo our temporary fixes in our project.

Also can confirm that upgrading to 0.81.5 fixed the issue. But 0.81.5 has other issues and I can understand if someone don't wish to upgrade to it and keep using patch

**Comment by aimilne** [comment]
Is it possible to get the React Native fix integrated into Expo 53? 

I was able to apply the fix as a patch and rebuild Android RN from source ([see this thread](https://github.com/facebook/react-native/pull/53898)) and it seems to work well

This is a pretty critical defect - it would be good for all expo 53 users to get this in an update (and not have to rebuild from source which adds a considerable amount of time to the builds, and load on the servers)

**Comment by hungrymike** [comment]
A little help to everyone that cannot upgrade to expo 54. I noticed the permissions worked in our videocall calls so you can use this fix:

// App root / _layout
import { registerGlobals } from 'react-native-webrtc-web-shim';
registerGlobals();

// HACK - Ask though the polyfill
const stream = await navigator.mediaDevices.getUserMedia({
        video: {
          width: 640,
          height: 480,
        },
        audio: false,
});
stream.getTracks().forEach((track) => track.stop());


... normal expo logic here, expo-camera or image picker.

This works on web, android and ios.

**Comment by arjunken** [comment]
When is this issue going to fixed? I am very disappointed that this issue is still exists and was not considered as a priority. I can't let my app users to launch their camera and easily take pictures which is very inconvenient. The workarounds are not helping out. I want Android and Expo to work together and prioritize this fix.

**Comment by taha200** [comment]
@arjunken  what is your expo Sdk version?

**Comment by arjunken** [comment]
@taha200 I was on 53+. Now, I moved to 54+ that solved the problem. The fix is in Expo SDK 54+ and that requires you to update your React Native to be on 0.81+. You will break things if you just upgrade React Native to 0.81. Going to 54.0 was also challenging for me. Lots of things broke and I had to fix them one by one. Now, I am good.

**Comment by deepakjha005** [comment]
I'm still able to reproduce this issue on the latest versions, and it appears to be the same behavior described in this issue.

**Environment**

Expo SDK: 54.0.2

expo-image-picker: 17.0.11

React Native: 0.81.5

Android: 16

**Devices tested:**

Pixel 8 Pro

Pixel 7a

**Observed behavior**

Calling ImagePicker.launchCameraAsync() does not open the camera immediately.

The interesting part is that the camera launch appears to be deferred until the application's Activity goes through another lifecycle transition.

**For example:**

Tap Use Camera.

launchCameraAsync() is called.

Nothing happens (camera does not open).

Put the app into the background (e.g. open another app from Recents) and then return.

The camera opens automatically.

The same behavior also occurs after locking and unlocking the device.

If the user taps the camera button multiple times while nothing is happening, multiple camera activities are queued and are launched one after another once the lifecycle transition occurs.

**Additional observations**

Camera permission is already granted before calling launchCameraAsync(), so this does not appear to be related to the permission request flow.

Reproduced consistently on both Pixel 7a and Pixel 8 Pro.

I verified the same flow on other Android devices and could not reproduce the issue there.

The issue persists even after killing and reopening the app.

Another commenter in this thread mentioned that triggering a lifecycle change using Linking.openURL(<app-scheme>://)works as a temporary workaround. That workaround also matches the behavior I'm observing, which further suggests that the camera launch is waiting for an Activity lifecycle transition before being executed.

**Relevant logcat**

When launchCameraAsync() is invoked, Expo reaches the Activity Result launcher:

expo.modules.kotlin.activityresult.AppContextActivityResultRegistry.onLaunch(AppContextActivityResultRegistry.kt:148)
expo.modules.kotlin.activityresult.AppContextActivityResultLauncher.launch(AppContextActivityResultLauncher.kt:26)
expo.modules.imagepicker.ImagePickerModule$definition$1$5$1.invokeSuspend(ImagePickerModule.kt:79)
expo.modules.imagepicker.ImagePickerModule$launchPicker$2.invokeSuspend(ImagePickerModule.kt:243)
Android also logs the following warnings immediately before the camera activity is started:

Implicit URI read grant for ImageCapture action will be discontinued from Android 18 onwards.
Implicit URI write grant for ImageCapture action will be discontinued from Android 18 onwards.
The camera activity is eventually launched by Android:

ActivityTaskManager: START u0 {act=android.media.action.IMAGE_CAPTURE ...}
cmp=com.google.android.GoogleCamera/com.android.camera.activity.CaptureActivity
Immediately afterwards, React Native reports the expected lifecycle callbacks:

ReactHost.onUserLeaveHint(activity)
ReactHost.onHostPause(activity)
ReactContext.onHostPause()
From my testing, this looks like the intent to launch the camera is created successfully, but on Pixel devices running Android 16 it is not presented until another Activity lifecycle transition occurs.

If there's any additional logging or a minimal reproduction that would help, I'd be happy to provide it.
