### ISSUE TITLE
Native tabs android missing images from built app

### ISSUE THREAD

**Issue by coryoso** [expo/expo#41031]
### Minimal reproducible example

https://github.com/coryoso/expo-native-tabs-images

### Steps to reproduce

When creating an app with the new native tabs (`expo-router/unstable-native-tabs`), icons are not visible when using `src` on Android non-development production/preview builds.

- Create new app
- Change `_layout` in (tabs) to:
```
import { Icon, Label, NativeTabs } from 'expo-router/unstable-native-tabs';
import React from 'react';

export default function TabLayout() {
  return (
    <NativeTabs>
      <NativeTabs.Trigger name="index">
        <Label>Home</Label>
        <Icon src={require('@/assets/images/home.png')} />
      </NativeTabs.Trigger>
      <NativeTabs.Trigger name="explore">
        <Icon src={require('@/assets/images/globe.png')} />
        <Label>Explore</Label>
      </NativeTabs.Trigger>
    </NativeTabs>
  );
}
```
- Add development build (`bunx expo install expo-dev-client`)
- Run app in simulator (`bunx expo run:android`), the images are present:
<img width="1280" height="2856" alt="Image" src="https://github.com/user-attachments/assets/e064d8f3-4fa3-45aa-9bbc-25cfae00bcf1" />
- Run app on device with built app, no metro server (`eas build --platform android --profile preview --local`, `adb install xy.apk`). The images are missing:

<img width="1084" height="2412" alt="Image" src="https://github.com/user-attachments/assets/27c8fd78-1d60-4262-b179-7569a26a6bba" />

### Environment

```text
expo-env-info 2.0.7 environment info:
  System:
    OS: macOS 26.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: DriverKit 25.1, iOS 26.1, macOS 26.1, tvOS 26.1, visionOS 26.1, watchOS 26.1
  IDEs:
    Android Studio: 2024.3 AI-243.25659.59.2432.13423653
    Xcode: 26.1.1/17B100 - /usr/bin/xcodebuild
  npmPackages:
    expo: ~54.0.23 => 54.0.23
    expo-router: ~6.0.14 => 6.0.14
    react: 19.1.0 => 19.1.0
    react-dom: 19.1.0 => 19.1.0
    react-native: 0.81.5 => 0.81.5
    react-native-web: ~0.21.0 => 0.21.2
  Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
17/17 checks passed. No issues detected!
```

**Comment by lephuvu1994** [comment]
The same issue. At first, I thought it might be related to fonts, but even when I tried using PNG images, it still didn’t work. I’m not sure if it has anything to do with the EAS build of Expo Dev Client.

**Comment by Ubax** [comment]
Hi @coryoso 
This is an issue in react-native-screens - https://github.com/software-mansion/react-native-screens/issues/3399

The screens team is working on solving it. Please monitor the linked issue.

**Comment by t0maboro** [comment]
should be resolved by: https://github.com/software-mansion/react-native-screens/pull/3413

**Comment by coryoso** [comment]
Very nice, thank you guys! Any idea when this will be live?

**Comment by colin-oos** [comment]
> Very nice, thank you guys! Any idea when this will be live?

Looks like it was released yesterday in v4.19.0 https://github.com/expo/expo/issues/41031#issuecomment-3570469414

**Comment by diptimaya-seneca** [comment]
I can confirm that this is **not fixed** with `"react-native-screens": "~4.19.0"`

However, this is supported already with v4.16.0, the following usage

```
      <NativeTabs.Trigger name="index">
        <Label>Home</Label>
        {Platform.select({
          ios: (
            <Icon
              src={{
                default: require("@/assets/icons/home.png"),
                selected: require("@/assets/icons/home-selected.png"),
              }}
            />
          ),
          android: <Icon drawable="tab_home" />
        })}
      </NativeTabs.Trigger>
```

If you are creating manual deployments, you can write a custom script file that places the drawables in android folder, the following are examples of the above icon for android

tab_home.xml
```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_selected="true" android:drawable="@drawable/tab_home_selected" />
    <item android:drawable="@drawable/tab_home_default" />
</selector>
```

Hope this helps.

**Comment by t0maboro** [comment]
Hi @diptimaya-seneca 

I've cloned the repro app https://github.com/coryoso/expo-native-tabs-images, and I can confirm that icons don't load when I'm using `react-native-screens@4.16.x` while I'm building the project in release mode with `npx expo run:android --variant release`. However, after upgrading to `react-native-screens@4.19.x`, everything works correctly - both: 
- when building via `eas build --platform android --profile preview --local` - as mentioned in the original issue 
- when I'm using `npx expo run:android --variant release`.

If I understand your use case correctly, where you're referencing drawables, the approach of adding assets via the Android Resource Manager is the proper one. This is currently the only way to load SVG assets on Android, as Fresco (the library we're relying on for loading icons in the tabs) doesn't have SVG support.

If you have any setup showing that the issue persists on your side, even after upgrading `react-native-screens` to `4.19`, could you provide a complete minimal repro that demonstrates the case that's still not working? This would help in investigating the issue

**Comment by ahmad2point0** [comment]
Add the following line inside the expo object in **app.json:**

`assetBundlePatterns": ["**/*", "src/assets/**/*"]`

This ensures that custom PNG icons for native tabs are properly bundled and displayed in the production build.
Thanks! 😊

**Comment by coryoso** [comment]
Had some time checking this. Did as @t0maboro was describing by overwriting the `react-native-screen` version to 4.19.x which worked great! Thank you.

@ahmad2point0 `assetBundlePatterns` seems to be deprecated as I couldn't find anything about this… As it was fine by just bumping the version in did not look too much into it tho. Will close the issue, again thx!

**Comment by ahmad2point0** [comment]
@coryoso Im using expo sdk 54 and when i run expo-doctor it shows use react-native-screen version 4.16.x which compatible with expo sdk 54.

**Comment by hoangman1108** [comment]
it happen to me.
"react-native-screens": "4.19.0",
 "expo-router": "6.0.19",
