### ISSUE TITLE
[expo-gl] Android SIGSEGV (SEGV_MAPERR) crash in expo::gl_cpp::ensurePrototypes with Hermes

### ISSUE THREAD

**Issue by schnellerzug** [expo/expo#41625]
### Minimal reproducible example

https://github.com/schnellerzug/repro-expo-gl-three

### Steps to reproduce

I am experiencing a consistent native crash (SIGSEGV) on Android in Release/Preview builds when rendering a basic @react-three/fiber scene. The crash occurs during the WebGL renderer initialization within libexpo-gl.so.

This issue is reproducible in a minimal standalone project and seems to be related to expo-gl's interaction with the JS runtime (Hermes) in production builds.

Steps to Reproduce
1.Clone the minimal reproduction repository
2.Install dependencies
3.Generate the Android native project npx expo prebuild -p android --clean
4. Build the release APK (crash does not reliably reproduce in development or in expo go): cd android && ./gradlew :app:assembleRelease
5.Install and launch on a physical device

Expected Behavior

The app should launch and render the simple 3D scene (e.g., a rotating cube) without crashing the native layer.
Actual Behavior

The app crashes immediately upon startup (or when the GL view initializes) with a native segmentation fault.

Crash Log:
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
...
#00 pc ... libhermes.so
#01 pc ... libexpo-gl.so (expo::gl_cpp::ensurePrototypes(facebook::jsi::Runtime&)+124)
#02 pc ... libexpo-gl.so (expo::gl_cpp::createWebGLRenderer...)
#03 pc ... libexpo-gl.so (expo::gl_cpp::EXGLContext::prepareContext...)
#04 pc ... libexpo-gl.so (EXGLContextPrepare...)

### Environment

```text
expo-env-info 2.0.8 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 24.3.0 - C:\nvm4w\nodejs\node.EXE
      Yarn: 1.22.22 - C:\nvm4w\nodejs\yarn.CMD
      npm: 11.4.2 - C:\nvm4w\nodejs\npm.CMD
    npmPackages:
      expo: ^54.0.0 => 54.0.29
      react: 19.1.0 => 19.1.0
      react-native: 0.81.5 => 0.81.5
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
17/17 checks passed. No issues detected!
```

**Comment by psnet** [comment]
Can confirm, updating working project with only one package with `expo-gl@16.0.9` causes crash, feels like it is related to **_bundled maven package_** (`/local-maven-repo/`) updated [here](https://github.com/expo/expo/blob/sdk-54/packages/expo-gl/package.json#L46)

**Comment by whomwah** [comment]
I can concur with @psnet. Our project has a suite of `patch` updates I did yesterday including a bump of `expo-gl@~16.0.7` to `expo-gl@~16.0.9` and started crashing on Android when attempting to use `expo-gl`. A pinned downgrade to `expo-gl@16.0.7` fixed the issue.

**Comment by divisuals** [comment]
+1

Confirming that this was introduced in `expo-gl@16.0.9`, probably as part of those performance optimizations. I pinned my app that uses expo-three down to `expo-gl@16.0.8` and the issue is resolved as well.

**Comment by psnet** [comment]
@divisuals these optimization were tested and working correctly, if problem was there it would not compile at all OR crash will be at the time of data supply for OGL (after context will be created), but crash is at init time before OGL context is created.

So problem is somewhere else.

**Comment by psnet** [comment]
I think @lukmccall can really help with this, hope he will be ok I mention him there during holidays

**Comment by TobiDevloft** [comment]
I'm experiencing the same issue on android, pinning to `expo-gl@16.0.7` did not resolve it for me however.

**Comment by psnet** [comment]
@TobiDevloft ensure you install exact version `expo-gl@16.0.7` because this version works (look for lock file for exact installed version).

**Comment by duyanhv** [comment]
> [@TobiDevloft](https://github.com/TobiDevloft) ensure you install exact version `expo-gl@16.0.7` because this version works (look for lock file for exact installed version).

Downgrade to 16.0.7 fix the crash issue on Android for me

**Comment by TobiDevloft** [comment]
@psnet  @duyanhv thank you guys, got it to work on` 16.0.7` - you were right with the version not being locked correctly.

**Comment by elongstreet88** [comment]
Thank you!
This fixed my issue. Oddly, it worked fine in expo go, bug debug/full apk version would always crash:
```
01-03 17:52:25.780 13100 13100 F DEBUG : uid: 10828 
01-03 17:52:25.780 13100 13100 F DEBUG : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 
01-03 17:52:25.780 13100 13100 F DEBUG : Cause: null pointer dereference 
01-03 17:52:25.780 13100 13100 F DEBUG : x0 b40000733b71f3f0 x1 000000328ac...
...
```

**Comment by psnet** [comment]
1 month has passed and no news about the fix

**Comment by tsapeta** [comment]
Hi! We [released beta version of SDK 55](https://expo.dev/changelog/sdk-55-beta) yesterday. I tried to reproduce this issue using the new `expo-gl@55.0.1` and it seems to work as expected (does not crash). My guess is that the precompiled binary of `16.0.9` is corrupted, i.e. built against different version of Hermes. Let me know if someone needs SDK 54-compatible version and using `16.0.7` is not enough.

**Comment by psnet** [comment]
SDK 55 is still in beta, it would be great to have latest `expo-gl` in SDK 54 too.

@tsapeta 

> My guess is that the precompiled binary of 16.0.9 is corrupted, i.e. built against different version of Hermes.

Maybe force rebuild of package?..

**Comment by luchinayan** [comment]
+1

**Comment by whomwah** [comment]
@tsapeta a SDK 54-compatible version would be super helpful as --certainly for the project we are using the lib on-- we are not ready to upgrade to SDK 55 yet. Thank you.

**Comment by renaldo2536** [comment]
Upgraded to Expo 55, android working fine. It's iOS now that happened to have the crash. Did you test it on iOS too ? @tsapeta

**Comment by tsapeta** [comment]
We're planning to release a patch for SDK 54 today.

@renaldo2536 The issue was reported for Android, so no, I didn't test this repro on iOS. Is it the same crash? That would be interesting as we don't prebuilt `expo-gl` on iOS.

**Comment by renaldo2536** [comment]
<img width="1024" height="228" alt="Image" src="https://github.com/user-attachments/assets/613e9790-1029-4472-88b1-ccdbd3fcd4d9" />
I got this error when running it on XCode and accessing the page that using R3F

Expo SDK 55
"expo-gl" : ~55.0.2
"@react-three/drei": "^10.7.7",
"@react-three/fiber": "^9.5.0",

**Comment by alanjhughes** [comment]
Version `16.0.10` of `expo-gl` is available

**Comment by tsapeta** [comment]
I confirm that `16.0.10` works fine for me in the provided repro, so I'm closing this issue.

@renaldo2536 This is a different crash. I'll take a look at that too, but it's unrelated to this one so feel free to open a new one if you want.
