### ISSUE TITLE
I get an 'xcrun simctl' error when in the Expo SDK when I open my project in the iOS simulator.

### ISSUE THREAD

**Issue by MarcusHurney** [expo/expo#418]
For the lifetime of my project and other projects I've made using the Expo SDK, I've gotten this error every single time I open my project in the iOS simulator. It doesn't affect my application in any way, but I do wonder why I am seeing it. Could you please help me understand this error?

<img width="573" alt="screen shot 2017-07-25 at 5 32 17 pm" src="https://user-images.githubusercontent.com/13347886/28599463-a1718274-715f-11e7-823e-e4fbf612ef75.png">

**Comment by lhp--** [comment]
i too

**Comment by lhp--** [comment]
1.sudo gem install cocoapods
2.pod install(in /ios)
3.react-native run-ios
it work :)

**Comment by ide** [comment]
You don't want to use CocoaPods for this, it's unrelated. I suspect that there's either an issue with your iOS simulator or your development server is not running.

First verify the development server is running by opening localhost:19000 (or whatever URL you see in the logs) in your browser. If you get back a JSON response, it's running. If not, click Restart.

Then try uninstalling the Expo app from the iOS simulator and opening your project in the simulator again from XDE. Make sure you're using the simulator with Xcode 8 (Xcode 9 beta is not supported). You also can try Reset Content & Settings in the simulator since it sometimes can get into a bad state, but this is less common.

**Comment by AlberZong** [comment]
Reset Ios content and settings your ios Simulator
I fixed this error

**Comment by skevy** [comment]
Please let us know if resetting the simulator didn't work for you.

Thanks!

**Comment by iamclaytonray** [comment]
@skevy @ide - 

I'm currently running into a similar issue as above. I do see a huge difference in the app. (Tested against several.) Even outside of Expo on the Simulator, everything is running incredibly slow. Every transition takes several seconds. I've deleted the app on the Simulator and my phone. I deleted Expo XDE from my Macbook Pro. I've reset Content & Settings. I've verified that the server is running.

Moving forward, what should I do that hasn't been recommended yet? I'm not really a mobile developer. I'm more of a web guy. In fact, this past month has been the first time I've used Expo.

As far as a repro goes, I can't share either of the apps I am currently working on but I did clone another app (not mine) that is also returning this error. I haven't touched anything in XCode or my `app.json` besides some basic things in the beginning, about a month ago. I changed a few styles and then out of nowhere, this error hit me.

Thanks for any help you can give!

PS: I am running the latest versions on everything, including my OS

**Comment by MarcusHurney** [comment]
Check to see if you are logging to the console frequently. That was the
issue with my app. I was using redux-logger and it was 100% the issue.

**Comment by milanperera93** [comment]
I think you have pressed command+T accidentally which activates the **slow animation feature** Press command+T in the simulator, it disables the Slow animations "feature".

**Comment by iamclaytonray** [comment]
@milanperera93 - Yep. I didn't know that feature existed, which made me think it was Expo. I was able to resolve the issue after accidentally noticing that it was enabled. Thanks! 😄

**Comment by alexi21** [comment]
I had the same problem with a different cause, posting my fix here in case someone encounters the same error. In the simulator go to the Hardware menu and click Erase All Contents And Settings. Try this if the above does not work.

**Comment by alexcittadini** [comment]
@milanperera93, wow you are an angel. Solved the problem and I had been pulling my hair out at how slow standard iOS functions are on the simulator.

**Comment by JacobAndrewSmith92** [comment]
@iamclaytonray I had no idea that it existed either until today. I don't even know when I would've pressed it. 😆

**Comment by hafizali05** [comment]
Fixed this issue by `xcrun simctl shutdown all
`

**Comment by CooLNuanfeng** [comment]
I shutdown my ios simulator and yarn start again , it works

**Comment by ArthurGamby** [comment]
**FOUNT IT!**

you must have a **.watchmanconfig file**   (*like below*)

![Capture d’écran 2019-11-20 à 13 45 11](https://user-images.githubusercontent.com/25017898/69240113-11396800-0b9c-11ea-93d4-841624c6dd7d.png)

When you initialize a project with  `expo init projectname`, there is no watchmanconfig file.

So, Inside this file, just initiale an empty object like this : 

![Capture d’écran 2019-11-20 à 13 49 02](https://user-images.githubusercontent.com/25017898/69240336-886efc00-0b9c-11ea-9c63-aef930db6de9.png)

Then you can start with `expo start` or `yarn/npm start` 

It solved all my problem.

**Comment by ravina26unikwork** [comment]
I tried with above all suggestions, but still getting same error

**Comment by profalves** [comment]
For anyone like me also searching this issue, it is possible to un-eject your app and run again like normal. From the docs, Delete the ios and android directories from your project. Delete the isDetached and detach keys from your project's app.json. You can now use your project like a normal Expo project (with no ExpoKit). Read more at https://docs.expo.io/versions/latest/expokit/advanced-expokit-topics/

**Comment by sharan21** [comment]
My error was that I was using both Xcode 10 and Xcode11, and did 'sudo xcode-select -s /Applications/Xcode10.app'. After changes it to Xcode10 it works.

**Comment by calsal8** [comment]
I did not have a Command Line Tools selected in Xcode. This solved it for me:

https://stackoverflow.com/questions/29108172/xcrun-unable-to-find-simctl

**Comment by brianandreasen1983** [comment]
> I did not have a Command Line Tools selected in Xcode. This solved it for me:
> 
> https://stackoverflow.com/questions/29108172/xcrun-unable-to-find-simctl

@calsal8 This also solved it for me thank you so much for taking the lead on that :)

**Comment by mariacheline** [comment]
> I had the same problem with a different cause, posting my fix here in case someone encounters the same error. In the simulator go to the Hardware menu and click Erase All Contents And Settings. Try this if the above does not work.

This one did it for me! :)
