### ISSUE TITLE
Android Splash Screen `resizeMode: Cover` Production Bug

### ISSUE THREAD

**Issue by SCasarotto** [expo/expo#4494]
### Environment

  Expo CLI 2.19.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 

Android

### Steps to Reproduce
- `resizeMode: Cover`
- `expo build:android`

### Expected Behavior
Display Splash Screen in production like it does on dev.

### Actual Behavior
Displays splash screen fully zoomed in.

### Reproducible Demo
Images for Reference.

On Dev `cover`:
![Screenshot_1559965251](https://user-images.githubusercontent.com/13336976/59141752-7267d900-8978-11e9-89b1-d73a42e0f66f.png)

On Dev `contain`:
![Screenshot_1559965207](https://user-images.githubusercontent.com/13336976/59141754-77c52380-8978-11e9-8fa5-345676a748f4.png)

On Prod `cover`:
![Screenshot_1559965730](https://user-images.githubusercontent.com/13336976/59141756-7f84c800-8978-11e9-9a4d-a96419fc2377.png)

On Prod `contain`:
![Screenshot_1559966391](https://user-images.githubusercontent.com/13336976/59141759-857aa900-8978-11e9-8a26-c76335475533.png)

Original File:
![splash](https://user-images.githubusercontent.com/13336976/59141760-8b708a00-8978-11e9-9933-d2867f9f1988.png)

**Comment by tanx** [comment]
I'm getting really wierd splash screen behavior as well in Expokit on Android. I did a fresh eject after upgrading to expo 33. Here's my setup:

    "expo": "^33.0.3",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "expokit": "^33.0.2",

**Comment by bbarthec** [comment]
Since SDK33 we've cleared some misbehaviours of splash screen modes on Android. You can read about it in [SDK33 SplashScreen docs](https://docs.expo.io/versions/v33.0.0/guides/splash-screens/#differences-between-environments---android). Moreover we have in mind that Android splash screen is troublesome and came up with an idea of clarifying it as described in #3611.

**Comment by CruelMoney** [comment]
I'm having trouble understanding the changes made in 33, and how to use it now.
Before cover mode was bahving as anticipated, and identically across platforms, but now I'm also seeing a image that is too small on android.

**Comment by donni106** [comment]
@CruelMoney same for me. developing with Expo everything seems fine. but with released APK the splash screen behaves like `contain` with some noticeable space around.

I have also created a forum post: https://forums.expo.io/t/sdk-33-splash-screen-with-resizemode-cover-in-production-apk-does-not-fill-the-whole-screen/23991

**Comment by tanx** [comment]
FYI I upgraded to the current expo-cli and expo npm dependencies are re-ejected to expokit. The issue I had with the splash screen was fixed! Thank you :)

**Comment by gopidon** [comment]
Its all confusing now. My standalone app on 33 is broken as far as splash screen is concerned.  "Cover" mode used to work like a charm across iOS and android. What was the need to break something that was working. Can someone from expo team clear this up please.

**Comment by creativemind1** [comment]
Yeah, I was working in the development and I suddenly saw the App not working and getting stuck at 100% Splash screen on Android but working fine in iOS.

**Comment by bbarthec** [comment]
As @tanx observed, please update your `expo-cli` to the newest version and re-eject. Unfortunately things were not ideal previously regarding Android Splash Screen and some other issues had been observed, so therefore some changes were required. sorry for the inconvenience 😢

**Comment by gopidon** [comment]
How abt apps that are not ejected? I still don't understand what was the issue previously? Its actually an issue NOW!

**Comment by donni106** [comment]
With the latest expo-cli (2.20.5) my splash screen works fine in the latest release!

**Comment by CruelMoney** [comment]
Confirmed, it works as before using the newest expo-cli.

**Comment by gopidon** [comment]
yup. it works after updating expo-cli to the latest version. Thanks

**Comment by rahamin1** [comment]
Same here. Tested splash resizeMode='cover' on Android only.

- Before SDK 33, expo-cli 2.x: worked well
- When upgraded to SDK 33, still using , expo-cli 2.x, displayed a small splash surrounded by black background
- Upgraded expo-cli to 3.0.2, using sdk-33, works well
