### ISSUE TITLE
g.nativeCallSyncHook is not a function 

### ISSUE THREAD

**Issue by saiyam-sage** [expo/expo#4500]
hello 

I have updated expo SDK version to 33 and it is working, then I have installed some expo library with this command 

now I am getting this error, so should I do?
![IMG_0064](https://user-images.githubusercontent.com/45175251/59148574-54f24800-8a28-11e9-9a1a-2f4692adbdcc.PNG)

**Comment by brentvatne** [comment]
please create a new issue and follow the issue template, thank you!

**Comment by bogrees** [comment]
@brentvatne, go here: https://www.npmjs.com/package/expo-codemod

Run this:
`npx expo-codemod sdk33-imports src`

**Comment by brentvatne** [comment]
if anyone encounters this, it happens when you have remote debugging (in chrome) enabled and production mode enabled at the same time

**Comment by sonyarouje** [comment]
thanks @brentvatne I was breaking my head for last couple of hours. I tried all different approach to solve it but nothing worked out. Lucky that I saw your comment and it resolved the issue.

Thanks once again.

**Comment by bscaspar** [comment]
I ran into this without Chrome remote debugging. I think upgrading to the latest version of expo-cli resolved it.

**Comment by tonypee** [comment]
@brentvatne - Can you explain please what that means? When it is running in production, i thought  debugging became disabled. I see that it's popping up the debug window - how do i turn this off? - I've just forgotten the process atm

**Comment by Xopsy** [comment]
> @brentvatne - Can you explain please what that means? When it is running in production, i thought debugging became disabled. I see that it's popping up the debug window - how do i turn this off? - I've just forgotten the process atm

You have to stop your remote debugging:
https://docs.expo.io/versions/v35.0.0/workflow/development-mode/

![Screen Shot 2019-10-28 at 15 09 01](https://user-images.githubusercontent.com/12572318/67709821-1dfbdf00-f995-11e9-8126-2c3744d2c19e.png)

Thanks @brentvatne ;)

**Comment by thanh90** [comment]
![Screen Shot 2019-11-05 at 5 36 07 PM](https://user-images.githubusercontent.com/30317015/68191442-e45d5080-fff2-11e9-8fb6-5871acaa65b9.png)
I accidently turned on the Production Mode

**Comment by wade-montague** [comment]
For me @brentvatne was exactly what I needed to do and have been noticing this on and off for a while but not figured out what it was so thanks for that! 

I had to switch expo back out of production mode to gain access to the full debug menu within the emulated device. Once done was able to switch expo back to production mode and use as normal.

**Comment by stuckj** [comment]
I just wasted a couple hours on this as well (this issue didn't pop up in a google search I stupid me didn't look here first). I'm gonna open a separate feature request to have a more useful error message or to just disable remote debugging when production mode is turned on.

**Comment by stuckj** [comment]
It's here: https://expo.canny.io/feature-requests/p/disable-remote-debugging-when-production-mode-is-enabled

Feel free to upvote if you've hit this and would like to help out future developers (or yourself in a year or so when you forget about this issue ;-)).

**Comment by bbarthec** [comment]
@stuckj, do you mind providing more detailed scenario when the crash is happening?
I've just tested following scenario, using the newest `expo-cli@4.3.4` and obtained no crash:
- `expo init` (SDK-40, managed with tabs) (also tested with SDK-39)
- `expo start` (`development mode`)
- open `dev menu` in the app and turn on `remote debugging` (opened chrome, set breakpoint in the code)
- change mode to `production` (either using switch on server Web UI or `p` key in CLI)
- back to the app (either on iOS Simulator or Android emulator), open `dev menu` and reload
- success (no crash, app reloaded)
  - on Android, remote debugging is not working - expected
  - on iOS, remote debugging seems to work anyway - not expected, but no crush here too 🤷

**Comment by bbarthec** [comment]
@stuckj, ok, I've just hit the error by changing the order of performed actions:
- `expo start`
- open the app in the simulator/emulator
- switch to `production mode` (this do not trigger auto-reload)
- in the app (that is still loaded a `development` version) enable `remote debugging`
- `reload` the app ➡️ crash 💥

**Comment by stuckj** [comment]
@bbarthec, I just repro'd the problem with the latest `expo-cli@4.3.4`. My steps were similar to yours, but in the order that it happened to me (and I think more likely to happen to an unsuspecting developer). Here's what I did:

- `expo start`
- With `production mode` off, start the app  in the simulator.
- Enable remote debugging (since you're debugging the non-production mode)
- Switch on `production mode` in developer tools (does not auto-reload)
- In the simulator, reload the app (Ctrl-Cmd-Z on Mac and choose reload from dev menu)
- The bundle will reload and the app will crash upon restart.

I think it's the same case you're hitting only the debugging is enabled before switching to production. I feel like if a dev enables debugging on a production app that's somewhat on them (though perhaps it should be prevented if it will crash). But, if it was left on from development mode when you switch to production mode I feel like it should get shut off automatically (or a warning...or basically anything to indicate what the problem is so they can turn debugging back off :) ).

Thanks for looking into this.

**Comment by bbarthec** [comment]
@stuckj, I've tried to reproduce the erroneous scenario for a couple of times now (both on physical device and iOS simulator), but I've failed to 😅 I've also tested it against current repository `master` branch and failed to be hit by that error message reported above 👀 
Do you mind checking once again if the error is still happening?
I've been testing using following:
- `expo-cli@4.10.1`
- SDK 42 managed blank project coming from the `expo init`
- iOS simulator running iOS 14.5

I believe the issue is fixed already (either by some minor Expo Go patch or `expo-cli` update) and you'll not hit the problem again 💪

**Comment by stuckj** [comment]
I can repro it in the simulator using the same steps I mentioned above. Just to verify it wasn't fixed in SDK 42 (which we're not using in our app yet), I made a fresh app with expo init. Here's a video showing the problem. This is with:

- `expo-cli@4.11.0`
- Latest expo go app (it installed an update when I ran with the test app). It says Client version: expo go 2.21.3.10300 in the home screen
- iPhone 12 simulator running iOS 14.5

https://user-images.githubusercontent.com/2205578/131711978-1867fbca-521d-4025-8ec9-fcf5f5c3485d.mp4

**Comment by bbarthec** [comment]
@stuckj thank you for your message 🙇 I'll dive once again in the code to ensure the problem is solved.

**Comment by leeqiangzi** [comment]
My solution：https://www.jianshu.com/p/a1be8f204a55

problem：Synchronous interaction

That's what the official website says：
Additionally, please note that if you choose to use RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD, your app can no longer use the Google Chrome debugger. This is because synchronous methods require the JS VM to share memory with the app. For the Google Chrome debugger, React Native runs inside the JS VM in Google Chrome, and communicates asynchronously with the mobile devices via WebSockets.
