### ISSUE TITLE
[SDK 33] Google.logInAsync Unexpected behaviour on standalone

### ISSUE THREAD

**Issue by emilibota** [expo/expo#4655]
### Environment

Expo CLI 2.20.0 environment info:
-  System:
-- OS: Windows 10
- Binaries:
-- npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
- App Target:
-- Android, Standalone
- Testing Device:
-- Huawei P20 Lite, Android 8.

### Steps to Reproduce

The project uses `Google.logInAsync` to log in the users. It works fine on the development environment, but when the aplication is built and in standalone, at the time the user selects the account to log in, the browser window in which the selection whas made redirects to google's website, and the promise is never acomplished (only on the browser window's cancelation). 

### Expected Behavior

The `Google.logInAsync` promise is resolved/rejected

### Actual Behavior

On standalone when the user selects the account, the browser shows the loading animation for a few seconds, then redirects to google's website

### Reproducible Demo
I created a simple app with the example in [Expo's "Google" Docs](https://docs.expo.io/versions/latest/sdk/google/#__next) : https://snack.expo.io/BJvu0uDJB
and the problem persists (works as expected in expo client, crashes in standalone)

**Comment by cruzach** [comment]
Hi @emilibota- could you provide any logs from the crash? That might provide a little bit more information. 

To view logs from your Android device/emulator:
- Ensure Android SDK is installed
- Ensure that USB debugging is enabled on your device (not necessary for emulator).
- Run `adb logcat`

**Comment by emilibota** [comment]
Sure!
The app is named `com.tstsnk.testggllogin`, and [here is the log](https://github.com/expo/expo/files/3306726/log.txt) 👌👌

**Comment by cruzach** [comment]
Okay, I reproduced this error on my end. I think there may be an issue with the `redirectURL`, but as a temporary workaround- you can take a look at the [AppAuth API](https://docs.expo.io/versions/latest/sdk/app-auth/) (since that is what's being used [behind the scenes](https://github.com/expo/expo/blob/master/packages/expo/src/Google.ts#L155))

**Comment by dacevedo12** [comment]
Same problem here, our standalone app redirects to google.com after login

**Comment by hotaryuzaki** [comment]
same problem here.
and i already follow instruction from Expo documentation
https://docs.expo.io/versions/v33.0.0/sdk/google/

**Comment by hotaryuzaki** [comment]
> Okay, I reproduced this error on my end. I think there may be an issue with the `redirectURL`, but as a temporary workaround- you can take a look at the [AppAuth API](https://docs.expo.io/versions/latest/sdk/app-auth/) (since that is what's being used [behind the scenes](https://github.com/expo/expo/blob/master/packages/expo/src/Google.ts#L155))

ok, i fix this issue with copy logInAsync function and customize it.
The solution is don't use redirectUrl when we call appAuth.authAsync

**Comment by dacevedo12** [comment]
Any update on this? i don't really want to refactor using AppAuth just to get around this problem. I'll downgrade for now

**Comment by cruzach** [comment]
The PR still needs to be reviewed, but you can always make the same changes in your own `node_modules` folder -> https://github.com/expo/expo/pull/4671/commits/8bb4663b092a87205cfabc2de0fb470e90fb500a

**Comment by huylv-teko** [comment]
Hope Expo team fix this soon

**Comment by otaviogaiao** [comment]
me too. I have implemented the change on my node_modules folder. awaiting for the fix to land

**Comment by dtmuturi** [comment]
Beat my head around for two days trying to fix this, I have the same redirect issue after upgrading to SDK 33. Trying out the fix on node modules for now.

**Comment by dtmuturi** [comment]
While attempting the fix recommended by cruzach above I couldn't locate 'packages/expo/src/Google.ts' from my node_modules, I instead fixed it with the recommended edit on this file path ''node_modules/expo/build/Google.js". After rebuilding my android app this fixed my redirect issue. PS. am on expo SDK 33.

On the Google.Js file replace the code from line 149 to 153 from ` const reverseClientId = `com.googleusercontent.apps.${guid}`;
  let redirectUrl;
  if (!isInExpo) {
    redirectUrl = config.redirectUrl || `${reverseClientId}:/oauth2redirect/google`; to this `let redirectUrl = config.redirectUrl
    ? config.redirectUrl
    : `${AppAuth.OAuthRedirect}:/oauth2redirect/google`;`
  }`

**Comment by cruzach** [comment]
Yeah, it seems the file was moved recently (before the PR was able to be merged). I'll edit the PR or just close it and make a new one

**Comment by AleksandarSavic95** [comment]
### I solved this without changing `Google.ts` or anything in the `node_modules`.
I didn't have any `redirectUrl` set before, but after I added it, it was fixed
```
import * as AppAuth from 'expo-app-auth'; // you will use this in your logInAsync method

// other stuff...

Google.logInAsync({ // this is somewhere inside your Google-button onPress callback
  androidClientId,
  iosClientId,
  androidStandaloneAppClientId,
  iosStandaloneAppClientId,
  clientId: iosClientId,
  scopes: ['profile', 'email'],
  redirectUrl: `${AppAuth.OAuthRedirect}:/oauth2redirect/google` // this is the LINE
});
```
So, by setting `redirectUrl` to a [URL that "allways works"](https://github.com/expo/expo/pull/4671#issue-290264117)`*`, You are making sure that You always get redirected back to Your app. :)

Note 1: I am still not sure why this works, because I've read the code in `expo/Google.ts`, but it does.. Any feedback for this solution is welcome  😊 
Note 2: I am aware that this is not the best solution, but it is the shortest/simplest one, at least not until expo releases a fix for this.

`*` as stated by @cruzach in [his PR](https://github.com/expo/expo/pull/4671)
