### ISSUE TITLE
ImagePicker: When Picking Videos Crashes App on iPhone xs Max 

### ISSUE THREAD

**Issue by sh-optimize** [expo/expo#4741]
### Environment

Expo CLI 2.11.6 environment info:
   System:
     OS: macOS 10.14.2
     Shell: 5.3 - /bin/zsh
   Binaries:
     Node: 12.3.0 - /usr/local/bin/node
     Yarn: 1.16.0 - /usr/local/bin/yarn
     npm: 6.9.0 - /usr/local/bin/npm
     Watchman: 4.9.0 - /usr/local/bin/watchman
   IDEs:
     Xcode: 10.1/10B61 - /usr/bin/xcodebuild
   npmPackages:
     expo: ^32.0.0 => 32.0.6
     react: 16.5.0 => 16.5.0
     react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
     react-navigation: ^3.1.2 => 3.1.2

The app is for android and iOS devices, but it specifically only crashes with only iPhone xs max for some reason ??? it crashes in both build and development 

### Steps to Reproduce

Simply try to pick a video with similar codec info as the following to view it on the screen.
The issue happens only when any video with the following codec is being picked, right after the compression is done on an iPhone xs max. 

<img width="602" alt="codec info 1" src="https://user-images.githubusercontent.com/47317400/60271569-45657100-98fb-11e9-8169-6ea7b2167897.png">
<img width="602" alt="codec info 2" src="https://user-images.githubusercontent.com/47317400/60271991-fbc95600-98fb-11e9-97fe-5d44df81ad3f.png">

### Expected Behavior

simply display the video on the screen after being picked. It happens normally on any phone.

### Actual Behavior

Picking and the video compresses, it ends up crashing the whole app.

### Reproducible Demo

[expo snack ](https://snack.expo.io/@samyoptimize/expo-imagepicker
)
Here you can find more info on the video I used, this is the meta data in it [Meta data on the video
](https://www.get-metadata.com/result/8d9bb576-161b-4eb8-9dfb-329e059df5f0)

**Comment by cruzach** [comment]
Hi @sh-optimize, is the crash happening with `ImagePicker.launchImageLibraryAsync`, or when you try and render the `Video` component with the source uri you provide?

**Comment by sh-optimize** [comment]
Hi @cruzach it crashes when `ImagePicker.launchImageLibraryAsync`, the snack was updated as well if you want to check again. I noticed that it doesn't work on for iOS versions above 12.1 for videos with those specs only on Xs and Xs Max.

**Comment by PhuTaliban** [comment]
__

**Comment by jamesether** [comment]
I'm also experiencing crashing when recording/selecting a video from `ImagePicker`. Photos work fine.

![IMG_1259](https://user-images.githubusercontent.com/4851924/61210358-26851e00-a6f4-11e9-86a3-e6db61245e41.PNG)

I have tried importing the component via:
`import { ImagePicker } from 'expo';`
and adding the separate module and importing via:
`import * as ImagePicker from 'expo-image-picker';`

My function is as follows:

`async actionTapped(index) {
    if (index === 2) {
      return;
    }

    const { status } = await Permissions.askAsync(
      Permissions.CAMERA,
      Permissions.CAMERA_ROLL
    );

    if (status !== 'granted') {
      Alert.alert(
        'Error',
        `We don't have access to your camera or photos, please update this in your phone's settings.`
      );

      return;
    }

    StatusBar.setBarStyle('dark', true);

    const opts = {
      mediaTypes: ImagePicker.MediaTypeOptions.Videos,
    };

    let video;

    switch (index) {
      case 0:
        video = await ImagePicker.launchCameraAsync(opts);
        break;

      case 1:
        video = await ImagePicker.launchImageLibraryAsync(opts);
        break;

      default:
        break;
    }

    StatusBar.setBarStyle('light-content', true);

    if (video.cancelled) {
      return;
    }

    this.video = video;
    this.navigate();
  }`

**Comment by fweffort** [comment]
Same here

**Comment by lukmccall** [comment]
@jamesether, @fweffort is it only occurred when picking videos with similar specs?

**Comment by jamesether** [comment]
@lukmccall No, it appears to happen with all videos for me.

**Comment by fweffort** [comment]
Same here. All videos

Em ter, 16 de jul de 2019 às 06:44, James Edmonston <
notifications@github.com> escreveu:

**Comment by lukmccall** [comment]
What version of SDK, you were using?

**Comment by sh-optimize** [comment]
@lukmccall it's on sdk 32, we just upgraded recently to 33 so we still gonna test if the same issue is there

**Comment by jamesether** [comment]
@lukmccall I'm on SDK 33.

**Comment by chrisnojima** [comment]
Hi,

I have this as well. I think its' because https://github.com/expo/expo/blob/master/packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m#L298 should reference `UIImagePickerControllerMediaURL` instead of `UIImagePickerControllerReferenceURL`

**Comment by lukmccall** [comment]
I think we fixed this bug earlier ((see)[https://github.com/expo/expo/pull/4903/commits/b592c3e29aa6ae4ba344d6c314c87fac2baf5cba]) and it won't occur in coming SKD 34.
Also, I've created a pull request, which updates the way of getting asset metadata.
It may resolve issues with `ImagePicker` on newer devices.

**Comment by fweffort** [comment]
Just to make sure I am following this.

Will this be fixed only in SDK 34?

**Comment by lukmccall** [comment]
@fweffort Yes, it would be fixed only in SDK 34.

**Comment by jamesether** [comment]
SDK 34 has fixed `launchCameraAsync` but `launchImageLibraryAsync` is still crashing. 😞

**Comment by lukmccall** [comment]
@jamesether I will check it.

**Comment by lukmccall** [comment]
@jamesether Could you provide me with more information and sum everything up? 
- It occurs on all kind of videos, isn't it? 
- Does this bug also exist on a simulator? 
- What iOS versions did you use?

**Comment by jamesether** [comment]
@lukmccall Sorry for the lengthy delay. It looks like the issue has been fixed on everything pre-iOS 13! There's a new issue tracking for iOS 13 here: https://github.com/expo/expo/issues/5321

Cheers

**Comment by lukmccall** [comment]
Ok, so then I will close this issue. Fell free to open it again if a similar situation occurred in the future.
