### ISSUE TITLE
[expo-sensors] Pedometer unable to query steps, documentation unclear/contradictory.

### ISSUE THREAD

**Issue by LarkStephens** [expo/expo#4895]
I've been troubleshooting my app's Pedometer on iOS as it has been saying the pedometer is not available and giving errors on a step count request and I noticed that the way you're recommended to use the Pedometer on the updated SDK 33 version of the Expo docs is to install expo-sensors and import it from there. 

However, this does not work on either Android or iOS on my app and I was able to reproduce this issue by running the letsGoForAWalk snack from the docs on the emulators as well. Both give an error message. On iOS it says there is an error retrieving the step count and that the pedometer is not available. On Android, it says that it is not available and that getting step count for date range is not supported on android yet.

The expo-sensors docs under expo also say that it should be pre-installed on managed apps, which mine is and I can import the Pedometer from expo still (For the record, it works on Android, but does not on iOS,). Which contradicts the SDK33 version of the Expo docs. I'm not really sure what to do at this point. I linked below the particular versions of the docs I'm looking at just in case I'm missing something.

Expo Pedometer Docs:
https://docs.expo.io/versions/latest/sdk/pedometer/#__next
expo-sensors:
https://github.com/expo/expo/tree/master/packages/expo-sensors

**Comment by LarkStephens** [comment]
It may be relevant that the iOS version I am using to test is somewhat old, being 10.3.3

**Comment by dimakura** [comment]
In my case it works for iOS (expo 33), but not Android.

**Comment by LarkStephens** [comment]
Which version of the Pedometer are you using? The separate expo-sensors or expo?

**Comment by dimakura** [comment]
I tried both. Both of them fail for android. "expo-sensors" worked well for iOS (not sure about "expo")

**Comment by LarkStephens** [comment]
That is strange because for me expo-sensors works for neither, but expo works for Android as it had before.

**Comment by Karpengold** [comment]
Have the same issue for Android:

Pedometer.isAvailableAsync(): false
Steps taken in the last 24 hours:  Could not get stepCount: getting steps count for date range is not supported on Android yet

**Comment by xcarpentier** [comment]
Any thought about it @ide?

**Comment by LarkStephens** [comment]
https://snack.expo.io/@lark/nervous-fudge
Just leaving a snack where I use the SDK 32 import syntax in case it helps.
Android receives a step count on my device but sometimes does not resolve.
It hangs waiting for availability on an emulator which it did not before. 
iOS is not available on emulator.

**Comment by LarkStephens** [comment]
Has anyone managed to get it to work? I have functionality still on SDK 32 with Android, but with SDK 32 being phased out with SDK 35 in September(?) I need to get it working with the 'expo-sensors' import soon.

**Comment by ide** [comment]
We're not planning to look into this for SDK 35 so the best way to get this fixed is to (1) identify the root cause of the issue and (2) submit a PR fixing the root cause.

**Comment by LarkStephens** [comment]
I'm afraid it's not an option for me at the moment, but thank you for giving me a heads up.

**Comment by naistran** [comment]
It seems that with the move to unimodules, `getStepCountAsync` was never re-implemented [for Android](https://github.com/expo/expo/blob/73c4d23244e24edfca24d7a60b6e86557cf7d85b/packages/expo-sensors/android/src/main/java/expo/modules/sensors/modules/PedometerModule.java#L72).

Since SDK 33 is being dropped soon, any chance we could include include this in the SDK 36 roadmap @sjchmiela?

**Comment by arzola** [comment]
@naistran I did something nasty as a workaround but it worked I added expo 33 as a legacy npm dependency and use only the pedometer module from there.

package.json
```
"expo": "^35.0.0",
 "expo-legacy": "npm:expo@33.0.0",
```
And use it like this

``` import {Pedometer} from 'expo-legacy'

**Comment by antoinedelp** [comment]
Does anyone have a get-around for bare react-native projects wanting to use Expo Pedometer?
I have not installed Expo as a dependency, only expo-sensors and unimodules. I'd like to know if there is a way to access Expo SDK 33's Pedometer rather than the current one (which does not work for Android). 
I am on react-native 0.59.0, react-native-unimodules 0.6.0 and expo-sensors 7.0.0
Cheers!

**Comment by antoinedelp** [comment]
Hi, apparently this issue was fixed in Expo V36 SDK.
However, I am working on a bare project using react-native-unimodules and expo-sensors, and the issue is still the same as before: "Getting step count date range is not supported on Android yet."

How does the relation between expo and expo-unimodules work? When will the new Pedometer version be available for bare react-native projects, or is there a work around to use Expo V36's new Android pedometer version?

I am using react-native-unimodules v 0.7.0 and expo-sensors v8.0.0

**Comment by klichg0ky** [comment]
> Hi, apparently this issue was fixed in Expo V36 SDK.
> However, I am working on a bare project using react-native-unimodules and expo-sensors, and the issue is still the same as before: "Getting step count date range is not supported on Android yet."
> 
> How does the relation between expo and expo-unimodules work? When will the new Pedometer version be available for bare react-native projects, or is there a work around to use Expo V36's new Android pedometer version?
> 
> I am using react-native-unimodules v 0.7.0 and expo-sensors v8.0.0

@antoinedelp Do you have a solution to this problem?

**Comment by antoinedelp** [comment]
Unfortunately, we haven't found a solution at the moment. We are looking
into different packages to use as our Android pedometer.
ᐧ

**Comment by nachourpi** [comment]
@antoinedelp did you managed to find a different package that properly works for Android? I asked you because expo-sensor was the only one that worked for me using the internal pedometer instead of Google-Fit API which I don't want to.

**Comment by antoinedelp** [comment]
We are working on our own package, but we need to improve it as is isn't as
reliable as we thought. It only works on devices with a hardware Step
Counter. Feel free to have a look:
https://www.npmjs.com/package/react-native-oui-pedometer

ᐧ

Le ven. 31 janv. 2020 à 19:52, nachourpi <notifications@github.com> a
écrit :

**Comment by nachourpi** [comment]
Thanks @antoinedelp  that's very cool! I've tested the library and quick reviewed the code and it's seems very simple! However I think It won't work for me as I needed a manner to get the step counts of the last x days and this one gets the step count as an event.

**Comment by pferriol** [comment]
I need to use pedometer with SDK 36 so I applied @arzola solution and it works for me, but I found a suspicious behaviour running the app on a device with Dev Tools.

It seems Dev Tools runs the app on two instances of the same device. I can see the message "Running application on HUAWEI VNS-L31." twice in the console, and all messages logged to the console appear twice. I'm using expo-cli 3.11.9 and the Expo app 2.14.0.

If I remove "expo-legacy": "npm:expo@33.0.0" line from package.json, this behaviour disappears. So, I guess that using both expo versions is causing it.

Before generating the standalone version and upload it to the app stores I would like to know if this behaviour could have unexpected consequences affecting the user of it is only an issue with the Dev Tools. I made some research on the internet but I didn't find anything. Anybody who has applied this solution has any feedback?

**Comment by arzola** [comment]
@pferriol Hello :) I uploaded the apk to the play store without issues and it was working but at the end I had to eject the app to integrate other pedometer solution

**Comment by antoinedelp** [comment]
Hi! 
Any chance you plan to bring back the Android getStepCount functionality for ejected apps?

**Comment by gypsicoder** [comment]
> @naistran I did something nasty as a workaround but it worked I added expo 33 as a legacy npm dependency and use only the pedometer module from there.
> 
> package.json
> 
> ```
> "expo": "^35.0.0",
>  "expo-legacy": "npm:expo@33.0.0",
> ```
> 
> And use it like this
> 
> `import {Pedometer} from 'expo-legacy' `
> 
> Surprisingly compiled and only increased 200kb the apk size

I am trying to use Pedometer in bare react-native project with unimodules and separate expo-sensors? Can I use expo-legacy in bare react-native project?

**Comment by achr3f** [comment]
hello :) plz any solution to  use  expo pedometer in android,  any step by step tutorial  ?? 
I'm using    
 "expo": "~38.0.9",
 "expo-sensors": "~9.0.1"

**Comment by shaynethiessen** [comment]
Is this going to get fixed at any point?

**Comment by ide** [comment]
I'm not aware of anyone working on this but the source is available here if this is a priority for you to work on: https://github.com/expo/expo/tree/master/packages/expo-sensors

**Comment by MalekGarbouj** [comment]
[Error: Getting step count for date range is not supported on Android yet.] error. How can I solve this problem ...
  "expo": "~38.0.9",
  "expo-sensors": "~9.0.1",
  I created a client with OAuth 2.0 client ID
  thank you

**Comment by waritthornnudee** [comment]
![image](https://user-images.githubusercontent.com/26889841/103755590-a74e7d00-5040-11eb-8613-25a6128844ea.png)

https://developer.android.com/about/versions/10/privacy/changes#:~:text=of%20legacy%20permissions-,Physical%20activity%20recognition,or%20moving%20in%20a%20vehicle.

On android 10 or above, In order to device's to track user step they need to request for ACTIVITY.RECOGNITION before tracking the steps. I think we should include this in the document.

**Comment by tony3918** [comment]
@waritthornnudee Thanks for sharing this! Could you please share how we can set the `ACTIVITY_RECOGNITION` permission? I added `com.google.android.gms.permission.ACTIVITY_RECOGNITION` in my [app.json](https://docs.expo.io/versions/latest/config/app/#permissions) but it still does not work. I've checked the permission types in [expo-permissions](https://docs.expo.io/versions/latest/sdk/permissions/#permission-types) but couldn't find anything that seems related to `ACTIVITY_RECOGNITION` 🙁

**Comment by holgersindbaek** [comment]
@tony3918 Did you manage to get it to work. I'm unsure as to whether the Expo pedometer API will work on Android? Is it broken when using with Expo?

**Comment by gus-waritthorn** [comment]
> @waritthornnudee Thanks for sharing this! Could you please share how we can set the `ACTIVITY_RECOGNITION` permission? I added `com.google.android.gms.permission.ACTIVITY_RECOGNITION` in my [app.json](https://docs.expo.io/versions/latest/config/app/#permissions) but it still does not work. I've checked the permission types in [expo-permissions](https://docs.expo.io/versions/latest/sdk/permissions/#permission-types) but couldn't find anything that seems related to `ACTIVITY_RECOGNITION` 🙁

Sorry for the late reply, I'm not sure about expo-permission as I read through the document but they didn't mentioned about activity_recognition. Mine using bare workflow with **react-native-permission** but I don't think this will work with expo.

**Comment by gus-waritthorn** [comment]
> @tony3918 Did you manage to get it to work. I'm unsure as to whether the Expo pedometer API will work on Android? Is it broken when using with Expo?

Maybe this will help, I have manage to get it to work with bare workflow, but I have experience a slow update on step, it's depends on device's brand for me sometime it take around 5 minutes to update the step also you have to walk. Shaking the device didn't update the step on most device.

**Comment by kirgy** [comment]
> > @tony3918 Did you manage to get it to work. I'm unsure as to whether the Expo pedometer API will work on Android? Is it broken when using with Expo?
> 
> Maybe this will help, I have managed to get it to work with bare workflow, but I have experienced a slow update on step, it depends on device's brand for me sometime it takes around 5 minutes to update the step. You also have to walk, shaking the device doesn't update the step on most device.

I've had historically done a small amount of Java native work with the Android activity recognition APIs as part of a small research project. The reason the APIs are not real-time as one may like is they collect a variety of information from various sensors to best guess the activity the user is doing - walking, running, cycling, driving, commuting, etc. In order to get best reliable information, it takes into account the position of the device and the type of movements. The feature-purpose being, for example, to pop up a new article when a user is seen to be commuting, or not spring a push notification when the user is driving.

In our scenario we read some raw sensor data alongside activity recognition API to try and determine more "real-time" an activity the user was doing. I can't elaborate too much on specific scenario because of NDAs around the research.

**Comment by spoeken** [comment]
Have someone figured this out?

**Comment by JoshSmithCode** [comment]
Expo docs aren't updated, not sure if this is in the pipeline for them but Android pedometer access isn't bugged/broken, it's deliberately not currently supported 
[see here](https://forums.expo.io/t/pedometer-getstepcountasync-doesnt-work-on-android/50279)
[and here](https://github.com/expo/expo/blob/d716ec8aca83be5a7e53860248628f019c1fbb43/packages/expo-sensors/android/src/main/java/expo/modules/sensors/modules/PedometerModule.java#L72)

**Comment by Yanis-lebzar** [comment]
Have someone figured this out?

**Comment by tetar998** [comment]
up

**Comment by SerranoPablo** [comment]
Not solved

**Comment by walgys** [comment]
You should inject this code into a file for example android-manifes.plugin.js and link it in the plugins list inside app.json.

```
const { withAndroidManifest } = require('@expo/config-plugins');

module.exports = function androiManifestPlugin(config) {
    return withAndroidManifest(config, async (configProps) => {
        const androidManifest = configProps.modResults.manifest;

        androidManifest.$ = {
        ...androidManifest.$,
        'xmlns:tools': 'http://schemas.android.com/tools',
        };

        const activityPerm1 = { $: { 'android:name': 'android.permission.ACTIVITY_RECOGNITION' } };
        const activityPerm2 = { $: { 'android:name': 'com.google.android.gms.permission.ACTIVITY_RECOGNITION' } };

        androidManifest['uses-permission'].push(activityPerm1);
        androidManifest['uses-permission'].push(activityPerm2);

        return configProps;
    });
};
```

**Comment by insiyapithapur** [comment]
After adding permission in AndroidManifiest.xml still i am not able to watch my step count . Pedometer.isAvailableSync() is coming true but step count is not increase when i walk . Here is my App.js file and and androidManifiest.xml file can @thegirlyoucallryan @walgys tell me where i am stuck
`import { useState, useEffect } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Pedometer } from 'expo-sensors';

export default function App() {
  const [isPedometerAvailable, setIsPedometerAvailable] = useState('checking');
  const [pastStepCount, setPastStepCount] = useState(0);
  const [currentStepCount, setCurrentStepCount] = useState(0);

  const subscribe = async () => {
    const isAvailable = await Pedometer.isAvailableAsync();
    setIsPedometerAvailable(String(isAvailable));

    if (isAvailable) {
      const end = new Date();
      const start = new Date();
      start.setDate(end.getDate() - 1);

      const pastStepCountResult = await Pedometer.getStepCountAsync(start, end);
      if (pastStepCountResult) {
        setPastStepCount(pastStepCountResult.steps);
      }

      return Pedometer.watchStepCount(result => {
        setCurrentStepCount(result.steps);
      });
    }
  };

  useEffect(() => {
    const subscription = subscribe();
    return () => subscription && subscription.remove();
  }, []);

  return (
    <View style={styles.container}>
      <Text>Pedometer.isAvailableAsync(): {isPedometerAvailable}</Text>
      <Text>Steps taken in the last 24 hours: {pastStepCount}</Text>
      <Text>Walk! And watch this go up: {currentStepCount}</Text>
    </View>
  );
}`

and Android Manifiest.xml is `<manifest xmlns:android="http://schemas.android.com/apk/res/android">
  <uses-permission android:name="PermissionsAndroid.PERMISSIONS.ACTIVITY_RECOGNITION"/>
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
  <uses-permission android:name="android.permission.VIBRATE"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
  <queries>
    <intent>
      <action android:name="android.intent.action.VIEW"/>
      <category android:name="android.intent.category.BROWSABLE"/>
      <data android:scheme="https"/>
    </intent>
  </queries>
  <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="true" android:theme="@style/AppTheme">
    <meta-data android:name="expo.modules.updates.ENABLED" android:value="false"/>
    <meta-data android:name="expo.modules.updates.EXPO_SDK_VERSION" android:value="49.0.0"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_CHECK_ON_LAUNCH" android:value="ALWAYS"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_LAUNCH_WAIT_MS" android:value="0"/>
    <activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize" android:theme="@style/Theme.App.SplashScreen" android:exported="true" android:screenOrientation="portrait">
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="com.insiya0804.StepCounter"/>
      </intent-filter>
    </activity>
    <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" android:exported="false"/>
  </application>
</manifest>`  and my sdk version is 49.0.15 and expo-sensor version is ~12.3.0
