### ISSUE TITLE
Icons appear as `?` in SDK 34 in Testflight app

### ISSUE THREAD

**Issue by athenawisdoms** [expo/expo#5110]
### Environment

```
  Expo CLI 3.0.6 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.2 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.6
```

Target: iOS

### Expected Behavior

Icons to appear as expected

![IMG_4744](https://user-images.githubusercontent.com/6615285/62148108-0bef9f00-b2c7-11e9-83a9-92bffb61a58c.jpg)

### Actual Behavior

Icons show up as `?` in the Testflight app but looks OK in the Expo iOS client app on the iPhone.

Does not occur in Testflight app using SDK 33 before updating to SDK 34.

![IMG_4745](https://user-images.githubusercontent.com/6615285/62148106-0bef9f00-b2c7-11e9-8b2a-0d454a973b2c.jpg)

### Reproducible Demo

Upgrade from Expo following the instructions at https://blog.expo.io/expo-sdk-34-is-now-available-4f7825239319#59ef

The icons are obtained from `'@expo/vector-icons'` package. An example of using this will be 

    <FontAwesome name="angle-right" size={24} />

**Comment by brentvatne** [comment]
hi there! thanks for pointing this out, i've released a fix. update the version of expo-font in your package.json to 6.0.1 :)

**Comment by athenawisdoms** [comment]
@brentvatne Thanks for the near-instant fix! 

My `package.json` does not have the expo-font package. How should I proceed?

```
  "dependencies": {
    "axios": "^0.19.0",
    "expo": "^34.0.1",
    "expo-ads-admob": "^6.0.0",
    "expo-analytics-amplitude": "^6.0.0",
    "expo-barcode-scanner": "^6.0.0",
    "expo-permissions": "^6.0.0",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "node-libs-react-native": "^1.0.3",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-dotenv": "^0.2.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.11.4",
    "react-navigation": "^3.11.1",
    "react-redux": "^7.1.0",
    "redux": "^4.0.4",
    "redux-persist": "^5.10.0",
    "redux-thunk": "^2.3.0",
    "remote-redux-devtools": "^0.5.16",
  },
```

**Comment by brentvatne** [comment]
ah if you're not using expo-font directly then vector-icons just uses the one bundled in the expo package. you can delete your node_modules and yarn.lock/package-lock.json and install it again and you should get the latest expo-font version by doing so. you can verify this by checking the lockfile after you install to ensure that the version you get is 6.0.1

**Comment by brentvatne** [comment]
another thing you could do is install `expo@34.0.3`, i just released that update and it includes the latest expo-font fixes

**Comment by athenawisdoms** [comment]
@brentvatne Perfect! Updated to `expo@34.0.3` as suggested and Testflight app no longer has the missing icon issue.

**Comment by ide** [comment]
Sorry about this -- glad it's working for you.

To reiterate, a simple fix is to upgrade to `expo@34.0.3` which fixes this issue with expo-font.

**Comment by javi10823** [comment]
Hi Everyone! I have the same issue

versions:
```
“expo”: “^34.0.3",
   “expo-font”: “~6.0.1",
```

- I deleted expo app in iPhone
- I removed node modules folder
- I executed yarn clear cache

Any ideas?

**Comment by billychasen** [comment]
@brentvatne still not getting fonts to load.  Should I update `"react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz"` as well?

**Comment by turculaurentiu91** [comment]
No, but you should delete node_modules folder and package-lock.json. Then run "npm i"

**Comment by john-harding** [comment]
Fix didn't work for me til I deleted `package-lock.json`.  Thanks!

**Comment by ibadsiddiqui** [comment]
Delete `package-lock.json` file. Then upgraded to your expo and expo-font packages to new latest versions `expo@34.0.3` and `expo-font@6.0.1`.
`npm i -s expo@34.0.3 expo-font@6.0.1`

I hope this helps.
