### ISSUE TITLE
Video component crashing when using useNativeControls

### ISSUE THREAD

**Issue by rodriggochaves** [expo/expo#577]
Hi! I'm trying to render a video in my app using a video hosted in my JWPlayer API. It works fine until I try to render the component with native controls. 

When I try this, it work but I can't play/pause the video.

```js
<Video
    source={{ uri: 'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4' }}
    rate={1.0}
    volume={1.0}
    muted={false}
    shouldPlay
    resizeMode="cover"
    style={{ width: 400, height: 225 }}
    onError={(error) => (console.log('ERROR!!!! => ', error))}
    onLoadStart={() => (console.log('Loading...'))}
    onLoad={params => (console.log('Played! ', params))}
    onProgress={params => (console.log('Playing! ', params))}
    onEnd={() => (console.log('END!!!'))}
    ref={this._handleVideoRef}
/>
```

But when add the `useNativeControls`, only audio works:

```js
<Video
    source={{ uri: 'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4' }}
    rate={1.0}
    volume={1.0}
    muted={false}
    shouldPlay
    resizeMode="cover"
    style={{ width: 400, height: 225 }}
    onError={(error) => (console.log('ERROR!!!! => ', error))}
    onLoadStart={() => (console.log('Loading...'))}
    onLoad={params => (console.log('Played! ', params))}
    onProgress={params => (console.log('Playing! ', params))}
    onEnd={() => (console.log('END!!!'))}
    ref={this._handleVideoRef}
    useNativeControls={true}
/>
```

I've done some searching and not found any solution to this problem. Instead I've found some people with the same problem as me.

+ https://stackoverflow.com/questions/44943637/react-native-play-video-using-expo-sdk 
this question have one awnser but it isn't been marked as correted.
+ https://stackoverflow.com/questions/45483777/react-native-expo-complex-video-component 
+ https://stackoverflow.com/questions/45804235/usenativecontrol-with-expo-video-component-causing-app-to-crash
these 2 questions also describe this problem and nobody awnsered.

I wonder what can I do to help me and these people. I'm only a graduation student but If this issue is really a problem thats need to be fixed, I can help!

**Comment by gkufera** [comment]
Hi @rodriggochaves!

I'm sorry you're experiencing this issue! Can you let me know what device/OS you are seeing this problem on, and what SDK you are running?

In SDK20, we fixed a bunch of issues with native controls, so it's extra unfortunate that this keeps popping up!

Thanks-- once you give us more info I will try to debug on my end.

Greg

**Comment by rodriggochaves** [comment]
Hi! @gkufera Thanks for so rapid response!

I'm experience this problem on iOS, using MacOS for developing and I'm using SDK20.

**Comment by Solitaryo** [comment]
Same here, on iPhone 7 Plus can't make it work, any workaround?

**Comment by sjchmiela** [comment]
Does the problem still occur, @rodriggochaves? I've just created an example app with just the video on Expo 23 and it looks like everything works:

- using `{play,pause}Async` methods on the Video instance with `useNativeControls={false}` works on both iOS and Android,
- toggling `shouldPlay={true/false}` on the Video instance works on both iOS and Android,
- using native controls with `useNativeControls={true}` to play and pause works on both iOS and Android.

Here's a reference Snack for you: https://snack.expo.io/rkF1ib3gf. :)

**Comment by sjchmiela** [comment]
I'll close this as the issue seems to have been solved (at least on SDK 23 it works). Should you encounter any more problems feel free to reopen the issue, I'll be happy to help!
