### ISSUE TITLE
[appauth][ios] authAsync() promise never resolves for issuer: microsoftonline

### ISSUE THREAD

**Issue by dsgrillo** [expo/expo#6245]
### Environment

  Expo CLI 3.4.1 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.16.2 - ~/.nvm/versions/node/v8.16.2/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v8.16.2/bin/npm
    IDEs:
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 

### Steps to Reproduce

1. Setup `AppAuth` to use Azure AD as the identity provider. 

```
async function doLogin(setResponse) {

  try {
    const response = await AppAuth.authAsync({
      clientId,
      issuer: `https://login.microsoftonline.com/${tenant}`,
      redirectUrl: 'host.exp.exponent://oauthredirect',
    })
    console.log('this row is not printed', response)
    setResponse(response)
  } catch (e) {
    setResponse({
      message: e.message
    })
  }
}
```
2. Call this function in an onclick of a button.

3. Put the proper credentials in azure.

### Expected Behavior

The response contains any data.

### Actual Behavior

The promise is never resolved (only on iOS). The same code works fine on Android.
I've also tried using a standalone build, with a custom deep link, but the issue remains.

### Reproducible Demo
https://github.com/dsgrillo/expo-app-auth-ios-issue

![ezgif-4-41d3b603c80d](https://user-images.githubusercontent.com/3859588/68676001-58e74080-0559-11ea-9d05-19ef055f282e.gif)

**Comment by cruzach** [comment]
Hm, just tested `authAsync` using Google to sign in and it returned just fine. I'll try this with the `microsoftonline` endpoint and see if i get any different behavior

**Comment by dsgrillo** [comment]
Thanks for the prompt reply!

If you want to try reproducing this issue with my current tenant in azure (https://github.com/dsgrillo/expo-app-auth-ios-issue) you can use the user: "test@dsgrillohotmailcom.onmicrosoft.com" and password: "Authissue01!"

**Comment by Lerosen** [comment]
Hi @dsgrillo  
I've just implemented Authentication for microsoft via AppAuth.authAsync and it worked. I had to configure the endpoints manually as on android the issuer cannot be a url with a path. With the endpoints configured it is working on both, Android and iOS. I use the common tenant but that shouldn't matter...
`
{
    ...
    issuer: 'https://login.microsoftonline.com',
    serviceConfiguration: {
        authorizationEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
        registrationEndpoint: '',
        revocationEndpoint: '',
        tokenEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/token'
    }
};
`

Have you tried that already?

**Comment by dsgrillo** [comment]
Hi @Lerosen 
I've just tried the configuration as you did, but the behaviour is the same: after doing successfully the login in the browser, the browser is closed and the expo app is again opened, but the promise is still not resolved (nor catched)

**Comment by shandye2** [comment]
Hello. I just wanted to use this expo-appauth to my project. I just used the sample. Im using Keycloak anyway. It is redirecting to the login page and return to the app. however, after the login, it is not being push through to the next line of code. I have this code:

`    authorize = async () => {
        try {
            console.log('Config: ', config);
            const authState = await AppAuth.authAsync(config);
            this.setState({ accessToken: authState.accessToken} );
            Alert.alert('Logged In: ', authState);
            await cacheAuthAsync(authState);
            console.log('signInAsync', authState);
        } catch (error) {
            Alert.alert('Failed to log in 1', error.message);
        }
    };`

and it was being called through this code:
`    render() {
        const { state } = this.state;
        console.log('Current State: ', state);
        return (
            <View>
                <Button title="Login/Register" onPress={this.authorize} />
            </View>
        );
    }`


I want to alert the authState and save the data to the redux store. but it did not reach the Alert('Logged In' after this code await AppAuth.authAsync(config);.

What i am missing?

**Comment by seanphilipp** [comment]
I'm experiencing the exact same behavior running in Expo Client on iOS 13. I'm also using an Azure Active Directory App Registration to provide the auth service. Same code works on an android simulator on Android 6.

Debugging and pausing on caught exceptions, I found the openid appauth code throwing an error code -3, which led me here: https://github.com/openid/AppAuth-iOS/issues/400

Running on my iPad, running iOS 12, it does the same thing 🤷‍♂️

**Comment by tomvanderlee** [comment]
Can confirm. Also using Azure AD. Promise wont resolve on iOS but does on android.

**Comment by ozerty** [comment]
Same problem here for IOS.
After many tries, I have found this setting "redirectUrl: urn:ietf:wg:oauth:2.0:oob" resolved the promise on IOS device but I don't understand this behaviour. Any idea why ?

**Comment by cdowding-sl** [comment]
"redirectUrl: urn:ietf:wg:oauth:2.0:oob" works for me as well. Where did this url come from?

**Comment by dolubajo** [comment]
After countless hours, using `redirectUrl: urn:ietf:wg:oauth:2.0:oob` worked perfectly for me.

I need to understand why however.

**Comment by AshleyRudland** [comment]
Hi @dolubajo - thanks so much for this. I had the exact same issue, but only on standalone builds, Expo and Simulator worked fine. Did you set the `redirectUrl` to just `rn:ietf:wg:oauth:2.0:oob` or `rn:ietf:wg:oauth:2.0:oob://`?

**Comment by dolubajo** [comment]
@AshleyRudland Apologies for the long delay.

I used just `redirectUrl: urn:ietf:wg:oauth:2.0:oob`

However, I have now moved away from using AppAuth, i'm now using AuthSession.
AppAuth didn't work on Android for me with Azure AD B2C.

AuthSession worked perfectly.
