### ISSUE TITLE
universal project / brand new setup stops working at Expo v37, but works at Expo v36

### ISSUE THREAD

**Issue by Albert-Gao** [expo/expo#7561]
It might be related to this bug https://github.com/expo/expo-cli/issues/1765

But seems everything is updated already, so I just canceled that waiting and start `expo start`.

Then press the `Run in the web browser` button in the Expo Metro Bundler window

Soon, received lots of warnings in the console:
![image](https://user-images.githubusercontent.com/18282328/78089189-1698a000-7423-11ea-9176-f377a59ce3bc.png)

And the app stops working
![image](https://user-images.githubusercontent.com/18282328/78089215-33cd6e80-7423-11ea-8299-b86f81f12e3b.png)

It indicates it is trying to render the native part on the web.

The setup of the web is like this:

in the App.tsx:

I imported the `Routes`

```typescript
import React from "react";
import { Routes } from "./routes/routes";
import { enableScreens } from "react-native-screens";
import { Platform } from "react-native";

if (Platform.OS === "ios" || Platform.OS === "android") {
  enableScreens();
}

const App: React.FC = () => {
  return <Routes />;
};

export default App;
```

The `Routes` is from 2 files:

- `routes.native.tsx`
- `routes.tsx`

That's all.

How to fix it? Or I miss something?

Thanks

**Comment by brentvatne** [comment]
hello! can you try doing a binary search of your code to see which particular things are impacting it? it's possible that one of the libraries in the app was updated and doesn't support web properly.

as for the warnings, this is a known issue with react-navigation (because of an issue in typescript) and will be resolved soon, those are not going to cause any problems in your app though.

**Comment by Albert-Gao** [comment]
How to do the search, thanks?

The native part stops working with the same error. Interesting.

```
  "dependencies": {
    "@expo/match-media": "0.0.0-alpha.5",
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/bottom-tabs": "^5.2.5",
    "@react-navigation/drawer": "^5.4.0",
    "@react-navigation/native": "^5.1.4",
    "@react-navigation/stack": "^5.2.9",
    "expo": "^37.0.0",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-web": "^0.11.7",
    "react-responsive": "^8.0.3",
    "react-router-dom": "^5.1.2"
  }
```

**Comment by brentvatne** [comment]
by binary search i mean remove half of the functionality from your app, see if it runs. if it doesn't, remove another half, etc. until it runs. once it does, add back half of the most recent part you removed, see if it runs, and so on, until you have narrowed down the problem

**Comment by Albert-Gao** [comment]
Thanks, seems everything is stops working

I made a barebones App.tsx

```typescript
import React from "react";
import { View, Text } from "react-native";

const App: React.FC = () => {
  return (
    <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
      <Text>Pricing Screen</Text>
    </View>
  );
};

export default App;
```

Then press the Run in the web browser button in the Expo Metro Bundler window

Warning from expo start
![image](https://user-images.githubusercontent.com/18282328/78090407-7cd2f200-7426-11ea-92de-ec75bd072b97.png)

Warning from the browser
![image](https://user-images.githubusercontent.com/18282328/78090423-8bb9a480-7426-11ea-93bf-de742da30f99.png)

**Comment by StevenPurn** [comment]
I see the same issue with a brand new expo project. Just running `expo-init app` and then `cd app` and `expo start`. I tried twice with a managed app; once with the `tabs` option and once with `blank`.

**Comment by blakebilliet** [comment]
Similar issue.

created new project
`npx expo-cli init foo`

ran project
`npm start`

Able to open in iOS Simulator on Macbook but getting error on Expo app on my iPhone: 
"There was a problem loading the requested app it looks like you may be using a LAN URL. Make sure your device is on the same network as the server or try using tunnel."

Tunnel also doesn't work.

Changed to "expo": "~36.0.0" in package.json and ran `npm install --save` 

Then ran `npm start`

Works perfectly.

**Comment by brentvatne** [comment]
@blakebilliet - that is a very different issue. your phone needs to be on the same network. possibly when restart packager after switching to sdk 36 you were able to connect to tunnel

**Comment by blakebilliet** [comment]
@brentvatne I don't think so. My phone and macbook are on the same network in both cases. 

Neither LAN nor Tunneling worked when I used v. 37. 

Both work when I use v. 36. 

Breaks again when I change to v. 37 (again no changes to network whatsoever)

**Comment by brentvatne** [comment]
do you have the latest expo client with sdk 37 support on your phone?

**Comment by blakebilliet** [comment]
@brentvatne ah, that looks to be the issue. current iOS app stops at 36. Thanks.

**Comment by brentvatne** [comment]
yeah it's taking a while to propagate the update on the stores for some reason :O

**Comment by EvanBacon** [comment]
This has been resolved in `expo-cli@3.17.5` please update your CLI with `npm install -g expo-cli`

**Comment by Albert-Gao** [comment]
It works now, thanks!

**Comment by LinusU** [comment]
Didn't find this via Google so just adding some search terms:

__fbBatchedBridgeConfig is not set, cannot invoke native modules

Expo upgrade SDK 36 37

**Comment by brentvatne** [comment]
@LinusU - ensure you are using the latest expo-cli, and if that doesn't resolve it, please provide a reproducible example
