### ISSUE TITLE
Expo detached android app not working. Shows up with a message "Could not load app. Are you sure XDE or exp is running"

### ISSUE THREAD

**Issue by skasanibanyan** [expo/expo#772]
Hi,

I created a project with expo client. I made some code changes and run it using expo app and it worked well. 
Now, i detached the project with **"exp detach"** command, built the code from android folder i got after detach in android studio and run it via usb. App is installed on the device but it is not loading. I am getting a blank screen showing a message **"Could not load app. Are you sure XDE or exp is running"**

**Comment by skasanibanyan** [comment]
Got it. 

We need to have the javascript code running in XDE or exp and that is how hot-reloading is done.

**Comment by abelta** [comment]
@skasanibanyan: I'm having this exact problem with a freshly ejected Expo app but don't understand how you got to fix it. Can you elaborate?

**Comment by rajeshpanwar007** [comment]
Facing same issue.

Please elaborate.

**Comment by skasanibanyan** [comment]
@rajeshpanwar007 
You need to keep the code running in expo even after it is detached. XDE or exp runs the JS server from which the app on your mobile accesses the code and live changes.

Only of you build a signed apk or a release variant build, you don't need the JS server from XDE or exp as the code is then bundled into the apk

**Comment by varunajmera0** [comment]
i ran exp start
then ran - react-native run-android.
it shows the same error @skasanibanyan

**Comment by manaka02** [comment]
@rajeshpanwar007  how did you do when you build a signed apk? I always have a crashed app when I try to do with this method [link]([](https://facebook.github.io/react-native/docs/signed-apk-android.html))

**Comment by nicoara** [comment]
Hello, Facing the same problem here with no solution. 
After two hours of debugging, all the answers here are still confusing as an answer. 
Please explain clearly the steps, as in (although the order below does not work):  
1) detach
2) open in Android Studio the detached project
3) open in Expo the detached project
4) run react-native run-android in command line

**Comment by skasanibanyan** [comment]
@nicoara 
You need to run "exp start" through another command line window and keep it running.

I think, even after ejecting, the code still needs to be run in a local server by expo.
"react-native run-android" command still looks a URL for this local server unlike a normal react-native app(made without expo).

I guess this solves the issue for you.

**Comment by faustoct** [comment]
still having this problem. Suddenly stopped working..

**Comment by faustoct** [comment]
solved!

**Comment by kazlaga** [comment]
@faustoct Could you please share how you fixed it ? My Expo app stopped working all of a sudden after working for days.

**Comment by oo7rm** [comment]
Is there any way of running the app without having the exp packager running in the background ?

**Comment by AdamJNavarro** [comment]
@oo7rm If you publish your project and build for production, it will pull your JS bundle from the production URL and that way you don't need to have xde or exp serving your JS. For development and debug builds, you need to have either of those tools serving your JS.

**Comment by oo7rm** [comment]
If I have to deploy a standalone apk (I do not need to publish or build it for production) will it work then ??

**Comment by leonelpena** [comment]
Can I run exp server with yarn start (app created with CRNA)? I ask because the URL has changed from "exp://192.168.1.109:19000" to "expe0b27ad569fd4264b5a2a078b2651e64://192.168.1.109:19000" (after detaching) is this the expected behavior?

The project was deployed on a Android phisical device (now the icon is on the screen), but when click on it or ran from Android Studio it is shows "Could not load app. Are you sure XDE or exp is running".

However if I scan the code (the second one) with expo client the app works fine. So is this the right way to load a detached app?

**Comment by avrono** [comment]
Does anyone have a definitive fix for this. I am having the same issue. I have tried exp start etc. It seems as if the URL that Expo is running the App on is not the same as the URL that is in the Java Class `DetachBuildConstants`

**Comment by leonelpena** [comment]
@avrono I have not look inside at `DetachBuildConstants`, but I was able to run the app. Once you have ejected the app with `yarn run eject` (if you created the project with CRNA) you have to run it with` exp start`. Then open Android Studio, compile and run the project. As soon as the apk is installed on the device (assuming you are running it on a physical one) the app will connect to the exp instance to download the JS code. It is very important that both the device and computer are in the same network.
Effectively the URL of the detached app will change I supposed that it is needed for make a difference from the non-detached app.

**Comment by avrono** [comment]
@leonelpena I'll give that a go, I am running an emulator in Android Studio - I did try running `exp start` and then running `react-native build-android` - this builds but wont run the Main Activity.

**Comment by leonelpena** [comment]
I had a similar issue, sadly I can not remember how I fixed it (it was three weeks ago...). What version of expo SDK are you running?. I have updated to the latest one before detaching.

**Comment by avrono** [comment]
27.0.0 .... I am actually simply trying to detach an empty project as I have some older code written in 20.0.0 which I want to migrate ... but if I can't even get a default blank project working, I fear my real requirement would be impossible.

**Comment by slvtrs** [comment]
My resolution was silly, but the step-by-step from @leonelpena got mine working.
You need to  run `exp start` (and leave it running) **before** opening Android Studio and building the app.

**Comment by logan1220** [comment]
Thanks @slvtrs that's exactly what my issue was. You need to have exp running **before** you build the app on Xcode or Android Studio

**Comment by ryandoss** [comment]
I have `exp start` running and I have built the app after doing so but I still get `Could not load app. Are you sure XDE or exp is running?` on physical android device.. it works perfect on iOS (both simulator and physical) and the android simulator.

I'm running the latest version of exp. What is happening!?!?

**Comment by slvtrs** [comment]
@ryandoss are you sure your device is connected to the same wifi as your computer?

**Comment by ryandoss** [comment]
@slvtrs that was it!! I had assumed my coworkers phone was on the employee wifi but it was on guest. Thank you 👍

**Comment by gshabanets** [comment]
Yep ^ they're right! For iOS it's similar, I ran "exp start" in my terminal and left it running, then went into the ios folder and clicked on the .xcworkspace file and ran it in XCode

**Comment by faustoct** [comment]
Quite busy so I couldn't check this thread out. I got it working using `yarn start` . It will open a browser tab with the expo service running on it. Go to the android studio and run your app.. @kazlaga 

I just moved away from managed expo, the same to detached, in my case it worked better adding separated expo modules, like https://docs.expo.io/versions/v32.0.0/bare/hello-world/

**Comment by sheshashayan** [comment]
@slvtrs Thank you so much ...

**Comment by bethshook** [comment]
Make sure your computer and mobile device are on the same wifi network

**Comment by Sunrays** [comment]
After ejecting to expokit, I face this issue often. Running Metro bundler through tunnel worked but painfully slow. So I had to kill processes running in metro bundler ports and start the app again.

- In Mac, find the process ID of the processes running in port: `$ sudo lsof -i :19000` where `19000` is my port.

- Replace `<PID>` with your process ID and kill the processes: `$ kill -9 <PID>`.

- `expo start -c` to clear cache while starting expo.


While expo is running, build the app.

**Comment by Changdao** [comment]
My standalone application raise "Something went wrong. Could not load app. Are you sure XDE or exp is runing?"

**Comment by OlegSabodash** [comment]
> solved!
fuck

**Comment by john20xdoe** [comment]
> My resolution was silly, but the step-by-step from @leonelpena got mine working.
> You need to run `exp start` (and leave it running) **before** opening Android Studio and building the app.

Still holds true with ejecting SDK 33 building Debug variant of Android. If you run `expo start` AFTER Android Studio the app will still not connect to the bundler.

Release variant does not need the local bundler, but it takes a while to build because of minify and proguard.

**Comment by niv-breez** [comment]
Hi everyone,
I follow @leonelpena  and @slvtrs steps, 
1. I ejected from expo to ExpoKit
2. Run expo start
3. Opened AndroidStudio
4. Build
5. Check my device terminal on the same wifi
6. Run from AndroidStudio

And still gets the message "Something went wrong. Could not load app. Are you sure XDE or exp is runing?"

I am sure I am on the same wifi, I check the file DetachBuildConstants and verify the URL.

What am I missing ?

**Comment by niv-breez** [comment]
log:


```
09/19 10:47:31: Launching app
$ adb install-multiple -r -t /home/niv/breez_home_cloud/breez_cloud/shopper_app/android/app/build/intermediates/resources/instant-run/debug/resources-debug.apk /home/niv/breez_home_cloud/breez_cloud/shopper_app/android/app/build/intermediates/split-apk/debug/slices/slice_8.apk /home/niv/breez_home_cloud/breez_cloud/shopper_app/android/app/build/intermediates/split-apk/debug/slices/slice_0.apk /home/niv/breez_home_cloud/breez_cloud/shopper_app/android/app/build/intermediates/split-apk/debug/slices/slice_2.apk /home/niv/breez_home_cloud/breez_cloud/shopper_app/android/app/build/intermediates/split-apk/debug/slices/slice_4.apk /home/niv/breez_home_cloud/breez_cloud/shopper_app/android/app/build/intermediates/split-apk/debug/slices/slice_1.apk /home/niv/breez_home_cloud/breez_cloud/shopper_app/android/app/build/intermediates/split-apk/debug/slices/slice_5.apk /home/niv/breez_home_cloud/breez_cloud/shopper_app/android/app/build/intermediates/split-apk/debug/slices/slice_3.apk /home/niv/breez_home_cloud/breez_cloud/shopper_app/android/app/build/intermediates/split-apk/debug/dep/dependencies.apk /home/niv/breez_home_cloud/breez_cloud/shopper_app/android/app/build/intermediates/split-apk/debug/slices/slice_9.apk /home/niv/breez_home_cloud/breez_cloud/shopper_app/android/app/build/intermediates/split-apk/debug/slices/slice_7.apk /home/niv/breez_home_cloud/breez_cloud/shopper_app/android/app/build/intermediates/split-apk/debug/slices/slice_6.apk /home/niv/breez_home_cloud/breez_cloud/shopper_app/android/app/build/intermediates/instant-run-apk/debug/app-debug.apk 
Split APKs installed in 2 s 469 ms
$ adb shell am start -n "com.breezapp.shopperapp/host.exp.exponent.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Waiting for process to come online
Connected to process 5158 on device Nexus_6_API_28 [emulator-5554]
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/zapp.shopperap: The ClassLoaderContext is a special shared library.
W/zapp.shopperap: JIT profile information will not be recorded: profile file does not exits.
I/chatty: uid=10086(com.breezapp.shopperapp) identical 10 lines
W/zapp.shopperap: JIT profile information will not be recorded: profile file does not exits.
I/MultiDex: VM with version 2.1.0 has multidex support
    Installing application
    VM has multidex support, MultiDex support library is disabled.
V/FA: Registered activity lifecycle callback
D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
I/FirebaseInitProvider: FirebaseApp initialization successful
I/InstantRun: starting instant run server: is main process
W/com.facebook.UserSettingsManager: Please set a value for AutoLogAppEventsEnabled. Set the flag to TRUE if you want to collect app install, app launch and in-app purchase events automatically. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-android#disable-auto-events.
    You haven't set a value for AdvertiserIDCollectionEnabled. Set the flag to TRUE if you want to collect Advertiser ID for better advertising and analytics results. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-android#disable-auto-events.
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/zapp.shopperap: Rejecting re-init on previously-failed class java.lang.Class<host.exp.exponent.network.ExponentNetwork$5>: java.lang.NoClassDefFoundError: Failed resolution of: Lexpolib_v1/okhttp3/Interceptor;
        at void host.exp.exponent.di.NativeModuleDepsProvider.<init>(android.app.Application) (NativeModuleDepsProvider.java:59)
        at void host.exp.exponent.di.NativeModuleDepsProvider.initialize(android.app.Application) (NativeModuleDepsProvider.java:80)
        at void host.exp.expoview.Exponent.<init>(android.content.Context, android.app.Application) (Exponent.java:137)
        at void host.exp.expoview.Exponent.initialize(android.content.Context, android.app.Application) (Exponent.java:119)
        at void host.exp.exponent.ExpoApplication.onCreate() (ExpoApplication.java:77)
        at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1154)
I/zapp.shopperap:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5871)
        at void android.app.ActivityThread.access$1100(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:199)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1650)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
        at void android.os.Looper.loop() (Looper.java:193)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "expolib_v1.okhttp3.Interceptor" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/base.apk", zip file "/data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/split_lib_resources_apk.apk", zip file "/data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/split_li
        at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at void host.exp.exponent.di.NativeModuleDepsProvider.<init>(android.app.Application) (NativeModuleDepsProvider.java:59)
        at void host.exp.exponent.di.NativeModuleDepsProvider.initialize(android.app.Application) (NativeModuleDepsProvider.java:80)
        at void host.exp.expoview.Exponent.<init>(android.content.Context, android.app.Application) (Exponent.java:137)
        at void host.exp.expoview.Exponent.initialize(android.content.Context, android.app.Application) (Exponent.java:119)
        at void host.exp.exponent.ExpoApplication.onCreate() (ExpoApplication.java:77)
        at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1154)
        at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5871)
        at void android.app.ActivityThread.access$1100(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:199)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1650)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
        at void android.os.Looper.loop() (Looper.java:193)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
    Rejecting re-init on previously-failed class java.lang.Class<host.exp.exponent.network.ExponentNetwork$5>: java.lang.NoClassDefFoundError: Failed resolution of: Lexpolib_v1/okhttp3/Interceptor;
        at void host.exp.exponent.di.NativeModuleDepsProvider.<init>(android.app.Application) (NativeModuleDepsProvider.java:59)
        at void host.exp.exponent.di.NativeModuleDepsProvider.initialize(android.app.Application) (NativeModuleDepsProvider.java:80)
        at void host.exp.expoview.Exponent.<init>(android.content.Context, android.app.Application) (Exponent.java:137)
        at void host.exp.expoview.Exponent.initialize(android.content.Context, android.app.Application) (Exponent.java:119)
        at void host.exp.exponent.ExpoApplication.onCreate() (ExpoApplication.java:77)
        at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1154)
        at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5871)
        at void android.app.ActivityThread.access$1100(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:199)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1650)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
        at void android.os.Looper.loop() (Looper.java:193)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
I/zapp.shopperap: Caused by: java.lang.ClassNotFoundException: Didn't find class "expolib_v1.okhttp3.Interceptor" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/base.apk", zip file "/data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/split_lib_resources_apk.apk", zip file "/data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/split_li
        at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at void host.exp.exponent.di.NativeModuleDepsProvider.<init>(android.app.Application) (NativeModuleDepsProvider.java:59)
        at void host.exp.exponent.di.NativeModuleDepsProvider.initialize(android.app.Application) (NativeModuleDepsProvider.java:80)
        at void host.exp.expoview.Exponent.<init>(android.content.Context, android.app.Application) (Exponent.java:137)
        at void host.exp.expoview.Exponent.initialize(android.content.Context, android.app.Application) (Exponent.java:119)
        at void host.exp.exponent.ExpoApplication.onCreate() (ExpoApplication.java:77)
        at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1154)
        at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5871)
        at void android.app.ActivityThread.access$1100(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:199)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1650)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
        at void android.os.Looper.loop() (Looper.java:193)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
W/zapp.shopperap: Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
    Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
    Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
W/zapp.shopperap: Accessing hidden method Landroid/os/UserManager;->get(Landroid/content/Context;)Landroid/os/UserManager; (light greylist, reflection)
D/SoLoader: init start
    adding system library source: /vendor/lib
    adding system library source: /system/lib
D/SoLoader: adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/lib/x86 flags = 0]
D/SoLoader: adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-main flags = 1]
    adding backup sources from split apks
    adding backup source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-0 flags = 1]
    adding backup source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-1 flags = 1]
    adding backup source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-2 flags = 1]
    adding backup source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-3 flags = 1]
    adding backup source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-4 flags = 1]
    adding backup source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-5 flags = 1]
    adding backup source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-6 flags = 1]
D/SoLoader: adding backup source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-7 flags = 1]
    adding backup source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-8 flags = 1]
    adding backup source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-9 flags = 1]
    adding backup source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-10 flags = 1]
    adding backup source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-11 flags = 1]
    Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
    Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
    Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.breezapp.shopperapp-t57j-kQc9yGJ71c4mP6dpg==/lib/x86 flags = 0]
    Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-11 flags = 1]
V/fb-UnpackingSoSource: locked dso store /data/user/0/com.breezapp.shopperapp/lib-11
V/fb-UnpackingSoSource: deps mismatch on deps store: regenerating
    so store dirty: regenerating
V/fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
V/fb-UnpackingSoSource: Finished regenerating DSO store com.facebook.soloader.ApkSoSource
V/fb-UnpackingSoSource: starting syncer worker
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-11 (from syncer thread)
V/fb-UnpackingSoSource: not releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-11 (syncer thread started)
D/SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-10 flags = 1]
V/fb-UnpackingSoSource: locked dso store /data/user/0/com.breezapp.shopperapp/lib-10
V/fb-UnpackingSoSource: deps mismatch on deps store: regenerating
    so store dirty: regenerating
V/fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
    Finished regenerating DSO store com.facebook.soloader.ApkSoSource
V/fb-UnpackingSoSource: starting syncer worker
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-10 (from syncer thread)
V/fb-UnpackingSoSource: not releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-10 (syncer thread started)
D/SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-9 flags = 1]
V/fb-UnpackingSoSource: locked dso store /data/user/0/com.breezapp.shopperapp/lib-9
V/fb-UnpackingSoSource: deps mismatch on deps store: regenerating
    so store dirty: regenerating
V/fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
V/fb-UnpackingSoSource: Finished regenerating DSO store com.facebook.soloader.ApkSoSource
    starting syncer worker
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-9 (from syncer thread)
V/fb-UnpackingSoSource: not releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-9 (syncer thread started)
D/SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-8 flags = 1]
V/fb-UnpackingSoSource: locked dso store /data/user/0/com.breezapp.shopperapp/lib-8
V/fb-UnpackingSoSource: deps mismatch on deps store: regenerating
    so store dirty: regenerating
V/fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
V/fb-UnpackingSoSource: Finished regenerating DSO store com.facebook.soloader.ApkSoSource
    starting syncer worker
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-8 (from syncer thread)
    not releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-8 (syncer thread started)
D/SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-7 flags = 1]
V/fb-UnpackingSoSource: locked dso store /data/user/0/com.breezapp.shopperapp/lib-7
V/fb-UnpackingSoSource: deps mismatch on deps store: regenerating
    so store dirty: regenerating
V/fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
V/fb-UnpackingSoSource: Finished regenerating DSO store com.facebook.soloader.ApkSoSource
    starting syncer worker
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-7 (from syncer thread)
V/fb-UnpackingSoSource: not releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-7 (syncer thread started)
D/SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-6 flags = 1]
V/fb-UnpackingSoSource: locked dso store /data/user/0/com.breezapp.shopperapp/lib-6
V/fb-UnpackingSoSource: deps mismatch on deps store: regenerating
    so store dirty: regenerating
V/fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
V/fb-UnpackingSoSource: Finished regenerating DSO store com.facebook.soloader.ApkSoSource
    starting syncer worker
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-6 (from syncer thread)
V/fb-UnpackingSoSource: not releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-6 (syncer thread started)
D/SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-5 flags = 1]
V/fb-UnpackingSoSource: locked dso store /data/user/0/com.breezapp.shopperapp/lib-5
V/fb-UnpackingSoSource: deps mismatch on deps store: regenerating
V/fb-UnpackingSoSource: so store dirty: regenerating
V/fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
V/fb-UnpackingSoSource: Finished regenerating DSO store com.facebook.soloader.ApkSoSource
    starting syncer worker
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-5 (from syncer thread)
V/fb-UnpackingSoSource: not releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-5 (syncer thread started)
D/SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-4 flags = 1]
V/fb-UnpackingSoSource: locked dso store /data/user/0/com.breezapp.shopperapp/lib-4
V/fb-UnpackingSoSource: deps mismatch on deps store: regenerating
    so store dirty: regenerating
V/fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
    Finished regenerating DSO store com.facebook.soloader.ApkSoSource
V/fb-UnpackingSoSource: starting syncer worker
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-4 (from syncer thread)
    not releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-4 (syncer thread started)
D/SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-3 flags = 1]
V/fb-UnpackingSoSource: locked dso store /data/user/0/com.breezapp.shopperapp/lib-3
V/fb-UnpackingSoSource: deps mismatch on deps store: regenerating
    so store dirty: regenerating
V/fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
    Finished regenerating DSO store com.facebook.soloader.ApkSoSource
    starting syncer worker
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-3 (from syncer thread)
    not releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-3 (syncer thread started)
D/SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-2 flags = 1]
V/fb-UnpackingSoSource: locked dso store /data/user/0/com.breezapp.shopperapp/lib-2
V/fb-UnpackingSoSource: deps mismatch on deps store: regenerating
    so store dirty: regenerating
V/fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
    Finished regenerating DSO store com.facebook.soloader.ApkSoSource
    starting syncer worker
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-2 (from syncer thread)
V/fb-UnpackingSoSource: not releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-2 (syncer thread started)
D/SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-1 flags = 1]
V/fb-UnpackingSoSource: locked dso store /data/user/0/com.breezapp.shopperapp/lib-1
V/fb-UnpackingSoSource: deps mismatch on deps store: regenerating
    so store dirty: regenerating
V/fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
V/fb-UnpackingSoSource: Finished regenerating DSO store com.facebook.soloader.ApkSoSource
    starting syncer worker
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-1 (from syncer thread)
    not releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-1 (syncer thread started)
D/SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-0 flags = 1]
V/fb-UnpackingSoSource: locked dso store /data/user/0/com.breezapp.shopperapp/lib-0
V/fb-UnpackingSoSource: deps mismatch on deps store: regenerating
    so store dirty: regenerating
V/fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
V/fb-UnpackingSoSource: Finished regenerating DSO store com.facebook.soloader.ApkSoSource
V/fb-UnpackingSoSource: starting syncer worker
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-0 (from syncer thread)
V/fb-UnpackingSoSource: not releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-0 (syncer thread started)
D/SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.breezapp.shopperapp/lib-main flags = 1]
V/fb-UnpackingSoSource: locked dso store /data/user/0/com.breezapp.shopperapp/lib-main
V/fb-UnpackingSoSource: deps mismatch on deps store: regenerating
    so store dirty: regenerating
I/zapp.shopperap: Background concurrent copying GC freed 25253(1192KB) AllocSpace objects, 10(360KB) LOS objects, 49% free, 3MB/6MB, paused 222us total 115.454ms
V/FA: Collection enabled
    App package, google app id: com.breezapp.shopperapp, 1:367315174693:android:f968efbb41d1fa7a
I/FA: App measurement is starting up, version: 16250
I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
    To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.breezapp.shopperapp
D/FA: Debug-level message logging enabled
D/ApkSoSource: not allowing consideration of lib/x86/libc++_shared.so: deferring to libdir
    not allowing consideration of lib/x86/libfb.so: deferring to libdir
D/ApkSoSource: not allowing consideration of lib/x86/libfolly_json.so: deferring to libdir
    not allowing consideration of lib/x86/libgifimage.so: deferring to libdir
    not allowing consideration of lib/x86/libglog.so: deferring to libdir
    not allowing consideration of lib/x86/libglog_init.so: deferring to libdir
    not allowing consideration of lib/x86/libimagepipeline.so: deferring to libdir
    not allowing consideration of lib/x86/libjsc.so: deferring to libdir
    not allowing consideration of lib/x86/libjscexecutor.so: deferring to libdir
    not allowing consideration of lib/x86/libjsinspector.so: deferring to libdir
    not allowing consideration of lib/x86/libreactnativejni.so: deferring to libdir
    not allowing consideration of lib/x86/libstatic-webp.so: deferring to libdir
    not allowing consideration of lib/x86/libyoga.so: deferring to libdir
V/fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
V/fb-UnpackingSoSource: Finished regenerating DSO store com.facebook.soloader.ApkSoSource
    starting syncer worker
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-main (from syncer thread)
    not releasing dso store lock for /data/user/0/com.breezapp.shopperapp/lib-main (syncer thread started)
D/SoLoader: init finish: 16 SO sources prepared
    init exiting
W/zapp.shopperap: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V (light greylist, reflection)
V/FA: Connecting to remote service
I/stetho: Listening on @stetho_com.breezapp.shopperapp_devtools_remote
D/ShortcutBadger: Finding badger
D/ShortcutBadger: Current badger:me.leolin.shortcutbadger.impl.DefaultBadger
D/SoLoader: init exiting
V/FA: Connection attempt already in progress
V/FA: onActivityCreated
E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}
E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}
W/zapp.shopperap: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (light greylist, reflection)
W/AsyncCondition: Could not find listener for key: openOptimisticExperienceActivity
    Could not find listener for key: openExperienceActivity
D/SoLoader: init exiting
E/AppLoader: Error fetching cached manifest, falling back to default timeout: java.io.IOException: No hard coded response found
D/OpenGLRenderer: HWUI GL Pipeline
I/FA: Tag Manager is not found and thus will not be used
E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}
E/AppLoader: Could not load app: Could not load app. Are you sure XDE or exp is running?
W/InstanceID: Instance ID SDK is deprecated, com.breezapp.shopperapp should update to use Firebase Instance ID
W/AsyncCondition: Could not find listener for key: devicePushToken
D/FA: Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=6168021120236147837}]
D/: HostConnection::get() New Host Connection established 0xcd80a7c0, tid 5207
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
    android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer: Swap behavior 0
D/EGL_emulation: eglCreateContext: 0xe44069e0: maj 2 min 0 rcv 2
D/EGL_emulation: eglMakeCurrent: 0xe44069e0: ver 2 0 (tinfo 0xcd835b30)
V/FA: Connection attempt already in progress
    Connection attempt already in progress
V/FA: Activity resumed, time: 511660
D/Exponent: Loaded exp.host status page.
E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}
D/EGL_emulation: eglMakeCurrent: 0xe44069e0: ver 2 0 (tinfo 0xcd835b30)
V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 252
V/FA: Connection attempt already in progress
V/FA: Activity paused, time: 511912
D/FA: Connected to remote service
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@535462b
V/FA: Processing queued up service tasks: 5
V/FA: onActivityCreated
E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}
E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}
E/ErrorFragment: ErrorActivity message: Could not load app. Are you sure XDE or exp is running?
D/FA: Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=MainActivity, firebase_previous_id(_pi)=6168021120236147837, firebase_screen_class(_sc)=ErrorActivity, firebase_screen_id(_si)=6168021120236147838}]
V/FA: Activity resumed, time: 512012
E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported post request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}
D/EGL_emulation: eglMakeCurrent: 0xe44069e0: ver 2 0 (tinfo 0xcd835b30)
V/FA: Inactivity, disconnecting from the service
E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}
E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported post request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}
```

**Comment by niv-breez** [comment]
Finally I solved it.
For anyone who will face this issue, what helps me is to remove and clean the node_modules and install it again:

```
watchman watch-del-all
rm -rf node_modules
rm -rf $TMPDIR/react-*
rm -rf $TMPDIR/npm-*
npm / yarn cache clean
npm install / yarn
npm /yarn start -- --reset-cache
```

from this [link](https://blog.expo.io/expokit-might-not-be-so-scary-3c26769215fa)

**Comment by hasnainalimj** [comment]
It happens when you build your app in MAC it will change the development URL inside **DetachBuildConstants.java** so you need to change this URL with your manifest URL.

After following these steps my application run successfully.
Steps to be followed.
1) Copy "**manifestUrl**" from "`ios/<project-name-folder>/Supporting/EXShell.json`"
2) Paste "**manifestUrl**" with "**DEVELOPMENT_URL**" inside "`android/app/src/main/java/host/exp/exponent/generated/DetachBuildConstants.java`"

**Comment by SeanCannon** [comment]
> exp://127.0.0.1:19000

This is a generated file - is there a source config file we can use instead so the change doesn't get lost?

**Comment by gerbus** [comment]
Updating to the latest expo-cli works to resolve this problem. 

Of course as of Feb 12, 2024, you now need to use Expo's EAS Update service to publish, which requires Expo SDK 45, so... I've got a long road ahead of me this month to upgrade my SDK from 33 to 45. Wish me luck!
