### ISSUE TITLE
getExpoPushTokenAsync() getting hang on some android devices

### ISSUE THREAD

**Issue by farazirfan47** [expo/expo#7884]
### Environment

  Expo CLI 3.5.0 environment info:
    System:
      OS: Linux 4.4 Ubuntu 16.04.6 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 8.16.2 - ~/.nvm/versions/node/v8.16.2/bin/node
      Yarn: 1.13.0 - /usr/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.16.2/bin/npm

Running app through expo client 2.15.1

### Steps to Reproduce
Used this  [snack](https://snack.expo.io/@charliecruzan/pushnotifications34) and not able to see token in console.

### Expected Behavior

I should see my token in console

### Actual Behavior

Not getting token for my android device.

### Reproducible Demo

Here is the demo [snack](https://snack.expo.io/@charliecruzan/pushnotifications34)

**Comment by byCedric** [comment]
Hi @farazirfan47! Thanks for reporting this. Unfortunately, I wasn't able to reproduce the error with the example/snack you linked. We do have some other reports about this, like [#7797](https://github.com/expo/expo/issues/7797#issuecomment-612190421). The only thing I can suggest (without being able to reproduce this) is the same from the other post:

> We've had some issues with the push notifications in Expo Client 2.15.0 on Android. [We patched some issues with push token requests that were hanging (not rejecting or resolving) in the latest Android version (`2.15.1`)](https://github.com/expo/expo/issues/7771#issuecomment-611654778). You can install it with the CLI `expo install:client:android` and select `latest`.

Could you try this and see if the token is either resolved or rejected?

Hope it helps 😄

**Comment by dichai1983** [comment]
I just tried building APK with Expo `37.0.7` and  CLI `3.18.5`.  And the push notification doesn't work on my Android phone.

**Comment by olegkalyta** [comment]
Having the same issue Expo `37.0`, CLI `3.17.18`

**Comment by sjchmiela** [comment]
Hey all,

- if you are experiencing this bug in Expo Client app, please ensure that you have the latest version (2.15.4, as of the time of writing this message). This bug has been fixed in the 2.15.1 release. Please also ensure that you are logged in in `expo-cli` as per https://github.com/expo/expo/issues/7831#issuecomment-613647709.
- if you are experiencing this bug in standalone apps:
  - if you are sure you provide a valid Google services configuration, please try rebuilding your apps. The fix has been deployed to builders on April 20th (not long ago). Check out https://github.com/expo/expo/issues/7727#issuecomment-616674874 to see why do you need to rebuild your app and ensure that your configuration is the way it should be. You may need to close and rerun the app.
  - if you aren't sure if you are providing a valid Google services configuration, head over to [Using FCM for Notifications guide](https://docs.expo.io/versions/latest/guides/using-fcm/) and follow it closely to fix the problem.

Let me know if this has helped you fix the problem!

**Comment by dichai1983** [comment]
This works: https://github.com/expo/expo/issues/7727#issuecomment-611544439

**Comment by cruzach** [comment]
Looks like this is probably resolved, so I'm going to mark as stale, but if you're still seeing this @farazirfan47 let us know

**Comment by satyam-dev** [comment]
Hi!
Anyone still facing the issue can login to expo client on CLI and android device!
1. Open your terminal and run `expo login` and enter your email and password.
2. Open your expo client Android app and from profile tab(right most) sign in with same email and password
3. Reload your app.

This should work!
