### ISSUE TITLE
Getting the following error on getLocationUpdatesAsync as Error: Attempt to invoke interface method 'java.util.Map org.unimodules.interfaces.taskManager.TaskInterface.getOptions()' on a null object reference

### ISSUE THREAD

**Issue by syedhaider03** [expo/expo#9188]
### Summary of Issue 
Getting the error on get background location updates async and the app crashes after sometime when on background 

Error: Attempt to invoke interface method 'java.util.Map org.unimodules.interfaces.taskManager.TaskInterface.getOptions()' on a null object reference

sometimes its works fine but most of the time its gives an error

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
I am using expo unimodules on  my bare react native app

### Steps to Reproduce
getting this error everytime when try to register getLocationUpdatesAsync method with task manager

### Expected Behavior vs Actual Behavior
must be working fine every time whether the app is background or in foreground when the task manager is registered

![Screenshot_1594578786](https://user-images.githubusercontent.com/43629380/87253954-809bf900-c498-11ea-8510-022bf30111e9.png)

**Comment by jmzwar** [comment]
I am also experiencing this issue in a managed app.

**Comment by dvester** [comment]
Also experiencing this issue, works fine for a while, then the app begins to crash repeatedly. On SDK 37 Managed.

![Screenshot_20200714-071421_Google](https://user-images.githubusercontent.com/55589943/87420022-82ea7a00-c5a2-11ea-9063-e6870df3c6d4.jpg)

**Comment by syedhaider03** [comment]
@dvester @jmzwar i was having this issue in sdk 38 which i have integrated it in my bare react native app, I was able to workaround this by deleting these four lines 
@Override
  public void didUnregister() {
    stopLocationUpdates();
    stopForegroundService();
    //  mTask = null;
    // mPendingIntent = null;
    // mLocationRequest = null;
    // mLocationClient = null;
  }

in didUnregister method on LocationTaskConsumer.java file in 
node_modules/expo-location/android/src/main/java/expo/modules/location/taskConsumers/LocationTaskConsumer.java

**Comment by dvester** [comment]
@syedhaider03 any way to make this work in the managed workflow?

**Comment by syedhaider03** [comment]
@dvester you need to either wait for expo team to fix it or you can eject and correct the file mentioned above.

**Comment by byCedric** [comment]
Hi @syedhaider03, thanks for reporting this! We have fixed this issue in PR #8612, we should have a fix out soon for this. (cc @tsapeta @mczernek, can we release this right away?)

Thanks for reporting this!

**Comment by dvester** [comment]
What is the process for getting the fixed version?

**Comment by tsapeta** [comment]
Hi all, I've just published `expo-location@8.3.0` and `expo-task-manager@8.4.0` which should include the fix from #8612. I'll be grateful for some feedback how these versions work 🙂

**Comment by syedhaider03** [comment]
Thanks, guys for the timely update appreciated  🙂

**Comment by m-jachym** [comment]
@tsapeta 
 I'm still in managed workflow.
For android 9 and 10 with location permission set to **always** it's working well.
For android < 9 it's not working.
We have 400+ users working everyday with the app, and still there are errors in android vitals, but it's much better with your fix!

**Comment by pmatheusvinhas** [comment]
I'm also facing this.
@syedhaider03 suggestion worked.

**Comment by Zanchee** [comment]
Just for reference, a lot of people in the linked issue don't think this is fixed.

**Comment by barnu5** [comment]
Having this issue with latest ios/android client

**Comment by bailaklf** [comment]
Still getting this issue in expo 41.0. The weird thing is that it used to wrk then just like that it started showing this error. Please anyone who can help ?

**Comment by G4L1L30** [comment]
I'm also having problems, when the gps signal is turned off after the app is closed. The app stops.

**Comment by audrew** [comment]
Anyone find solution for that? I am getting this error on sdk 42. Couldnt find any solution online...
