### ISSUE TITLE
Umbrella issue for task manager and background location issues on Android

### ISSUE THREAD

**Issue by byCedric** [expo/expo#9288]
**Edit**: First of all, I'm sorry for the current ongoing issues with the task manager and/or background location. The scope of the original issue was limited to the task manager's tasks not being unregistered on Android. But now that this thread has moved from this scope to all issues with task manager in combination with background location on Android, I think its good to update this issue with the context for this.

_Original post and scope are below_

## Latest Update (10/19/20)

The issues listed below, and more, are fixed in Expo Client `2.17.4`. Please upgrade to this client if you encounter any of the related issues. If you still receive these issues, please let us know!

## Update (09/29/20)

We have identified and fixed a handful of issues on Android, all related to using the task manager in combination with background location. Here are the ones that you probably have encountered yourself. 

These fixes will be available in the next patch update for the Expo Client, we will keep this issue open (but locked to avoid clutter) until this is released. 

### `ClassNotFoundException: host.exp.exponent.taskManager.ExpoHeadlessAppLoader`

This issue is related to how we initiate the environment for the task manager in managed. When we start a task through task manager, using background location for example, we need to boot the full app. But, because we don't have to render anything we create a smaller custom environment in which the task can run. Unfortunately, there were some issues with starting this environment. 

Due to the async nature of this background process, this didn't cause the app to crash. It did cause unresponsiveness in the background location updates.

<details>
<summary>An ADB log example of this error</summary>
<pre>
System.err: java.lang.ClassNotFoundException: host.exp.exponent.taskManager.ExpoHeadlessAppLoader
System.err: 	at java.lang.Class.classForName(Native Method)
System.err: 	at java.lang.Class.forName(Class.java:454)
System.err: 	at java.lang.Class.forName(Class.java:379)
System.err: 	at l.d.a.a.a(AppLoaderProvider.java:2)
System.err: 	at l.d.a.a.b(AppLoaderProvider.java:2)
System.err: 	at expo.modules.taskManager.TaskService.getAppLoader(TaskService.java:2)
System.err: 	at expo.modules.taskManager.TaskService.isStartedByHeadlessLoader(TaskService.java:1)
System.err: 	at expo.modules.taskManager.TaskService.setTaskManager(TaskService.java:2)
System.err: 	at expo.modules.taskManager.TaskManagerInternalModule.onCreate(TaskManagerInternalModule.java:5)
System.err: 	at l.d.b.f.h(ModuleRegistry.java:9)
System.err: 	at l.d.b.f.a(ModuleRegistry.java:2)
System.err: 	at org.unimodules.adapters.react.ModuleRegistryReadyNotifier.initialize(ModuleRegistryReadyNotifier.java:1)
System.err: 	at com.facebook.react.bridge.ModuleHolder.doInitialize(ModuleHolder.java:9)
System.err: 	at com.facebook.react.bridge.ModuleHolder.markInitializable(ModuleHolder.java:7)
System.err: 	at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceInitialized(NativeModuleRegistry.java:5)
System.err: 	at com.facebook.react.bridge.CatalystInstanceImpl$4.run(CatalystInstanceImpl.java:1)
System.err: 	at android.os.Handler.handleCallback(Handler.java:883)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:100)
System.err: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
System.err: 	at android.os.Looper.loop(Looper.java:214)
System.err: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
System.err: 	at java.lang.Thread.run(Thread.java:919)
System.err: Caused by: java.lang.ClassNotFoundException: host.exp.exponent.taskManager.ExpoHeadlessAppLoader
System.err: 	... 22 more
</pre>
</details>

### `Unable to start LocationTaskService: java.lang.NullPointerException`

This issue is related to how we restart the location service on Android. When we start this service, we need to know what app and for what task this service is started. But, unfortunately, there was an issue with this detection when the service is restarted. 

In some edge cases, this might have resulted in an app crash.

<details>
<summary>An ADB log example of this error</summary>
<pre>
AndroidRuntime: java.lang.RuntimeException: Unable to start service abi38_0_0.expo.modules.location.services.LocationTaskService@7bd9a81 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4105)
AndroidRuntime:        at android.app.ActivityThread.access$1800(ActivityThread.java:219)
AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
AndroidRuntime:        at abi38_0_0.expo.modules.location.services.LocationTaskService.onStartCommand(LocationTaskService.java:1)
AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
AndroidRuntime:        ... 8 more
</pre>
</details>

## Temporary workaround

If you need a fix right now, you should be able to use the bare workflow for the `ExpoHeadlessAppLoader` error and [manually patch the `LocationService`](https://github.com/expo/expo/blob/sdk-39/packages/expo-location/android/src/main/java/expo/modules/location/services/LocationTaskService.java#L51) by replacing `START_STICKY` with `START_REDELIVER_INTENT`. You can still use OTA with bare, and revert back to managed flow once we deployed the patches.

---

# Umbrella issue for tasks not being unregistered with task manager 

## Overview

We noticed a bug in `expo-task-manager` that incorrectly unregistered tasks on **Android**. Luckily, this has been fixed in [PR #8612](https://github.com/expo/expo/pull/8612) and published with version `expo-task-manager@8.4.0`. You can use this in bare projects at the moment, for managed we need to release a new Expo Client. This issue keeps track of that.

### Related issues

- https://github.com/expo/expo/issues/9241
- https://github.com/expo/expo/issues/9188
- https://github.com/expo/expo/issues/9083

**Comment by Zanchee** [comment]
I'm curious if my use case would fall under this umbrella, so I'll ask here before I make an issue.

**Comment by Zanchee** [comment]
@byCedric Do you think this will go out in Expo SDK 39?

**Comment by byCedric** [comment]
Yes, we patched the task manager code already. This issue will be closed after SDK 39 release. I kept it open to link and remove new duplicate issues 😁

**Comment by Zanchee** [comment]
👍 Thanks!

**Comment by dvester** [comment]
When is 39 scheduled to go out? This kind of leaves us dead in the water on SDK 38. We won't be able to release until this fix is available.

**Comment by Zanchee** [comment]
Agreed, this puts us in a bad light with Android users. We released our background tracking feature on iOS last Friday, but we had to refactor Android to use only foreground location to at least get some of the functionality. I don't think Expo has ever done a minor release before though.

@dvester my recommendation would be to refactor to use foreground `watchPositionAsynx` until this fox is out. (Probably mid September)

**Comment by dvester** [comment]
Expo, any comment on timing of the SDK 39, or a potential hotfix.

**Comment by Zanchee** [comment]
Their latest blog post sets for September for iOS 14 @dvester

**Comment by dvester** [comment]
@Zanchee No chance at a hotfix? Do you use the managed workflow? Can I just pull in the updated versions for expo-location and expo-task-manager and deploy with those, or am I missing something?

**Comment by Zanchee** [comment]
> @Zanchee No chance at a hotfix? Do you use the managed workflow? Can I just pull in the updated versions for expo-location and expo-task-manager and deploy with those, or am I missing something?

If you're using the managed flow. No, the bug was in native code which requires a new Expo SDK release. You can eject to a bare workflow and update yourself if you wish. Expo has not traditionally done minor fox versions for their SDK, so I think you'll have to wait.

**Comment by AronNM** [comment]
Also being held back by this bug. @byCedric - Any update regarding a hotfix or an ETA for the release of SDK 39? Thanks!

**Comment by Zanchee** [comment]
> Also being held back by this bug. @byCedric - Any update regarding a hotfix or an ETA for the release of SDK 39? Thanks!

@AronNM, as mentioned above, multiple times, the ETA for SDK 39 is September.

**Comment by imshreyansh** [comment]
What about #9570 will it also be fixed in SDK 39 ?

**Comment by Zanchee** [comment]
Unsure, @imshreyansh. I'd encourage you to reproduce that issue in an ejected project and see if it is solved on the latest expo-location. If it is, then it probably will be solved by this.

**Comment by Zanchee** [comment]
@byCedric is there any benefit to adding this to the manifest?

https://github.com/abdullah-abunada/expo/commit/bac2714fd8dc2ba2bfc26e26dfa27f807e06cd6c

**Comment by Zanchee** [comment]
@mczernek thoughts on my above message? Figured I would ask since you were the one who originally fixed it.

**Comment by nimrodbens** [comment]
in on a bare react project and using task manager 8.4.0 and still get this issue? am i missing something? the app crashes when killed by the OS if background location is running. on android that is.

**Comment by Zanchee** [comment]
@nimrodbens have you tried 9.0.0 the latest?

**Comment by nimrodbens** [comment]
@Zanchee do you mean expo-task-manager 9.0.0?

**Comment by Zanchee** [comment]
Expo location

**Comment by Zanchee** [comment]
There is also 8.5.0 for the task manager

**Comment by Zanchee** [comment]
@nimrodbens not making any claims that they are fixed, but would be good to verify that they are actually fixed before it's too late to get things into Expo 39. Seems like you have a project that is setup to test, so would be great if you could let us know.

**Comment by nimrodbens** [comment]
it appears to be working *sometimes*.

before upgrading to 9.0.0 and 8.5.0 the app always crashed when killed by the OS if background location is on. 

now, it seems that sometimes it does and sometimes it doesn't. at first i was super happy because it worked for like 3 straight attempts but then i checked again and it crashed. then again it didn't for a couple more tries. 

i'm afraid the results are not as expected.

**Comment by nimrodbens** [comment]
are there any versions of task manager and location that i can safely roll back to where this issue doesn't happen?

what happened for me now is when i run background location and the app is killed then the next time i load the app my entire app is broken. the user is shows the onboarding screen even though they were logged in and even though there is a valid token. and also in that onboarding screen the components are not clickable. it completely breaks my app. and if i turn off background location and kill the app the next time the user opens it everything is working as it should and the main screen is shown.

**Comment by miroslavskela** [comment]
Hi, I have built android apk and it does not even log in, it says "Cannot initialize app loader. host.exp.exponent.taskManager.ExpoHeadlessAppLoader", is it sure that this will be fixed in version 39? If someone knows. Tnx

**Comment by nimrodbens** [comment]
if anyone needs a fix in the meanwhile i came up with the following. i am using [this background timer library](https://github.com/ocetnik/react-native-background-timer).

that's about how i defined the task (i simplified it):
`BackgroundTimer.setTimeout` returns an id for the task, so i also make sure to call `BackgroundTimer.clearTimeout(id);` where needed.

    TaskManager.defineTask(LOCATION_TRACKING, async ({data, error}) => {
        Location.stopLocationUpdatesAsync(LOCATION_TRACKING);
        .... // your code
        BackgroundTimer.setTimeout(() => { 
            Location.startLocationUpdatesAsync(LOCATION_TRACKING, {...});
        }, 5 * MINUTE);
    });

and then just simply start your task as you would.

    Location.startLocationUpdatesAsync(LOCATION_TRACKING, {...});

it may be a weird way to go about it, but it works for now.

**Comment by imshreyansh** [comment]
@nimrodbens But for that we need to eject the project from expo

**Comment by nimrodbens** [comment]
@imshreyansh you are correct, sorry. i should've mentioned i'm on a bare react project.

**Comment by imshreyansh** [comment]
@nimrodbens also the library works for background but what if we close the application ?

**Comment by nimrodbens** [comment]
again, this is a temporary fix. it prevents the app from crashing while providing the basic use case. i do not use background location while the app is killed.

**Comment by m-jachym** [comment]
> Yes, we patched the task manager code already. This issue will be closed after SDK 39 release. I kept it open to link and remove new duplicate issues 😁

Not working after upgrading to SDK39

`"expo": "^39.0.0",
    "expo-location": "~9.0.0",
    "expo-task-manager": "~8.5.0",`

**Comment by Zanchee** [comment]
@m-jachym care to elaborate on the error you're receiving?

**Comment by m-jachym** [comment]
@Zanchee I can't debug remote JS due to [#10284](https://github.com/expo/expo/issues/10284) 
After building .apk and installing on device, running background location and swiping out the app, there should stay notification telling you, that your app is using location tracking. 
In this case notification disappear, and after starting the app again, there is [this](https://github.com/expo/expo/issues/9188#issuecomment-658124322) popup (with name of my app ofc, not expo), and I need to clear app cache to start it again...

**Comment by Zanchee** [comment]
@m-jachym you can use adb logcat in Android Studio on a real device and an emulator to see the cause of the crash.

**Comment by m-jachym** [comment]
@Zanchee Here is a log https://pastebin.pl/view/b98ca01f hope it's enough, cause i don't have experience with logcat etc

**Comment by nimrodbens** [comment]
@m-jachym 

> expo.modules.location.services.LocationTaskService.onStartCommand(LocationTaskService.java:1)
> expo.modules.location.services.LocationTaskService@b5190b5 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference

**Comment by JosephLep** [comment]
This still seems to be happening in SDK 39... was this not tested?

**Comment by eltan-tell** [comment]
At first I thought it was a joke, but it really doesn't work... 

A lot of people were waiting for this fix. Please, if this doesn't get fixed, just let us know. 
We can't release new versions to store since end of july

@byCedric @brentvatne @tsapeta

**Comment by brentvatne** [comment]
we'll get back to you when we have time to investigate. until then, if someone would like to dig in and try to resolve the issues that you're facing it would be appreciated. the code here is all open source.

**Comment by JosephLep** [comment]
@brentvatne was this tested???

**Comment by brentvatne** [comment]
@JosephLep - i understand that you're frustrated, like i said we will get back to you when we have time to investigate

**Comment by eltan-tell** [comment]
@brentvatne Thanks for the answer. 

Of course I understand that it's all open source, and you are working hard to release all these cool new features in SDK39.
 
I just want to point out that the problem is with one of the main concepts for a lot of existing apps, and after 2 moths of waiting a lot of users are still dead in the water.

**Comment by JosephLep** [comment]
Will this also be something we have to wait for SDK 40 now to be fixed?  Waiting another quarter will kill us - looks like we will have to move away from Expo if so.  Would love an update

**Comment by Zanchee** [comment]
@JosephLep I don't think Expo has a precedent of releasing minor versions, but if there is a time to set precedent, this would be one. It's a very common feature used by many applications, including mine 😄 I have already had to refund my clients for lack of background location support on Android.

🤞 they fix this soon.

**Comment by Zanchee** [comment]
@byCedric similar issues found... Linking for reference.
#9200 - (Updates stop on Android / mentions of crashes)
#8483 (Null pointer exception)
#6017 (Null pointer exception)

**Comment by ashishsober** [comment]
Anyone from the expo team can update on this.
It will be very helpful for everyone.

**Comment by Zanchee** [comment]
@ashishsober the issue has already been acknowledged by Expo and they said they would follow up with more information when they had it. Let's keep comments useful and informational so that we don't drone out conversation about the actual issue.

**Comment by mounirzarkan** [comment]
does anyone have a workarround for this in expo (doesn't) matter how dirty and shitty it is. perhaps clearing the application data on close app ? are something like this

**Comment by brentvatne** [comment]
@mounirzarkan - you can eject your app and fix the code manually on your own if you need to.

<hr />

@byCedric is working on issues related to task manager and he'll provide updates soon! i'm going to lock this thread for now to keep this message at the bottom of the thread. we will unlock it again when we have an update, likely later this week.

**Comment by byCedric** [comment]
I've updated the issue with the latest update, again sorry for the inconvenience. We will keep this issue open, but locked to avoid clutter, until a new version of the Expo Client on Android is released.

**Comment by byCedric** [comment]
Hi all! All of the listed issues are fixed in Expo Client `2.17.4`, please upgrade to this client if you encounter these issues. Thanks to everyone who helped and sorry for the turnaround!
