### ISSUE TITLE
Location.getCurrentPositionAsync not working on Android

### ISSUE THREAD

**Issue by carsonwah** [expo/expo#946]
expo: v22.0.0
Android: 6.0.1

```
export const getLocationAsync = async () => {
  let { status } = await Permissions.askAsync(Permissions.LOCATION);
  if (status !== 'granted') {
    throw new Error('Location permission not granted');
  }
  return await Location.getCurrentPositionAsync({ enableHighAccuracy: false, maximumAge: 15000 });
};
```

`askAsync` is working fine. But `getCurrentPositionAsync` will keep running forever. Setting any timeout will eventually go into `Error: Location request timed out`.

I have tried it in real device v6.0.1 (nexus 5). I have also tried Android 5 and 6 in simulator. No luck for all of them.

I guess [this code](https://github.com/expo/expo/blob/ios/sdk22/android/app/src/main/java/abi16_0_0/host/exp/exponent/modules/api/LocationModule.java#L68) may have some hints to it.

Actually I have been waiting for the fix since expo v18.0.0. I saw some issues somewhat related to this, but I could not find any solution. Any update on this will be very much appreciated.

**Comment by jimmylee** [comment]
Hey @carsonwah I've pinged @nikki93 who is working on issues related to the SDK to take a look. I'm sorry you're encountering issues.

**Comment by carsonwah** [comment]
@jimmylee @nikki93 This problem seems solved now, on my nexus 5, both expo client and standalone. I have upgraded to expo v23.0.0 but not sure if it's the fix. Thanks so much for the hard work anyway.

**Comment by carsonwah** [comment]
@jimmylee @nikki93 I have set up Sentry for error report on my production app. Although my Nexus 5 is working fine, I am currently seeing > 130 users experiencing this issue (`Error: Location request timed out.`) from Sentry dashboard.

From what I see, the characteristic of this issue is that it happens on Android 22-25, with device year  2012-2014, even with Expo version v24.0.0.

I know this may be some kind of native bug, which is really hard to debug in Android. But while my users are still experiencing it, I want to reopen this issue just to hope that some fix may be found in the future.

If you guys want more details, I can send Sentry logs to you privately. Thanks.

<img width="318" alt="2018-01-23 17 02 32" src="https://user-images.githubusercontent.com/25053707/35266877-822362ae-005f-11e8-8b25-4485abb84534.png">
<img width="191" alt="2018-01-23 17 02 40" src="https://user-images.githubusercontent.com/25053707/35266876-81f9c46c-005f-11e8-98f2-188c63cfb3e5.png">
<img width="330" alt="2018-01-23 17 02 46" src="https://user-images.githubusercontent.com/25053707/35266875-81d0803e-005f-11e8-9d29-345d0150897d.png">

**Comment by conrad-vanl** [comment]
We appear to be experiencing this issue as well. Happy to provide any diagnostic info to help.

Code we're using to get location: https://github.com/NewSpring/Apollos/blob/master/src/%40utils/getLocation/index.js

And the app on expo:
https://expo.io/@newspring-builds/apollos-master

**Comment by Casy** [comment]
Any update on this? did you solve it @carsonwah ?

**Comment by edumelzer** [comment]
The problem continues with Expo v.25.0.0.

**Comment by carsonwah** [comment]
I am guessing this may be related to the device support of [Geolocation package](https://facebook.github.io/react-native/docs/geolocation.html), which is being used by Expo, from react-native itself.

I cannot test it for now, as it requires some unsupported devices. If anyone has those devices and maybe try it out will be very appreciated.

At this moment, I am still letting it happen in my app😅.

**Comment by vysakh0** [comment]
@carsonwah I have this issue only with the android builds, but works fine in the expo app, any idea what could be wrong?

**Comment by raajnadar** [comment]
Turned on High accuracy on my device that fixed the issue!

Android Nougat - 7.1.1
Settings -> Location -> Mode and set to High accuracy

**Comment by carsonwah** [comment]
@vysakh0 No, idea. I recently added some checkings with [`Location.getProviderStatusAsync()`](https://docs.expo.io/versions/v27.0.0/sdk/location). Hope things get clearer after I deployed the newsion.

I suspect that `gpsAvailable` and somethings like that will be `false`. However, since my Nexus 5 is working now, I have no way to check if it is the case. 

@raajnadar Did you use `{enableHighAccuracy: false}` when you getAsync()?

**Comment by raajnadar** [comment]
```
getLocationAsync = async () => {
    let { status } = await Permissions.askAsync(Permissions.LOCATION);

    if (status === 'granted') {
        console.log('Approved!');
        return Location.getCurrentPositionAsync({ enableHighAccuracy: false });
    } else {
       console.log('Rejected!');
       throw new Error('Location permission not granted');
    }
}
```
This is how I call the function
```
componentWillMount() {
   this.getDataAsync();
}
```
The location is only tracked when the location track mode is in **High accuracy** or **Battery saver**

**Comment by carsonwah** [comment]
@raajnadar You are right! If I set it to "Device only", it halts forever at `getCurrentPositionAsync()`, and return timeout error, which matches the behaviour described above.

![screenshot_20180428-144800](https://user-images.githubusercontent.com/25053707/39393092-8921ccb0-4af3-11e8-9f41-52cdb3fb5990.png)
![screenshot_20180428-144803](https://user-images.githubusercontent.com/25053707/39393093-895aaec2-4af3-11e8-9804-0ffe3930288c.png)

Not sure if this is the source of this error. But I can now provide more instruction to user to enable the location function. Thanks!

**Comment by clementino36** [comment]
Seems like the behavior is still the same. It is impossible to get the location while in "Phone only" mode (and not in "High accuracy" or "Battery saving"). And it is still not mentioned in the doc as @carsonwah suggested. 
I'm guessing this is not the wanted behavior ?

**Comment by hugogrochau** [comment]
My app depends greatly on Location Services, and after getting bug reports from some users we decided to investigate it further. Here are the problems we mapped out:

- With `enableHighAccurary: false` and GPS only mode on android `Location.getCurrentPositionAsync` hangs indefinitely
- With `enableHighAccurary: true` and GPS only *or* High accuracy mode on android `Location.getCurrentPositionAsync` hangs indefinitely
- On some phones (it seems to be affecting Motorola phones mostly, I've tested on an Android 7.1 Moto G4) nothing seems to work. `Location.getCurrentPositionAsync` either returns with "Location services are disabled" or hangs indefinitely

I've also prepared a snack to facilitate tests. It's configured to timeout after 5s instead of hanging indefinitely while running `Location.getCurrentPositionAsync`:
https://snack.expo.io/@hugogrochau/location-tests

**Comment by pindamonhangaba** [comment]
I can't get the location, no matter how long I wait. The promise just doesn't resolve or throw.

Tried downgrading to v29, but it still doesn't work. Location settings don't change anything.

**Comment by linux08** [comment]
@pindamonhangaba you got any solution yet.Currently facing the same issue

**Comment by tsapeta** [comment]
Hey everyone and thanks for all the details you gave about this issue 😄 

I've been trying to quickly investigate this issue but with no success. I thought it might be something with the library we're using to get the locations, however I also can't get a location using Android's APIs like LocationManager or FusedLocationProvider when the *GPS only mode* is enabled. I'll do more research on this but if anyone is interested, feel free to help 🙂

**Comment by fson** [comment]
https://stackoverflow.com/questions/48929941/fusedlocationprovider-any-way-to-get-a-location-if-location-mode-is-device-on

**Comment by ahmedsamyabdelhay** [comment]
@tsapeta Hi, any luck with this solve ?

**Comment by rafaeluzzi** [comment]
@ricpar11 I found the same thing. Location.getCurrentPositionAsync() works the first time, if called again quickly it will hang, on iOS it works fine

**Comment by tsapeta** [comment]
@ricpar11 @rafaeluzzi your issue is completely different than described in this thread, so please move the discussion to this new topic #3221 

Regarding issue described here, I'm working on it right now, will be back here soon 😉

**Comment by bhadkaria** [comment]
@tsapeta we are also stuck on this...our project is heavily depended on the feature and now our release is delayed.
Do we have any alternative that you can suggest us to explore at this time?

**Comment by tsapeta** [comment]
@bhadkaria Unfortunately, for now I don't see any workaround other than asking your users to enable *high accuracy* mode in Android's location settings. 

I did some more investigations and experiments - it seems like both **FusedLocationProviderClient** and **LocationManager** just don't work properly with *device only* setting. Having this setting, I was also unable to find my location using Google Maps app, so it must be an internal issue on Android platform. The best solution I've found is to check whether the user's setting is enough to get current location and if not, show a handy dialog with an option to enable *high accuracy* mode. Example here:

![screenshot_20190118-140741_google play services](https://user-images.githubusercontent.com/1714764/51389068-81660000-1b2b-11e9-98a8-b8b2b269ad0d.jpg)

I'm going to add such feature into `getCurrentPositionAsync` and `watchPositionAsync` methods. Returned promise will be rejecting with an error `E_LOCATION_SETTINGS_UNSATISFIED` if you cancel this dialog. Choosing "OK" will automatically modify the location mode to *High accuracy* which will allow you to get new locations.

I hope this solution will be satisfactory for you 😉

**Comment by vpontis** [comment]
@tsapeta thanks for looking into this!

> The best solution I've found is to check whether the user's setting is enough to get current location and if not, show a handy system dialog with an option to enable high accuracy mode.

Do you have a code example?

**Comment by tsapeta** [comment]
@vpontis do you mean an example in JS? In fact nothing will change there, this dialog will be shown during `getCurrentPositionAsync` and `watchPositionAsync` calls, but only when the network provider is not available. I'll also add an option to opt out of this feature, but in that case this issue may continue to appear as network provider is required to get the position in some cases 😞

**Comment by vpontis** [comment]
@tsapeta yea, I meant an example in JS. 

It sounds like you need to modify the native code for this? I thought you could do it only w/ JS.

**Comment by tsapeta** [comment]
@vpontis yes, I'm refactoring some native parts of Android's location module right now, trying to solve a bunch of issues. I haven't found another solution to this problem 😞

**Comment by Lucifer1662** [comment]
Hey I ran into a similar problem and it was because I was using mock location app to change my location and I uninstalled it but it didn't reset my location back to normal so all location data on my phone was wrong, so I installed the mock location app again and made sure to turn it off before uninstalling. 
Might not be your problem though, hope this helps someone.

**Comment by heyaj19** [comment]
@tsapeta  would be great to actually have this tagged in the expo document on the location page. Kind of annoying

**Comment by simsketch** [comment]
I tried updating my app to expo 32.0.6 but the location still isn't loading on Android. I changed values in package.json, then rm -rf node_modules/, then npm i, then expo build:android...no luck. In app.json you cannot change sdkVersion to a point release, it has to be 32.0.0 or the apk won't even begin compiling.

**Comment by simsketch** [comment]
I had success getting location to work for Android, using expo 32.0.6:

`npm install expo-location`
make sure it is now in your `package.json` file as "^3.0.0"
`rm -rf node_modules/`
`npm i`
check inside `node_modules/expo-location/package.json` to make sure that version 3.0.0 was installed
`expo start` to test locally if you'd like
`expo build:android` to generate apk because changes any changes to `app.json` require a new store submission.

My expo Location code that was working in previous builds and then broke, is now working again as expected. I was using expo-location 2.0.1 previously and it looks like they came out with 3.0.0 6 days ago https://www.npmjs.com/package/expo-location, so I thought I would give it a shot because in another issue around here they said they had some fixes in the works.

Thanks for the fix Team Expo!

**Comment by superyarik** [comment]
@simsketch it's strange to add expo-location to expo project. also as i know adding ACCESS_FINE_LOCATION section will delete default permissions of application.

**Comment by simsketch** [comment]
it was already there but i needed to make sure expo-location was version 3.0, it's included as a dependency of expo normally...with regard to the permissions section, I originally added the permissions section to my app.json after a Google Play policy change about SMS where I had to implement the permission if I was using it. In my case I was not using it so I am explicitly requesting the location permission here so nothing else gets added. In retrospect it probably would have worked with just LOCATION as the only permission and I might change it to that in the future but it is working for me for now.

**Comment by jdnichollsc** [comment]
Same issue here with expo 32.0.6, also adding `permissions` from app.json file
Any help is really appreciated

**Comment by brentvatne** [comment]
if you are still having an issue like this then please create a new issue and follow the issue template closely to describe exactly what your circumstances and provide a reproducible example, because as far as we can tell it has been resolved. thanks!
