### ISSUE TITLE
Expo keeps stopping when the app is killed while background location methods

### ISSUE THREAD

**Issue by imdhemy** [expo/expo#9570]
### Summary of Issue 
I registered a task for receiving the location updates in the background using `Location.startLocationUpdatesAsync(taskName, options)`, And defined a task in the global scope using `TaskManager.defineTask(taskName, task)`. The app frequently crashes when killed if the background task is active. 

- The Expo client refuses to start unless clearing its storage on Android.

- The standalone app starts after at least two trials with a crash message.

### Environment

- expo: `^38.0.0`
- expo-task-manager: `~8.3.0`
- expo-location: `~8.2.1`

### Screenshot
<img src='https://user-images.githubusercontent.com/22864831/89450617-1a368d80-d75b-11ea-8188-09e3cce36932.jpeg' width=200/>

 
### Steps to Reproduce
1- `Location.startLocationUpdatesAsync`
2- `TaskManager.defineTask`
3- Kill the application.

### Expected Behavior vs Actual Behavior

- **Expected behavior:** The running task terminates smoothly.
- **Actual behavior:**: The running task is killed, and the app can be restarted without a crash message.

**Comment by guilhermepaula** [comment]
I'm having the same issue. A lot of users reporting this behavior after installing the version with SDK 38. 

Android Vitals page shows:

```
java.lang.RuntimeException: 
  at android.app.job.JobService$JobHandler.handleMessage (JobService.java:147)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6351)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:896)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:786)
Caused by: java.lang.NullPointerException: 
  at expo.modules.taskManager.TaskService.executeTask (TaskService.java:408)
  at expo.modules.taskManager.Task.execute (Task.java:58)
  at expo.modules.location.taskConsumers.LocationTaskConsumer.executeTaskWithLocationBundles (LocationTaskConsumer.java:330)
  at expo.modules.location.taskConsumers.LocationTaskConsumer.didExecuteJob (LocationTaskConsumer.java:150)
  at expo.modules.taskManager.TaskService.handleJob (TaskService.java:331)
  at expo.modules.taskManager.TaskJobService.onStartJob (TaskJobService.java:13)
  at android.app.job.JobService$JobHandler.handleMessage (JobService.java:143)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6351)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:896)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:786)
```

**Comment by michaelkleinhenz** [comment]
This looks like the issue in https://github.com/expo/expo/issues/9415

**Comment by Ericthestein** [comment]
I am also experiencing this issue and encountering the, "Cannot initialize app loader. host.exp.exponent.taskManager.ExpoHeadlessAppLoader" error. This occurs on an Android simulator when testing using Expo and using a standalone app published to the Google Play store.

Could someone confirm that this error does not occur prior to SDK 38 before I try downgrading?

**Comment by michaelkleinhenz** [comment]
I'd consider this a serious issue. The background location feature is not working on Android and crashes the dev client and standalone apps.

**Comment by ntbosscher** [comment]
I'm hitting nearly the same stack trace as @guilhermepaula after some recent changes. Recently I upgraded to sdk-38 and started using the new `expo-notifications` package for notifications.

```
java.lang.RuntimeException: 
  at android.app.job.JobServiceEngine$JobHandler.handleMessage (JobServiceEngine.java:112)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7156)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:975)
Caused by: java.lang.NullPointerException: 
  at expo.modules.taskManager.TaskService.executeTask (TaskService.java:408)
  at expo.modules.taskManager.Task.execute (Task.java:58)
  at expo.modules.backgroundfetch.BackgroundFetchTaskConsumer.didExecuteJob (BackgroundFetchTaskConsumer.java:90)
  at expo.modules.taskManager.TaskService.handleJob (TaskService.java:331)
  at expo.modules.taskManager.TaskJobService.onStartJob (TaskJobService.java:13)
  at android.app.job.JobService$1.onStartJob (JobService.java:62)
  at android.app.job.JobServiceEngine$JobHandler.handleMessage (JobServiceEngine.java:108)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7156)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:975)
```

The related JS code

```js
import * as BackgroundFetch from "expo-background-fetch";
import * as TaskManager from "expo-task-manager";

async init() {
    if (TaskManager.isTaskDefined(offlineSyncTaskName)) {
      await TaskManager.unregisterTaskAsync(offlineSyncTaskName);
    }
    
    TaskManager.defineTask(offlineSyncTaskName, () => this.backgroundTask());
    // interval is ~10-15 mins
    await BackgroundFetch.registerTaskAsync(offlineSyncTaskName, {});
    ...
}

async backgroundTask() {
    try {
      await this.sync();
      await notificationService.check();

      return BackgroundFetch.Result.NewData;
    } catch (e) {
      console.error(e);
      return BackgroundFetch.Result.Failed;
    }
 }
```

**Comment by ntbosscher** [comment]
Slightly unrelated, in debugging this issue I'd be happy to debug the native code and try to find a solution. But I found that it was too difficult to get an environment setup to do that. It would be really nice if you could easily open your project in android studio and run it in debug mode to debug the native code.

**Comment by michaelkleinhenz** [comment]
> Slightly unrelated, in debugging this issue I'd be happy to debug the native code and try to find a solution. But I found that it was too difficult to get an environment setup to do that. It would be really nice if you could easily open your project in android studio and run it in debug mode to debug the native code.

I did not try this, but afaik `expo eject` should give you an Android Studio project.

**Comment by guilhermepaula** [comment]
Any relation with [8.3.0 release](https://github.com/expo/expo/blob/master/packages/expo-location/CHANGELOG.md#830--2020-07-16)?

**Comment by michaelkleinhenz** [comment]
> Any relation with [8.3.0 release](https://github.com/expo/expo/blob/master/packages/expo-location/CHANGELOG.md#830--2020-07-16)?

Interesting. I experience this issue and `expo-location` is on `8.2.1`. Upgrading it manually results in a warning about inconsistent expo versions when building. Can someone clear this up a bit: are the `expo-*` libraries tied to the SD release? What is the roadmap there? Is there a way to test out newer, unreleased versions? Or any other way to get `expo-location` `8.3.0` or higher into my project?

**Comment by michaelkleinhenz** [comment]
Ok, I force-upgraded to `expo-location 8.3.0` and the Android client still crashes. No change.

**Comment by michaelkleinhenz** [comment]
Note: in the 8.3.0 release notes, the link to the relevant PR for the NPEs is wrong, should be this: https://github.com/expo/expo/pull/8868

**Comment by michaelkleinhenz** [comment]
Also tried to upgrade `expo-taskmanager` to 8.4.0, no luck, same crash.

**Comment by Aryk** [comment]
> I haven't been getting any crashes after ejecting and upgrading the expo-task-manager to 8.4.0. I set the permission to "Allow all the time" as well and so far so good. It was posted somewhere that this version fixes this crash and will be rolled out in the expo SDK 39. It was my first time ejecting from expo so it was kind of a pain to set up for me, but at least it got the job done.

Would be nice to confirm that this will indeed be fixed in 39? Did you see it in a github ticket?

Are there any work arounds without having to eject and stay on 38?

**Comment by Kokopelli84** [comment]
It is mentioned on Issue [#9288](https://github.com/expo/expo/issues/9288). I worked for weeks on this, but was unable to find a workaround. Only ejecting and upgrading the `expo-task-manager` to 8.4.0 solved this for me.

**Comment by michaelkleinhenz** [comment]
@Kokopelli84  @Aryk Is there a difference between ejecting and manually updating `location-manager` to `8.4.0` in `package.json`? Because I tried the `package.json` variant and also verified the deps had `8.4.0` in `node_modules`, but the client was still crashing..

**Comment by Kokopelli84** [comment]
> @Kokopelli84 @Aryk Is there a difference between ejecting and manually updating `location-manager` to `8.4.0` in `package.json`? Because I tried the `package.json` variant and also verified the deps had `8.4.0` in `node_modules`, but the client was still crashing..

It doesn't work that way. The reason is that it is not supported by Expo SDK 38. Have a look [here](https://github.com/expo/expo/issues/9288) to see an explanation for it.

**Comment by Aryk** [comment]
In the meantime...I created my own "background task" for location on android only. It will poll the users location and send it up while the app is not killed... It will tie me over until the 39 release.

**Comment by m-jachym** [comment]
@Aryk 
Soo, you have created something like [backgroundFetch.registerTaskAsync](https://docs.expo.io/versions/latest/sdk/background-fetch/#backgroundfetchregistertaskasynctaskname-options) with [Location.getCurrentPositionAsync(options)](https://docs.expo.io/versions/latest/sdk/location/#locationgetcurrentpositionasyncoptions) ??

**Comment by Sebascabarcas** [comment]
@Aryk 
Is it possible for u share a little bit about your solution?

**Comment by Aryk** [comment]
No problem. Something like this is what i have.

```ts
import {useEffect, useRef} from "react";
import haversine from "haversine";

  // In android, sdk 38 managed workflow, we cannot use startLocationUpdatesAsync.
  // So we add a callback in a component to check for changes in the location and send them to the server....
  // works "ok", but will not work when the app is shutoff. We'll have to wait until SDK 39.0 for it to hopefully be solved.
  // https://forums.expo.io/t/startlocationupdatesasync-crashes-app-on-sdk-38-android-managed/42035
  useLocationUpdateForAndroid = () => {
    const lastPosition = useRef<ICoordinates>();
    const locationEnabled = useRef<Boolean>(false);

    // We should not be running useLocationUpdateForAndroid in a place where we don't have permission async, but "just in case", I put this
    // check here.
    useEffect(() => {
      Location.getPermissionsAsync().then(({status}) => {
        if (status === "granted") {
          locationEnabled.current = true;
        }
      });
    }, []);

    const runLocationUpdate = () => locationEnabled.current ? Location.getLastKnownPositionAsync().then(({coords: {latitude, longitude}}) => {
      let updateLocation = true;
      // If they haven't moved more than 15m from last reading don't persist their new location.
      if (lastPosition.current && !haversine({latitude, longitude}, lastPosition.current, {unit: "meter", threshold: 15})) {
        updateLocation = false;
      }
      if (updateLocation) {
        // send to server
      }
      lastPosition.current = {latitude, longitude};
    }) : undefined;

    useEffect(() => {
      const interval = setInterval(() => runLocationUpdate(), 30000);
      return () => clearInterval(interval);
    }, []);
```

**Comment by michaelkleinhenz** [comment]
Ok, but this solution only works if the app is in the foreground and used. That will not work for me, sadly, as I need a true background task to fech location and notify the user if some location matches.

**Comment by m-jachym** [comment]
Unfortunatelly @michaelkleinhenz is right. I don't understand why expo can't fix it, and we have to wait to sdk39 release.
This example shows that managed workflow is still not suitable for any commercial projects.

**Comment by michaelkleinhenz** [comment]
I am still not convinced that it is actually fixed in 39. I haven't seen a PR that directly refers to this issue. And you're right, this is a major issue in an essential component. This should be fixed asap and with a hotfix. It is clearly understandable and clearly verifyable. And given that there are mutiple issues related to this issue, has a bit of gravity to it.

My fear is that this is an issue that exposes some deeper issues that are not easily fixable. I've seen a few source comments like "more checks for NPEs, if this does not help, we have a deeper issue with thread safety..". Those stuff makes me concerned..

**Comment by Aryk** [comment]
@michaelkleinhenz what about this comment - https://github.com/expo/expo/issues/9288#issuecomment-664354295

**Comment by Zanchee** [comment]
These definitely seem like the same issue. @m-jachym they can fix it, and I think they have... but the issue is in native code, not JavaScript. In order to fix the issue they need to compile a new root binary for the managed workflow, which I'm sure is no small task. If you are concerned about needing this fix sooner, you can always eject, to the bare workflow. There are pros and cons to each flow, and the managed one is that you are relying on Expo to do all the complicated things you don't want to do.

**Comment by Zanchee** [comment]
@michaelkleinhenz just for clarity, and understanding for everyone...

When you said you tried different versions of the dependency, I'm assuming you didn't actually eject the project? If that's the case it makes sense that it still "Doesn't Work" on Expo 38, because the bug is in native code.

In order to test that those versions did fix the issue, you would need to be testing with an ejected project in the bare flow.

If you tested it with an bare/ejected project, then we should address that by looping in the person who fixed it originally, but I don't believe that is the case.

**Comment by ashishsober** [comment]
> > I haven't been getting any crashes after ejecting and upgrading the expo-task-manager to 8.4.0. I set the permission to "Allow all the time" as well and so far so good. It was posted somewhere that this version fixes this crash and will be rolled out in the expo SDK 39. It was my first time ejecting from expo so it was kind of a pain to set up for me, but at least it got the job done.
> 
> Would be nice to confirm that this will indeed be fixed in 39? Did you see it in a github ticket?
> 
> Are there any work arounds without having to eject and stay on 38?
> 
> I made a forum posting tying this all together:
> 
> https://forums.expo.io/t/startlocationupdatesasync-crashes-app-on-sdk-38-android-managed/42035

yes,anyone please confirm

**Comment by ashishsober** [comment]
> @michaelkleinhenz just for clarity, and understanding for everyone...
> 
> When you said you tried different versions of the dependency, I'm assuming you didn't actually eject the project? If that's the case it makes sense that it still "Doesn't Work" on Expo 38, because the bug is in native code.
> 
> In order to test that those versions did fix the issue, you would need to be testing with an ejected project in the bare flow.
> 
> If you tested it with an bare/ejected project, then we should address that by looping in the person who fixed it originally, but I don't believe that is the case.

@Zanchee ,you mean to say that ,we have to wait for the next release of the expo version which is 39 or go with the bare flow

**Comment by zwass** [comment]
I am encountering possibly the same issue (similar stacktrace), but I am not making any use of location services.

I get the following stacktrace upon startup of the app (only when built as standalone .apk):

```
2020-08-27 21:14:26.021 18702-18702/? E/Expo: Cannot initialize app loader. host.exp.exponent.taskManager.ExpoHeadlessAppLoader
2020-08-27 21:14:26.021 18702-18702/? W/System.err: java.lang.ClassNotFoundException: host.exp.exponent.taskManager.ExpoHeadlessAppLoader
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at java.lang.Class.classForName(Native Method)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at java.lang.Class.forName(Class.java:454)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at java.lang.Class.forName(Class.java:379)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at l.d.a.b.a(AppLoaderProvider.java:2)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at l.d.a.b.b(AppLoaderProvider.java:2)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at expo.modules.taskManager.TaskService.getAppLoader(TaskService.java:2)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at expo.modules.taskManager.TaskService.isStartedByHeadlessLoader(TaskService.java:1)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at expo.modules.taskManager.TaskManagerInternalModule.isRunningInHeadlessMode(TaskManagerInternalModule.java:1)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at expo.modules.taskManager.TaskManagerInternalModule.onHostResume(TaskManagerInternalModule.java:1)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at org.unimodules.adapters.react.services.d$c.onHostResume(UIManagerModuleWrapper.java:2)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:5)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:3)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:11)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:3)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at java.lang.reflect.Method.invoke(Native Method)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at host.exp.exponent.k.a(RNObject.java:17)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at host.exp.exponent.k.a(RNObject.java:12)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at host.exp.exponent.k.a(RNObject.java:58)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at host.exp.exponent.experience.k.onResume(ReactNativeActivity.java:3)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at host.exp.exponent.experience.f.onResume(BaseExperienceActivity.java:1)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at host.exp.exponent.experience.ExperienceActivity.onResume(ExperienceActivity.java:1)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at android.app.Activity.performResume(Activity.java:7962)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at android.os.Handler.dispatchMessage(Handler.java:107)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at android.os.Looper.loop(Looper.java:214)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at android.app.ActivityThread.main(ActivityThread.java:7356)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at java.lang.reflect.Method.invoke(Native Method)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-08-27 21:14:26.021 18702-18702/? W/System.err: Caused by: java.lang.ClassNotFoundException: host.exp.exponent.taskManager.ExpoHeadlessAppLoader
2020-08-27 21:14:26.021 18702-18702/? W/System.err: … 35 more
```

**Comment by Obversity** [comment]
Experiencing this issue in an app in production right now, which was just upgraded to SDK 38 and where we just started using `Location.startLocationUpdatesAsync`. Here's the stack trace from the crash report in the play console. 

```
java.lang.RuntimeException: 
  at android.app.job.JobServiceEngine$JobHandler.handleMessage (JobServiceEngine.java:112)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:216)
  at android.app.ActivityThread.main (ActivityThread.java:7266)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:975)
Caused by: java.lang.NullPointerException: 
  at expo.modules.taskManager.TaskService.executeTask (TaskService.java:408)
  at expo.modules.taskManager.Task.execute (Task.java:58)
  at expo.modules.location.taskConsumers.LocationTaskConsumer.executeTaskWithLocationBundles (LocationTaskConsumer.java:330)
  at expo.modules.location.taskConsumers.LocationTaskConsumer.didExecuteJob (LocationTaskConsumer.java:150)
  at expo.modules.taskManager.TaskService.handleJob (TaskService.java:331)
  at expo.modules.taskManager.TaskJobService.onStartJob (TaskJobService.java:13)
  at android.app.job.JobService$1.onStartJob (JobService.java:62)
  at android.app.job.JobServiceEngine$JobHandler.handleMessage (JobServiceEngine.java:108)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:216)
  at android.app.ActivityThread.main (ActivityThread.java:7266)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:975)
```

Any confirmation that this will be fixed in SDK 39 would be great, as this has reduced my client's confidence in the platform somewhat.

**Comment by Zanchee** [comment]
@Obversity the linked ticket states it will go out in 39

**Comment by nimrodbens** [comment]
any solution for it? i'm on a bare react project and i tried to update to expo-location 9.0.0 and expo-task-manager 8.5.0 and whenever i run background location and kill the app it breaks my app. whenever background location if off and i kill the app everything remains fine. maybe there are older versions i can roll back to where this issue doesn't happen?

for me what happens is when i run background location and the app is killed then the next time i load the app my entire app is broken. the user is shown the onboarding screen even though they were logged in and even though there is a valid token. and also in that onboarding screen the components are not clickable. it completely breaks my app. and if i turn off background location and kill the app the next time the user opens it everything is working as it should and the main screen is shown. this is happening consistently when background location is on/off.

**Comment by nimrodbens** [comment]
if anyone needs a fix in the meanwhile i came up with the following. i am using [this background timer library](https://github.com/ocetnik/react-native-background-timer).

that's about how i defined the task (i simplified it):
`BackgroundTimer.setTimeout` returns an id for the task, so i also make sure to call `BackgroundTimer.clearTimeout(id);` where needed.

    TaskManager.defineTask(LOCATION_TRACKING, async ({data, error}) => {
        Location.stopLocationUpdatesAsync(LOCATION_TRACKING);
        .... // your code
        BackgroundTimer.setTimeout(() => { 
            Location.startLocationUpdatesAsync(LOCATION_TRACKING, {...});
        }, 5 * MINUTE);
    });

and then just simply start your task as you would.

    Location.startLocationUpdatesAsync(LOCATION_TRACKING, {...});

it may be a weird way to go about it, but it works for now.

**Comment by ankit-kumar615** [comment]
A project which was working fine a couple of days ago (sdk 26.0.0) has stopped working now. When trying to open it, the app crashes with only the “Expo keeps stopping” error message. I proceeded to update the cli, the sdk and the android app to their latest versions, however, even now when i run a project with expo init and expo start, the app simply crashes. The apps in the Featured section of the expo android app seem to be working fine. Does anybody have any experience with this? This has pretty much killed all the expo projects i am working on and any insight would be greatly appreciated

**Comment by roger-schaer** [comment]
I have tested the background location methods with Expo SDK 39, and I still get the same behavior as before, i.e. the app crashes if it is "swiped" away while the background location task is running. I've tested it on emulators with Android 9, 10 & 11, as well as on a real device with Android 11.

I'm really disappointed, as I desperately need this feature to work and had put all my hopes in the new version solving these issues (as described in the CHANGELOG for expo-location / expo-task-manager).

**Comment by eltan-tell** [comment]
There is an umbrella issue [#9288 ](https://github.com/expo/expo/issues/9288) , but I'm not sure anyone cares about this issue ;____;

**Comment by brentvatne** [comment]
@ankit-kumar615 - this is not related to this issue. please create a new issue with more info if you believe this is a bug in expo code.

**Comment by Zanchee** [comment]
@brentvatne these are definitely the same issue...

**Comment by Aryk** [comment]
> I have tested the background location methods with Expo SDK 39, and I still get the same behavior as before, i.e. the app crashes if it is "swiped" away while the background location task is running. I've tested it on emulators with Android 9, 10 & 11, as well as on a real device with Android 11.
> 
> I'm really disappointed, as I desperately need this feature to work and had put all my hopes in the new version solving these issues (as described in the CHANGELOG for expo-location / expo-task-manager).

Can someone from Expo please comment on this? 

Many have waited for this release for this to be fixed (including myself) but appears that it's happening for everyone on Android...

**Comment by Zanchee** [comment]
@Aryk please take the conversation to the umbrella issue. Expo has acknowledged and responded to this. There is no need to post additional "unhelpful" comments like this, it simply drones out useful information. A simple emoji reaction would have been sufficient.

**Comment by RodolfoGS** [comment]
I have a similar issue and the bug is related to **Proguard**. I'm not using background location, I'm using background fetch.

[x] If **Proguard** is enabled, the app crash in background (_AppName_ has stopped)
[✓] If **Proguard** is disabled, all works perfect.

Logcat:
```
2020-09-30 07:53:43.632 5371-5371/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xxx, PID: 5371
    java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke interface method 'void l.b.a.b.a(android.content.Context, l.b.a.b$b, java.lang.Runnable, l.b.b.l.e)' on a null object reference
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void l.b.a.b.a(android.content.Context, l.b.a.b$b, java.lang.Runnable, l.b.b.l.e)' on a null object reference
        at expo.modules.taskManager.h.a(Unknown Source:125)
        at expo.modules.taskManager.c.a(Unknown Source:2)
        at expo.modules.backgroundfetch.BackgroundFetchTaskConsumer.didExecuteJob(Unknown Source:8)
        at expo.modules.taskManager.h.b(Unknown Source:64)
        at expo.modules.taskManager.TaskJobService.onStartJob(Unknown Source:9)
        at android.app.job.JobService$1.onStartJob(JobService.java:71)
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
```

package.json
```
expo: 39.0.3
expo-background-fetch: 8.5.0
expo-task-manager: 8.5.0
```

**Comment by byCedric** [comment]
Sorry for not updating this issue earlier. This set of changes fixed this issue:
- https://github.com/expo/expo/pull/10410
- https://github.com/expo/expo/pull/10411
- https://github.com/expo/expo/pull/10409

Happy holidays!
