### ISSUE TITLE
[media-library] "Error: Option "after" must be a valid ID!" after update to 9.0.0

### ISSUE THREAD

**Issue by ahmetbicer** [expo/expo#9719]
### Summary of Issue 
After updating media-library to 9.0.0, `MediaLibrary.getAssetsAsync()` gives `Error: Option "after" must be a valid ID!`. Before this update if i want to get the first page of the assets i didn't use the `after` prop. I think it is now required to give this prop but i don't know what to give if i want to get the first page.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Bare react native project
"react-native": "0.63.2"
"expo-av": "^8.5.0",
"expo-media-library": "^9.0.0",
"expo-video-thumbnails": "^4.2.1",
"react-native-unimodules": "^0.10.1",

buildToolsVersion = "29.0.0"
minSdkVersion = 21
compileSdkVersion = 29
targetSdkVersion = 29

### Reproducible Demo
Call `MediaLibrary.getAssetsAsync()` without after prop. I am using this code snippet to get the first 10 asset.

```
getAlbumData = async (album) => {
    try {
      var result = await MediaLibrary.getAssetsAsync({
        first: 10,
        album: album.id,
        mediaType: MediaLibrary.MediaType.video,
        sortBy: MediaLibrary.SortBy.creationTime,
      })
      if (result.totalCount > 0) {
        return { album: album, count: result.totalCount }
      }
      else {
        return null
      }
    } catch (error) {
      console.warn(error) // Error: Option "after" must be a valid ID! 
    }
  }
```

### Steps to Reproduce
Call `MediaLibrary.getAssetsAsync()` without `after` prop.

### Expected Behavior vs Actual Behavior
Expected: If `after` prop don't specified, get the first page of the assets.
Actual: `after` prop always required.

I think it is related to this issue #9440  which closed by this pr #9466 

**Edit: Using "0" as `after` prop seems like the solution but i just want to be sure about this.**

**Comment by barthap** [comment]
I have fixed that in #9666, but the fix came right after publishing 9.0.0 😞

**Comment by ahmetbicer** [comment]
@barthap ahh i didn't see that. Thank you so much for the fix! I am closing the issue since it will resolve once it released.

**Comment by barthap** [comment]
Hi, `expo-media-library@9.1.0` has just been published! It contains the fix.

**Comment by mSenad** [comment]
@barthap Hi. Did you try it with the new version because I'm still having the same problem... 

I have "expo-media-library": "9.1.0" version installed and when calling:

```
const { status } = await MediaLibrary.getPermissionsAsync();
if (status !== 'granted') return;
MediaLibrary.getAssetsAsync({
      mediaType: MediaLibrary.MediaType.photo,
      sortBy: MediaLibrary.SortBy.creationTime,
    }).then(this.processPhotos);
```

My android app still gets crashed without any errors. Am I doing something wrong or?

Thanks.

**Comment by barthap** [comment]
@mSenad So is it the same problem or crash without any error? These are two different things and I'm confused.

**Comment by mSenad** [comment]
@barthap It crashes without any error. I'm trying to access my camera's roll photos and on IOS everything works as expected but on android, it just crashes... I tried with the **expo-media-library@9.1.0** and calling 

`MediaLibrary.getAssetsAsync({
      mediaType: MediaLibrary.MediaType.photo,
      sortBy: MediaLibrary.SortBy.creationTime,
    }).then(this.processPhotos);`

... just crashes the android app in development and production. Not sure if I'm doing something wrong.

**Comment by barthap** [comment]
It may be related to this issue: #10398 - try removing or changing the `sortBy` parameter. If it doesn't help, please open a new issue, because this one concerns different problem and it's already closed.

**Comment by mSenad** [comment]
@barthap Still nothing... I'll open a new issue because the same problem is occurring when all these params are removed. Thank you very much.
