### ISSUE TITLE
[expo-background-fetch] Background fetch is not running

### ISSUE THREAD

**Issue by maxgfr** [expo/expo#9900]
### Summary of Issue

Hi everyone, I'm writing this issue because `expo-background-fetch` doesn't work with my project.

### Environment 

```
  Expo CLI 3.24.2 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - ~/.nvm/versions/node/v10.19.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.24.2
```
### Reproducible Demo

I've created a little project which is [here](https://github.com/maxgfr/expo-test-background-tasks). 

It's a little app which uses some chunks of code that I've seen in this [issue](https://github.com/expo/expo/issues/3582).

### Expected Behavior vs Actual Behavior

My task function doesn't work whereas I initialized the tasks.

```
console.log(
      "Task is running in background each ",
      INTERVAL_TASKS,
      " seconds."
    );
```

I also try to switch between my actuel version of the npm package to the latest (8.4.0). It doesn't change

```
"dependencies": {
    "expo": "~38.0.8",
    "expo-background-fetch": "~8.3.0",
    "expo-status-bar": "^1.0.2",
    "expo-task-manager": "~8.3.0",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-web": "~0.11.7"
  },
```

Any guesses to solve this issue ?

Thanks for your help.

**Comment by trajano** [comment]
In my case I upgraded to the latest Expo dependencies, but it still does not work only on iOS with the `expo client:ios`.  It works properly on Expo Go on Android though.

**Comment by trajano** [comment]
@maxgfr your code looks like it should work with Expo Go on Android though.  It looks similar to mine.  Are you still having issues with the Android platform?

**Comment by trajano** [comment]
There's a notice in https://developer.apple.com/documentation/uikit/uiapplication/1623100-setminimumbackgroundfetchinterva regarding setMinimumBackgroundFetchInterval being deprecated and replaced with https://developer.apple.com/documentation/backgroundtasks/bgapprefreshtask but I can't find `BGAppRefreshTask` when I do a search on the repo

**Comment by maxgfr** [comment]
@trajano Hi Archimedes, I've only tried on iOS using Expo Go, 6 months ago. The latest version that I use to try this feature was on iOS 13 🤔. I've not more investigated

**Comment by trajano** [comment]
@maxgfr  thanks for the info.

I created my own MVCE as well for this https://github.com/trajano/expo-mvce it works with Android, but not iOS with the current versions of Expo.  I also tried upgrading to the 9.0 for background fetch and task manager but no luck with it either.

**Comment by trajano** [comment]
I think I got it running, but the frequency is quite random.  You need to have your device plugged in for the most part as well.

**Comment by srikanthkh** [comment]
@trajano Did it start working when you added the location permission? https://github.com/trajano/expo-mvce/commit/ed899fc12289c00dc555597dff3136753c5b052e

**Comment by trajano** [comment]
I think I added it to the props but I never actually requested the location access it in the code.

**Comment by srikanthkh** [comment]
I see.. In my code I am not seeing the notification working. But background fetch did work and update asyncstorage. Just the notification does not show up.

**Comment by srikanthkh** [comment]
I'll copy paste your code in my app and see if notification works. Did it work because you Ejected? I have not ejected mine yet... still using managed expo.

**Comment by trajano** [comment]
Notification will only show up if you have a custom IOS client.  That's written in the instructions I think.  I didn't eject.

**Comment by srikanthkh** [comment]
So in my code I am showing a Notification when I register a background task... and that works. But the notification inside the defined background task does not work. I am testing on the actual device by pushing the code to testflight.

**Comment by srikanthkh** [comment]
const backgroundFetch = async (body: TaskManager.TaskManagerTaskBody): Promise<BackgroundFetch.Result> => {
    // the executor code should not be accessing any
    // React-Native context data

    // This is the test text
    const text = new Date(Date.now()).toLocaleTimeString();
    console.log(BACKGROUND_FETCH_TASK, body);
    await AsyncStorage.setItem(BACKGROUND_FETCH_TASK, text)
    await Notifications.scheduleNotificationAsync(
        {
            content: {
                title: "Time's up!",
                body: `Set value to ${text}`,
            },
            trigger: null
        }
    );
    return BackgroundFetch.Result.NewData;
}

This Time'up notification is what never shows up.

**Comment by srikanthkh** [comment]
Did you use a custom IOS client?

**Comment by trajano** [comment]
Yes it's required by the docs.

**Comment by srikanthkh** [comment]
I was reading through the expo docs last day and it says you cannot handle push notifications in the background. 
https://docs.expo.io/introduction/why-not-expo/
So I had given up on trying to get this work... but if you say that you got notification working through a background task that is great news. I am getting back on to solving this 👍

**Comment by trajano** [comment]
Push notifications should work (but I didn't try), but not in China for Android which is why I had to go through alternatives that do not involve Google.  Another alternative I tried but failed was https://pushy.me/ but that does not work in Expo https://github.com/pushy-me/pushy-react-native/issues/61

**Comment by ppulwey** [comment]
@trajano I have the same issue. Code runs perfectly on Android but iOS (with custom Expo client) is not working. How did you manage to get it run?
I've already opened a stackoverflow question (here)[https://stackoverflow.com/questions/66086788/reactnative-expo-background-fetch].
The error message for iOS (when I open the client after some time >15 minutes):
```
Cannot connect to the Metro server.

Try the following to fix the issue:
- Ensure that the Metro server is running and available on the same network
- Ensure that the Metro server URL is correctly set in AppDelegate

URL: 192.168.178.27:19000

Error: The operation couldn’t be completed. Socket is not connected
```

**Comment by trajano** [comment]
@ppulwey keep your device plugged in.  Make sure you don't have the app running but you ran it once.

**Comment by ppulwey** [comment]
I can't confirm this is working on iOS. 
* App runs in background, it is not manually killed
* Device was plugged in via USB
* Background fetch is enabled in App Settings of custom Expo client

I don't get the YouTube thing...

This is really frustrating. I've even tried the "official" background fetch source code of expo team with the same results. The task never runs on iOS.

**Comment by trajano** [comment]
YouTube uses a somewhat similar mechanism from what I gather (not push notifications).  If you don't get notifications on YouTube then chances are something else is preventing it from popping up.

**Comment by trajano** [comment]
I just pushed a change on my MVCE to remove all the other background operations

**Comment by trajano** [comment]
@ppulwey try to do `expo upgrade` I just did that and it resolved my issue in #11866

**Comment by ashtyn3** [comment]
Is there any fixes for this yet? if not they should put a disclaimer in the docs it doesn't work.

**Comment by ajsmth** [comment]
hey there - have you folks attempted to trigger background fetch via the Xcode debug menu? 

<img width="304" alt="Screen Shot 2021-06-11 at 11 36 22 AM" src="https://user-images.githubusercontent.com/40680668/121968009-4e3cf080-cd26-11eb-84b9-0d3bd3a9e9c2.png">

I was able to reliably trigger background tasks on the simulator by using this option.

We'll update the documentation to include a more thorough example as well as instructions around this menu option. Hopefully this helps a little bit!

**Comment by nikitincryoocyte** [comment]
we're still having problem with it om IOS. our application can works in offline mode and we need to send some data to the backend when the app is in the background and the internet is available. but as I can see IOS doesn't allow us to send several requests to the backend in background. Is there anyone there who has figured this out?

**Comment by DogukanTansuk** [comment]
I still have that issue for iOS. Android works perfectly fine, but iOS won't fire the fetch event when the app is backgrounded. Does anyone have a solution for this situation?
